'use client';
import {useState} from 'react';
import Link from '@/components/research-link';
import './style.css';
const pages=['专题','案例','资产','问题与改版'];
export default function Page(){const [page,setPage]=useState(0);const [guide,setGuide]=useState(false);const [notes,setNotes]=useState(false);const [kind,setKind]=useState('全部');const [asset,setAsset]=useState('工作流');function go(n:number){setPage(n);setGuide(false);window.scrollTo({top:0,behavior:'instant'})}
return <main className="ps"><aside className="ps-review"><Link href="/community-options/content-system">← 内容体系</Link><span>交互样板 · 示例内容与资产均未发布</span><button onClick={()=>setNotes(!notes)}>设计说明</button></aside>
{notes&&<div className="ps-notes"><h2>关键检查</h2><p>专题发现 → 案例理解 → 资产选择 → 使用条件 → 反馈与版本关联。下方四个视图模拟独立页面；下载、复制、运行与提交尚未接入。</p><p>工作流、画布项目分别展示打开方式和条件；教程作为无可用资产时的替代路径。案例、问题、版本均使用明确示例，不代表已验证效果。</p><p>此样板属于研究室方案探索，不替代真实C端产品基线。制作优先由 MakeNow 承接。画布为用户确认已有能力；电商 Agent 和工作流工具为规划能力，本样板尚未连接真实服务。</p></div>}
<header><strong>多元拾光</strong><nav><button onClick={()=>go(0)}>发现方法</button><Link href="/community-options/home-draft#creation">创作交流</Link></nav></header>
<nav className="ps-steps" aria-label="样板页面">{pages.map((p,i)=><button key={p} aria-current={page===i?'page':undefined} onClick={()=>go(i)}>{String(i+1).padStart(2,'0')} {p}</button>)}</nav>
{page===0&&<><div className="ps-intro"><small>电商营销 / 商品图片制作</small><h1>从你的商品和用途开始</h1><p>看相似案例，找到可以继续使用的做法与项目。</p></div><div className="ps-tabs">{['全部','主图','详情图'].map(x=><button key={x} aria-pressed={kind===x} onClick={()=>setKind(x)}>{x}</button>)}</div><div className="ps-grid">{kind!=='详情图'&&<article className="ps-card"><div className="ps-preview"><span>原图</span><b>商品 → 新背景</b><span>结果对照位</span></div><small>案例 · 教程 · 工作流</small><h2>换了背景，标签与包装还对吗？</h2><p>适合已有清晰商品照片，想更换背景的使用者。</p><button className="ps-primary" onClick={()=>go(1)}>看案例与做法 →</button></article>}{kind!=='主图'&&<article className="ps-card"><div className="ps-preview canvas-preview"><span>参考 / 卖点 / 图序</span><b>一套图，先想清楚每张说什么</b></div><small>可编辑项目 · 画布</small><h2>商品详情图序怎么安排？</h2><p>把商品事实、参考图和文案放在同一个项目里。</p><button onClick={()=>{setAsset('画布项目');go(2)}}>看项目与使用条件 →</button></article>}</div><section className="ps-section"><h2>制作时卡住了？</h2><button className="ps-row" onClick={()=>go(3)}>背景满意，标签却发生变化：如何描述问题？ <span>查看反馈结构 →</span></button></section></>}
{page===1&&<><small>商品换背景 / 案例结构示例</small><h1>先保留商品，再调整背景</h1><p className="ps-lead">结果、做法与可复用资产放在一处，先判断是否适合自己的商品。</p><div className="ps-split"><article><div className="ps-preview"><span>原始素材位</span><b>输入 → 修改 → 结果</b><span>正式案例需提供对应图片</span></div><h2>需要准备</h2><p>主体清晰的原图、想要的背景参考，以及需要保留的标签、颜色与结构。</p><h2>关键选择</h2><ol><li>说明背景目标，列出不希望改变的商品细节。</li><li>比较候选结果，发现问题时进入 MakeNow 调整内容。</li><li>对照原图检查标签、轮廓、颜色和配件。</li></ol><p><a href="/community-options/cases/ecommerce#comparison" target="_blank" rel="noopener noreferrer">查看本任务的实际研究材料 ↗</a></p></article><aside className="ps-card"><h2>继续做</h2><p>选择适合自己的起点。</p><button className="ps-primary" onClick={()=>{setAsset('工作流');go(2)}}>查看工作流条件（待接入） →</button><button onClick={()=>setGuide(!guide)}>查看步骤教程结构</button>{guide&&<p>正式教程需要给出具体工具、素材规格、操作步骤和检查结果。示例当前仅展示这套结构。</p>}<button onClick={()=>go(3)}>查看问题与改版 →</button></aside></div></>}
{page===2&&<><small>资产详情 / 待接入示例</small><h1>{asset==='工作流'?'商品背景替换工作流':'商品图序画布项目'}</h1><div className="ps-tabs">{['工作流','画布项目'].map(x=><button key={x} aria-pressed={asset===x} onClick={()=>setAsset(x)}>{x}</button>)}</div><div className="ps-split"><article><div className="ps-preview"><small>资产结构示意</small><b>{asset==='工作流'?'商品输入 → 区域处理 → 输出检查':'参考素材 ｜ 商品事实 ｜ 文案与图序'}</b></div><h2>拿到后，可以改什么</h2><p>{asset==='工作流'?'替换商品输入与背景参考，按作者说明调整配置。具体节点由实际文件决定。':'整理参考图、调整每张图的表达目标、移动内容顺序，并补充自己的商品信息。'}</p><h2>使用条件</h2><dl><dt>打开方式</dt><dd>{asset==='工作流'?'MakeNow 工作流工具（规划中）；执行方式与依赖待接入时明确。':'MakeNow 画布（已有能力）；此示例项目尚未接入，项目打开与复制需对接。'}</dd><dt>素材与许可</dt><dd>需具有使用权的商品素材；作者与资产许可待接入。</dd><dt>可用状态</dt><dd>本页示例尚未绑定真实 MakeNow 项目或工作流。</dd><dt>版本关联</dt><dd>正式接入后记录验证日期、依赖版本与关联案例。</dd></dl></article><aside className="ps-card"><h2>使用这个资产</h2><button disabled>{asset==='工作流'?'在 MakeNow 使用 · 规划中':'在 MakeNow 打开 · 示例未接入'}</button><p>画布由已有 MakeNow 承接；工作流工具及电商 Agent 规划中。当前按钮仅展示未来路径。</p><button className="ps-primary" onClick={()=>go(1)}>先看案例与准备要求 →</button><button onClick={()=>go(3)}>问题与版本说明 →</button></aside></div></>}
{page===3&&<><small>反馈结构 / 示例</small><h1>把问题挂到具体结果上</h1><p className="ps-lead">关联案例、资产版本与出错位置，方便别人理解和回应。</p><div className="ps-split"><article className="ps-card"><small>示例问题 · 非真实用户反馈</small><h2>背景换好了，但标签不一致</h2><dl><dt>原本目标</dt><dd>只替换背景，保留商品包装。</dd><dt>使用条件</dt><dd>应附工具、资产版本、输入与相关配置。</dd><dt>问题位置</dt><dd>应附输入与输出的局部对照，指出具体文字或形状。</dd><dt>已尝试什么</dt><dd>说明修改过的步骤，避免重复建议。</dd></dl><button disabled>提交反馈 · 样板未接入</button></article><aside><h2>回应之后怎么接续</h2><ol><li>作者或参与者定位问题，说明建议及适用条件。</li><li>使用者补充再次尝试的结果。</li><li>解决方法关联原步骤；必要时更新资产版本。</li></ol><p>得到回复、问题解决、资产已更新分开记录。</p><button onClick={()=>go(2)}>返回资产 →</button><button onClick={()=>go(0)}>返回专题 →</button></aside></div></>}
<section className="ps-section" id="concepts"><h2>核心页面概念稿</h2><p>生图概念稿用于讨论视觉与内容布局；具体功能以本页交互样板为准。图中文字与节点并非可运行资产。</p><div className="ps-grid">{[["topic-v1.png","专题页概念稿"]].map(([file,title])=><figure key={file}><a href={"/product-concepts/"+file} target="_blank" rel="noopener noreferrer"><img src={"/product-concepts/"+file} alt={title} style={{width:"100%",height:"auto"}} loading="lazy"/></a><figcaption>{title} · 点击放大</figcaption></figure>)}</div></section><footer>研究室产品样板 · 用于确认信息架构与路径 · <Link href="/community-options/content-system">内容与资产设计</Link></footer></main>}
