'use client';
import {useState} from 'react';
import {Button,Card,Empty,Progress,Select,Space,Table,Tabs,Tag,Statistic} from 'antd';
import data from './analytics-retained-data.json';
type Row=Record<string,string|number>;
type Dataset=Record<string,unknown>&{columns:Record<string,{title:string;key:string;dataIndex?:string}[]>};
const growth=data.growth as unknown as Dataset,user=data.user as unknown as Dataset;
export function AnalyticsRetained({page,state,go,filters}:{page:string;state:string;go:(s:string)=>void;filters:Record<string,string>}){
 const [metric,setMetric]=useState('PV'),[compare,setCompare]=useState('前一等长周期');
 const {search='',...appliedDims}=filters;
 function table(src:Dataset,rows:string,cols:string){const items=(src[rows]||[]) as Row[];return <Table<Row> size="small" rowKey="key" dataSource={state==='empty'?[]:items.filter(r=>(!search||Object.values(r).some(v=>String(v).toLowerCase().includes(search.toLowerCase())))&&Object.entries(appliedDims).every(([k,v])=>!v||!(k in r)||String(r[k])===v))} columns={src.columns[cols].map(c=>({...c,render:c.key==='lookup'?(_,r)=><Button type="link" onClick={()=>go(r.lookup==='注册来源'?'user-register-sources':'users')}>{r.lookup}</Button>:undefined}))} scroll={{x:900}} pagination={{defaultPageSize:20,showSizeChanger:true,pageSizeOptions:[20,50,100],showQuickJumper:false}}/>;}
 if(state==='empty')return <Empty description="暂无统计数据"/>;
 const stats=(src:Dataset,key:string)=><div className="pm-stats">{state!=='empty'&&(src[key] as {label:string;value:string}[]).map(r=><Card size="small" key={r.label}><Statistic title={r.label} value={r.value}/></Card>)}</div>;
 if(['analytics-growth','analytics-channels'].includes(page))return <><Tag>固定演示样本 · 2026-08-17 至 2026-08-23</Tag>{stats(growth,'GROWTH_STATS')}<Card size="small" title="首次触点渠道占比">{(growth.GROWTH_FIRST_TOUCH_BARS as {label:string;percent:number}[]).map(r=><div key={r.label}><span>{r.label}</span><Progress percent={r.percent} size="small"/></div>)}</Card><Card size="small" title="归因分析"><Tabs items={[['首次触点','GROWTH_FIRST_TOUCH_ROWS','FIRST_TOUCH_COLUMNS'],['本次会话触点','GROWTH_SESSION_ROWS','SESSION_COLUMNS'],['注册触点','GROWTH_REGISTER_TOUCH_ROWS','REGISTER_TOUCH_COLUMNS'],['UTM投放参数','GROWTH_UTM_ROWS','UTM_COLUMNS']].map(([label,rows,cols])=>({key:rows,label,children:table(growth,rows,cols)}))}/></Card><Card size="small"><Tabs items={[['来源类型结构','GROWTH_SOURCE_TYPE_ROWS','SOURCE_TYPE_COLUMNS'],['电脑端与移动端','GROWTH_DEVICE_ROWS','DEVICE_COLUMNS'],['入口页表现','GROWTH_ENTRY_ROWS','ENTRY_COLUMNS']].map(([label,rows,cols])=>({key:rows,label,children:table(growth,rows,cols)}))}/></Card></>;
 if(page==='analytics-users')return <><Tag>固定演示样本 · 2026-08-17 至 2026-08-23</Tag>{stats(user,'USERS_STATS')}<Card size="small" title="激活时效"><Space wrap size="large">{(user.USERS_ACTIVATION as {label:string;value:string;note:string;helpText:string}[]).map(r=><div key={r.label} title={r.helpText}><Statistic title={r.label} value={r.value}/><small>{r.note}</small></div>)}</Space></Card><Card size="small" title="活跃用户趋势"><div className="pm-trend">{(user.USERS_DAU_TREND as {label:string;value:number}[]).map(r=><div key={r.label}><span>{r.value}</span><div style={{height:r.value,background:'#1677ff'}}/><small>{r.label}</small></div>)}</div></Card><Card size="small" title="用户激活与留存"><Tabs items={[['注册来源激活','USERS_SOURCE_WINDOW_ROWS','SOURCE_WINDOW_COLUMNS'],['注册到创作转化','USERS_CONVERSION_ROWS','CONVERSION_COLUMNS'],['注册来源结构','USERS_SOURCE_STRUCTURE_ROWS','SOURCE_STRUCTURE_COLUMNS'],['复访与再次有效行为','USERS_REVISIT_ROWS','REVISIT_COLUMNS'],['注册后再登录','USERS_RELOGIN_ROWS','RELOGIN_COLUMNS']].map(([label,rows,cols])=>({key:rows,label,children:table(user,rows,cols)}))}/></Card><Card size="small" title="首个有效价值行为">{state==='empty'?<Empty/>:(user.USERS_FIRST_ACTION as {label:string;value:number}[]).map(r=><div key={r.label}><span>{r.label} · {r.value}人</span><Progress percent={Math.round(r.value/57*100)} size="small"/></div>)}</Card></>;
 if(page==='analytics-overview'){const values=metric==='UV'?[70,86,95,91,113,89,82]:metric==='新增注册'?[3,4,6,5,8,5,5]:[151,170,210,178,220,181,170];return <Card size="small" title="趋势与异常定位"><Space wrap><Select aria-label="趋势指标" value={metric} onChange={setMetric} options={['PV','UV','新增注册'].map(value=>({value}))}/><Select aria-label="比较周期" value={compare} onChange={setCompare} options={['前一等长周期','不比较'].map(value=>({value}))}/><Tag>固定演示样本</Tag></Space>{state==='empty'?<Empty/>:<div className="pm-trend">{values.map((n,i)=><div key={i}><span>{n}{compare!=='不比较'?' / '+Math.round(n*.9):''}</span><div style={{height:n/2,background:'#1677ff'}}/><small>{['09-29','09-30','10-01','10-02','10-03','10-04','10-05'][i]}</small></div>)}</div>}<Space wrap><Button type="link" onClick={()=>go('analytics-channels')}>来源与入口异常</Button><Button type="link" onClick={()=>go('analytics-users')}>用户激活异常</Button><Button type="link" onClick={()=>go('analytics-quality')}>数据质量异常</Button></Space></Card>;}
 return null;
}
