'use client';
import {useEffect,useState} from 'react';
import {App,Button,Descriptions,Drawer,Form,Input,Modal,Result,Select,Space,Table,Tag} from 'antd';
import {MarkdownEditor} from './markdown-editor';
import {ContentBlockPreview} from './content-media';
import {appendSystemLog,readSystemStore,systemStorageKey,systemStamp} from './system-model';
type Notice={read_count?:number;created_by?:string;id:string;name:string;status:string;kind:string;summary:string;body:string;author?:string;date:string;publishedAt?:string;updatedAt?:string;[key:string]:unknown};
const defaults:Notice[]=[{id:'ANN-DEMO-1',read_count:128,created_by:'内容运营',name:'社区创作指南',status:'已发布',kind:'全部注册用户',summary:'了解内容发布与交流规范。',body:'## 开始创作\n\n分享原创内容，保留素材来源。',date:'2026-10-05 10:00:00'},{id:'ANN-DEMO-2',read_count:36,created_by:'管理员',name:'功能更新说明',status:'未发布',kind:'全部注册用户',summary:'本期更新内容。',body:'## 更新说明\n\n完善创作和浏览体验。',date:'2026-10-05 10:00:00'}];
const notices=()=>{const s=readSystemStore();return ((Array.isArray(s.announcements)?s.announcements:defaults) as Notice[]).map(row=>({...row,read_count:row.read_count??defaults.find(x=>x.id===row.id)?.read_count??0,created_by:row.created_by??defaults.find(x=>x.id===row.id)?.created_by}));};
export function AnnouncementManagement({state}:{state:string}){
 const {message,modal}=App.useApp();const [rows,setRows]=useState<Notice[]>([]),[filter,setFilter]=useState<string>(),[applied,setApplied]=useState<string>(),[editing,setEditing]=useState<Notice|null>(null),[detail,setDetail]=useState<Notice|null>(null),[action,setAction]=useState<{row:Notice;label:string}|null>(null),[dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[localState,setState]=useState(state);const [form]=Form.useForm();
 useEffect(()=>{queueMicrotask(()=>{try{setRows(notices());}catch{setState('load-failed');}});},[]);
 const canWrite=!busy&&!['loading','no-permission','permission-denied','readonly','read-only'].includes(localState);
 function close(){if(busy)return;if(dirty)modal.confirm({title:'放弃未保存的修改？',okText:'放弃修改',cancelText:'继续编辑',onOk:()=>{setEditing(null);setDirty(false);}});else setEditing(null);}
 useEffect(()=>{if(!dirty)return;const guard=(e:Event)=>{e.preventDefault();modal.confirm({title:'放弃未保存的修改？',okText:'放弃修改',cancelText:'继续编辑',onOk:()=>{setDirty(false);setEditing(null);(e as CustomEvent<{proceed:()=>void}>).detail.proceed();}});};window.addEventListener('prototype-before-navigate',guard);return()=>window.removeEventListener('prototype-before-navigate',guard);},[dirty,modal]);
 function edit(r?:Notice){if(!canWrite)return;const n=r||{id:crypto.randomUUID(),read_count:0,created_by:'内容运营',name:'',status:'未发布',kind:'全部注册用户',summary:'',body:'',date:systemStamp()};setEditing(n);setDetail(null);setDirty(false);}
 useEffect(()=>{if(editing){form.resetFields();form.setFieldsValue({...editing,kind:'全部注册用户'});}},[editing,form]);
 async function write(r:Notice,label:string,patch?:Partial<Notice>){if(busy||['loading','no-permission','permission-denied','readonly','read-only'].includes(localState))return false;setBusy(true);await new Promise(resolve=>setTimeout(resolve,200));if(['save-error','save-failed'].includes(localState)){message.error('提交失败，请重试');setState('normal');setBusy(false);return false;}try{const latest=readSystemStore(),items=notices(),old=items.find(x=>x.id===r.id);if(label!=='保存草稿'&&!old)throw Error('公告已不存在');if(old?.status==='已发布'&&['保存草稿','删除'].includes(label))throw Error('请先下架公告');let next:Notice|undefined;if(label!=='删除')next={...(old||r),...patch,updatedAt:systemStamp()};const updated=label==='删除'?items.filter(x=>x.id!==r.id):old?items.map(x=>x.id===r.id?next!:x):[next!,...items];const store=appendSystemLog({...latest,announcements:updated},(label==='保存草稿'?'保存公告草稿':label+'公告'),'公告管理',r.id,old||{},next||{},label);localStorage.setItem(systemStorageKey,JSON.stringify(store));setRows(updated);setDetail(null);setEditing(null);setAction(null);setDirty(false);message.success('操作成功');return true;}catch(e){message.error(e instanceof Error?e.message:'保存失败，请重试');return false;}finally{setBusy(false);}}
 async function save(){try{const v=await form.validateFields();if(editing)await write(editing,'保存草稿',{...v,status:'未发布',kind:'全部注册用户'});}catch{/* Form validation remains inline. */}}
 let userRows:unknown[]=[];try{const raw=readSystemStore().users;userRows=Array.isArray(raw)?raw:[];}catch{/* Load failure is rendered by the page. */}
 const users=userRows as {id:string;name:string;kind?:string;accountType?:string;official?:boolean;status:string;officialStatus?:string;purposes?:string[]}[];
 const authors=users.filter(u=>(u.kind==='官方账号'||u.accountType==='官方账号'||u.official)&&!['停用','冻结','限制登录','删除'].includes(u.status)&&u.officialStatus!=='停用'&&(!u.purposes?.length||u.purposes.includes('announcement')));
 const actions=(r:Notice)=><Space size={0}>{r.status!=='已发布'?<Button type="link" disabled={!canWrite} onClick={()=>edit(r)}>编辑</Button>:<Button type="link" disabled={!canWrite} onClick={()=>setAction({row:r,label:'下架并编辑'})}>下架并编辑</Button>}<Button type="link" disabled={!canWrite} danger={r.status==='已发布'} onClick={()=>setAction({row:r,label:r.status==='已发布'?'下架':'上架'})}>{r.status==='已发布'?'下架':'上架'}</Button>{r.status!=='已发布'&&<Button type="link" disabled={!canWrite} danger onClick={()=>setAction({row:r,label:'删除'})}>删除</Button>}</Space>;
 if(['no-permission','permission-denied'].includes(localState))return <Result status="403" title="暂无查看权限"/>;
 if(localState==='loading')return <Result title="加载中"/>;
 if(['error','load-failed'].includes(localState))return <Result status="error" title="加载失败" extra={<Button onClick={()=>{try{setRows(notices());setState('normal');}catch{message.error('本地数据无法读取');}}}>重新加载</Button>}/>;
 return <section className="pm-root"><Space wrap><Select aria-label="公告状态" allowClear placeholder="请选择状态" value={filter} onChange={setFilter} style={{width:160}} options={['已发布','未发布'].map(value=>({value}))}/><Button type="primary" onClick={()=>setApplied(filter)}>搜索</Button><Button type="primary" disabled={!canWrite} onClick={()=>edit()}>发布公告</Button></Space><Table rowKey="id" size="small" loading={localState==='loading'} dataSource={localState==='empty'?[]:rows.filter(r=>!applied||(r.status==='已发布'?'已发布':'未发布')===applied)} scroll={{x:1350}} pagination={{defaultPageSize:20,pageSizeOptions:[20,50,100],showSizeChanger:true,showQuickJumper:false}} columns={[{title:'公告ID',dataIndex:'id',width:170},{title:'标题',dataIndex:'name',width:220},{title:'目标人群',render:()=> '全部注册用户',width:130},{title:'状态',render:(_,r)=><Tag>{r.status==='已发布'?'已发布':'未发布'}</Tag>,width:90},{title:'阅读数',dataIndex:'read_count',width:100,render:value=>value??0},{title:'创建人',dataIndex:'created_by',width:140,render:value=>value||'—'},{title:'发布时间',render:(_,r)=>r.publishedAt||'—',width:170},{title:'更新时间',render:(_,r)=>r.updatedAt||r.date,width:170},{title:'操作',fixed:'right',width:285,render:(_,r)=><Space size={0}><Button type="link" onClick={()=>setDetail(r)}>查看</Button>{actions(r)}</Space>}]}/>
 <Drawer open={!!editing} title={rows.some(r=>r.id===editing?.id)?'编辑公告':'新建公告'} size={960} onClose={close} mask={{closable:false}} destroyOnHidden footer={<Space><Button onClick={close} disabled={busy}>取消</Button><Button type="primary" loading={busy} onClick={save}>保存草稿</Button></Space>}><Form form={form} layout="vertical" disabled={busy} onValuesChange={()=>setDirty(true)}>{editing&&rows.some(r=>r.id===editing.id)&&<Form.Item label="公告ID"><Input value={editing.id} disabled/></Form.Item>}<Form.Item label="公告状态"><Input value="未发布" disabled/></Form.Item><Form.Item name="kind" label="目标人群"><Select options={[{value:"全部注册用户",label:"全部注册用户"}]}/></Form.Item><Form.Item name="author" label="公开作者"><Select allowClear showSearch={{optionFilterProp:"label"}} placeholder="请选择启用中的官方账号" options={authors.map(u=>({value:u.id,label:u.name+' · '+u.id}))}/></Form.Item><Form.Item name="name" label="公告标题" rules={[{required:true,whitespace:true,min:4,max:40,message:'请输入4–40个字符'}]}><Input maxLength={40} showCount/></Form.Item><Form.Item name="summary" label="摘要" rules={[{required:true,whitespace:true,message:"请输入摘要"},{max:512}]}><Input.TextArea rows={3} maxLength={512}/></Form.Item><Form.Item name="body" label="公告正文（Markdown）" rules={[{required:true,whitespace:true,message:'请输入正文'}]}><MarkdownEditor value={String(editing?.body||'')} onChange={v=>{form.setFieldValue('body',v);setDirty(true);}}/></Form.Item></Form></Drawer>
 <Modal open={!!detail} title="公告详情" width={960} onCancel={()=>setDetail(null)} footer={detail?actions(detail):null}>{detail&&<><Descriptions bordered column={2} items={[{key:'id',label:'公告ID',children:detail.id},{key:'status',label:'状态',children:detail.status==='已发布'?'已发布':'未发布'},{key:'name',label:'标题',span:2,children:detail.name},{key:'audience',label:'目标人群',children:'全部注册用户'},{key:'reads',label:'阅读数',children:detail.read_count??0},{key:'creator',label:'创建人',children:detail.created_by||'—'},{key:'published',label:'发布时间',children:detail.publishedAt||'—'},{key:'updated',label:'更新时间',children:detail.updatedAt||detail.date}]}/><ContentBlockPreview block={{id:detail.id,type:'Markdown',text:detail.body}}/></>}</Modal>
 <Modal open={!!action} title={'确认'+(action?.label||'')+'公告？'} onCancel={()=>!busy&&setAction(null)} confirmLoading={busy} okText="确认" cancelText="取消" onOk={async()=>{if(!action)return;const {row,label}=action;if(label==='下架并编辑'){if(await write(row,'下架',{status:'未发布'}))edit({...row,status:'未发布'});return;}if(label==='上架'&&(!row.body.trim()||row.name.trim().length<4)){message.error('请完善标题和正文');return;}void write(row,label,label==='上架'?{status:'已发布',publishedAt:systemStamp(),publishedBody:row.body,publishedName:row.name,publishedSummary:row.summary}:label==='下架'?{status:'未发布'}:undefined);}}><p>{action?.row.name}</p></Modal></section>;
}
