'use client';
import {useState} from 'react';
import {Alert,Button,DatePicker,Descriptions,Drawer,Input,Select,Space,Table,Tabs,Tag,Typography} from 'antd';
import dayjs from 'dayjs';
type Metric={key:string;label:string;rule:string;unit?:string};
const view:Metric[]=[{key:'views',label:'浏览次数',rule:'详情成功加载且可见；每次打开或刷新一次，重复上报去重。'},{key:'visitors',label:'浏览人数',rule:'查询区间按账号或匿名访客身份去重；不累加每日人数，不强行跨设备合并。'}];
const publish:Metric[]=[{key:'publishers',label:'发布人数',rule:'首次发布提交成功的账号，按整个区间去重。'},{key:'published',label:'发布数',rule:'首次发布提交成功；草稿、失败、编辑及同一帖子重提不新增。'}];
const engagement:Metric[]=[['likes','点赞次数','成功建立点赞关系；同用户、对象、自然日最多新增一次。'],['likers','点赞人数','周期内成功点赞的去重账号。'],['comments','评论数','成功创建评论或回复；删除不抹掉历史发生数。'],['commenters','评论人数','周期内成功评论的去重账号。'],['saves','收藏次数','成功建立收藏关系；同用户、对象、自然日最多一次。'],['savers','收藏人数','周期内成功收藏的去重账号。'],['shares','分享入口点击次数','调用分享入口；不表示分享送达。'],['sharers','分享入口点击人数','周期内触发分享入口的去重身份。'],['copies','复制链接次数','剪贴板复制成功；同一次操作重报去重。'],['copiers','复制链接人数','周期内复制成功的去重身份。'],['currentLikes','期末点赞数','截止时仍有效的关系数；取消影响存量，不倒扣历史发生数。'],['currentSaves','期末收藏数','截止时仍有效的收藏；不累计每日快照。'],['currentComments','期末可见评论数','截止时可见的评论；删除后减少。']].map(([key,label,rule])=>({key,label,rule}));
const metrics:Record<string,Metric[]>={
 circle:[...view,{key:'joins',label:'加入次数',rule:'同用户、圈子、自然日最多一次；反复退出重加入不重复计。'},{key:'joiners',label:'新增加入人数',rule:'周期内加入成功的去重账号。'},{key:'exits',label:'退出次数',rule:'有效成员主动解除关系；不计后台移除。'},{key:'exiters',label:'退出人数',rule:'周期内主动退出的去重账号。'},{key:'members',label:'期末成员数',rule:'截止时有效成员快照，不累加每日值。'},...publish,...engagement.map(m=>({...m,label:'圈内帖子'+m.label}))],
 post:[...view,...publish,...engagement],
 app:[...view,{key:'uses',label:'使用入口点击次数',rule:'可用入口实际触发；不代表外站使用或创作成功。'},{key:'users',label:'使用入口点击人数',rule:'周期内有效点击的去重身份。'},{key:'rate',label:'使用入口点击率',rule:'同期既浏览又点击该应用的身份数 ÷ 浏览身份数；分母为0显示—。'},...engagement],
 topic:[...view,{key:'clicks',label:'专题内内容点击次数',rule:'实际点击专题内内容；目标加载失败仍是点击，但不计目标浏览。'},{key:'clickers',label:'专题内内容点击人数',rule:'周期内点击专题内内容的去重身份。'}],
 task:[{key:'participants',label:'参与人数',rule:'按现有任务有效参与事实去重，缺失时不以浏览人数替代。'},{key:'completedUsers',label:'完成人数',rule:'业务系统确认完成的去重账号。'},{key:'completed',label:'完成次数',rule:'依任务周期、次数上限和完成记录去重。'},{key:'rewardUsers',label:'奖励到账人数',rule:'实际生效积分流水的去重账号；完成不代表到账。'},{key:'points',label:'到账积分',rule:'有效到账流水积分合计，重复回调不新增；自动发放。'}]
};
const labels:Record<string,string>={circle:'圈子',post:'帖子',app:'AI应用',topic:'专题',task:'社区任务'};
const objects:Record<string,string[]>={circle:['影像练习圈','创作交流圈'],post:['旧照片修复练习','海边日落创作','角色设计过程'],app:['照片修复助手','文案灵感助手'],topic:['影像修复专题','创作入门专题'],task:['圈子浏览','圈子发帖','圈子点赞','圈子转发','圈子收藏','AI应用浏览','AI应用使用','AI应用点赞','AI应用转发','AI应用收藏','专题浏览']};
type Row={id:string;name:string;status:string;values:Record<string,string|number>};
export function CommunityAnalytics({mode}:{mode:'content'|'activity'|'metrics'}){
 const [kind,setKind]=useState(mode==='activity'?'task':'circle');const [keyword,setKeyword]=useState('');const [range,setRange]=useState<[dayjs.Dayjs,dayjs.Dayjs]|null>([dayjs('2026-10-01'),dayjs('2026-10-07')]);const [applied,setApplied]=useState(range);const [detail,setDetail]=useState<Row|null>(null);const [definition,setDefinition]=useState<Metric|null>(null);
 const fields=metrics[kind];const [group,setGroup]=useState('overview');const shownFields=group==='all'?fields:group==='interaction'?fields.filter(m=>['likes','likers','comments','commenters','saves','savers','shares','sharers','copies','copiers'].includes(m.key)):group==='stock'?fields.filter(m=>m.key.startsWith('current')||m.key==='members'):fields.filter(m=>!engagement.some(e=>e.key===m.key));
 const selectedDays=Array.from({length:7},(_,i)=>dayjs('2026-10-01').add(i,'day')).filter(d=>applied&&d.valueOf()>=applied[0].startOf('day').valueOf()&&d.valueOf()<=applied[1].endOf('day').valueOf());
 const rows:Row[]=selectedDays.length?objects[kind].map((name,i)=>{const values:Row['values']={};for(const m of fields){const people=m.label.endsWith('人数');const snapshot=/期末/.test(m.label);const users=new Set<string>();let count=0;for(const d of selectedDays){const n=d.date();const base=['uses','users','clicks','clickers'].includes(m.key)?3+i:['completedUsers','completed','rewardUsers'].includes(m.key)?2+i:5+i;for(let u=0;u<base;u++)users.add('demo-'+((u+n)%11));count+=base+(people||['likes','saves','joins'].includes(m.key)?0:2);}values[m.key]=snapshot?20+i*8+selectedDays.at(-1)!.date():people?users.size:m.key==='points'?count*10:count;}if(kind==='post'){const submitted=selectedDays.some(d=>d.date()===i+1)?1:0;values.published=submitted;values.publishers=submitted;}if(kind==='app')values.rate=((Number(values.users)/Number(values.visitors))*100).toFixed(1)+'%';return{id:kind+'-'+(i+1),name,status:kind==='task'?'进行中':i===1?'已下架':'已上架',values};}):[];
 const columns=[{title:kind==='task'?'任务类型':'对象',key:'name',width:200,fixed:'left' as const,render:(_:unknown,r:Row)=><><div>{r.name}</div><Typography.Text type="secondary">{r.id}</Typography.Text></>},...shownFields.map(m=>({title:<Button type="text" size="small" onClick={()=>setDefinition(m)}>{m.label} ⓘ</Button>,key:m.key,width:160,render:(_:unknown,r:Row)=>r.values[m.key]})),{title:'操作',key:'actions',fixed:'right' as const,width:90,render:(_:unknown,r:Row)=><Button type="link" onClick={()=>setDetail(r)}>详情</Button>}];
 return <div><Tag>演示数据 · 2026-10-01 至 2026-10-07</Tag><Tabs activeKey={kind} onChange={k=>{setKind(k);setGroup('overview');setDetail(null);setDefinition(null);setKeyword('');}} items={(mode==='activity'?['task']:mode==='metrics'?Object.keys(metrics):['circle','post','app','topic']).map(k=>({key:k,label:labels[k]}))}/><Space wrap style={{marginBottom:16}}>{mode==='content'&&kind!=='topic'&&<Select aria-label="指标分组" value={group} onChange={setGroup} style={{width:150}} options={[{value:'overview',label:'浏览与行为'},{value:'interaction',label:'互动数据'},{value:'stock',label:'期末存量'}]}/>} {mode!=='metrics'&&<><DatePicker.RangePicker aria-label="社区统计日期范围" value={range} onChange={v=>setRange(v?.[0]&&v[1]?[v[0],v[1]]:null)} allowClear={false}/><Button type="primary" disabled={!range||range[1].diff(range[0],'day')>89} onClick={()=>setApplied(range)}>查询</Button></>}<Input aria-label="搜索社区统计" placeholder={mode==='metrics'?'搜索指标名称':'搜索名称或编号'} value={keyword} onChange={e=>setKeyword(e.target.value)} style={{width:220}}/><Button onClick={()=>{setKeyword('');const r:[dayjs.Dayjs,dayjs.Dayjs]=[dayjs('2026-10-01'),dayjs('2026-10-07')];setRange(r);setApplied(r);}}>重置</Button>{range&&range[1].diff(range[0],'day')>89&&<Typography.Text type="danger">日期范围最多90天</Typography.Text>}</Space>
 {mode!=='metrics'&&applied&&(applied[0].isBefore(dayjs('2026-10-01'),'day')||applied[1].isAfter(dayjs('2026-10-07'),'day'))&&<Alert type="warning" style={{marginBottom:12}} title="所选日期包含未采集区间；下表仅展示2026-10-01至2026-10-07范围内的数据，不代表完整周期。"/>}
 {mode==='metrics'?<Table rowKey="key" dataSource={fields.filter(m=>m.label.includes(keyword))} columns={[{title:'指标',dataIndex:'label'},{title:'口径',dataIndex:'rule'},{title:'操作',render:(_:unknown,m:Metric)=><Button type="link" onClick={()=>setDefinition(m)}>查看定义</Button>}]} pagination={{defaultPageSize:20,showSizeChanger:true,pageSizeOptions:[20,50,100],showQuickJumper:false}}/>:<Table rowKey="id" dataSource={rows.filter(r=>(r.name+r.id).includes(keyword))} columns={columns} scroll={{x:shownFields.length*160+290}} locale={{emptyText:!selectedDays.length?'所选日期未采集演示数据':'暂无匹配记录'}} pagination={{defaultPageSize:20,showSizeChanger:true,pageSizeOptions:[20,50,100],showQuickJumper:false}}/>}
 <Drawer title={detail?.name} open={!!detail} onClose={()=>setDetail(null)} size={560}><Space style={{marginBottom:16}}><Tag>{detail?.status}</Tag><Typography.Text>{applied?.map(d=>d.format('YYYY-MM-DD')).join(' 至 ')}</Typography.Text></Space><p>数据覆盖：{selectedDays[0]?.format('YYYY-MM-DD')} 至 {selectedDays.at(-1)?.format('YYYY-MM-DD')}；存量截止：{selectedDays.at(-1)?.format('YYYY-MM-DD')} 23:59:59</p><Descriptions column={1} bordered items={fields.map(m=>({key:m.key,label:m.label,children:detail?.values[m.key]}))}/></Drawer>
 <Drawer title={definition?.label} open={!!definition} onClose={()=>setDefinition(null)} size={480}><p>{definition?.rule}</p><p>按北京时间统计；缺失与真实零值分开。历史行为保留，当前关系与可见内容按截止快照计算。官方、测试及内部流量的排除沿用V0.2。</p></Drawer></div>;
}
