'use client';
import {useSyncExternalStore} from 'react';
import {editorialSeeds,type AppEditorial} from '../app-editorial';
import type {Block} from './store';
export type ContentKind='post'|'tutorial'|'app';
export type ReviewState='草稿'|'待审核'|'已退回'|'已通过';
export type Visibility='未公开'|'已公开'|'已下架';
export type ContentDraft=AppEditorial&{title:string;summary:string;body:string;blocks:Block[];media:string;cover:string;category:string;circle:string;circleId?:string;source:string;license:string;learningGoal:string;preparation:string;toolVersion:string;limitations:string;attachments:string[];inputs:string;outputs:string;device:string;entry:string;refs:string[]};
export type ContentLog={at:string;action:string;reason:string;operator:string};
export type AdminContent={id:string;kind:ContentKind;author:string;authorId?:string;authorAvatar?:string;official:boolean;maintainer:string;interactions?:{likes:number;shares:number;favorites:number};draft:ContentDraft;published:ContentDraft|null;review:ReviewState;visibility:Visibility;runtime:'可用'|'暂停'|'待核验';revision:number;submissionId:string|null;submittedAt:string|null;firstPublishedAt:string|null;createdAt:string;updatedAt:string;edited:boolean;pinned:boolean;pinOrder:number;logs:ContentLog[]};
export type CommentRecord={id:string;contentId:string;author:string;authorId?:string;authorAvatar?:string;body:string;image:string;parentId:string|null;state:'待审核'|'公开'|'后台屏蔽'|'本人删除';reason:string;createdAt:string;revision:number;logs:ContentLog[]};
export type ReportRecord={id:string;targetType:'帖子'|'教程'|'AI应用'|'评论';targetId:string;reporter:string;reporterId?:string;reporterAvatar?:string;category:string;description:string;state:'待处理'|'处理中'|'已处理'|'已驳回';result:string;createdAt:string;revision:number;logs:ContentLog[]};
export type PendingContentWrite={id:string;entity:'content'|'comment'|'report';targetId:string;after:AdminContent|CommentRecord|ReportRecord;expectedRevision:number;operation:string;reason:string;createdAt:string;related?:{entity:'content'|'comment';targetId:string;after:AdminContent|CommentRecord;expectedRevision:number}[]};
export type ContentModel={records:AdminContent[];comments:CommentRecord[];reports:ReportRecord[];pending:PendingContentWrite[];completed:string[]};
export const CONTENT_MODEL_KEY='ai666-admin-content-20261006-v1';
export const contentCategories=['电商营销','IP与文创','摄影','设计','生活'];
export const contentCircles=['创作交流','摄影创作','电商视觉'];
// Legacy local demo records may lack identity fields; the fallback depends only on the user nickname, never a content ID.
export function contentUserId(name:string,id?:string){if(id)return id;if(name==='多元拾光编辑部')return 'demo-user-official-editorial';let hash=2166136261;for(const point of Array.from(name.normalize('NFC')))hash=Math.imul(hash^point.codePointAt(0)!,16777619);return 'demo-user-'+(hash>>>0).toString(36);}
export function contentTime(){return new Date().toLocaleString('sv-SE');}
export function blankContentDraft(kind:ContentKind):ContentDraft{return {title:'',summary:'',body:'',blocks:[{id:'markdown-body',type:'Markdown',text:''}],media:'',cover:'',category:contentCategories[0],circle:'',source:'官方原创',license:'',learningGoal:'',preparation:'',toolVersion:'',limitations:'',attachments:[],inputs:'',outputs:'',device:'手机与电脑',entry:kind==='app'?'/community-options/cross-prototype?page=app&item=copy':'',refs:[]};}
export function createContent(kind:ContentKind):AdminContent{return {id:`${kind}-${crypto.randomUUID().slice(0,8)}`,kind,author:'多元拾光编辑部',authorId:'demo-user-official-editorial',official:true,maintainer:'内容编辑',draft:blankContentDraft(kind),published:null,review:'草稿',visibility:'未公开',runtime:'可用',revision:0,submissionId:null,submittedAt:null,firstPublishedAt:null,createdAt:contentTime(),updatedAt:contentTime(),edited:false,pinned:false,pinOrder:0,logs:[]};}
export function saveOfficialContent(item:AdminContent,publish:boolean,now=contentTime()):AdminContent{
 if(!item.official||!['post','app'].includes(item.kind))throw new Error('仅官方帖子和应用可直接发布');
 const apply=publish||!!item.published;
 return {...item,updatedAt:now,review:apply?'已通过':'草稿',submissionId:null,submittedAt:apply?(item.submittedAt||now):null,published:apply?structuredClone(item.draft):null,visibility:item.visibility==='已下架'?'已下架':apply?'已公开':'未公开',firstPublishedAt:apply?(item.firstPublishedAt||now):item.firstPublishedAt,edited:apply&&!!item.published};
}
function seedContent():ContentModel{const records:AdminContent[]=[];for(const kind of ['post','tutorial','app'] as const){for(let i=1;i<=27;i++){const d=blankContentDraft(kind);d.title=kind==='post'?(i%4===0?'':`旧照片修复时，我先做的三件事${i>1?' · '+i:''}`):kind==='tutorial'?`旧照片修复：从观察破损到复查${i>1?' · '+i:''}`:`文案改写${i>1?' · 场景 '+i:''}`;d.summary=kind==='tutorial'?'保留原图，逐处处理损伤，最后检查真实细节。':'将创作方法与实际使用条件写清楚。';d.body='先保存原图副本，再观察划痕和人物细节。';d.blocks=[{id:'markdown-body',type:'Markdown',text:kind==='tutorial'?'## 目标\n保留真实细节，完成一次自然的旧照修复。\n\n### 准备\n- 保留原图副本\n- 使用电脑端工具检查细节\n\n### 方法\n先处理划痕，再检查人物五官。\n\n|检查项|通过条件|\n|---|---|\n|人物细节|没有过度磨皮|\n\n```text\n修复划痕，保留原有纹理和人物细节\n```':'## 适合用来\n整理产品介绍、社交文案和日常表达。\n\n### 输入准备\n提供原文、发布用途与希望使用的语气。\n\n### 输出\n一份可继续修改的文案。'}];d.cover='/home-prototype/restore.png';d.media=kind==='post'&&i%3===0?'/home-prototype/sea.png':'';d.circle=kind==='post'?contentCircles[i%3]:'';d.source=kind==='post'&&i%5!==0?'用户原创':'官方原创';d.learningGoal='学会判断旧照损伤并完成一次局部修复';d.preparation='原图副本、电脑端编辑工具';d.toolVersion='MakeNow 当前公开版';d.limitations='严重缺失的细节需要人工判断，不能保证恢复历史原貌。';d.inputs='原文，以及用途和语气要求';d.outputs='一份可继续编辑的改写文案';const review=(['已通过','待审核','已退回','草稿','已通过'] as ReviewState[])[(i-1)%5];const publicItem=i%5===0||i%5===1;const time=`2026-10-${String(6-(i%5)).padStart(2,'0')} 10:30:00`;records.push({id:`${kind}-${i}`,kind,author:kind==='post'&&i%5!==0?'林间 · '+i:'多元拾光编辑部',official:kind!=='post'||i%5===0,maintainer:'内容编辑',draft:d,published:publicItem?structuredClone(d):null,review,visibility:publicItem?(i%10===0?'已下架':'已公开'):'未公开',runtime:'可用',revision:1,submissionId:review==='待审核'?`${kind}-${i}-submission-1`:null,submittedAt:review==='待审核'?time:null,firstPublishedAt:publicItem?time:null,createdAt:time,updatedAt:time,edited:false,pinned:kind==='post'&&i===1,pinOrder:10,logs:[{at:time,action:publicItem?'首次公开':'创建内容',reason:'示例资料录入',operator:'内容编辑'}]});}}
const comments:CommentRecord[]=Array.from({length:24},(_,i)=>({id:`comment-${i+1}`,contentId:i%3===0?'tutorial-1':'post-1',author:`社区成员 ${i+1}`,body:i===0?'这组处理很自然，能分享一下细节吗？':i===1?'谢谢，我也按这个方法试了局部修复。':'先比较原图再检查细节，这一步很有帮助。',image:i===3?'/home-prototype/restore.png':'',parentId:i===1?'comment-6':null,state:i===5?'本人删除':i===6?'后台屏蔽':i%7===2?'待审核':'公开',reason:i===6?'包含与讨论无关的推广信息':'',createdAt:`2026-10-05 ${String(10+i%10).padStart(2,'0')}:20:00`,revision:1,logs:[]}));
const reports:ReportRecord[]=Array.from({length:12},(_,i)=>({id:`report-${i+1}`,targetType:i%2===0?'评论':'帖子',targetId:i%2===0?`comment-${i+1}`:`post-${i+1}`,reporter:`举报用户 ${i+1}`,category:i%2===0?'无关推广':'版权与授权',description:'请核对该条内容是否符合社区规范，示例证据留存在原记录。',state:i%4===3?'已处理':'待处理',result:i%4===3?'已核对并保留内容':'',createdAt:'2026-10-05 14:20:00',revision:1,logs:[]}));return {records,comments,reports,pending:[],completed:[]};}
let initial='';function initialSnapshot(){if(!initial)initial=JSON.stringify(seedContent());return initial;}
function snapshot(){if(typeof window==='undefined')return initialSnapshot();return localStorage.getItem(CONTENT_MODEL_KEY)||initialSnapshot();}
function subscribe(cb:()=>void){window.addEventListener('ai666-content-model-change',cb);window.addEventListener('storage',cb);return()=>{window.removeEventListener('ai666-content-model-change',cb);window.removeEventListener('storage',cb);};}
function normalizeContentModel(db:ContentModel):ContentModel{for(const seed of editorialSeeds){for(const kind of ['app','tutorial'] as const){const id=kind+'-'+seed.key;if(db.records.some(r=>r.id===id))continue;const d=blankContentDraft(kind);Object.assign(d,{title:kind==='app'?seed.title:seed.tutorial,summary:seed.summary,cover:seed.cover,inputs:seed.input,outputs:seed.output,entry:seed.entry,device:'仅电脑',learningGoal:seed.tutorial,blocks:[{id:'markdown-body',type:'Markdown',text:seed.body}],refs:kind==='app'?['tutorial-'+seed.key]:[],...(kind==='app'?{appCase:JSON.parse(JSON.stringify(seed.case)),topicRefs:seed.key==='suite'||seed.key==='storyboard'?['tp-launch']:[]}:{} )});db.records.push({id,kind,author:'多元拾光编辑部',official:true,maintainer:'内容编辑',draft:d,published:structuredClone(d),review:'已通过',visibility:'已公开',runtime:'可用',revision:1,submissionId:null,submittedAt:null,firstPublishedAt:'2026-10-08 10:00:00',createdAt:'2026-10-08 10:00:00',updatedAt:'2026-10-08 10:00:00',edited:false,pinned:false,pinOrder:0,logs:[]});}}for(const item of db.records){if(item.official&&['post','app'].includes(item.kind)){item.review=item.published?'已通过':'草稿';item.submissionId=null;}if(/^post-\d+$/.test(item.id)){for(const draft of [item.draft,item.published])if(draft)draft.body=draft.body.replace('\n\n我会先修复小范围问题，再对比原图判断是否自然。你们通常先处理哪一处？','');}if(item.kind!=='app')continue;if(item.runtime==='待核验')item.runtime='可用';for(const draft of [item.draft,item.published]){if(!draft)continue;draft.attachments=[];draft.blocks=draft.blocks.filter(b=>!['附件','attachment'].includes(b.type as string)).map(b=>({...b,text:b.text.replace('费用和执行结果在MakeNow查看。','')}));const legacy=draft as ContentDraft&{accountCost?:string;entryVerified?:boolean};delete legacy.accountCost;delete legacy.entryVerified;}if(!item.interactions){const seed=/^app-(\d+)$/.exec(item.id);const n=seed&&item.firstPublishedAt?Number(seed[1]):0;item.interactions=n?{likes:128+n*17,shares:12+n*3,favorites:64+n*9}:{likes:0,shares:0,favorites:0};}}return db;}
export function useContentModel():ContentModel{const raw=useSyncExternalStore(subscribe,snapshot,initialSnapshot);try{return normalizeContentModel(JSON.parse(raw));}catch{return normalizeContentModel(JSON.parse(initialSnapshot()));}}
export function readContentModel():ContentModel{try{return normalizeContentModel(JSON.parse(snapshot()));}catch{return normalizeContentModel(JSON.parse(initialSnapshot()));}}
export function changeContentModel(change:(db:ContentModel)=>void){const db=readContentModel();change(db);localStorage.setItem(CONTENT_MODEL_KEY,JSON.stringify(db));window.dispatchEvent(new Event('ai666-content-model-change'));}
export function requestContentWrite(command:PendingContentWrite){changeContentModel(db=>{if(!db.pending.some(x=>x.id===command.id)&&!db.completed.includes(command.id))db.pending.push(command);});}
export function discardConflictedContentWrite(commandId:string){changeContentModel(db=>{db.pending=db.pending.filter(x=>x.id!==commandId);});}
export function applyContentWrite(command:PendingContentWrite){let outcome='已完成';changeContentModel(db=>{if(db.completed.includes(command.id)){outcome='原处理已完成';return;}const updates=[{entity:command.entity,targetId:command.targetId,after:command.after,expectedRevision:command.expectedRevision},...(command.related||[])];for(const item of updates){const list=item.entity==='content'?db.records:item.entity==='comment'?db.comments:db.reports;const current=list.find(x=>x.id===item.targetId);if((current?.revision||0)!==item.expectedRevision)throw new Error('内容已被其他操作更新，请核对当前版本后重新处理。');}for(const item of updates){const after={...item.after,revision:item.expectedRevision+1,logs:[{at:contentTime(),action:command.operation,reason:command.reason||'按社区规则处理',operator:'内容编辑'},...item.after.logs]};if(item.entity==='content'){db.records=db.records.some(x=>x.id===item.targetId)?db.records.map(x=>x.id===item.targetId?after as AdminContent:x):[after as AdminContent,...db.records];}else if(item.entity==='comment'){db.comments=db.comments.map(x=>x.id===item.targetId?after as CommentRecord:x);}else db.reports=db.reports.map(x=>x.id===item.targetId?after as ReportRecord:x);}db.pending=db.pending.filter(x=>x.id!==command.id);db.completed.push(command.id);});return outcome;}
export function graphemeCount(value:string){return Array.from(new Intl.Segmenter('zh-CN',{granularity:'grapheme'}).segment(value.replace(/\r\n/g,'\n'))).length;}
