'use client';
/* oxlint-disable next/no-img-element -- Local prototype media. */
import {useCallback,useEffect,useRef,useState,type ReactNode} from 'react';
import {Alert,App,Avatar,Button,Card,DatePicker,Descriptions,Drawer,Empty,Form,Input,InputNumber,Modal,Radio,Result,Select,Space,Spin,Table,Tabs,Tag,Typography} from 'antd';
import type {ColumnsType} from 'antd/es/table';
import dayjs,{type Dayjs} from 'dayjs';
import {AppCaseEditor} from './app-case-editor';
import {AppCaseContent} from '../c-prototype/app-case';
import {appCaseErrors} from '../app-editorial';
import {MarkdownBodyEditor,markdownBody} from './markdown-editor';
import {AttachmentPicker,ContentBlockPreview,MediaPicker,MediaPreview,mediaReady} from './content-media';
import {applyContentWrite,contentUserId,contentCircles,contentTime,createContent,saveOfficialContent,graphemeCount,readContentModel,useContentModel,type AdminContent,type CommentRecord,type ContentDraft,type ContentKind,type PendingContentWrite,type ReportRecord} from './content-model';
import {currentContentCircles,contentCircleId,contentCircleName} from '../c-prototype/content-data';
import {activeTaxonomyNames,useTaxonomyOptions} from './taxonomy-adapter';
import './content-management.css';
const kindNames={post:'帖子',tutorial:'教程',app:'AI应用'};
const commonStates=['normal','empty','error','loading','no-permission'],writeStates=['normal','save-error','no-permission'];
export const contentManagementPages=[{id:'posts',title:'帖子管理',module:'内容管理',states:commonStates},{id:'post-detail',title:'帖子详情',module:'内容管理',states:['normal','no-permission']},{id:'post-edit',title:'编辑帖子',module:'内容管理',states:writeStates},{id:'tutorials',title:'教程管理',module:'内容管理',states:commonStates},{id:'tutorial-detail',title:'教程详情',module:'内容管理',states:['normal','no-permission']},{id:'tutorial-edit',title:'编辑教程',module:'内容管理',states:writeStates},{id:'apps',title:'AI应用管理',module:'内容管理',states:commonStates},{id:'app-detail',title:'AI应用详情',module:'内容管理',states:['normal','no-permission']},{id:'app-edit',title:'编辑AI应用',module:'内容管理',states:writeStates},{id:'comments',title:'评论管理',module:'审核与治理',states:[...commonStates,'save-error']},{id:'reviews',title:'审核工作台',module:'审核与治理',states:[...commonStates,'review-error']}];
type Filter={keyword:string;status:string;category:string;circle:string;source:string;from:string;to:string};
const blankFilter:Filter={keyword:'',status:'',category:'',circle:'',source:'',from:'',to:''};
type Decision={kind:'review'|'publish'|'down'|'restore'|'pin'|'remove-circle'|'availability'|'withdraw'|'comment'|'report';content?:AdminContent;comment?:CommentRecord;report?:ReportRecord};
function UserIdentity({name,id,avatar,official=false}:{name:string;id?:string;avatar?:string;official?:boolean}){return <div className="cm-user"><Avatar size={32} src={avatar} className="cm-user-avatar">{Array.from(name.trim())[0]||'用'}</Avatar><div><div className="cm-user-name">{name}{official&&<Tag color="blue">官方</Tag>}</div><Typography.Text className="cm-user-id" type="secondary">{contentUserId(name,id)}</Typography.Text></div></div>;}
function ContentAuthor({item}:{item:AdminContent}){return <UserIdentity name={item.author} id={item.authorId} avatar={item.authorAvatar} official={item.official}/>;}
function CommentAuthor({item}:{item:CommentRecord}){return <UserIdentity name={item.author} id={item.authorId} avatar={item.authorAvatar}/>;}
function requiresReason(action:Decision['kind'],choice:string){return action==='down'||action==='report'||action==='review'&&choice==='拒绝'||action==='comment'&&choice==='屏蔽';}
function StateTag({value}:{value:string}){return <Tag color={['已通过','已公开','公开','可用'].includes(value)?'green':['待审核','待处理','处理中'].includes(value)?'gold':['已退回','后台屏蔽','暂停'].includes(value)?'red':'default'}>{value}</Tag>;}
function SafeMedia({value}:{value:string}){return !value?<span className="cm-muted">无媒体</span>:mediaReady(value)?<MediaPreview value={value}/>:<Alert type="warning" title="媒体加载失败" description="请重新上传该文件。"/>;}
function Body({record,draft=false}:{record:AdminContent;draft?:boolean}){const d=draft?record.draft:record.published||record.draft;return record.kind==='post'?<><div className="cm-post-body">{d.body}</div>{d.media&&<SafeMedia value={d.media}/>}</>:<>{record.kind==='app'&&<AppCaseContent value={d.appCase}/>}<div className="cm-markdown"><ContentBlockPreview block={{id:record.id+'-markdown',type:'Markdown',text:markdownBody(d.blocks)}}/></div>{d.blocks.filter(b=>['图片','视频','资源引用'].includes(b.type)).map(b=><ContentBlockPreview key={b.id} block={b}/>)}{record.kind!=='app'&&d.attachments.length>0&&<Descriptions title="附件" size="small" column={1} items={d.attachments.map((x,i)=>({key:x,label:`附件 ${i+1}`,children:mediaReady(x)?x.split(':').at(-1):'需重新选择原文件'}))}/>}</>;}
export function ContentManagement({page,state,go}:{page:string;state:string;go:(target:string)=>void}){
 const db=useContentModel(),{message,modal}=App.useApp(),[sampleState,setSampleState]=useState(state),[filter,setFilter]=useState<Filter>(blankFilter),[query,setQuery]=useState<Filter>(blankFilter),[currentPage,setCurrentPage]=useState(1),[pageSize,setPageSize]=useState(20),[advanced,setAdvanced]=useState(false),[dates,setDates]=useState<[Dayjs|null,Dayjs|null]|null>(null),[edit,setEdit]=useState<AdminContent|null>(null),[isNew,setIsNew]=useState(false),[original,setOriginal]=useState(''),[errors,setErrors]=useState<Record<string,string>>({}),[mediaError,setMediaError]=useState(''),[decision,setDecision]=useState<Decision|null>(null),[reason,setReason]=useState(''),[choice,setChoice]=useState('通过'),[order,setOrder]=useState(10),[busy,setBusy]=useState(false),[writeResult,setWriteResult]=useState<{status:'success'|'failure';text:string;command?:PendingContentWrite}|null>(null),[detailTab,setDetailTab]=useState('content');
 const rejectedMedia=useRef(false),allowNavigation=useRef(false),hydrated=useRef(false),routeStarted=useRef(false),isList=['posts','tutorials','apps'].includes(page),kind:ContentKind=page.startsWith('post')?'post':page.startsWith('app')?'app':'tutorial',params=typeof window==='undefined'?new URLSearchParams():new URLSearchParams(location.search),selectedId=params.get('id'),hasSelectedId=params.has('id'),record=params.has('id')?db.records.find(x=>x.id===selectedId&&x.kind===kind):page.endsWith('-edit')?(db.records.find(x=>x.kind===kind&&x.official&&x.review==='草稿')||db.records.find(x=>x.kind===kind&&x.official&&x.review!=='待审核')):(db.records.find(x=>x.kind===kind&&x.visibility==='已公开'&&x.published)||db.records.find(x=>x.kind===kind)),detail=page.endsWith('-detail'),filterKey=`ai666-content-filters:${page.replace(/-(detail|edit)$/,'s')}`;
 useEffect(()=>{queueMicrotask(()=>{try{const saved=localStorage.getItem(filterKey);if(saved){const value=JSON.parse(saved);setFilter({...blankFilter,...value.query});setQuery({...blankFilter,...value.query});setDates(value.query?.from||value.query?.to?[value.query.from?dayjs(value.query.from):null,value.query.to?dayjs(value.query.to):null]:null);setCurrentPage(value.currentPage||1);setPageSize([20,50,100].includes(value.pageSize)?value.pageSize:20);setAdvanced(!!value.advanced);}}catch{/* Keep defaults. */}hydrated.current=true;});},[filterKey]);
 useEffect(()=>{if(hydrated.current)localStorage.setItem(filterKey,JSON.stringify({query,currentPage,pageSize,advanced}));},[query,currentPage,pageSize,advanced,filterKey]);
 const categoryOptions=useTaxonomyOptions(kind),editorCategoryOptions=useTaxonomyOptions(kind,edit?.draft.category);
 const dirty=!!edit&&JSON.stringify(edit)!==original;
 const closeEditor=useCallback((next?:()=>void)=>{if(busy)return;if(dirty)modal.confirm({title:'放弃未保存的修改？',content:'尚有内容未保存，离开后本次修改将丢失。',okText:'放弃修改',cancelText:'继续编辑',okButtonProps:{danger:true},onOk:()=>{setEdit(null);setMediaError('');next?.();}});else{setEdit(null);setMediaError('');next?.();}},[busy,dirty,modal]);
 useEffect(()=>{if(!edit)return;const handler=(event:Event)=>{if(allowNavigation.current||!dirty&&!busy)return;event.preventDefault();const target=event as CustomEvent<{proceed:()=>void}>;if(!busy)closeEditor(target.detail.proceed);};const unload=(event:BeforeUnloadEvent)=>{if(dirty||busy)event.preventDefault();};window.addEventListener('prototype-before-navigate',handler);window.addEventListener('beforeunload',unload);return()=>{window.removeEventListener('prototype-before-navigate',handler);window.removeEventListener('beforeunload',unload);};},[edit,dirty,busy,closeEditor]);
 const startEdit=useCallback((item:AdminContent,newItem=false)=>{if(sampleState==='no-permission')return;if(!item.official){void message.warning('普通用户内容仅支持审核和治理，不能改写正文。');return;}const next=newItem?{...item,draft:{...item.draft,category:activeTaxonomyNames(item.kind)[0]||''}}:item;setEdit(structuredClone(next));setOriginal(JSON.stringify(next));setIsNew(newItem);setErrors({});setMediaError('');rejectedMedia.current=false;setWriteResult(null);},[sampleState,message]);
 useEffect(()=>{if(routeStarted.current||!page.endsWith('-edit')||sampleState==='no-permission')return;routeStarted.current=true;const target=hasSelectedId?db.records.find(x=>x.id===selectedId&&x.kind===kind):(db.records.find(x=>x.kind===kind&&x.official&&x.review==='草稿')||db.records.find(x=>x.kind===kind&&x.official&&x.review!=='待审核')); if(target)queueMicrotask(()=>startEdit(target));},[page,sampleState,selectedId,hasSelectedId,db.records,kind,startEdit]);
 function field<K extends keyof ContentDraft>(key:K,value:ContentDraft[K]){setEdit(x=>x?{...x,draft:{...x.draft,[key]:value}}:null);setErrors(x=>({...x,[key]:''}));}
 function command(entity:'content'|'comment'|'report',after:AdminContent|CommentRecord|ReportRecord,operation:string,why:string):PendingContentWrite{return {id:`request-${crypto.randomUUID()}`,entity,targetId:after.id,after,expectedRevision:after.revision,operation,reason:why,createdAt:contentTime()};}
 async function perform(cmd:PendingContentWrite,success:string){if(busy||sampleState==='no-permission')return;setBusy(true);setWriteResult(null);await new Promise(resolve=>setTimeout(resolve,450));if(['save-error','review-error'].includes(sampleState)){setSampleState('normal');void message.error('提交失败，输入已保留，请重试。');setBusy(false);return;}try{applyContentWrite(cmd);setWriteResult(null);if(cmd.entity==='content'&&edit?.id===cmd.targetId){setEdit(null);setMediaError('');if(page.endsWith('-edit')){allowNavigation.current=true;go(`${kind}-detail?id=${cmd.targetId}`);allowNavigation.current=false;}}setDecision(null);void message.success(success);}catch(error){void message.error(error instanceof Error?error.message:'处理失败，请重试。');}finally{setBusy(false);}}

 function validate(item:AdminContent){const d=item.draft,e:Record<string,string>={};const old=readContentModel().records.find(x=>x.id===item.id);if((!old||old.draft.category!==d.category)&&!activeTaxonomyNames(item.kind).includes(d.category))e.category='请选择启用的分类';if(item.kind!=='post'&&!d.title.trim())e.title='请输入标题';if(graphemeCount(d.title)>60)e.title='标题最多60个字符';if(item.kind==='post'){if(!d.body.trim())e.body='正文必填，纯媒体不能发布';if(graphemeCount(d.body)>20000)e.body='正文最多20,000个字符';if(d.media&&!mediaReady(d.media))e.media='请重新选择有效媒体';if(d.media.split('|').filter(Boolean).length>4)e.media='帖子最多4张图或1段视频';}else{if(!d.cover)e.cover='请选择封面';if(!d.summary.trim())e.summary='请填写简介';if(!markdownBody(d.blocks).trim())e.body='请填写正文或使用说明';if(graphemeCount(markdownBody(d.blocks))>100000)e.body='正文最多100,000个字符';if(!mediaReady([d.cover,...d.blocks.filter(b=>['图片','视频'].includes(b.type)).map(b=>b.text),...(item.kind==='app'?[]:d.attachments)].join('|')))e.media='本地素材需要重新选择后才能提交';if(item.kind==='tutorial'&&!d.learningGoal.trim())e.learningGoal='请填写教学目标';if(item.kind==='app'){const issues=appCaseErrors(d.appCase);if(d.appCase?.items.some(x=>x.image&&!mediaReady(x.image)))issues.push('请重新选择有效案例图片');if(issues.length)e.appCase=issues.join('；');if(!d.inputs.trim())e.inputs='请说明输入准备';if(!d.outputs.trim())e.outputs='请说明输出形态';if(d.entry.trim()&&!(/^(https:\/\/[^\s/\\]+(?:[/?#][^\s\\]*)?|\/(?!\/)[^\s\\]*)$/.test(d.entry)))e.entry='请填写HTTPS地址或站内定向入口';}}setErrors(e);if(Object.keys(e).length)void message.warning('资料不完整：'+Object.values(e).join('；'));return !Object.keys(e).length&&!mediaError;}
 function saveEditor(publish:boolean){if(!edit)return;const apply=publish||!!edit.published;if(apply&&!validate(edit))return;const latest=readContentModel().records.find(x=>x.id===edit.id);if(latest&&latest.revision!==edit.revision){setErrors({save:'内容已更新，请复制输入并重新打开当前版本。'});return;}const after=saveOfficialContent(edit,publish);const label=apply?(edit.published?'保存修改':'发布'):'保存草稿';void perform(command('content',after,label,''),label==='保存修改'?'修改已保存':label==='发布'?'已发布':'草稿已保存');}
 function openDecision(next:Decision){if(sampleState==='no-permission')return;setDecision(next);setReason('');setChoice(next.kind==='report'?'保留内容':next.kind==='comment'?next.comment?.state==='后台屏蔽'?'恢复':'屏蔽':'通过');setOrder(next.content?.pinOrder||10);setErrors({});setWriteResult(null);}
 function submitDecision(){if(!decision||busy)return;const {kind:action,content:item,comment,report}=decision;const needsReason=requiresReason(action,choice);if(needsReason&&!reason.trim()){setErrors({reason:'请填写具体处理说明'});return;}setErrors({});if(item){const current=readContentModel().records.find(x=>x.id===item.id);if(!current||current.revision!==item.revision){setWriteResult({status:'failure',text:'对象状态已更新，请重新打开当前记录。'});return;}let after={...current,updatedAt:contentTime()};if(action==='review'){if(current.official||current.review!=='待审核'||!current.submissionId){setWriteResult({status:'failure',text:'该提交已撤回或处理，不能套用旧审核结果。'});return;}after={...after,review:choice==='通过'?'已通过':'已退回',submissionId:null};if(choice==='通过'&&item.kind==='post'&&!validate(current)){setWriteResult({status:'failure',text:'帖子正文或媒体无效，尚未公开；请核对原提交并重新补齐有效资料。'});return;}if(choice==='通过'&&item.kind==='post')after={...after,published:structuredClone(current.draft),visibility:current.visibility==='已下架'?'已下架':'已公开',firstPublishedAt:current.firstPublishedAt||current.submittedAt||contentTime(),edited:!!current.published};}if(action==='publish'){if(!current.official||!['post','app'].includes(current.kind)||current.visibility==='已下架'){void message.warning('当前内容不可直接发布');return;}if(!validate(current))return;after=saveOfficialContent(current,true);}if(action==='down')after={...after,visibility:'已下架',pinned:false};if(action==='restore'){if(!current.published){setWriteResult({status:'failure',text:'没有已发布内容，请先编辑并发布。'});return;}after={...after,visibility:'已公开',pinned:false};}if(action==='pin'){if(!current.published?.circle||current.visibility!=='已公开'){setWriteResult({status:'failure',text:'仅公开且归属圈子的帖子可设置圈内置顶。'});return;}after={...after,pinned:!current.pinned,pinOrder:order};}if(action==='remove-circle')after={...after,pinned:false,draft:{...current.draft,circle:'',circleId:undefined},published:current.published?{...current.published,circle:'',circleId:undefined}:null};if(action==='availability'){after={...after,runtime:current.runtime==='暂停'?'可用':'暂停'};}if(action==='withdraw')after={...after,review:'草稿',submissionId:null,submittedAt:null};const operations={review:choice==='通过'?'审核通过':'审核拒绝',publish:'发布',down:'后台下架',restore:'上架内容',pin:current.pinned?'取消圈内置顶':'设置圈内置顶','remove-circle':'移出圈子',availability:current.runtime==='暂停'?'恢复入口':'暂停入口',withdraw:'撤回提交',comment:'',report:''};void perform(command('content',after,operations[action],reason.trim()),action==='review'&&choice==='通过'&&item.kind!=='post'?'审核通过，等待正式发布':'操作完成，已更新同一内容记录');}
 if(comment){if(comment.state==='本人删除'){setWriteResult({status:'failure',text:'本人已删除的评论不能后台恢复。'});return;}const after:CommentRecord={...comment,state:choice==='恢复'||choice==='通过'?'公开':'后台屏蔽',reason};void perform(command('comment',after,choice==='恢复'?'恢复评论':choice==='通过'?'评论审核通过':'屏蔽评论',reason),'评论状态已更新，合法回复独立保留');}
 if(report){if(['已处理','已驳回'].includes(report.state))return;const after:ReportRecord={...report,state:choice==='驳回举报'?'已驳回':'已处理',result:reason};const cmd=command('report',after,choice==='驳回举报'?'驳回举报':choice==='屏蔽目标'?'举报处理：限制目标内容':'完成举报处理',reason);if(choice==='屏蔽目标'){const fresh=readContentModel();if(report.targetType==='评论'){const target=fresh.comments.find(x=>x.id===report.targetId);if(!target||target.state==='本人删除'){setWriteResult({status:'failure',text:'原评论已删除或不可处理，请保留原删除事实并记录核对结论。'});return;}cmd.related=[{entity:'comment',targetId:target.id,after:{...target,state:'后台屏蔽',reason},expectedRevision:target.revision}];}else{const target=fresh.records.find(x=>x.id===report.targetId);if(!target){setWriteResult({status:'failure',text:'原内容不存在，请先核对原目标。'});return;}cmd.related=[{entity:'content',targetId:target.id,after:{...target,visibility:'已下架',pinned:false},expectedRevision:target.revision}];}}void perform(cmd,'举报结论与目标状态已按同一处理记录保存');}}
 const filterOne=(item:{id:string;createdAt:string},text:string,statusValue:string,category='',circle='',source='')=>(!query.keyword||`${item.id} ${text}`.toLowerCase().includes(query.keyword.trim().toLowerCase()))&&(!query.status||query.status===statusValue)&&(!query.category||query.category===category)&&(!query.circle||query.circle===circle)&&(!query.source||query.source===source)&&(!query.from||item.createdAt.slice(0,10)>=query.from)&&(!query.to||item.createdAt.slice(0,10)<=query.to);
 const records=sampleState==='empty'?[]:db.records.filter(x=>x.kind===kind&&filterOne(x,`${x.draft.title} ${x.draft.body} ${x.author} ${contentUserId(x.author,x.authorId)}`,query.status&&['草稿','待审核','已退回','已通过'].includes(query.status)?x.review:x.visibility,x.draft.category,x.draft.circle,x.official?'官方':'用户')).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)),comments=sampleState==='empty'?[]:db.comments.filter(x=>filterOne(x,`${x.body} ${x.author} ${contentUserId(x.author,x.authorId)} ${x.contentId}`,x.state)),reports=sampleState==='empty'?[]:db.reports.filter(x=>filterOne(x,`${x.description} ${x.targetId} ${x.reporter} ${contentUserId(x.reporter,x.reporterId)}`,x.state,x.category)),pendingReview=sampleState==='empty'?[]:db.records.filter(x=>!x.official&&x.kind!=='tutorial'&&x.review==='待审核'&&filterOne({...x,createdAt:x.submittedAt||x.createdAt},`${x.draft.title} ${x.author} ${contentUserId(x.author,x.authorId)}`,x.kind));
 function detailGo(item:AdminContent){go(`${item.kind}-detail?id=${item.id}`);}
 const pagination={current:currentPage,pageSize,total:isList?records.length:page==='comments'?comments.length:page==='reports'?reports.length:pendingReview.length,showQuickJumper:false,showSizeChanger:true,pageSizeOptions:[20,50,100],showTotal:(n:number)=>`共 ${n} 条`,onChange:(n:number,size:number)=>{setCurrentPage(size!==pageSize?1:n);setPageSize(size);}};
 function contentActions(item:AdminContent){return <Space size={10} wrap>{item.official&&<Button type="link" size="small" onClick={()=>startEdit(item)}>编辑</Button>}{!item.official&&item.review==='待审核'&&<Button type="link" size="small" onClick={()=>openDecision({kind:'review',content:item})}>审核</Button>}{item.official&&!item.published&&item.visibility!=='已下架'&&<Button type="link" size="small" onClick={()=>openDecision({kind:'publish',content:item})}>发布</Button>}{item.visibility==='已公开'&&<Button type="link" size="small" danger onClick={()=>openDecision({kind:'down',content:item})}>下架</Button>}{item.visibility==='已下架'&&<Button type="link" size="small" onClick={()=>openDecision({kind:'restore',content:item})}>上架</Button>}{item.kind==='post'&&item.visibility==='已公开'&&item.draft.circle&&<Button type="link" size="small" onClick={()=>openDecision({kind:'pin',content:item})}>{item.pinned?'取消圈内置顶':'设置圈内置顶'}</Button>}{item.kind==='post'&&item.draft.circle&&<Button type="link" size="small" onClick={()=>openDecision({kind:'remove-circle',content:item})}>移出圈子</Button>}{item.kind==='app'&&item.published&&<Button type="link" size="small" onClick={()=>openDecision({kind:'availability',content:item})}>{item.runtime==='暂停'?'恢复入口':'暂停入口'}</Button>}</Space>;}
 const columns:ColumnsType<AdminContent>=[{title:kind==='app'?'应用':'内容',key:'title',width:285,render:(_,x)=><div className="cm-title-cell"><Button type="link" onClick={()=>detailGo(x)}>{x.draft.title||x.draft.body.slice(0,40)||'未命名草稿'}</Button><Typography.Text type="secondary">{x.id}</Typography.Text></div>},{title:'作者 / 来源',key:'author',width:235,render:(_,x)=><ContentAuthor item={x}/>},...(kind==='app'?[{title:'互动数据',key:'engagement',width:190,render:(_:unknown,item:AdminContent)=><div className="cm-engagement"><span>点赞 {item.interactions?.likes??0}</span><span>评论 {db.comments.filter(c=>c.contentId===item.id&&c.state==='公开').length}</span><span>转发 {item.interactions?.shares??0}</span><span>收藏 {item.interactions?.favorites??0}</span></div>}] as ColumnsType<AdminContent>:[]),{title:kind==='post'?'圈子':'分类',key:'category',width:120,render:(_,x)=>kind==='post'?x.draft.circle||'社区交流':x.draft.category},{title:'公开状态',dataIndex:'visibility',width:100,render:value=><StateTag value={value}/>},...(kind==='post'?[{title:'审核状态',key:'review',width:110,render:(_:unknown,item:AdminContent)=>item.official?'—':<StateTag value={item.review}/>}]:[]),...(kind==='app'?[{title:'运行入口',dataIndex:'runtime',width:100,render:(value:string)=><StateTag value={value}/>}] as ColumnsType<AdminContent>:[]),{title:'更新时间',dataIndex:'updatedAt',width:175},{title:'操作',key:'actions',width:280,fixed:'right',render:(_,item)=><Space size={10} wrap><Button type="link" size="small" onClick={()=>detailGo(item)}>详情</Button>{contentActions(item)}</Space>}];
 const commentColumns:ColumnsType<CommentRecord>=[{title:'评论 / 回复',key:'body',width:360,render:(_,x)=><div><div>{x.state==='本人删除'?<Typography.Text type="secondary">本人已删除</Typography.Text>:x.body||'图片评论'}</div>{x.image&&x.state!=='本人删除'&&<img className="cm-comment-image" src={x.image} alt="评论附件"/>}{x.parentId&&<Typography.Text type="secondary">{db.comments.find(p=>p.id===x.parentId)?.state==='本人删除'?'原父项已删除，合法回复独立保留':`回复 ${x.parentId}`}</Typography.Text>}</div>},{title:'作者',key:'author',width:235,render:(_,x)=><CommentAuthor item={x}/>},{title:'所属内容',dataIndex:'contentId',width:135,render:value=>{const target=db.records.find(x=>x.id===value);return target?<Button type="link" onClick={()=>detailGo(target)}>{value}</Button>:<Typography.Text type="secondary">{value}</Typography.Text>;}},{title:'状态',dataIndex:'state',width:110,render:value=><StateTag value={value}/>},{title:'时间',dataIndex:'createdAt',width:170},{title:'操作',key:'action',width:145,fixed:'right',render:(_,x)=><Space><Button type="link" onClick={()=>openDecision({kind:x.state==='待审核'?'review':'comment',comment:x})} disabled={x.state==='本人删除'}>{x.state==='待审核'?'审核':x.state==='后台屏蔽'?'恢复':'屏蔽'}</Button></Space>}];
 const reportColumns:ColumnsType<ReportRecord>=[{title:'举报',key:'report',width:220,render:(_,x)=><><Typography.Text strong>{x.category}</Typography.Text><div className="cm-muted">{x.id}</div></>},{title:'目标',key:'target',width:170,render:(_,x)=><>{x.targetType}<div>{x.targetId}</div></>},{title:'举报人',key:'reporter',width:235,render:(_,x)=><UserIdentity name={x.reporter} id={x.reporterId} avatar={x.reporterAvatar}/>},{title:'举报说明',dataIndex:'description',width:310},{title:'状态',dataIndex:'state',width:100,render:value=><StateTag value={value}/>},{title:'接受时间',dataIndex:'createdAt',width:175},{title:'操作',key:'actions',width:130,fixed:'right',render:(_,x)=><Button type="link" onClick={()=>openDecision({kind:'report',report:x})}>{['已处理','已驳回'].includes(x.state)?'查看结果':'处理'}</Button>}];
 const reviewColumns:ColumnsType<AdminContent>=[{title:'提交内容',key:'title',width:300,render:(_,x)=><><Button type="link" onClick={()=>detailGo(x)}>{x.draft.title||x.draft.body.slice(0,40)}</Button><div className="cm-muted">{x.submissionId}</div></>},{title:'类型',dataIndex:'kind',width:100,render:(value:ContentKind)=>kindNames[value]},{title:'作者',key:'author',width:235,render:(_,x)=><ContentAuthor item={x}/>},{title:'提交时间',dataIndex:'submittedAt',width:175},{title:'公开状态',dataIndex:'visibility',width:110,render:value=><StateTag value={value}/>},{title:'操作',key:'actions',width:100,fixed:'right',render:(_,x)=><Button type="link" onClick={()=>openDecision({kind:'review',content:x})}>审核</Button>}];
 function filtersPanel(){const opts=isList?(kind==='app'?['未公开','已公开','已下架']:['未公开','已公开','已下架','草稿','待审核','已退回','已通过']):page==='comments'?['待审核','公开','后台屏蔽','本人删除']:page==='reports'?['待处理','处理中','已处理','已驳回']:['post'];return <Card size="small" className={`cm-filter-card${page==='posts'?' cm-post-filters':''}`}><Form layout="inline" onFinish={()=>{if(filter.from&&filter.to&&filter.from>filter.to){void message.warning('开始日期不能晚于结束日期');return;}setQuery({...filter,keyword:filter.keyword.trim()});setCurrentPage(1);}}><Form.Item label="关键词"><Input allowClear placeholder="名称 / 正文 / 作者 / ID" value={filter.keyword} onChange={e=>setFilter({...filter,keyword:e.target.value})}/></Form.Item>{page!=='reviews'&&<Form.Item label="状态"><Select allowClear placeholder="全部" value={filter.status||undefined} onChange={value=>setFilter({...filter,status:value||''})} options={opts.map(x=>({value:x,label:x==='post'?'帖子':x==='tutorial'?'教程':x==='app'?'AI应用':x}))}/></Form.Item>}{isList&&<Form.Item label={kind==='post'?'圈子':'分类'}><Select allowClear placeholder="全部" value={(kind==='post'?filter.circle:filter.category)||undefined} onChange={value=>setFilter({...filter,[kind==='post'?'circle':'category']:value||''})} options={kind==='post'?contentCircles.map(x=>({value:x,label:x})):categoryOptions}/></Form.Item>}<Form.Item className="cm-filter-actions"><Space><Button type="primary" htmlType="submit">查询</Button><Button onClick={()=>{setFilter({...blankFilter});setQuery({...blankFilter});setDates(null);setCurrentPage(1);setSampleState('normal');}}>重置</Button>{page!=='posts'&&<Button type="link" onClick={()=>setAdvanced(!advanced)}>{advanced?'收起筛选':'更多筛选'}</Button>}</Space></Form.Item>{(advanced||page==='posts')&&<div className="cm-advanced">{isList&&kind!=='app'&&<Form.Item label="来源"><Select allowClear placeholder="全部" value={filter.source||undefined} onChange={value=>setFilter({...filter,source:value||''})} options={[{value:'官方',label:'官方'},{value:'用户',label:'用户'}]}/></Form.Item>}<Form.Item label={page==='reviews'?'提交时间':'创建时间'}><DatePicker.RangePicker value={dates} onChange={value=>{setDates(value);setFilter({...filter,from:value?.[0]?.format('YYYY-MM-DD')||'',to:value?.[1]?.format('YYYY-MM-DD')||''});}}/></Form.Item></div>}</Form></Card>;}
 const selectedContent=record;
 function detailPanel(item:AdminContent){const reviewingSubmission=!item.official&&['待审核','已退回'].includes(item.review);const displayed=reviewingSubmission?item.draft:item.published||item.draft;const relevant=db.comments.filter(x=>x.contentId===item.id);return <><Card className="cm-detail-title"><Space wrap><StateTag value={item.visibility}/>{!item.official&&<StateTag value={item.review}/>}<Typography.Text type="secondary">{item.id}</Typography.Text></Space><Typography.Title level={3}>{displayed.title||displayed.body.slice(0,40)||'未命名草稿'}</Typography.Title><div aria-label="运营动作">{contentActions(item)}</div></Card><div className="cm-detail-grid"><Card><Tabs activeKey={detailTab} onChange={setDetailTab} items={[{key:'content',label:'内容',children:<Body record={item} draft={reviewingSubmission}/>},{key:'comments',label:'评论',children:<><Table rowKey="id" size="small" dataSource={relevant} pagination={{defaultPageSize:20,showQuickJumper:false,showSizeChanger:true,pageSizeOptions:[20,50,100]}} columns={commentColumns}/></>}]}/></Card><Card title="维护与展示信息"><Descriptions column={1} size="small" items={[{key:'author',label:'作者',children:<ContentAuthor item={item}/>},{key:'source',label:'来源',children:displayed.source},{key:'maintenance',label:'维护人',children:<UserIdentity name={item.maintainer}/>},{key:'first',label:'首次公开',children:item.firstPublishedAt||'尚未公开'},{key:'category',label:'分类',children:displayed.category},...(item.kind==='post'?[{key:'circle',label:'圈子',children:displayed.circle||'社区交流'},{key:'pin',label:'圈内置顶',children:item.pinned?`已置顶 · 顺序 ${item.pinOrder}`:'未置顶'}]:[]),...(item.kind==='tutorial'?[{key:'goal',label:'教学目标',children:displayed.learningGoal},{key:'prepare',label:'准备条件',children:displayed.preparation},{key:'version',label:'工具版本',children:displayed.toolVersion},{key:'limits',label:'结果限制',children:displayed.limitations}]:[]),...(item.kind==='app'?[{key:'inputs',label:'输入准备',children:displayed.inputs},{key:'outputs',label:'输出形态',children:displayed.outputs},{key:'device',label:'支持设备',children:displayed.device},{key:'runtime',label:'运行入口',children:<StateTag value={item.runtime}/>},{key:'entry',label:'MakeNow入口',children:<Typography.Text copyable>{displayed.entry}</Typography.Text>}]:[])]}/></Card></div></>;}
 function fieldItem(name:keyof ContentDraft,label:string,node:ReactNode,required=false){return <Form.Item label={label} required={required} validateStatus={errors[name]?'error':undefined} help={errors[name]}>{node}</Form.Item>;}
 const decisionTitle=decision?{review:'审核提交',publish:'发布',down:'下架内容',restore:'上架内容',pin:decision.content?.pinned?'取消圈内置顶':'设置圈内置顶','remove-circle':'移出圈子',availability:decision.content?.runtime==='暂停'?'恢复应用入口':'暂停应用入口',withdraw:'撤回当前提交',comment:'评论治理',report:'举报处理'}[decision.kind]:'';
 return <section className="cm-admin"><div className="cm-page-head"><div>{detail||page.endsWith('-edit')?<Button type="link" onClick={()=>go(kind+'s')}>← 返回{kindNames[kind]}列表</Button>:null}</div><Space>{isList&&sampleState!=='no-permission'&&<Button type="primary" onClick={()=>startEdit(createContent(kind),true)}>新建{kindNames[kind]}</Button>}</Space></div>

 {writeResult&&!decision&&<Alert className="cm-spaced" closable={{onClose:()=>setWriteResult(null)}} type={writeResult.status==='failure'?'error':'success'} title={writeResult.text}/> }
 {sampleState==='no-permission'?<Result status="403" title="暂无当前模块访问权限" subTitle="请联系管理员确认账号职责与授权范围。"/>:sampleState==='loading'?<div className="cm-state"><Spin description="正在加载记录"/></div>:sampleState==='error'?<Result status="error" title="记录加载失败" subTitle="查询条件已保留，请重试。" extra={<Button type="primary" onClick={()=>setSampleState('normal')}>重新加载</Button>}/>:detail||page.endsWith('-edit')?selectedContent?detailPanel(selectedContent):<Result status="404" title="内容不存在或类型不符" extra={<Button onClick={()=>go(kind+'s')}>返回列表</Button>}/>:<> {filtersPanel()}<Card className="cm-table-card">{isList?<Table<AdminContent> rowKey="id" dataSource={records} columns={columns} pagination={pagination} scroll={{x:kind==='app'?1390:1280}} locale={{emptyText:<Empty description="没有符合条件的内容"/>}}/>:page==='comments'?<Table<CommentRecord> rowKey="id" columns={commentColumns} dataSource={comments} pagination={pagination} scroll={{x:1275}}/>:page==='reports'?<Table<ReportRecord> rowKey="id" columns={reportColumns} dataSource={reports} pagination={pagination} scroll={{x:1485}}/>:<Tabs items={[{key:'content',label:'内容提交',children:<Table<AdminContent> rowKey="id" dataSource={pendingReview} columns={reviewColumns} pagination={pagination} scroll={{x:1115}}/>},{key:'comment',label:'评论审核',children:<Table<CommentRecord> rowKey="id" dataSource={sampleState==='empty'?[]:db.comments.filter(x=>x.state==='待审核'&&filterOne(x,`${x.body} ${x.author} ${contentUserId(x.author,x.authorId)} ${x.contentId}`,query.status))} columns={commentColumns} scroll={{x:1150}} pagination={{defaultPageSize:20,showQuickJumper:false,showSizeChanger:true,pageSizeOptions:[20,50,100]}}/>}]}/>}</Card></>}
 <Drawer className="cm-editor" size={edit?.kind==='post'?720:980} open={!!edit&&sampleState!=='no-permission'} title={edit?`${isNew?'新建':'编辑'}${kindNames[edit.kind]}`:''} mask={{closable:false}} keyboard={!busy} onClose={()=>closeEditor(()=>{if(page.endsWith('-edit'))go(kind+'s');})} footer={<Space className="cm-drawer-footer"><Button disabled={busy} onClick={()=>closeEditor(()=>{if(page.endsWith('-edit'))go(kind+'s');})}>取消</Button><>{!edit?.published&&<Button loading={busy} disabled={!!writeResult?.command} onClick={()=>saveEditor(false)}>保存草稿</Button>}<Button type="primary" loading={busy} disabled={!!writeResult?.command} onClick={()=>saveEditor(true)}>{edit?.published?'保存修改':'发布'}</Button></></Space>}>
 {edit&&<>{writeResult?.status==='failure'&&<Alert className="cm-spaced" type="error" title={writeResult.text}/>} <Form layout="vertical" disabled={busy||!!writeResult?.command}><Descriptions className="cm-spaced" size="small" column={2} items={[{key:'author',label:'署名',children:<ContentAuthor item={edit}/>},{key:'official',label:'来源',children:'官方维护'}]}/>{fieldItem('title',edit.kind==='post'?'标题（选填）':'标题',<Input value={edit.draft.title} onChange={e=>field('title',e.target.value)} count={{show:true,max:60,strategy:graphemeCount}}/>,edit.kind!=='post')}
 {edit.kind==='post'?<>{fieldItem('body','正文',<Input.TextArea rows={10} value={edit.draft.body} onChange={e=>field('body',e.target.value)} count={{show:true,max:20000,strategy:graphemeCount}}/>,true)}{fieldItem('circle','所属圈子',<Select allowClear placeholder="社区交流，无圈子归属" value={contentCircleName(edit.draft.circle,edit.draft.circleId)||undefined} onChange={value=>{field('circle',value||'');field('circleId',contentCircleId(value||''));}} options={currentContentCircles().filter(c=>c.status!=='已关闭').map(c=>({value:c.name,label:c.name}))}/>)}<Form.Item label="图片或视频" validateStatus={mediaError||errors.media?'error':undefined} help={mediaError||errors.media}><Typography.Paragraph type="secondary">最多4张图或1段视频，二选一；媒体不会替代正文。</Typography.Paragraph><MediaPicker mode="work" value={edit.draft.media} disabled={busy||!!writeResult?.command} onError={value=>{if(value||!rejectedMedia.current)setMediaError(value);}} onChange={value=>{if(value.split('|').filter(Boolean).length>4){rejectedMedia.current=true;setMediaError('最多4张图片，请减少选择数量');return;}if(/\.(gif|avif)(\||$)/i.test(value)){rejectedMedia.current=true;setMediaError('图片仅支持JPG、JPEG、PNG、WebP');return;}rejectedMedia.current=false;setMediaError('');field('media',value);}}/></Form.Item></>:<>{fieldItem('summary','简介',<Input.TextArea rows={3} value={edit.draft.summary} onChange={e=>field('summary',e.target.value)}/>,true)}{fieldItem('cover','封面',<MediaPicker mode="image" value={edit.draft.cover} disabled={busy||!!writeResult?.command} onError={value=>{if(value||!rejectedMedia.current)setMediaError(value);}} onChange={value=>field('cover',value)}/>,true)}{fieldItem('category','分类',<Select value={edit.draft.category} onChange={value=>field('category',value)} options={editorCategoryOptions}/>)}
 {edit.kind==='tutorial'?<><div className="cm-form-grid">{fieldItem('learningGoal','教学目标',<Input.TextArea rows={2} value={edit.draft.learningGoal} onChange={e=>field('learningGoal',e.target.value)}/>,true)}{fieldItem('preparation','准备条件',<Input.TextArea rows={2} value={edit.draft.preparation} onChange={e=>field('preparation',e.target.value)}/>)}{fieldItem('toolVersion','工具及版本',<Input value={edit.draft.toolVersion} onChange={e=>field('toolVersion',e.target.value)}/>)}{fieldItem('limitations','结果限制',<Input.TextArea rows={2} value={edit.draft.limitations} onChange={e=>field('limitations',e.target.value)}/>)}</div></>:<><div className="cm-form-grid">{fieldItem('inputs','输入准备',<Input.TextArea rows={2} value={edit.draft.inputs} onChange={e=>field('inputs',e.target.value)}/>,true)}{fieldItem('outputs','输出形态',<Input.TextArea rows={2} value={edit.draft.outputs} onChange={e=>field('outputs',e.target.value)}/>,true)}{fieldItem('device','支持设备',<Select value={edit.draft.device} onChange={value=>field('device',value)} options={['手机与电脑','仅电脑','仅手机'].map(x=>({value:x,label:x}))}/>)}</div>{fieldItem('entry','MakeNow定向入口',<Input value={edit.draft.entry} onChange={e=>field('entry',e.target.value)}/>)}</>}
 {edit.kind==='app'&&<><AppCaseEditor value={edit.draft} onError={setMediaError} onChange={value=>{field('appCase',value.appCase);field('refs',value.refs);field('topicRefs',value.topicRefs);}}/>{errors.appCase&&<Alert type="error" title={errors.appCase}/>}</>}<Form.Item label={edit.kind==='tutorial'?'教程正文（Markdown）':'使用说明（Markdown）'} required validateStatus={errors.body?'error':undefined} help={errors.body}><div className={busy||!!writeResult?.command?'cm-editor-disabled':''}><MarkdownBodyEditor body={edit.draft.blocks} onChange={value=>field('blocks',value)} onError={setMediaError}/></div></Form.Item>{edit.kind!=='app'&&<Form.Item label="附件"><div className={busy||!!writeResult?.command?'cm-editor-disabled':''}><AttachmentPicker value={edit.draft.attachments} onChange={value=>field('attachments',value)} onError={setMediaError}/></div></Form.Item>}</>}
 {mediaError&&<Alert type="error" title={mediaError}/>} {errors.media&&<Alert type="error" title={errors.media}/>} {errors.save&&<Alert type="error" title={errors.save}/>}</Form></>}
 </Drawer>
 <Modal className="cm-modal" title={decisionTitle} open={!!decision} onCancel={()=>{if(!busy)setDecision(null);}} mask={{closable:false}} keyboard={!busy} width={decision?.kind==='report'?680:600} confirmLoading={busy} okText={decision?.kind==='review'?'提交':'确认处理'} cancelText="取消" okButtonProps={{danger:['down','comment'].includes(decision?.kind||''),disabled:!!decision?.report&&['已处理','已驳回'].includes(decision.report.state)}} onOk={()=>{submitDecision();}}>
 {decision&&<><Typography.Paragraph strong>{decision.content?.draft.title||decision.content?.draft.body.slice(0,40)||decision.comment?.body||decision.report?.id}</Typography.Paragraph>{decision.content&&<ContentAuthor item={decision.content}/>} {decision.content&&<Space className="cm-spaced"><StateTag value={decision.content.visibility}/>{!decision.content.official&&<StateTag value={decision.content.review}/>}</Space>}{writeResult&&<Alert className="cm-spaced" type={writeResult.status==='failure'?'error':'success'} title={writeResult.text}/>} {decision.kind==='review'&&<><Radio.Group disabled={busy||!!writeResult?.command} value={choice} onChange={e=>setChoice(e.target.value)} options={['通过','拒绝']}/></>}
 {decision.kind==='pin'&&<><Form.Item label="置顶顺序"><InputNumber min={0} max={9999} precision={0} value={order} onChange={value=>setOrder(value||0)}/></Form.Item></>}
 {decision.comment&&<><Descriptions column={1} size="small" items={[{key:'author',label:'作者',children:<CommentAuthor item={decision.comment}/>},{key:'state',label:'状态',children:<StateTag value={decision.comment.state}/>},{key:'parent',label:'关联回复',children:db.comments.filter(x=>x.parentId===decision.comment?.id&&x.state!=='本人删除').length}]}/>{decision.comment.image&&<img className="cm-comment-image" src={decision.comment.image} alt="评论图片"/>}{decision.kind==='comment'&&<Radio.Group value={choice} disabled={busy||!!writeResult?.command} onChange={e=>setChoice(e.target.value)} options={[{label:'屏蔽原条目',value:'屏蔽',disabled:decision.comment.state==='后台屏蔽'},{label:'恢复公开',value:'恢复',disabled:decision.comment.state!=='后台屏蔽'}]}/>}</>}
 {decision.report&&<><Descriptions column={1} size="small" items={[{key:'reporter',label:'举报人',children:<UserIdentity name={decision.report.reporter} id={decision.report.reporterId} avatar={decision.report.reporterAvatar}/>},{key:'target',label:'原目标',children:`${decision.report.targetType} · ${decision.report.targetId}`},{key:'category',label:'举报类型',children:decision.report.category},{key:'description',label:'举报说明',children:decision.report.description},{key:'result',label:'处理结果',children:decision.report.result||'尚未处理'}]}/>{!['已处理','已驳回'].includes(decision.report.state)&&<Radio.Group value={choice} disabled={busy||!!writeResult?.command} onChange={e=>setChoice(e.target.value)} options={['保留内容','屏蔽目标','驳回举报']}/>}</>}
 {requiresReason(decision.kind,choice)&&<Form.Item className="cm-spaced" label="处理原因" required validateStatus={errors.reason?'error':undefined} help={errors.reason}><Input.TextArea rows={3} disabled={busy||!!writeResult?.command||!!decision.report&&['已处理','已驳回'].includes(decision.report.state)} value={reason||decision.report?.result} onChange={e=>setReason(e.target.value)} placeholder="请输入处理说明"/></Form.Item>}</>}
 </Modal>

 </section>;
}
