'use client';
import {createPortal} from 'react-dom';
import {useEffect,useRef,useState} from 'react';
import {Alert,App,Button,Form,Input,InputNumber,Modal,Select,Space,Table,Tabs,Tag} from 'antd';
import {readOperations,writeOperations,appendLog,publicOperationRows,type OpRow} from './operations-model';
import {useContentModel} from './content-model';
import {MediaPicker} from './content-media';
const placements=[{key:'searchTopics',label:'专题推荐'},{key:'searchApps',label:'应用推荐'},{key:'hotwords',label:'推荐词'}];
export function ContentPlacements({area,state,actionHost}:{area:'app'|'search';state:string;actionHost:HTMLDivElement|null}){
 const {message,modal}=App.useApp();const content=useContentModel();const [data,setData]=useState(readOperations);const [searchTab,setSearchTab]=useState('searchTopics');const tab=area==='app'?'appBanner':searchTab;const word=tab==='hotwords',banner=tab==='appBanner';const [query,setQuery]=useState('');const [editor,setEditor]=useState<OpRow|null>(null);const [form]=Form.useForm();const [pagination,setPagination]=useState({current:1,pageSize:20});const failed=useRef(false);const [retried,setRetried]=useState(false);
 useEffect(()=>{const refresh=()=>setData(readOperations());window.addEventListener('bp-operations-change',refresh);return()=>window.removeEventListener('bp-operations-change',refresh);},[]);
 const label=banner?'应用 Banner':placements.find(p=>p.key===tab)!.label;
 const targets=tab==='searchTopics'?publicOperationRows(data.rows.topics).filter(r=>r.status==='已发布'&&r.published!==false).map(r=>({value:r.id,label:r.name})):content.records.filter(r=>r.kind==='app'&&r.visibility==='已公开'&&r.runtime==='可用'&&!!r.published).map(r=>({value:r.id,label:r.published!.title}));
 const rows=data.rows.slots.filter(r=>r.slotTab===tab);const filtered=(state==='empty'?[]:rows).filter(r=>(r.name+r.id).includes(query)).sort((a,b)=>a.order-b.order);
 function persist(row:OpRow,remove=false){if(state==='save-failed'&&!failed.current){failed.current=true;message.error('保存失败，请重试');return false;}try{const db=readOperations();writeOperations(appendLog({...db,rows:{...db.rows,slots:remove?db.rows.slots.filter(r=>r.id!==row.id):db.rows.slots.some(r=>r.id===row.id)?db.rows.slots.map(r=>r.id===row.id?row:r):[...db.rows.slots,row]}},'slots',row.id,remove?'删除':'保存',label));message.success(remove?'删除成功':'保存成功');return true;}catch{message.error('保存失败，请重试');return false;}}
 function edit(row?:OpRow){const value=row||{id:'',name:'',targetId:undefined,cover:'',type:label,slotTab:tab,order:(rows.length+1)*10,status:'停用'};setEditor(value);form.resetFields();form.setFieldsValue(value);}
 async function save(){try{const v=await form.validateFields();if(!editor)return;if(rows.some(r=>r.id!==editor.id&&(word?r.name===v.name.trim():r.targetId===v.targetId))){message.warning('该内容已添加');return;}if(!word&&!targets.some(t=>t.value===v.targetId)){message.warning('请选择公开有效的内容');return;}if(persist({...editor,...v,id:editor.id||'placement-'+crypto.randomUUID().slice(0,8),name:word||banner?v.name.trim():targets.find(t=>t.value===v.targetId)!.label,slotTab:tab,type:label,published:true})){setEditor(null);}}catch{/* keep validation and inputs */}}
 if(state==='load-failed'&&!retried)return <Alert type="error" title="加载失败" action={<Button onClick={()=>setRetried(true)}>重试</Button>}/>;
 return <>{area==='search'&&<Tabs activeKey={searchTab} items={placements} onChange={v=>{setSearchTab(v);setQuery('');setPagination(p=>({...p,current:1}));}}/>}<Space wrap style={{marginBottom:12}}><Input.Search placeholder="名称或编号" value={query} onChange={e=>{setQuery(e.target.value);setPagination(p=>({...p,current:1}));}}/>{actionHost&&createPortal(<Button type="primary" onClick={()=>edit()}>添加{label}</Button>,actionHost)}</Space><Table<OpRow> rowKey="id" dataSource={filtered} pagination={{...pagination,showSizeChanger:true,showQuickJumper:false,onChange:(current,pageSize)=>setPagination({current,pageSize})}} columns={[{title:word?'推荐词':'名称',dataIndex:'name'},...(!word?[{title:'关联内容',render:(_:unknown,r:OpRow)=>targets.find(t=>t.value===r.targetId)?.label||'内容已失效'}]:[]),{title:'排序',dataIndex:'order'},{title:'状态',render:(_:unknown,r:OpRow)=><Tag>{r.status==='已发布'?'已上架':'已下架'}</Tag>},{title:'操作',render:(_:unknown,r:OpRow)=><Space><Button type="link" onClick={()=>edit(r)}>编辑</Button><Button type="link" onClick={()=>{if(r.status!=='已发布'&&!word&&!targets.some(t=>t.value===r.targetId)){message.warning('关联内容已失效，请重新选择');return;}modal.confirm({title:r.status==='已发布'?'确认下架？':'确认上架？',okText:'确认',cancelText:'取消',onOk:()=>{persist({...r,status:r.status==='已发布'?'停用':'已发布'});}});}}>{r.status==='已发布'?'下架':'上架'}</Button><Button type="link" danger onClick={()=>modal.confirm({title:'确认删除？',okText:'删除',cancelText:'取消',onOk:()=>{persist(r,true);}})}>删除</Button></Space>}]}/><Modal centered width={800} className="placement-editor" title={(editor?.id?'编辑':'添加')+label} open={!!editor} onCancel={()=>setEditor(null)} onOk={save} okText="保存" cancelText="取消" destroyOnHidden><Form className="placement-form" form={form} layout="vertical" preserve={false}>{(word||banner)&&<Form.Item name="name" label={word?'推荐词':'标题'} rules={[{required:true,whitespace:true,message:'请输入内容'},{max:50}]}><Input maxLength={50}/></Form.Item>}{!word&&<Form.Item name="targetId" label={tab==='searchTopics'?'关联专题':'关联AI应用'} rules={[{required:true,message:'请选择关联内容'}]}><Select showSearch={{optionFilterProp:'label'}} options={targets}/></Form.Item>}{banner&&<Form.Item className="placement-full placement-media" name="cover" label="Banner图片" rules={[{required:true,message:'请上传图片'}]}><PlacementCover/></Form.Item>}<Form.Item name="order" label="排序" rules={[{required:true}]}><InputNumber min={0} precision={0}/></Form.Item><Form.Item name="status" label="状态"><Select options={[{value:'已发布',label:'上架'},{value:'停用',label:'下架'}]}/></Form.Item></Form></Modal></>;
}
function PlacementCover({value='',onChange}:{value?:string;onChange?:(v:string)=>void}){const {message}=App.useApp();return <MediaPicker value={value} mode="image" onChange={v=>onChange?.(v)} onError={text=>{message.error(text);}}/>;}
