import {initialTaxonomyRows} from './taxonomy-adapter';
import { prototypeStore, shopRecords, checkinRecords } from '../c-prototype/storage';
import { readEventConfigs, readPublishedEventConfigs, saveEventDraft, publishEventConfig, type EventConfig } from './retained-event-config';
import { readShopSites, readShopProducts, readStock, readActivitySubmissions } from './operations-data';
import { defaultSlots } from '../c-prototype/slots';

export type Bucket = 'circles'|'topics'|'taxonomy'|'features'|'slots'|'events'|'submissions'|'sites'|'products'|'stock'|'redemptions'|'points'|'checkin'|'invite';
export type OpRow = { id:string; name:string; status:string; type:string; order:number; owner?:string; summary?:string; count?:number; published?:boolean; [key:string]:unknown };
export type OpLog = {id:string;at:string;actor:string;module:string;object:string;action:string;detail:string};
export type OperationsData = { placementsMigrated?:boolean; rows:Record<Bucket,OpRow[]>; logs:OpLog[]; revision:number };
export const opKey='bp-operations-management-v1';
const row=(id:string,name:string,type:string,status='已发布',extra:Partial<OpRow>={}):OpRow=>({id,name,type,status,order:10,...extra});
export const eventRow=(config:EventConfig):OpRow=>row(config.code,config.name,config.type,config.status,{order:config.sort_order,config,count:config.tasks.length,published:true});
export function seedOperations():OperationsData {
 const events=readEventConfigs().map(eventRow);
 const imported=readActivitySubmissions().map(s=>row(s.id,s.title,s.kind==='post'?'帖子':'作品','已接受',{activity:s.activityCode,activityName:s.activityName,submittedAt:s.submittedAt,contentStatus:s.contentStatus,eligibility:s.eligibility==='valid'?'通过':'待核验',review:'待评审',reward:s.reward==='success'?'已到账':'待判定',reason:s.reviewReason||'',material:s.body||s.title}));
 return {revision:0,logs:[],rows:{
 circles:[row('ci-image','影像练习圈','圈子','开放',{summary:'照片修复与构图讨论',announcement:'分享过程，也欢迎提出问题。',cover:'restore',pins:['post-1'],postIds:['post-1'],count:24,published:true}),row('ci-visual','视觉创作圈','圈子','关闭',{summary:'产品视觉、光线与配色',announcement:'暂时关闭新发帖，历史内容仍可浏览。',cover:'perfume',pins:[],postIds:[],count:16,published:true})],
 topics:[row('tp-perfume','电商营销','专题','已发布',{summary:'从产品图片到展示短片',cover:'perfume',refs:['work-sea'],published:true}),row('tp-restore','图像修复','专题','已发布',{summary:'修复方法与案例',cover:'restore',refs:['work-1','tutorial-1'],published:true})],
 taxonomy:[...initialTaxonomyRows().map(t=>row(t.id,t.name,t.type,t.status,{...t,count:0})),row('tag-new','新手友好','教程标签','启用',{count:6,order:30})],
 features:[row('ft-work','首页爆款作品','作品推荐','已发布',{refs:['work-1'],published:true}),row('ft-post','PC交流推荐','帖子推荐','已发布',{refs:['post-1'],published:true}),row('ft-app','PC全部应用顺序','应用排序','已发布',{refs:['app-1'],published:true}),row('ft-banner','精选应用Banner','应用推荐','草稿',{refs:[],published:false}),row('ft-search-topic','搜索默认专题','专题推荐','草稿',{refs:[]}),row('ft-search-app','搜索默认应用','应用推荐','草稿',{refs:[]}),row('ft-hotwords','搜索推荐词','推荐词','已发布',{words:['旧照修复','产品海报'],refs:[],published:true})],
 slots:defaultSlots.map((s,i)=>row(s.id,s.title,s.type,s.status,{...s,order:i+1,published:true})),events,
 submissions:imported.length?imported:[row('sub-demo-1','旧照修复练习','作品','已接受',{activity:'ai_image_challenge',activityName:'生图挑战',user:'用户 · 017',period:'202610',submittedAt:1791266400000,contentStatus:'公开',eligibility:'通过',review:'待评审',reward:'待判定',reason:'',material:'作品图片及提示词已随投稿保留。',work:'work-1'}),row('sub-demo-2','构图讨论与练习','帖子','已接受',{activity:'prompt_co_creation',activityName:'Prompt 共创计划',user:'用户 · 032',period:'202610',submittedAt:1791266400000,contentStatus:'下架',eligibility:'待核验',review:'待评审',reward:'待判定',reason:'要求公开，需先核对当前状态。',material:'原投稿正文已保留；公开入口当前不可访问。',work:'post-1'})],
 sites:readShopSites().map(s=>row(s.id,s.name,'站点','启用',{url:s.url,summary:s.remark})),
 products:readShopProducts().map(p=>row(p.id,p.name,'卡密商品',p.status,{price:p.price,siteId:p.siteId,site:p.site,summary:p.description,start:p.start,end:p.end})),
 stock:readStock().map(s=>row(s.id,'[CARD_CODE]','演示卡密',s.status,{productId:s.productId,code:'[DEMO_CARD_CODE:'+s.id+']',recordId:s.recordId,createdAt:s.createdAt})),
 redemptions:[row('rd-demo-01','十元卡密','卡密兑换','成功',{user:'用户 · 017',productId:'dy-ten',price:1000,code:'[DEMO_CARD_CODE:rd-demo-01]',at:'2026-10-05 16:20',returnAmount:0,availableReturn:0}),row('rd-demo-02','镜像周卡','卡密兑换','兑换处理中',{user:'用户 · 032',productId:'mirror-week',price:500,at:'2026-10-05 17:10',reason:'兑换正在处理中，请核对原兑换记录。'}),row('rd-demo-03','两元卡密','卡密兑换','返还处理中',{user:'用户 · 028',productId:'dy-two',price:200,at:'2026-10-05 18:10',reason:'交付失败，原扣减流水正在返还。',returnAmount:200,availableReturn:150,expiredReturn:50,originalExpiry:'2026-10-05 18:00'})],
 points:[row('pt-01','连续创作里程碑','活动奖励','已到账',{user:'用户 · 017',points:50,source:'ai_image_challenge',at:'2026-10-05 12:30',expires:'2026-11-04 12:30'}),row('pt-02','一句话生成','生成预占','已预占',{user:'用户 · 032',points:-20,source:'task-demo-02',at:'2026-10-05 13:00'}),row('pt-03','两元卡密','兑换扣减','返还处理中',{user:'用户 · 028',points:-200,source:'rd-demo-03',at:'2026-10-05 18:10'})],
 checkin:[row('checkin-plan','自然周签到计划','自然周计划','启用',{rewards:Array.from({length:7},(_,i)=>({day_index:i+1,points:20})),streak_rewards:[{streak_days:3,points:20},{streak_days:5,points:30},{streak_days:7,points:50}],summary:'北京时间周一至周日，断签或跨周重计连续进度。'}),row('ck-user-17','用户 · 017','签到记录','已签到',{week:'2026-W41',streak:2,points:5,at:'2026-10-06 08:20'}),row('ck-user-32','用户 · 032','签到记录','未签到',{week:'2026-W41',streak:0,points:0,at:'2026-10-05 09:10'})],
 invite:[row('invite-plan','邀请有礼规则','邀请规则','启用',{registerPoints:20,publishPoints:50,dailyLimit:5,monthlyLimit:30,expireDays:30,summary:'未绑定的新旧账号均可补绑，无注册后期限；首次成功关系不可换绑。'}),row('iv-17-32','邀请关系 · 017 → 032','邀请关系','有效',{inviter:'用户 · 017',invitee:'用户 · 032',stage:'注册完成',reward:'已到账',points:20,at:'2026-10-05 12:10',reason:''}),row('iv-17-28','邀请关系 · 017 → 028','邀请关系','待核验',{inviter:'用户 · 017',invitee:'用户 · 028',stage:'有效发布待核验',reward:'待判定',points:0,at:'2026-10-05 14:10',reason:'由运营核对有效事件，不自动拦截或改账。'})]
 }};
}
export function readOperations():OperationsData {
 let data:OperationsData|undefined;try {const raw=prototypeStore.getItem(opKey);if(raw){const parsed=JSON.parse(raw) as OperationsData;if(parsed.rows&&parsed.logs)data=parsed;}}catch{/* preserve seeded review state */}data=data||seedOperations();
 if(!data.placementsMigrated){const mapping:Record<string,string>={"ft-banner":"appBanner","ft-search-topic":"searchTopics","ft-search-app":"searchApps","ft-hotwords":"hotwords"};for(const legacy of publicOperationRows(data.rows.features)){const slotTab=mapping[legacy.id];if(!slotTab)continue;const values=slotTab==="hotwords"?legacy.words:(legacy.liveRefs??legacy.refs);for(const [index,value] of (Array.isArray(values)?values:[]).entries()){const id="migrated-"+legacy.id+"-"+index;if(!data.rows.slots.some(x=>x.id===id))data.rows.slots.push(row(id,slotTab==="hotwords"?String(value):legacy.name,slotTab,slotTab==="appBanner"?"停用":legacy.status,{slotTab,targetId:slotTab==="hotwords"?undefined:String(value),order:index+1,cover:legacy.cover||"",published:true}));}}data.placementsMigrated=true;}
for(const feature of data.rows.features){if(feature.type==='热门词')feature.type='推荐词';if(feature.id==='ft-hotwords')feature.name='搜索推荐词';}for(const circle of [...data.rows.circles,...data.rows.topics]){delete circle.owner;if(circle.publicSnapshot)delete (circle.publicSnapshot as OpRow).owner;}for(const base of initialTaxonomyRows())if(!data.rows.taxonomy.some(x=>x.id===base.id||x.name===base.name&&x.type===base.type))data.rows.taxonomy.push(row(base.id,base.name,base.type,base.status,{...base,count:0}));
 // Repair only the untouched legacy demonstration topic, never an edited composition.
 const demoTopic=data.rows.topics.find(x=>x.id==='tp-perfume');if(demoTopic&&!demoTopic.publicSnapshot&&!demoTopic.draftPending&&!data.logs.some(x=>x.object==='tp-perfume')&&demoTopic.name==='电商营销'&&demoTopic.summary==='从产品图片到展示短片'&&JSON.stringify(demoTopic.refs)==='["work-perfume"]')demoTopic.refs=['work-sea'];
 for(const item of data.rows.taxonomy)if(item.type==='作品标签')item.type='内容话题';
 const plan=data.rows.checkin.find(x=>x.type==='自然周计划');if(plan&&!Array.isArray(plan.rewards)){plan.rewards=Array.from({length:7},(_,i)=>({day_index:i+1,points:Number(plan.daily??20)}));plan.streak_rewards=[{streak_days:3,points:Number(plan.milestone3??20)},{streak_days:5,points:Number(plan.milestone5??30)},{streak_days:7,points:Number(plan.milestone7??50)}];delete plan.daily;delete plan.milestone3;delete plan.milestone5;delete plan.milestone7;delete plan.expireDays;}
 // Accepted C records remain authoritative; B processing adds status without changing their identity/material.
 const submissions=readActivitySubmissions();for(const s of submissions){const previous=data.rows.submissions.find(r=>r.id===s.id);const next=row(s.id,s.title,s.kind==='post'?'帖子':'作品','已接受',{...previous,activity:s.activityCode,activityName:s.activityName,submittedAt:s.submittedAt,contentStatus:s.contentStatus,material:s.body||s.title,eligibility:previous?.eligibility||'待核验',review:previous?.review||'待评审',reward:s.reward==='success'?'已到账':previous?.reward||'待判定'});data.rows.submissions=previous?data.rows.submissions.map(r=>r.id===s.id?next:r):[next,...data.rows.submissions];}
 for(const r of shopRecords()){const previous=data.rows.redemptions.find(x=>x.id===r.id);const next=row(r.id,r.name,'卡密兑换',r.status==='success'?'成功':r.status==='pending'?'兑换处理中':'失败',{...previous,productId:r.productId,price:r.price,site:r.site,at:r.createdAt,code:'[DEMO_CARD_CODE:'+r.id+']',user:'当前演示用户'});data.rows.redemptions=previous?data.rows.redemptions.map(x=>x.id===r.id?next:x):[next,...data.rows.redemptions];}
 for(const r of checkinRecords()){const id='cp-checkin-'+r.date;if(!data.rows.checkin.some(x=>x.id===id))data.rows.checkin.push(row(id,'当前演示用户','签到记录','已签到',{at:r.date,points:r.points,week:'北京时间自然周',streak:'以原签到结果为准'}));}
 data.rows.stock=readStock().map(s=>row(s.id,'[CARD_CODE]','演示卡密',s.status,{...data!.rows.stock.find(x=>x.id===s.id),status:s.status,productId:s.productId,code:'[DEMO_CARD_CODE:'+s.id+']',recordId:s.recordId,createdAt:s.createdAt}));
 return data;
}
export function writeOperations(data:OperationsData){prototypeStore.setItem(opKey,JSON.stringify(data));window.dispatchEvent(new Event('bp-operations-change'));}
export function appendLog(data:OperationsData,bucket:Bucket,object:string,action:string,detail:string):OperationsData {return {...data,revision:data.revision+1,logs:[{id:'log-'+Date.now()+'-'+data.revision,at:new Date().toLocaleString('zh-CN',{timeZone:'Asia/Shanghai'}),actor:'演示运营员',module:bucket,object,action,detail},...data.logs]};}
export function persistEventDraft(config:EventConfig){saveEventDraft(config);}
export function publishEvent(config:EventConfig){persistEventDraft(config);publishEventConfig(config);}
export function publishedEvent(code:string){return readPublishedEventConfigs().find(r=>r.code===code);}

export function publicOperationRows(rows:OpRow[],current?:OpRow):OpRow[]{return rows.map(row=>{if(current&&row.id===current.id)return current;if(row.publicSnapshot){const snapshot=row.publicSnapshot as OpRow;return snapshot.status==='草稿'||snapshot.published===false?null:snapshot;}if(row.draftPending||row.status==='草稿')return null;return row;}).filter((row):row is OpRow=>row!==null);}

export function readTemplateAigcModelOptions(current='') {let models=[{id:'image-standard',name:'图片生成',status:'启用'},{id:'video-standard',name:'视频生成',status:'启用'},{id:'text-standard',name:'文本创作',status:'停用'}];try{const raw=typeof window==='undefined'?null:localStorage.getItem('research-b-platform-v1');if(raw){const value=JSON.parse(raw);if(Array.isArray(value.models))models=value.models;}}catch{/* Preserve demo options. */}const options=models.map(x=>{const row=x as typeof x & {code?:string};const enabled=['1','启用'].includes(row.status);return {value:row.code||row.id,label:row.name+(enabled?'':'（已停用）'),disabled:!enabled};});if(current&&!options.some(x=>x.value===current))options.push({value:current,label:current+'（历史绑定）',disabled:true});return options;}
