'use client';
import {useState,useSyncExternalStore} from 'react';
import {readShopSites,saveShopSites,readShopProducts,saveShopProducts,readStock,saveStock,type ShopSite,type ShopProduct} from './operations-data';
import {shopRecords} from '../c-prototype/storage';
import './retained-store-config.css';
const newId=(prefix:string)=>prefix+Date.now().toString(36);
const subscribe=(cb:()=>void)=>{window.addEventListener('bp-operations-change',cb);return()=>window.removeEventListener('bp-operations-change',cb)};
const snapshot=()=>JSON.stringify([readShopSites(),readShopProducts(),readStock(),shopRecords()]);
export function RetainedStoreConfig({state='normal'}:{state?:string}){
 useSyncExternalStore(subscribe,snapshot,()=> '');
 const sites=readShopSites(),products=readShopProducts(),stocks=readStock(),records=shopRecords();
 const [tab,setTab]=useState('站点与产品'),[siteId,setSiteId]=useState(''),[siteDraft,setSiteDraft]=useState<ShopSite|null>(null),[product,setProduct]=useState<ShopProduct|null>(null),[productId,setProductId]=useState(''),[codes,setCodes]=useState(''),[notice,setNotice]=useState(''),[remove,setRemove]=useState<{type:'site'|'product'|'stock';id:string}|null>(null);
 const field=(label:string,value:string,onChange:(v:string)=>void,type='text')=><label>{label}<input type={type} value={value} onChange={e=>onChange(e.target.value)}/></label>;
 const saveSite=()=>{if(!siteDraft)return;if(!siteDraft.name.trim()||!/^https:\/\/[^\s]+$/.test(siteDraft.url)){setNotice('请填写站点名称和有效的 HTTPS 域名。');return;}saveShopSites(sites.some(s=>s.id===siteDraft.id)?sites.map(s=>s.id===siteDraft.id?siteDraft:s):[...sites,siteDraft]);setSiteDraft(null);setNotice('站点已保存。')};
 const saveProduct=()=>{if(!product)return;if(!product.name.trim()||!product.siteId||!Number.isInteger(product.price)||product.price<=0||product.start&&product.end&&product.start>=product.end){setNotice('请检查商品名称、站点、积分价格和有效期。');return;}saveShopProducts(products.some(p=>p.id===product.id)?products.map(p=>p.id===product.id?product:p):[...products,product]);setProduct(null);setNotice('商品配置已保存。')};
 const importStock=()=>{const lines=codes.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);if(!productId||!lines.length){setNotice('请选择产品并输入演示卡密。');return;}if(lines.some(x=>!/^DEMO-[a-zA-Z0-9_-]+$/.test(x))){setNotice('此研究原型仅接收 DEMO- 开头的演示卡密，请勿粘贴真实卡密。');return;}if(new Set(lines).size!==lines.length||lines.some(x=>stocks.some(r=>r.code===x))){setNotice('存在重复卡密，本次未入库。');return;}saveStock([...stocks,...lines.map(code=>({id:'stock-'+code,productId,code,status:'可用' as const,createdAt:new Date().toISOString()}))]);setCodes('');setNotice('演示库存已入库。')};
 const deleteItem=()=>{if(!remove)return;const hasLegacyRecords=records.some(r=>!r.productId||!r.siteId);if(remove.type==='site'){if(products.some(p=>p.siteId===remove.id)||hasLegacyRecords||records.some(r=>r.siteId===remove.id)){setNotice('该站点仍有关联产品或历史兑换记录，不能删除。');return;}saveShopSites(sites.filter(s=>s.id!==remove.id));}else if(remove.type==='product'){if(stocks.some(r=>r.productId===remove.id)||hasLegacyRecords||records.some(r=>r.productId===remove.id)){setNotice('该产品仍有关联库存或历史兑换记录，可停用，不能删除。');return;}saveShopProducts(products.filter(p=>p.id!==remove.id));}else{if(stocks.some(r=>r.id===remove.id&&r.status!=='可用'))return;saveStock(stocks.filter(r=>r.id!==remove.id));}setRemove(null);setNotice('已删除。')};
 if(state==='permission-denied')return <section className="bop-panel"><h2>商品与兑换</h2><p>暂无此页面的查看权限。</p></section>;
 return <section className="bop-panel retained-store"><h2>商品与兑换</h2><div className="bop-actions">{['站点与产品','卡密库存','兑换记录'].map(t=><button key={t} aria-pressed={tab===t} onClick={()=>{setTab(t);setNotice('')}}>{t}</button>)}</div>
 {tab==='站点与产品'&&<><button className="store-primary" onClick={()=>setSiteDraft({id:newId('site-'),name:'',url:'',remark:''})}>新增站点</button><div className="store-table-scroll"><table><thead><tr><th>站点名称</th><th>域名</th><th>产品数量</th><th>备注</th><th>操作</th></tr></thead><tbody>{sites.map(s=><tr key={s.id}><td>{s.name}</td><td>{s.url}</td><td><button className="store-link" onClick={()=>setSiteId(s.id)}>查看产品（{products.filter(p=>p.siteId===s.id).length}）</button></td><td>{s.remark||'—'}</td><td><button onClick={()=>setSiteDraft({...s})}>编辑站点</button><button className="store-danger" onClick={()=>setRemove({type:'site',id:s.id})}>删除站点</button></td></tr>)}</tbody></table></div>
 {siteId&&<section className="store-products"><div className="store-section-head"><h3>{sites.find(s=>s.id===siteId)?.name} · 产品</h3><button className="store-primary" onClick={()=>setProduct({id:newId('product-'),siteId,site:sites.find(s=>s.id===siteId)?.name||'',name:'',price:0,stock:0,status:'可兑换',description:'',delivery:'卡密'})}>新增产品</button></div><div className="store-table-scroll"><table><thead><tr><th>产品名称</th><th>积分价格</th><th>可用库存</th><th>状态</th><th>描述</th><th>操作</th></tr></thead><tbody>{products.filter(p=>p.siteId===siteId).map(p=><tr key={p.id}><td>{p.name}</td><td>{p.price}</td><td>{p.stock}</td><td>{p.status}</td><td>{p.description}</td><td><button onClick={()=>setProduct({...p})}>编辑产品</button><button className="store-danger" onClick={()=>setRemove({type:'product',id:p.id})}>删除产品</button></td></tr>)}</tbody></table></div></section>}
 {siteDraft&&<div className="bop-panel"><h3>站点维护</h3><div className="rec-grid">{field('站点名称',siteDraft.name,v=>setSiteDraft({...siteDraft,name:v}))}{field('域名',siteDraft.url,v=>setSiteDraft({...siteDraft,url:v}))}{field('备注',siteDraft.remark,v=>setSiteDraft({...siteDraft,remark:v}))}</div><button onClick={saveSite}>保存站点</button><button onClick={()=>setSiteDraft(null)}>取消</button></div>}
 {product&&<div className="bop-panel"><h3>产品维护</h3><div className="rec-grid">{field('产品名称',product.name,v=>setProduct({...product,name:v}))}{field('积分价格',String(product.price),v=>setProduct({...product,price:Number(v)}),'number')}{field('描述',product.description,v=>setProduct({...product,description:v}))}<label>状态<select value={product.status} onChange={e=>setProduct({...product,status:e.target.value as ShopProduct['status']})}><option>可兑换</option><option>已停用</option></select></label>{field('开始时间（可选）',product.start||'',v=>setProduct({...product,start:v}),'datetime-local')}{field('结束时间（可选）',product.end||'',v=>setProduct({...product,end:v}),'datetime-local')}</div><p>可用库存：{product.stock}；库存由卡密记录统计。</p><button onClick={saveProduct}>保存产品</button><button onClick={()=>setProduct(null)}>取消</button></div>}</>}
 {tab==='卡密库存'&&<><label>产品<select value={productId} onChange={e=>setProductId(e.target.value)}><option value="">选择产品</option>{products.map(p=><option key={p.id} value={p.id}>{p.site} · {p.name}</option>)}</select></label><label>演示卡密，每行一条<textarea value={codes} onChange={e=>setCodes(e.target.value)} placeholder="DEMO-review-001"/></label><button className="store-primary" onClick={importStock}>新增卡密</button><div className="store-table-scroll"><table><thead><tr><th>ID</th><th>卡密</th><th>站点 / 产品</th><th>库存状态</th><th>兑换方式</th><th>实扣积分</th><th>兑换用户</th><th>兑换时间</th><th>入库时间</th><th>操作</th></tr></thead><tbody>{stocks.filter(r=>!productId||r.productId===productId).map(r=><tr key={r.id}><td>{r.id}</td><td>DEMO-••••</td><td>{products.find(p=>p.id===r.productId)?.site}<br/>{products.find(p=>p.id===r.productId)?.name}</td><td>{r.status}</td><td>{r.status==='已兑换'?'积分兑换':'—'}</td><td>{records.find(item=>item.id===r.recordId)?.price??'—'}</td><td>{r.status==='已兑换'?'演示用户':'—'}</td><td>{r.exchangedAt?new Date(r.exchangedAt).toLocaleString('zh-CN'):'—'}</td><td>{new Date(r.createdAt).toLocaleDateString('zh-CN')}</td><td><button disabled={r.status!=='可用'} onClick={()=>setRemove({type:'stock',id:r.id})}>删除库存</button></td></tr>)}</tbody></table></div></>}
 {tab==='兑换记录'&&(records.length?<div className="store-table-scroll"><table><thead><tr><th>商品</th><th>站点</th><th>实扣积分</th><th>状态</th><th>兑换时间</th></tr></thead><tbody>{records.map(r=><tr key={r.id}><td>{r.name}</td><td>{r.site}</td><td>{r.status==='success'?r.price:'—'}</td><td>{r.status==='success'?'成功':r.status==='pending'?'待确认':'失败'}</td><td>{new Date(r.createdAt).toLocaleString('zh-CN')}</td></tr>)}</tbody></table></div>:<div className="store-empty">暂无兑换记录</div>)}
 {remove&&<div role="alertdialog" className="bop-panel store-confirm"><p>确认删除？已兑换库存和有下游关联的对象不能删除。</p><button className="store-danger" onClick={deleteItem}>确认删除</button><button onClick={()=>setRemove(null)}>取消删除</button></div>}{notice&&<output className="store-notice">{notice}</output>}</section>;
}
