'use client';
import {useSyncExternalStore} from 'react';
export type TaxonomyKind='work'|'post'|'tutorial'|'app'|'work-topic'|'work-scenario'|'work-model';
export type SharedCategory={id:string;name:string;type:string;status:string;order:number;shortName?:string;mergedInto?:string};
const names=['电商营销','IP与文创','摄影','设计','生活'],codes=['ecommerce','ip','photography','design','life'],labels={work:'作品分类',post:'帖子分类',tutorial:'教程分类',app:'应用分类','work-topic':'内容话题','work-scenario':'使用场景','work-model':'模板模型'};
export function initialTaxonomyRows():SharedCategory[]{return (Object.keys(labels) as TaxonomyKind[]).flatMap(kind=>(kind==='work-topic'?['光影练习','旧照片修复']:kind==='work-scenario'?['社交分享','电商营销','日常创作']:kind==='work-model'?['Seedream','Flux','Midjourney','Veo']:names).map((name,i)=>({id:`category-${kind}-${codes[i]||i}`,name,type:labels[kind],status:'启用',order:(i+1)*10,shortName:name})));}
function rawSnapshot(){return typeof window==='undefined'?'':localStorage.getItem('bp-operations-management-v1')||'';}
function subscribe(cb:()=>void){window.addEventListener('bp-operations-change',cb);window.addEventListener('storage',cb);return()=>{window.removeEventListener('bp-operations-change',cb);window.removeEventListener('storage',cb);};}
export function taxonomyCategories(kind:TaxonomyKind,raw=rawSnapshot()):SharedCategory[]{let configured:SharedCategory[]=[];try{configured=JSON.parse(raw)?.rows?.taxonomy||[];}catch{/* Use baseline categories. */}const rows=configured.filter(x=>x.type===labels[kind]||(kind==='work-topic'&&x.type==='作品标签'));for(const base of initialTaxonomyRows().filter(x=>x.type===labels[kind]))if(!rows.some(x=>x.name===base.name||x.id===base.id))rows.push(base);return rows.sort((a,b)=>a.order-b.order||a.id.localeCompare(b.id));}
export function activeTaxonomyNames(kind:TaxonomyKind){return taxonomyCategories(kind).filter(x=>x.status==='启用'&&!x.mergedInto).map(x=>x.name);}
export function useTaxonomyOptions(kind:TaxonomyKind,current?:string|string[]){const raw=useSyncExternalStore(subscribe,rawSnapshot,()=>''),all=taxonomyCategories(kind,raw),options=all.filter(x=>x.status==='启用'&&!x.mergedInto).map(x=>({value:x.name,label:x.name,identity:x.id,disabled:false}));for(const value of Array.isArray(current)?current:current?[current]:[]){if(!options.some(x=>x.value===value)){const old=all.find(x=>x.name===value);options.push({value,label:value+'（已停用）',identity:old?.id||'legacy-'+value,disabled:true});}}return options;}
