import Link from '@/components/research-link';
import AConceptCase from '@/components/a-concept-case';
import {ProposalEvidence} from '@/components/proposal-comparison';
import data from '@/lib/presentation-narrative.json';
import {notFound} from 'next/navigation';
import '@/components/market-social.css';
import '../briefs.css';
const refs:Record<string,{label:string;href:string}[]>={a:[{label:'商品图已有办法与剩余问题',href:'/research-decisions/tasks#T-01'},{label:'教程评论：工具、版本与素材',href:'/?section=dp-comments#content-demand'}],b:[{label:'实际试做与排错',href:'/task-research#task-learning-troubleshooting'},{label:'Runway课程机制',href:'/#runway'}],c:[{label:'角色创作与反馈',href:'/research-decisions/tasks#T-36'},{label:'作者连载与修订',href:'/?section=closure-story#content-demand'}],d:[{label:'RunningHub资源与使用路径',href:'/#runninghub'},{label:'LiblibAI供给与维护',href:'/?section=liblib-supply-model#liblib'}],e:[{label:'手作读图的已有帮助',href:'/research-decisions/tasks#T-40'},{label:'人像修改与采用结果',href:'/research-decisions/tasks#T-38'}]};
export default async function Page({params}:{params:Promise<{id:string}>}){const {id}=await params;const o=data.options.find(x=>x.id===id);if(!o)notFound();return <main className="ms-report proposal-brief"><p><Link href={'/research-brief#'+id+'-journey'}>回到本方案主讲</Link> / <Link href="/community-options/briefs">早期比较稿</Link></p><header><p>方案 {o.code} / 产品与运营</p><h1>{o.title}</h1><p>早期分析稿 · <Link href={'/community-options/proposals/'+id}>当前方案与概念稿 →</Link></p></header><nav className="brief-nav">{id==='a'&&<a href="#concrete-case">任务时效校准</a>}{[['journey','用户经历'],['product','产品与内容'],['operations','运营与供给'],['boundaries','起步与取舍'],['evidence','案例依据']].map(([anchor,label])=><Link key={anchor} href={'#'+anchor}>{label}</Link>)}</nav>{id==='a'&&<AConceptCase/>}<section id="journey"><h2>从用户的任务出发</h2><p>{o.paragraphs[0].text}</p><div className="brief-path">{o.rows[0][1].split('→').map((x,i)=><div key={i}><span>{String(i+1).padStart(2,'0')}</span><p>{x}</p></div>)}</div></section><section id="product"><h2>产品怎样承接</h2><p>{o.paragraphs.find(p=>p.label==='完整形态')?.text}</p><article className="brief-example"><h3>内容实例 · 设计示例</h3><p>{o.rows[1][1]}</p></article><article><h3>什么使它成为社区</h3><p>{o.rows[6][1]}</p></article></section><section id="operations"><h2>供给与运营</h2><h3>一次完整运营安排</h3><ol>{o.lifecycle.map(x=><li key={x}>{x}</li>)}</ol>{o.rows.slice(2,6).map(([title,text])=><article key={title}><h3>{title}</h3><p>{text}</p></article>)}</section><section id="boundaries"><h2>起步范围与商业取舍</h2>{o.paragraphs.filter(p=>['起步版本','商业与取舍'].includes(p.label)).map(p=><article key={p.label}><h3>{p.label}</h3><p>{p.text}</p></article>)}</section><section id="evidence"><h2>案例与判断依据</h2><ProposalEvidence id={id}/>{refs[id].map(r=><p key={r.href}><Link href={r.href} target="_blank" rel="noopener noreferrer">{r.label} ↗</Link></p>)}<Link href="/research-status" target="_blank" rel="noopener noreferrer">统一证据状态 ↗</Link></section><p><Link href={'/research-brief#'+id+'-journey'}>回到主讲对应章节</Link></p></main>}
