'use client';
import {useRef,useState} from 'react';
import './compare.css';
type Browser='Safari'|'Chrome'|'微信';
export default function Compare(){
 const [browser,setBrowser]=useState<Browser>('Safari'); const [quiet,setQuiet]=useState(false); const [offset,setOffset]=useState(0); const frames=useRef<(HTMLIFrameElement|null)[]>([]);
 const sizes=browser==='Safari'?[100,36,48]:browser==='Chrome'?[58,0,58]:[48,48,48];
 function update(index:number,scroll:number,hideTop:boolean){const doc=frames.current[index]?.contentDocument;if(!doc)return;let style=doc.getElementById('comparison-style');if(!style){style=doc.createElement('style');style.id='comparison-style';doc.head.appendChild(style);}style.textContent=`.mh-header{position:${hideTop?'static':'sticky'}!important}${index===2?'.mh-bottom{display:none!important}.mh-search input{font-size:16px!important}':''}`;frames.current[index]?.contentWindow?.scrollTo(0,scroll);}
 function ready(index:number){update(index,offset,quiet);if(index===2){setTimeout(()=>{const doc=frames.current[index]?.contentDocument;(doc?.querySelector('button[aria-label="搜索"]') as HTMLButtonElement)?.click();setTimeout(()=>{(doc?.activeElement as HTMLElement)?.blur();},100);},800);}}
 return <main className="bc-page"><header className="bc-heading"><div><p>移动端首页 · 浏览器空间对比</p><h1>把浏览器也放进来看看。</h1><p>同为 390 × 844 逻辑尺寸。外框与键盘为示意，未复刻具体系统版本；第三屏展示搜索输入。</p></div><a href="/community-options/mobile-home">打开首页 ↗</a></header><div className="bc-controls"><div>{(['Safari','Chrome','微信'] as Browser[]).map(b=><button key={b} className={browser===b?'selected':''} onClick={()=>setBrowser(b)}>{b}</button>)}</div><label><input type="checkbox" checked={quiet} onChange={e=>{setQuiet(e.target.checked);[0,1,2].forEach(i=>update(i,offset,e.target.checked));}}/> 顶部随页面滚走</label><div>{[0,320,640].map(y=><button key={y} className={offset===y?'selected':''} onClick={()=>{setOffset(y);[0,1,2].forEach(i=>update(i,y,quiet));}}>{y===0?'首屏':`下移 ${y}px`}</button>)}</div></div><section className="bc-grid">{['浏览器栏展开','浏览器栏收起','搜索 · 键盘弹出'].map((label,i)=>{const chrome=sizes[i];const height=844-44-22-chrome-(i===2?278:0);const top=browser!=='Safari';return <article key={i}><div className="bc-label"><h2>{label}</h2><span>网页可见高度 {height}px</span></div><div className="bc-phone"><div className="bc-status"><b>9:41</b><span>▮▮▮　Wi-Fi　▰</span></div>{top&&chrome>0&&<div className="bc-chrome top" style={{height:chrome}}>{browser==='微信'?<><span>‹　×</span><b>多元拾光</b><span>···</span></>:<><span>⌂</span><span className="bc-address">ai666.net</span><span>⋮</span></>}</div>}<iframe title={label} ref={el=>{frames.current[i]=el;}} onLoad={()=>ready(i)} src="/community-options/mobile-home" style={{height}}/>{!top&&<div className={'bc-chrome safari '+(i===0?'expanded':'')} style={{height:chrome}}><div className="bc-address">{i===0?'aA　　':' '}ai666.net　↻</div>{i===0&&<div className="bc-browser-actions"><span>‹</span><span>›</span><span>↑</span><span>♡</span><span>▢</span></div>}</div>}{i===2&&<div className="bc-keyboard" aria-label="模拟键盘"><div className="bc-suggestions">夏天　　创作　　摄影</div>{['QWERTYUIOP','ASDFGHJKL','⇧ZXCVBNM⌫'].map((row,j)=><div className="bc-key-row" key={j}>{row.split('').map((key,k)=><span key={k}>{key}</span>)}</div>)}<div className="bc-key-row last"><span>123</span><span>◎</span><span className="space">空格</span><span className="search">搜索</span></div></div>}<div className="bc-home-indicator"><i/></div></div><p className="bc-note">{i===0?'看作品是否被入口挤到首屏下方。':i===1?browser==='微信'?'此处按固定顶栏模拟，不假设微信随滚动隐藏。':'看内容增加的空间，以及底部导航的占位。':'此屏模拟输入时隐藏站内底栏，保留搜索操作。'}</p></article>})}</section><footer>可直接在各屏内滚动、点击。上方按钮用于同步比较位置；键盘为静态外框。实际浏览器栏动画、系统键盘与安全区仍需真机验证。</footer></main>
}

