export const scenarios = [
  {id:'ecommerce',name:'电商营销',task:'一件商品的主图、场景图与详情图',core:'原图与套图案例、品类检查教程、可改版式、局部问题讨论',optional:'批处理工作流；自动套图 Agent',asset:'商品素材＋画布项目／模板；批量时再选工作流',check:'商品保真、文字、用途与图序',route:'选用途 → 看套图 → 查素材与方法 → 制作 → 逐图核对',proof:'RevenueCat：手机拍摄到 Shopify 发布',kind:'2026-08-19 · 厂商客户案例',url:'https://www.photoroom.com/customer-stories/revenuecat',known:'有拍摄、编辑与发布的连续描述。',gap:'同一商品的全部候选、源工程与独立验收未齐。',lesson:'案例保留原图与用途；资产按品类和编辑范围选择。',detail:'/community-options/cases/ecommerce#cases'},
  {id:'local-business',name:'本地经营宣传',task:'套餐上新的一套活动物料',core:'活动案例、可改信息表与版式、改价/延期方法',optional:'批量门店变体；自动文案与尺寸延展',asset:'活动信息表＋可编辑版式；实拍与装饰分开',check:'价格、日期、门店、限制条件',route:'确认活动 → 选用途 → 填真实信息 → 改版式 → 商家确认',proof:'美团海报实践与 Adobe 多尺寸宣传教程',kind:'2026-06/08 · 平台实践与官方教程',url:'https://tech.meituan.com/2026/06/18/AIGC-poster.html',known:'已有生成、编辑与质量检查的组织参照。',gap:'缺一间门店从改稿、使用到再次更新的连续记录。',lesson:'把活动信息作为底稿；一次变更能找到受影响物料。',detail:'/community-options/scenarios/local-business#evidence'},
  {id:'knowledge',name:'知识内容创作',task:'一篇有出处的解释图文',core:'解释案例、来源清单、图文对应方法、核稿讨论',optional:'可编辑图解；多形式生成项目',asset:'出处定位与解释结构；有许可再提供图解文件',check:'事实、推断、图文对应与更正',route:'明确问题 → 核读来源 → 搭结构 → 制作图文 → 核稿',proof:'NotebookLM Google I/O 来源与多成品示例',kind:'2026-05-27 · 厂商公开样本',url:'https://blog.google/innovation-and-ai/products/notebooklm/notebooklm-google-io-2026/',known:'来源与不同解释形式可以在一个项目中关联。',gap:'中文知识作者的发布、专业核稿和更正过程仍缺。',lesson:'详情保留关键判断与出处；生成图注和原始材料相互可查。',detail:'/community-options/scenarios/knowledge#evidence'},
  {id:'character',name:'角色与故事',task:'同一角色的一段连贯图文故事',core:'连读案例、设定与分镜、问题格修正方法',optional:'角色参考项目；逐格制作工作流',asset:'角色设定＋分镜＋参考条件',check:'人物、道具、视线与情节连续',route:'读片段 → 查设定 → 看分镜 → 分格制作 → 连读检查',proof:'六角色教材求助与原作者后续反馈',kind:'2026年核读 · 个人求助与反馈',url:'https://www.reddit.com/r/generativeAI/comments/1qis7dv/what_ai_can_produce_consistent_characters_for_a/',known:'作者报告使用参考图路径后有所改善。',gap:'没有公开完整书稿或逐格修改版本。',lesson:'反馈应连回具体角色、参考版本和问题格。',detail:'/community-options/scenarios/character#evidence'},
  {id:'portrait',name:'人像与生活影像',task:'经授权且保留人物特征的纪念影像',core:'获授权前后对照、保留项清单、局部方法与反馈',optional:'写真画布项目；纪念排版模板',asset:'授权示例＋局部编辑说明；私人原片由本人保管',check:'人物特征、修改意愿、公开范围',route:'确认保留项 → 选局部方法 → 比较候选 → 核对相似度并确认公开许可',proof:'旧人像修复求助与采用、拒绝反馈',kind:'2026年核读 · 个人反馈',url:'https://www.reddit.com/r/photorestore/comments/1sqk7x8/portrait_restoration_looking_for_tools_or_help_ai/',known:'同一讨论中能看到对保留人物特征的不同评价。',gap:'未做独立视觉验收；写真与纪念排版缺完整过程。',lesson:'相似度与清晰度分开比较，公开意愿在分享前确认。',detail:'/community-options/scenarios/portrait#evidence'},
  {id:'design',name:'设计与视觉表达',task:'一张主视觉延展为系列版式',core:'系列案例、设计简报、可编辑主版、多画幅修改方法',optional:'素材生成工作流；批量延展',asset:'品牌约束＋主版工程＋字体素材依赖',check:'品牌一致、信息层级、可编辑交付',route:'看系列 → 查简报与约束 → 选主版 → 延展 → 检查工程',proof:'全速：小象超市冰淇淋季主视觉与延展',kind:'2026-09-01 · 代理公司自述',url:'https://m.adquan.com/case2/detail-363125',known:'有统一场景下的主视觉、开机屏及品牌专场画面。',gap:'改稿轮次、客户验收与可授权源工程未公开。',lesson:'先展示整套，再解释固定与可变元素；源文件条件独立说明。',detail:'/community-options/scenarios/design#brand-cases'},
  {id:'writing',name:'写作与编辑',task:'从个人材料或草稿写到作者定稿',core:'改稿对照、修改理由、编辑约束、具体句段讨论',optional:'提示词／Skill；有授权的匿名样稿',asset:'编辑简报＋对照样稿＋核对清单',check:'原意、事实、语气与作者取舍',route:'看改动 → 理解理由 → 定编辑目标 → 改自己的稿 → 作者选择',proof:'少数派作者的三版披露与公开定稿',kind:'2026-03-11 · 作者自述及成稿',url:'https://sspai.com/post/107066',known:'过程披露连接公开定稿，可观察作者选择。',gap:'私有原料与三版全文没有全部公开。',lesson:'保留修改理由与采用关系；不能只有一个万能提示词。',detail:'/community-options/scenarios/writing#evidence'},
  {id:'work-learning',name:'职场与学习',task:'已有资料转成汇报或讲义',core:'资料到成品案例、大纲骨架、出处对照、试讲/试用改稿',optional:'演示模板；复习卡生成方法',asset:'材料结构＋演示/讲义骨架＋更新清单',check:'听众、原始口径、可讲性与更新',route:'选交付用途 → 整资料 → 定大纲 → 制作 → 试讲/试用 → 修订',proof:'大学化学：AI课件、试讲与教学调整',kind:'2026-07-10 · 校方应用报道',url:'https://science.eitech.edu.cn/2026/0710/c1203a6485/page.htm',known:'有课程规划、实际授课与根据困难调整的描述。',gap:'源课件与逐页差异未公开；企业汇报交付仍待补。',lesson:'汇报与学习分路；模板按用途选，结论保留资料定位。',detail:'/community-options/scenarios/work-learning#teaching-case'},
  {id:'ip',name:'IP与文创',task:'原创形象延展为表情、动作与数字应用',core:'设定与系列案例、动作修正、应用适配、许可说明',optional:'可复用角色资产；系列生成工作流',asset:'设定页＋动作规范＋应用版式',check:'辨识特征、文化出处、许可与版本',route:'看系列 → 查设定 → 试复杂动作 → 延展 → 应用核对',proof:'TDP社群角色：AI制作、后期处理与投稿受阻',kind:'2026-01-02发布，08-30更新 · 作者自述',url:'https://mintimate.cn/2026/01/02/genWechatEmoji/',known:'作者记录角色生成、白边调整与人工处理，Demo未正式上架。',gap:'同一动作完整改前改后、最终应用与素材授权未核。',lesson:'先试复杂动作，检查后再延展；应用版与设定版本相连。',detail:'/community-options/scenarios/ip#ai-process'},
];
