import Link from '@/components/research-link';
export const editorialPlan = [
  {id:'ecommerce',name:'电商营销',level:'重点专题',reason:'有拍摄到发布的客户案例、现成套图路径和品类反馈；适合具体比较。',entry:'一件商品，要做哪几张图？',home:'展示同一商品的原图与用途明确的成套成果，按品类进入。',cards:'套图案例 → 品类方法 → 可改版式 → 局部问题',tool:'MakeNow承接经核对的视觉素材；Agent和自动套图保留为规划。',people:'编辑组织品类与用途；作者解释取舍；商家确认商品事实。',hold:'不承诺自动生成即可上架，也不把平台案例当本站效果。',source:'/community-options/cases/ecommerce#cases'},
  {id:'design',name:'设计与视觉',level:'重点专题',reason:'已有具名品牌系列项目，能说明主视觉与延展关系；仍需授权工程。',entry:'一张主视觉，怎样扩成一套？',home:'优先看整套，再看固定元素、可变元素和不同画幅。',cards:'系列案例 → 设计简报 → 主版资产 → 版式修改',tool:'MakeNow用于兼容的视觉编排；原始工程不兼容时保留原工具。',people:'编辑选择能解释取舍的系列；作者说明延展规则；品牌方确认约束。',hold:'未授权的源文件只展示来源；不承诺直接商用或客户验收。',source:'/community-options/scenarios/design#brand-cases'},
  {id:'writing',name:'写作与编辑',level:'重点专题',reason:'有作者定稿选择及互读反馈；可分别组织方法比较和创作研讨。',entry:'这篇稿子，应该怎样改？',home:'并排说明修改目标、关键改动与作者选择，避免只放成稿。',cards:'取舍案例 → 对照节选 → 编辑简报 → 句段讨论',tool:'继续在合适的文字工具中编辑；MakeNow仅按需处理配图。',people:'作者决定原意与采用；编辑整理对照；愿意互读的同行回应具体片段。',hold:'没有完整对照稿时不编造改前改后；不承诺专业代改。',source:'/community-options/review#increment'},
  {id:'character',name:'角色与故事',level:'内容覆盖',reason:'有参考图路径与改善自述，完整连读稿和逐格修改仍不足。',entry:'同一角色，怎样贯穿这一段故事？',home:'以可连读片段进入，问题定位到具体格与设定。',cards:'故事片段 → 角色设定 → 问题格 → 修改反馈',tool:'MakeNow按兼容条件承接参考与分镜编排；连续生成能力另核。',people:'作者给出创作意图；同行讨论连续性；编辑保留版本关系。',hold:'暂不承诺长篇一致性或一站式动画制作。',source:'/community-options/scenarios/character#evidence'},
  {id:'portrait',name:'人像与生活影像',level:'内容覆盖',reason:'已有采用与拒绝反馈，适合解释清晰度和人物特征的取舍。',entry:'哪些地方要修，哪些必须保留？',home:'用获授权局部对照和保留项进入，私人原片留在本人环境。',cards:'修整案例 → 保留项清单 → 局部方法 → 本人反馈',tool:'MakeNow仅承接已核对的局部编辑；公开与上传各自确认许可。',people:'熟悉人物者确认相似度；作者说明处理；编辑核对展示授权。',hold:'暂不承诺还原真实容貌，也不默认公开私人原片。',source:'/community-options/scenarios/portrait#evidence'},
  {id:'knowledge',name:'知识内容',level:'内容覆盖',reason:'有来源组织样本；中文发布与专业纠错过程尚不足。',entry:'把这个问题讲清楚，依据在哪里？',home:'先呈现解释问题与出处，再展示图文如何对应。',cards:'解释案例 → 来源清单 → 图解方法 → 核稿问题',tool:'原资料工具组织出处；MakeNow按需编排已核实的图解。',people:'作者核读来源；编辑查对应关系；专业问题由相关人员判断。',hold:'暂不承诺自动事实核验或专业内容审定。',source:'/community-options/scenarios/knowledge#evidence'},
  {id:'local-business',name:'本地经营',level:'内容覆盖',reason:'有品牌活动系列和平台实践；国内单店连续改稿、使用仍缺。',entry:'这次活动，需要哪些宣传物料？',home:'按活动用途展示系列，经营信息与装饰素材分开。',cards:'活动系列 → 信息表 → 可改版式 → 变更检查',tool:'MakeNow的文字编辑、延展和导出逐项核对，未核时保留原工具。',people:'商家确认价格日期；作者说明可改范围；编辑组织用途和版本。',hold:'暂不承诺一站式经营效果，也不假设模板已获商用许可。',source:'/community-options/scenarios/local-business#brand-case'},
  {id:'work-learning',name:'职场与学习',level:'分支覆盖',reason:'教学已有试讲与调整；企业汇报仍未取得完整采用链。',entry:'这些资料，要讲给谁听？',home:'教学与企业汇报分路，展示材料如何取舍及讲者如何使用。',cards:'教学案例 → 资料结构 → 讲稿骨架 → 试讲调整',tool:'讲义与演示继续在原文档工具制作；MakeNow只处理兼容视觉素材。',people:'作者组织解释；资料负责人核事实；教师或讲者确认可讲性。',hold:'企业汇报先作方法参照；内部资料不要求上传，暂不承诺交付代做。',source:'/community-options/scenarios/work-learning#teaching-case'},
  {id:'ip',name:'IP与文创',level:'内容覆盖',reason:'新增AI角色制作与投稿受阻自述；同一动作修正与实际应用仍未连齐。',entry:'这个形象，怎样变成一组可用动作？',home:'先展示设定与复杂动作，再分别看表情、主视觉和应用。',cards:'系列案例 → 设定页 → 动作修改 → 应用条件',tool:'MakeNow按兼容条件组织参考与版式；表情制作和上架留在对应工具。',people:'作者说明设定与每项产物；编辑核对许可和应用状态。',hold:'暂不承诺自动成套、审核通过或商业销售。',source:'/community-options/scenarios/ip#ai-process'},
];
export default function EditorialPlan(){return <section id="editorial-plan"><h2>九类保留，三类先做重点专题</h2><p>建议先把电商营销、设计与视觉、写作与编辑做成可深入阅读的专题。其余六类先提供可靠案例与方法入口，材料成熟后再加深。这个顺序依据当前材料、任务差异与产品承接条件，不代表市场规模排名。</p><p><strong>先后区别：</strong>重点专题预留完整页面编排，优先取得代表案例和可用材料；覆盖类先按已有内容收录，不要求凑齐每一种卡片。商品图与写作仍是首先比较新增价值的两项。</p><div className="ec-two">{editorialPlan.map(p=><article key={p.id} id={'plan-'+p.id}><small>{p.level}</small><h3>{p.name} · {p.entry}</h3><p><strong>为什么这样排：</strong>{p.reason}</p><p><strong>首页与专题：</strong>{p.home}</p><p><strong>内容组合：</strong>{p.cards}</p><p><strong>继续制作：</strong>{p.tool}</p><p><strong>谁负责：</strong>{p.people}</p><p className="ec-muted">{p.hold}</p><Link href={p.source} target="_blank" rel="noopener noreferrer">任务与依据 ↗</Link></article>)}</div><p>以上是推荐配置，尚未调整真实C端首页。案例、教程、资产和问题各自独立发布，专题维护关联；MakeNow项目导入与成果回流尚需集成验收。</p></section>}
