'use client';
/* oxlint-disable next/no-img-element -- Local prototype artwork and user-selected image previews. */
import {useState,useEffect,useRef} from 'react';
type Item={id:number;type:string;prompt:string;image:string;ratio:string};
export default function CreationWorkbench({active,seed,notify}:{active:boolean;seed:{title:string;image:string}|null;notify:(s:string)=>void}){
 const [type,setType]=useState('图片生成'),[prompt,setPrompt]=useState(''),[ratio,setRatio]=useState('1:1'),[model,setModel]=useState('Seedream 5.0'),[refs,setRefs]=useState<string[]>([]),[busy,setBusy]=useState(false),[history,setHistory]=useState<Item[]>([]),[preview,setPreview]=useState<Item|null>(null),[activity,setActivity]=useState('不参加活动');const timer=useRef<ReturnType<typeof setTimeout>|null>(null);
 const [previousSeed,setPreviousSeed]=useState(seed);
 if(active&&seed&&seed!==previousSeed){setPreviousSeed(seed);setType('图片生成');setPrompt(seed.title);setRefs(['/home-prototype/'+seed.image+'.png']);}
 useEffect(()=>()=>{if(timer.current)clearTimeout(timer.current);},[]);
 const generate=()=>{if(!prompt.trim()||busy)return;const item={id:Date.now(),type,prompt,ratio,image:seed?.image||'cat'};setBusy(true);timer.current=setTimeout(()=>{setHistory(h=>[...h,item]);setBusy(false);},1200);};
 if(!active)return null;
 return <section className="hp-workbench"><div className="hp-session">{history.filter(i=>i.type===type).length===0&&!busy?<div className="hp-intro"><img src="/home-prototype/icons/sparkling-line.svg" alt=""/><p>AI 灵感工作台</p><h2>输入提示词，生成你想要的内容</h2><span>图片、剧本与视频，让灵感成形</span></div>:history.filter(i=>i.type===type).map(i=><article className="hp-session-item" key={i.id}><p>{i.prompt}</p>{i.type==='剧本创作'?<div className="hp-script"><h3>夏日来信</h3><p>海边的小镇，一封未寄出的信。</p><p>镜头一：午后阳光照进窗边，主角翻开旧日记。</p><p>镜头二：沿着白色石阶走向海边，风掀起信纸。</p><p>镜头三：落日下，主角收起信，微笑着继续向前。</p></div>:<button className="hp-session-image" onClick={()=>setPreview(i)}><img style={{aspectRatio:i.ratio.replace(':','/')}} src={'/home-prototype/'+i.image+'.png'} alt={i.type==='视频生成'?'视频结果封面':'生成结果'}/></button>}<div className="hp-session-actions"><button onClick={()=>{setPrompt(i.prompt);notify('已填入原提示词');}}>再次编辑</button><button onClick={()=>setPreview(i)}>查看结果</button>{i.type!=="剧本创作"&&<a href={'/home-prototype/'+i.image+'.png'} download>下载{type==='视频生成'?'封面':''}</a>}</div></article>)}{busy&&<div className="hp-loading">正在生成…</div>}</div>
 <div className="hp-composer"><nav>{['图片生成','剧本创作','视频生成'].map(t=><button key={t} className={type===t?'active':''} onClick={()=>{setType(t);setModel(t==='视频生成'?'Seedance 2.0':t==='剧本创作'?'剧本创作':'Seedream 5.0');}}>{t}</button>)}</nav><div className="hp-reference-row">{refs.map((src,i)=><div key={src}><img src={src} alt="参考图"/><button aria-label="移除参考图" onClick={()=>setRefs(r=>r.filter((_,n)=>n!==i))}>×</button></div>)}{type!=='剧本创作'&&<label className="hp-reference-add">＋ 添加参考图<input type="file" accept="image/*" onChange={e=>{const f=e.target.files?.[0];if(!f)return;if(f.size>10485760){notify('请选择10MB以内的图片');return;}const r=new FileReader();r.onload=()=>{const data=r.result;if(typeof data==='string')setRefs(v=>[...v.slice(-3),data]);};r.readAsDataURL(f);}}/></label>}</div><textarea aria-label="创作提示词" value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder={type==='剧本创作'?'输入故事设定、人物关系或短片想法…':type==='视频生成'?'描述镜头、角色动作和画面氛围…':'描述你想生成的画面…'}/><div className="hp-composer-toolbar"><select aria-label="模型" value={model} onChange={e=>setModel(e.target.value)}>{(type==='图片生成'?['Seedream 5.0','Nano Banana Pro']:type==='视频生成'?['Seedance 2.0']:['剧本创作']).map(m=><option key={m}>{m}</option>)}</select>{type!=='剧本创作'&&<select aria-label="画面比例" value={ratio} onChange={e=>setRatio(e.target.value)}>{['1:1','4:3','3:4','9:16','16:9'].map(r=><option key={r}>{r}</option>)}</select>}<select aria-label="投稿活动" value={activity} onChange={e=>setActivity(e.target.value)}><option>不参加活动</option><option>一起画个夏天</option></select><button className="hp-primary" onClick={generate} disabled={!prompt.trim()||busy}>{busy?'生成中':'生成'} ↑</button></div></div>
 {preview&&<div className="hp-result-overlay"><button onClick={()=>setPreview(null)}>← 返回工作台</button>{preview.type==='剧本创作'?<div className="hp-script"><h2>夏日来信</h2><p>海边的小镇，一封未寄出的信。用三个镜头，讲述一次重新出发。</p></div>:<img src={'/home-prototype/'+preview.image+'.png'} alt="结果预览"/>}<div><button onClick={()=>{notify('已保存到当前生成记录');setPreview(null);}}>保存结果</button><button onClick={()=>{setPrompt(preview.prompt);setPreview(null);}}>继续编辑</button></div></div>}
 </section>;
}

