const fs=require('fs');
const path=require('path');
const dir=__dirname;
const data=JSON.parse(fs.readFileSync(path.join(dir,'findings.json'),'utf8'));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pages=[['home','首页'],['community','社区首页'],['work','作品详情'],['post','帖子详情'],['circles','圈子列表'],['circle','圈子详情'],['tutorial','教程详情'],['topics','专题列表'],['topic','专题详情'],['apps','AI应用列表'],['app','应用详情'],['creation-entry','创作与发布入口'],['create','AIGC生成'],['post-edit','发布作品'],['post-publish','发布帖子'],['mine','我的'],['my-relations','关注作者'],['my-circles','我的圈子'],['profile-edit','编辑资料'],['login','登录'],['notifications','消息中心'],['activities','活动列表'],['activity','活动详情'],['points','积分中心'],['checkin','每日签到'],['invite','邀请有礼'],['shop','AI商城'],['shop-exchange','兑换弹层'],['shop-records','兑换记录'],['search','搜索'],['author','作者主页'],['resource','资源详情']];

const done=data.findings.filter(f=>f.disposition!=='研发实现参考，不要求原型补齐');
const reference=data.findings.filter(f=>f.disposition==='研发实现参考，不要求原型补齐');
const html=`<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>移动原型审查 · 按演示边界收敛</title><style>body{font:16px/1.8 system-ui,sans-serif;color:#242830;background:#f7f8fa;margin:0}main{max-width:980px;margin:auto;padding:32px 24px}h1{font-size:26px}h2{font-size:20px;margin-top:32px}table{border-collapse:collapse;width:100%;background:white}td,th{padding:12px;border:1px solid #ddd;text-align:left;vertical-align:top}p{margin:12px 0}.note{padding:18px;background:#eaf1ed;border-left:4px solid #4b8265}small{color:#666}figure{display:inline-block;margin:8px;vertical-align:top}img{max-width:280px;max-height:440px;object-fit:contain}a{color:#245f98}details{margin:12px 0;padding:12px;background:white}code{font-size:12px;overflow-wrap:anywhere}</style><main><h1>移动端原型与需求审查</h1><p><small>2026-10-03 · 已按演示原型边界重新收敛</small></p><div class="note"><b>原型用于清楚演示页面和操作，不模拟完整业务系统。</b><p>上一版14项不再作为原型缺陷总数或优先级清单。真实鉴权、审核处理、数据同步、任务标识、并发与服务端校验等，由页面需求定义、研发实现。</p></div><h2>本轮处理</h2><table><tr><th>范围</th><th>处理结果</th></tr><tr><td>收藏教程</td><td>名称改为“产品背景与光线的搭配”，明确跳转对应产品教程。</td></tr><tr><td>活动返回</td><td>优先返回实际来源；无来源直达时回活动中心。</td></tr><tr><td>专题状态</td><td>移除“部分完成／单项”的阅读台入口；少量内容、关联失效在同一模板和需求中表达。</td></tr><tr><td>邀请活动需求</td><td>说明当前邀请有礼类型直接进入邀请页，其他活动复用详情模板，不增建页面。</td></tr><tr><td>商城需求</td><td>列表用商品名称表达权益，完整说明在兑换确认弹层展示，保持卡片简洁。</td></tr></table><h2>原型与需求各自负责什么</h2><ul><li>原型：正常内容优先，布局可读，入口明确，主要按钮可演示，跳转内容相符，必要状态能解释清楚。</li><li>需求：字段约束、业务条件、状态触发、错误恢复、权限和上下游关系写清，不夹杂实现过程。</li><li>研发：鉴权、持久化、跨设备同步、任务和评论标识、动态配置与排序、接口校验、并发及幂等。</li></ul><h2>验证范围</h2><p>TypeScript与85条页面需求结构检查通过。本轮浏览器核对收藏教程对应关系、积分中心进入活动再返回、活动直达返回列表、专题正常展示与状态入口移除。原审查的32页首屏证据保留作历史观察，不视为真实业务验收。</p><h2>调整后的截图</h2><figure><a href="after-topic.jpg"><img src="after-topic.jpg" alt="专题调整后"></a><figcaption>专题移除两项独立状态入口</figcaption></figure><figure><a href="after-favorite-tutorial.jpg"><img src="after-favorite-tutorial.jpg" alt="收藏教程目标"></a><figcaption>收藏进入对应教程</figcaption></figure><h2>原审查记录的去向</h2><p>以下仅用于追溯，不构成新的原型待办；不要求为覆盖这些实现分支再新增演示页面。</p><table><tr><th>原编号与观察</th><th>本轮归类</th></tr>${data.findings.map(f=>'<tr><td>'+esc(f.id+' '+f.title)+'</td><td>'+esc(f.disposition)+'</td></tr>').join('')}</table><details><summary>查看研发参考的原始观察</summary>${reference.map(f=>'<p><b>'+esc(f.id+' '+f.title)+'</b><br>'+esc(f.detail)+'<br><small>需求：'+esc(f.contract)+'</small></p>').join('')}</details><details><summary>原始32页首屏截图</summary>${pages.map(([id,t])=>'<a style="display:inline-block;margin:6px" href="'+id+'.jpg">'+esc(t)+'</a>').join('')}</details><p><small>本地静态原型，不代表真实账号、发布、积分、授权或服务端流程已实现。没有修改线上系统。</small></p></main></html>`;
fs.writeFileSync(path.join(dir,'index.html'),html);
console.log('Report updated to prototype scope');
