const fs=require('fs');const p='app/community-options/b-prototype/';
let s=fs.readFileSync(p+'operations-management.tsx','utf8');
s=s.replace('Card,Collapse,','Card,').replace(',Tag,Typography}',',Tag}');
s=s.replace("import dayjs from 'dayjs';","import dayjs from 'dayjs';\nimport {UserIdentity} from './user-identity';");
s=s.replace("const [logs,setLogs]=useState(false);","const [logs,setLogs]=useState(false);const [rulesOpen,setRulesOpen]=useState(false);");
s=s.replace('<div><Typography.Title level={3}>{spec[1]}</Typography.Title><p>{rules[bucket]}</p></div><Space>','<Space><Button onClick={()=>setRulesOpen(true)}>走查规则</Button>');
s=s.replace(/<Collapse className="om-gap" items=\{\[\{key:'rules',label:'页面规则与验收',children:<>(.*?)<\/>\}\]\}\/>/s,'<Modal title="走查规则" open={rulesOpen} onCancel={()=>setRulesOpen(false)} footer={<Button onClick={()=>setRulesOpen(false)}>关闭</Button>}>$1</Modal>');
s=s.replaceAll('showSizeChanger:true,pageSizeOptions:[20,50,100]','showSizeChanger:false,showQuickJumper:true');
s=s.replaceAll('pagination={{pageSize:5}}','pagination={{pageSize:5,showQuickJumper:true,showSizeChanger:false}}').replaceAll('pagination={{pageSize:10}}','pagination={{pageSize:10,showQuickJumper:true,showSizeChanger:false}}');
s=s.replaceAll('<Button size="small"','<Button type="link" size="small"');
s=s.replaceAll("{title:'用户',dataIndex:'user'}","{title:'用户',dataIndex:'user',width:180,render:(v:unknown)=><UserIdentity id={str(v)}/>} ");
s=s.replace("if(bucket==='submissions')return [","if(bucket==='submissions')return [{title:'投稿人',width:180,render:(_:unknown,r:OpRow)=><UserIdentity id={str(r.user)}/>},");
s=s.replace("if(bucket==='checkin')return [","if(bucket==='checkin')return [{title:'用户',width:180,render:(_:unknown,r:OpRow)=>r.user?<UserIdentity id={str(r.user)}/>: '—'},");
s=s.replace("if(bucket==='invite')return [","if(bucket==='invite')return [{title:'邀请人',width:180,render:(_:unknown,r:OpRow)=>r.inviter?<UserIdentity id={str(r.inviter)}/>: '—'},{title:'被邀请人',width:180,render:(_:unknown,r:OpRow)=>r.invitee?<UserIdentity id={str(r.invitee)}/>: '—'},");
fs.writeFileSync(p+'operations-management.tsx',s);
s=fs.readFileSync(p+'platform-management.tsx','utf8');
s=s.replace("import dayjs from 'dayjs';","import dayjs from 'dayjs';\nimport {UserIdentity} from './user-identity';");
s=s.replace('render:(name:string,r)=><><Button','render:(name:string,r)=>page===\'users\'?<UserIdentity id={r.id} name={name} avatar={String(r.avatar||\'\')} onClick={()=>setDetail(r)}/>:<><Button');
s=s.replaceAll("dataIndex:'user',width:160","dataIndex:'user',width:200,render:(id:string)=>{const u=data.users.find(x=>x.id===id);return <UserIdentity id={id} name={u?.name} avatar={String(u?.avatar||'')}/>}");
s=s.replaceAll("dataIndex:'user',width:150","dataIndex:'user',width:200,render:(id:string)=>{const u=data.users.find(x=>x.id===id);return <UserIdentity id={id} name={u?.name} avatar={String(u?.avatar||'')}/>}");
s=s.replaceAll('<h1>{titles[page]}</h1>','');
s=s.replace('<Button onClick={()=>setRuleOpen(!ruleOpen)}>页面规则</Button>','<Button onClick={()=>setRuleOpen(true)}>走查规则</Button>');
s=s.replace('{ruleOpen&&<Alert title={rules} type="info" closable={{onClose:()=>setRuleOpen(false)}}/>}','<Modal title="走查规则" open={ruleOpen} onCancel={()=>setRuleOpen(false)} footer={<Button onClick={()=>setRuleOpen(false)}>关闭</Button>}><p>{rules}</p></Modal>');
s=s.replaceAll('showSizeChanger:true,pageSizeOptions:[20,50,100]','showSizeChanger:false,showQuickJumper:true').replaceAll('showSizeChanger:true','showSizeChanger:false,showQuickJumper:true');
s=s.replace('<Card size="small"><Space wrap>','<Card size="small" className="pm-filter"><Space wrap>');
fs.writeFileSync(p+'platform-management.tsx',s);
