'use client';
/* Local design assets retain native image ratios; no remote optimizer is used in this preview. */
/* oxlint-disable next/no-img-element */
import Link from '@/components/research-link';
import {useEffect,useRef,useState} from 'react';
import './style.css';
type Item={id:number;name:string;scene:string;group:string;image?:string;ratio?:string;kind:string;author:string;uses:number;input:string;output:string;text?:string};
const scenes=['全部','电商营销','本地经营','知识内容','角色故事','人像影像','视觉设计','写作编辑','职场学习','IP文创'];
const items:Item[]=[
{id:1,name:'商品换景',scene:'电商营销',group:'商品上架',image:'perfume',kind:'AI应用',author:'鹿与光',uses:826,input:'商品原图',output:'场景商品图'},
{id:2,name:'品牌海报延展',scene:'视觉设计',group:'视觉创作',image:'poster',kind:'AI应用',author:'ChenQ',uses:684,input:'主视觉与文案',output:'系列海报'},
{id:3,name:'角色三视图',scene:'角色故事',group:'视觉创作',image:'character',kind:'AI应用',author:'山野',uses:969,input:'角色参考图',output:'正面、侧面、背面图'},
{id:4,name:'长文提炼',scene:'职场学习',group:'文字处理',kind:'AI应用',author:'林小言',uses:512,input:'长文或会议记录',output:'摘要与行动事项',text:'让三页会议记录，\n变成一张行动清单。'},
{id:5,name:'商品细节精修',scene:'电商营销',group:'商品上架',image:'perfume',kind:'AI应用',author:'拾光',uses:642,input:'商品照片',output:'精修图片'},
{id:6,name:'文案精简',scene:'写作编辑',group:'文字处理',kind:'AI应用',author:'她与海',uses:438,input:'待修改的文章',output:'保留原意的精简稿',text:'删掉重复，\n留下自己的语气。'},
{id:7,name:'IP形象设定',scene:'IP文创',group:'视觉创作',image:'character',kind:'AI应用',author:'夏目川',uses:391,input:'角色描述',output:'角色设定图'},
{id:8,name:'开业海报',scene:'本地经营',group:'视觉创作',image:'poster',kind:'AI应用',author:'Tide',uses:273,input:'门店信息与图片',output:'竖版开业海报'},
{id:9,name:'知识卡片',scene:'知识内容',group:'文字处理',kind:'AI应用',author:'小简',uses:317,input:'资料与知识点',output:'结构化知识卡片',text:'一个概念，\n一张卡片讲清楚。'}];
const asset='/community-design/';
function Icon({name}:{name:string}){return <img className="ci-icon" src={`${asset}icons/${name}-line.svg`} alt=""/>}
export default function Interface(){
const [view,setView]=useState('apps-a'),[scene,setScene]=useState('全部'),[query,setQuery]=useState(''),[sort,setSort]=useState('推荐'),[filter,setFilter]=useState(false),[format,setFormat]=useState('全部'),[saved,setSaved]=useState<number[]>([]),[active,setActive]=useState<Item|null>(null),[notes,setNotes]=useState(false),[notice,setNotice]=useState('');
const dialog=useRef<HTMLDialogElement>(null),toastTimer=useRef<ReturnType<typeof setTimeout>|null>(null);
useEffect(()=>()=>{if(toastTimer.current)clearTimeout(toastTimer.current)},[]);
useEffect(()=>{const id=requestAnimationFrame(()=>{const v=new URLSearchParams(location.search).get('view');if(v&&['home','apps-a','apps-b'].includes(v))setView(v)});return()=>cancelAnimationFrame(id)},[]);
useEffect(()=>{if(active)dialog.current?.showModal();else dialog.current?.close()},[active]);
function change(v:string){setView(v);setScene('全部');setQuery('');setFormat('全部');setActive(null);history.replaceState(null,'',`?view=${v}`)}
function flash(s:string){if(toastTimer.current)clearTimeout(toastTimer.current);setNotice(s);toastTimer.current=setTimeout(()=>setNotice(''),3000)}
const home=view==='home';
const list=items.filter(i=>(scene==='全部'||i.scene===scene)&&(!query||[i.name,i.scene,i.input,i.output].join(' ').includes(query))&&(format==='全部'||(format==='图片'?!!i.image:!i.image))).sort((a,b)=>sort==='最多使用'?b.uses-a.uses:sort==='最新'?b.id-a.id:a.id-b.id);
function card(raw:Item){const kind=home?['AI应用','作品','画布项目','讨论','工作流','教程'][(raw.id-1)%6]:'AI应用';const i=home?{...raw,name:({2:'光与形 · 海报练习',3:'角色设定画布',4:'会议摘要应该保留哪些细节？',5:'商品精修工作流',6:'怎样删掉文章中的重复',8:'蓝与白的视觉练习',9:'把知识整理成一页'} as Record<number,string>)[raw.id]||raw.name}:raw;return <article className="ci-card" key={i.id}>
<button className="ci-cover" onClick={()=>setActive({...i,kind})} aria-label={`查看${i.name}`}>
{i.image?<img className="ci-art" src={`${asset}${i.image}.png`} alt={i.output} width={i.image==='poster'?1024:1536} height={i.image==='poster'?1536:i.image==='character'?1536:1024}/>:<div className="ci-textcover"><span>文字工作室</span><strong>{i.text}</strong><p>{i.input} → {i.output}</p></div>}
<span className="ci-tags"><span>{home?kind:i.scene}</span></span></button>
<button className="ci-title" onClick={()=>setActive({...i,kind})}>{i.name}</button>
{!home&&<p className="ci-summary">{i.input} → {i.output}</p>}
<div className="ci-meta"><span className="ci-author"><span>{i.author.slice(0,1)}</span>{i.author}</span><span className="ci-count"><Icon name={kind==='作品'?'heart':kind==='讨论'?'chat-1':'play'}/>{kind==='作品'?'赞':kind==='讨论'?'回复':kind==='工作流'?'运行':kind==='画布项目'?'复用':kind==='教程'?'收藏':'使用'} {i.uses}</span><button aria-label={`${saved.includes(i.id)?'取消收藏':'收藏'}${i.name}`} aria-pressed={saved.includes(i.id)} onClick={()=>setSaved(saved.includes(i.id)?saved.filter(n=>n!==i.id):[...saved,i.id])}><Icon name={saved.includes(i.id)?'check':'bookmark'}/>{Math.floor(i.uses/12)+(saved.includes(i.id)?1:0)}</button></div></article>}
return <div className="ci-root">
<header className="ci-header"><Link className="ci-brand" href="?view=home" onClick={e=>{e.preventDefault();change('home')}}><img src="/brand/duoyuan-shiguang-logo-mark.svg" alt=""/><b>多元拾光</b></Link><nav aria-label="主导航">{['发现','专题','AI应用','圈子','模型广场'].map((n,k)=><button key={n} className={(home?k===0:k===2)?'selected':''} onClick={()=>k===0?change('home'):k===2?change('apps-a'):flash(`${n}页面不在本次预览范围`)}>{n}</button>)}</nav><label className="ci-search"><Icon name="search"/><input aria-label="搜索应用与内容" placeholder={home?'搜索内容与应用':'搜索应用'} value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="ci-utilities">{[['megaphone','活动'],['shopping-bag-3','商城'],['gift','邀请']].map(([icon,t])=><button key={t} aria-label={t} onClick={()=>flash(`${t}入口保留，当前设计预览不接入业务`)}><Icon name={icon}/><span>{t}</span></button>)}<button aria-label="通知" onClick={()=>flash('暂无新通知')}><Icon name="notification-3"/></button><button className="ci-account" onClick={()=>flash('个人中心、积分与签到沿用现有业务')}><span>积分 —</span><span><Icon name="calendar-check"/>每日签到</span><Icon name="user"/><Icon name="arrow-down-s"/></button></div></header>
<main className="ci-main">
{home?<section className="ci-hero" aria-label="精选内容"><button className="ci-banner" onClick={()=>flash('活动详情将在活动中心承接')}><img src={`${asset}poster.png`} alt="纸与织物的创作"/><div><span>创作活动</span><h1>让创作，被看见</h1><b>查看活动 <Icon name="arrow-right-s"/></b></div></button><div className="ci-topics">{[['电商营销','perfume'],['视觉设计','poster'],['写作编辑',''],['角色故事','character']].map(([name,img])=><button key={name} onClick={()=>setScene(name)}>{img?<img src={`${asset}${img}.png`} alt=""/>:<div className="ci-topic-text">文字的力量</div>}<strong>{name}</strong></button>)}</div></section>:<section className="ci-appintro"><div><p>创作工具</p><h1>AI应用</h1></div><div className="ci-shortcuts"><span>快捷使用</span>{items.slice(0,4).map(i=><button key={i.id} onClick={()=>setActive(i)}>{i.image?<img src={`${asset}${i.image}.png`} alt=""/>:<Icon name="chat-1"/>}{i.name}<Icon name="arrow-right-s"/></button>)}</div></section>}
<div className="ci-controls"><nav aria-label="场景筛选">{scenes.map(s=><button key={s} aria-pressed={scene===s} className={scene===s?'selected':''} onClick={()=>setScene(s)}>{s}</button>)}</nav><div className="ci-sort"><select aria-label="排序" value={sort} onChange={e=>setSort(e.target.value)}><option>推荐</option><option>最新</option><option>最多使用</option></select><button aria-expanded={filter} aria-controls="ci-output-filter" onClick={()=>setFilter(!filter)}><Icon name="equalizer"/>筛选</button></div></div>
{filter&&<div id="ci-output-filter" className="ci-filter"><span>输出形式</span>{['全部','图片','文字'].map(f=><button key={f} aria-pressed={format===f} onClick={()=>setFormat(f)}>{f}</button>)}<button onClick={()=>{setFormat('全部');setQuery('');setScene('全部')}}>重置</button></div>}
{list.length===0?<div className="ci-empty"><h2>没有找到相关内容</h2><p>换个关键词，或查看其他场景。</p><button onClick={()=>{setQuery('');setScene('全部');setFormat('全部')}}>查看全部</button></div>:view==='apps-b'?['商品上架','视觉创作','文字处理'].map(g=>{const group=list.filter(i=>i.group===g);return group.length>0&&<section key={g} className="ci-group"><h2>{g}<span>{group.length} 个应用</span></h2><div className="ci-masonry">{group.map(card)}</div></section>}):<section className="ci-masonry" aria-label={home?'发现内容':'应用列表'}>{list.map(card)}</section>}
</main>
<aside className="ci-review" aria-label="设计方案切换"><Link href="/community-options/home-draft">研究室</Link><span/><button className={home?'active':''} onClick={()=>change('home')}>发现页</button><button className={view==='apps-a'?'active':''} onClick={()=>change('apps-a')}>应用 · 方案一</button><button className={view==='apps-b'?'active':''} onClick={()=>change('apps-b')}>应用 · 方案二</button><button onClick={()=>setNotes(!notes)}>设计说明</button></aside>
{notes&&<aside className="ci-notes"><button aria-label="关闭设计说明" onClick={()=>setNotes(false)}><Icon name="close"/></button><h2>设计范围</h2><p>发现页独有Banner与四专题。全局导航保持单行黑白灰。AI应用页使用紧凑快捷入口。</p><p>方案一按内容效果浏览，方案二按任务分组；两版共用同一批应用。等宽可变高卡片保留横、竖、方图比例；文字封面与界面文字用HTML排版。列距24px，卡片间距32px。</p><p>搜索、场景、排序、输出形式筛选、收藏与详情可操作。应用、作者、统计及生成素材为设计样例。未接入模型、上传、支付与真实使用统计；详情不执行生成。</p><p>次数来自对应使用事件的产品设想，不以浏览量替代。活动、商城、邀请与个人中心仅保留入口。此页面不替代正式C端PRD。</p><p>快捷入口当前由示例配置提供；最近使用须登录及实际记录后才能展示，不虚构个人历史。</p></aside>}
{notice&&<output className="ci-toast">{notice}</output>}
<dialog ref={dialog} className="ci-dialog" onCancel={()=>setActive(null)}>{active&&<><button className="ci-dialog-close" aria-label="关闭详情" onClick={()=>setActive(null)}><Icon name="close"/></button><div className="ci-detail-art">{active.image?<img src={`${asset}${active.image}.png`} alt={active.output}/>:<h2>{active.text}</h2>}</div><div className="ci-detail-copy"><small>{active.scene} · {active.kind}</small><h2>{active.name}</h2><p>{active.author}</p><h3>{active.kind==='讨论'?'正在讨论':active.kind==='作品'?'创作思路':'准备材料'}</h3><p>{active.kind==='讨论'?'摘要越短，越容易漏掉分歧和待确认的问题。你会单独列出，还是保留在正文中？':active.kind==='作品'?'围绕同一主题尝试构图、光线与版式，让作品保持视觉联系。':active.input}</p><h3>{active.kind==='讨论'?'交流重点':active.kind==='教程'?'学习步骤':'内容要点'}</h3><p>{active.kind==='讨论'?'保留结论依据、明确待办负责人、标记仍有分歧的事项。':active.kind==='教程'?'标出重复信息，调整句子顺序，核对是否改变原意。':active.output}</p>{['AI应用','工作流','画布项目'].includes(active.kind)&&<><button className="ci-primary" onClick={()=>flash('当前为设计预览，尚未接入制作服务')}>了解使用条件 <Icon name="arrow-right-s"/></button><p className="ci-detail-note">接入后将在此确认材料要求与费用。</p></>}</div></>}</dialog>
</div>}
