'use client';
import {useEffect,useState} from 'react';
import Link from '@/components/research-link';
import './style.css';
import {topics} from './topics';
import {caseChoices} from '../../content-system/case-choices';
export default function Page(){const [topic,setTopic]=useState('ecommerce'),[view,setView]=useState('专题'),[notes,setNotes]=useState(false);const s=topics.find(t=>t.id===topic)!;useEffect(()=>{const id=window.location.hash.slice(1);if(topics.some(t=>t.id===id))setTopic(id)},[]);
return <main className="mc"><aside className="mc-review"><Link href="/community-options/content-system">← 内容配置与社区结构</Link><span>概念稿 · 图中内容为虚构示意</span><button onClick={()=>setNotes(!notes)} aria-expanded={notes}>设计说明</button></aside>
{notes&&<section className="mc-notes"><button onClick={()=>setNotes(false)}>关闭说明</button><h2>共同骨架，任务各有重点</h2><p>九张生图用于比较视觉组织；下方详情用于检查字段与路径。真实研究证据通过独立链接阅读。图片里的文案、人物、产品和图解不作为真实案例或功能事实。</p><p>专题连接案例、教程、资产和讨论；创作交流保留独立入口。页面为研究设计输入，不替代真实C端基线。MakeNow已有画布，示例项目、复制、导入和回流尚未接入；学习与文稿继续在适合工具中完成。</p><p>切换专题保留所处详情类型；所有制作与反馈动作均为未接入状态，不收集素材，不伪造下载、生成或提交成功。</p></section>}
<header className="mc-title"><p>多元拾光 / 多场景专题</p><h1>九类任务，一起看</h1><p>比较成果预览、方法与材料的位置，再看使用者如何进入详情。</p></header>
<nav className="mc-topics" aria-label="专题选择">{topics.map(t=><button key={t.id} aria-pressed={s.id===t.id} onClick={()=>{setTopic(t.id);window.history.replaceState(null,'','#'+t.id)}}>{t.name}</button>)}</nav>
<div className="mc-tabs" role="group" aria-label="页面选择">{['专题','案例详情','教程','资产详情','问题与改版'].map(v=><button key={v} aria-pressed={view===v} onClick={()=>setView(v)}>{v}</button>)}</div>
<section className="mc-view" aria-live="polite"><div className="mc-view-head"><h2>{s.name} · {view}</h2><a href={s.evidence} target="_blank" rel="noopener noreferrer">真实研究依据 ↗</a></div>
{view==='专题'?<><figure><a href={'/product-concepts/'+s.image} target="_blank" rel="noopener noreferrer"><img src={'/product-concepts/'+s.image} alt={s.name+'专题生图概念稿，内容为虚构布局示意'} /></a><figcaption>点击放大 · 图中示例不代表已发布内容、可用资产或验证结果。</figcaption></figure><div className="mc-next"><div><h3>{s.context}</h3><p>{s.title}</p></div><button onClick={()=>setView('案例详情')}>进入案例详情 →</button><button onClick={()=>setView('资产详情')}>查看材料条件 →</button></div></>:view==='案例详情'?<div className="mc-detail"><article><small>案例结构示例</small><h2>{s.title}</h2><h3>原始条件</h3><p>{s.input}</p><h3>两种做法</h3><p>{caseChoices[s.id].alternatives}</p><h3>本例拟采用的取舍</h3><p>{caseChoices[s.id].reason}</p><h3>应展示的成果</h3><p>{caseChoices[s.id].result}</p><p>图片是布局示意；实际成果、候选和采用记录由授权案例补充。</p></article><aside><h3>接着看</h3><button onClick={()=>setView('教程')}>看具体步骤 →</button><button onClick={()=>setView('资产详情')}>查看材料条件 →</button><button onClick={()=>setView('问题与改版')}>看相关问题 →</button></aside></div>:view==='教程'?<div className="mc-detail"><article><small>结构示例 · 非真实用户案例</small><h2>{view==='教程'?s.name+'：步骤与检查':s.title}</h2><h3>准备什么</h3><p>{s.input}</p><h3>关键做法</h3><ol>{s.steps.map(x=><li key={x}>{x}</li>)}</ol><h3>怎样判断完成</h3><p>{s.check}</p><h3>修改记录应展示什么</h3><p>原始输入、问题区域、修改动作、最终选择及理由。没有取得的候选与采用反馈保留为空，不用概念图补成过程证据。</p></article><aside><h3>相关材料</h3><p>{s.asset}</p><p>{s.format}</p><button onClick={()=>setView('资产详情')}>查看条件与可改范围 →</button><button onClick={()=>setView(view==='教程'?'案例详情':'教程')}>{view==='教程'?'回看案例取舍':'查看步骤教程'} →</button><h3>相关问题</h3><p>{s.issue}</p><button onClick={()=>setView('问题与改版')}>看修改路径 →</button></aside></div>:view==='资产详情'?<div className="mc-detail"><article><small>拟议资产 · 未绑定真实文件</small><h2>{s.asset}</h2><dl><dt>形式</dt><dd>{s.format}</dd><dt>可以修改</dt><dd>{s.editable}</dd><dt>素材要求</dt><dd>{s.input}</dd><dt>使用条件</dt><dd>{s.condition}</dd><dt>作者、许可与版本</dt><dd>接入实际文件时核对；当前没有可下载资产。</dd></dl><h3>没有文件，仍可先学方法</h3><p>回到案例与研究来源，按步骤准备自己的材料。外部工具依照原作者说明使用。</p><button onClick={()=>setView('案例详情')}>返回案例与准备要求 →</button></article><aside><h3>继续制作</h3><p>{s.toolPath}</p><button disabled>{s.toolLabel}</button><p>这里不上传材料、不运行生成。</p><button onClick={()=>setView('问题与改版')}>查看相关问题 →</button></aside></div>:<div className="mc-detail"><article><small>问题结构示例 · 非真实反馈</small><h2>{s.issue}</h2><h3>描述问题</h3><p>附可公开的局部、所用方法和版本、希望保留的内容，以及已经试过的处理。</p><h3>可能的修改路径</h3><p>{s.fix}</p><h3>回应之后</h3><p>使用者比较修改结果，补充是否采用及原因；如资产需要更新，再关联新版本。收到回复、采用建议和完成修复分别记录。</p></article><aside><h3>检查标准</h3><p>{s.check}</p><button disabled>提交反馈 · 样板未接入</button><button onClick={()=>setView('资产详情')}>返回资产条件 →</button></aside></div>}
</section><footer><Link href="/community-options/scenarios">全部九类任务</Link><Link href="/community-options/content-system">内容配置与产品结构</Link><Link href={"/community-options/home-draft#"+s.id}>返回首页对应场景</Link></footer></main>}
