export const topics = [
  {id:'ecommerce',name:'电商营销',image:'topic-ecommerce-v2.png',title:'一件商品，完成三种用途的图片',input:'有使用权的商品实拍、准确卖点与用途；包装、颜色和标志需要保留。',steps:['确认主图、场景图与详情图分别表达什么','选择背景与构图，保留原始商品对照','逐张核对包装、文字、配件和图序'],check:'每张图适合对应用途；细节与真实商品一致。',asset:'商品图画布',format:'画布项目',editable:'参考、构图、图序与配套文字；商品信息由使用者确认。',condition:'需真实商品素材及对应项目许可；项目复制与导出能力待核对。',issue:'背景换好了，标签却变了',fix:'回到原图核对问题区域，缩小修改范围，保留采用前后的对照。',evidence:'/community-options/cases/ecommerce#cases',context:'商品保真与成套交付',toolPath:'MakeNow 画布（示例未接入）',toolLabel:'画布项目待绑定'},
  {id:'character',name:'角色故事',image:'topic-character-v1.png',title:'同一个角色，完成一段连贯故事',input:'原创或获授权角色、人物关系、情节梗概；先写清固定特征与可变项。',steps:['用角色设定页固定轮廓、服装和标志物','先排分镜，再逐格制作并保留候选','连读画面，只修改人物或叙事偏离的格'],check:'角色、道具、视线与事件顺序可连续理解。',asset:'角色设定与分镜参考',format:'设定页／画布项目',editable:'故事节点、分镜顺序和可变造型；身份保留项单独列出。',condition:'示例角色为生图虚构；尚未绑定可下载设定文件或MakeNow项目。',issue:'换装后，角色看起来像另一个人',fix:'对照固定身份项，先试一个复杂姿态，再决定是否延展整套。',evidence:'/community-options/scenarios/character#evidence',context:'角色设定与叙事连续性',toolPath:'MakeNow 画布（示例未接入）',toolLabel:'角色项目待绑定'},
  {id:'knowledge',name:'知识图文',image:'topic-knowledge-v2.png',title:'把一个问题讲清楚，并留下出处',input:'明确的问题、适合读者、可追溯原文；图片需说明要解释什么。',steps:['选择来源，记录关键说法与原文位置','把解释结构、配图目的和图注一起写清','逐项核对文字、数据、箭头和示意关系'],check:'事实与推断分开，图和文字对应；更正能定位受影响内容。',asset:'来源表与图解结构',format:'来源清单／图解模板',editable:'来源定位、图注、层级和图形；机制及数据由作者核对。',condition:'图中彩虹仅为视觉占位，不是经科学核验的教程；模板文件及许可待绑定。',issue:'图里的箭头与文字解释不一致',fix:'回查原始依据，修正图或解释；专业机制存疑时请领域人员核稿。',evidence:'/community-options/scenarios/knowledge#evidence',context:'来源、解释与图文核对',toolPath:'资料与图解在适合工具中处理',toolLabel:'工具与文件待接入'},
  {id:'local-business',name:'本地经营',image:'topic-local-business-v1.png',title:'一份活动信息，做成海报、手机宣传图与菜单',input:'已确认的活动、品项、价格、日期、门店与限制条件；实拍和可公开的品牌素材分开准备。',steps:['先确认活动范围和每种投放用途','把价格、日期和门店写入信息表，再调整版式','由商家逐项核对后记录这次改动影响的物料'],check:'价格、日期、门店和限制条件与已确认活动一致。',asset:'活动信息表与宣传版式',format:'信息表／可编辑版式',editable:'活动名称、品项、价格、日期、门店与版式层级；实拍内容按授权替换。',condition:'示例未绑定真实门店、可下载文件或制作入口；图片与品牌素材须有使用权。',issue:'改了活动日期，旧海报还在使用',fix:'从活动信息表回查受影响物料，替换过期版本并保留确认记录。',evidence:'/community-options/scenarios/local-business#evidence',context:'活动信息与门店确认',toolPath:'MakeNow 画布或原设计工具（示例未接入）',toolLabel:'物料项目待绑定'},
  {id:'portrait',name:'人像影像',image:'topic-portrait-v1.png',title:'保留本人特征，统一一组照片',input:'本人或有权授权者允许使用的原片、希望保留和可以调整的部位，以及公开范围。',steps:['先写清人物特征与修改意愿','先统一组照的光线与色调，再调整允许修改的局部','由本人或有权授权者比较候选后确认是否分享'],check:'组照光线与色调协调；人物特征、修改意愿与公开范围得到确认。',asset:'局部调整说明与组照参考画布',format:'编辑说明／画布项目',editable:'局部修饰、排版顺序和说明文字；人物身份特征与公开范围单独确认。',condition:'私人原片由本人保管；示例未绑定照片、可下载资产或MakeNow项目。',issue:'修饰后看起来不像本人',fix:'回到原片比对保留项，撤回过度修改，只调整获得同意的局部。',evidence:'/community-options/scenarios/portrait#evidence',context:'人物特征与分享同意',toolPath:'MakeNow 画布（示例未接入）',toolLabel:'影像项目待绑定'},
  {id:'design',name:'视觉设计',image:'topic-design-v1.png',title:'从一张主视觉，延展出一组可编辑版式',input:'设计简报、品牌约束、已授权字体与素材，以及需要覆盖的画幅和信息层级。',steps:['先读简报，区分固定品牌元素与可变内容','完成主版后再按画幅延展，并保留工程结构','逐张检查层级、字体依赖和导出用途'],check:'品牌一致、信息清楚，且交付范围内的版式可以继续编辑。',asset:'品牌约束与主版工程',format:'设计简报／可编辑工程',editable:'文案、画幅、可变图像和版式延展；固定品牌元素依照简报处理。',condition:'示例未绑定源工程、字体许可或可下载文件；实际兼容性接入时核对。',issue:'延展后信息层级变乱了',fix:'回到主版的层级规则，逐个画幅删减信息并检查字体和留白。',evidence:'/community-options/scenarios/design#evidence',context:'主版约束与系列延展',toolPath:'MakeNow 画布或原设计工具（示例未接入）',toolLabel:'设计工程待绑定'},
  {id:'writing',name:'写作编辑',image:'topic-writing-v1.png',title:'把既有草稿改到作者愿意采用',input:'作者允许编辑的草稿、目标读者、事实来源与希望保留的语气或结论。',steps:['先标注要解决的编辑目标和不能改变的原意','逐段展示改动与理由，并核对事实出处','由作者选择采用、调整或保留原句，并记录取舍'],check:'原意、事实、语气和作者取舍都能回查。',asset:'编辑简报与改稿对照',format:'编辑简报／对照样稿',editable:'句段、结构和表达顺序；事实、引用与作者意图须由作者确认。',condition:'示例不含真实稿件或可下载文件；编辑工具、协作权限与版本记录待接入。',issue:'改顺了文字，却把作者原意改掉了',fix:'回看编辑简报和原句，说明每处改动理由，由作者决定是否采用。',evidence:'/community-options/scenarios/writing#evidence',context:'修改理由与作者选择',toolPath:'适合的文稿工具（示例未接入）',toolLabel:'编辑对照待绑定'},
  {id:'work-learning',name:'职场学习',image:'topic-work-learning-v1.png',title:'把已有资料整理成能讲清楚的汇报或讲义',input:'允许使用的资料、听众或学习目标、原始口径，以及需要更新的时间范围。',steps:['先区分汇报或学习用途，整理资料出处','按听众和目标搭出大纲，再制作讲义或演示','试讲或试用后，补齐理解困难处并更新引用'],check:'听众、原始口径、可讲性和更新位置都能说明。',asset:'资料结构与讲义骨架',format:'资料清单／演示或讲义骨架',editable:'大纲、示例、讲解顺序和复习提示；结论应保留资料定位。',condition:'示例未绑定课程、企业资料、模板文件或制作工具；资料权限和更新责任待确认。',issue:'内容很多，但讲完别人不知道重点',fix:'回到听众目标，压缩为少量主结论，并让每个结论连回资料位置。',evidence:'/community-options/scenarios/work-learning#evidence',context:'用途分路与资料定位',toolPath:'适合的文稿与演示工具（示例未接入）',toolLabel:'讲义骨架待绑定'},
  {id:'ip',name:'IP文创',image:'topic-ip-v1.png',title:'让原创形象延展成一套可辨认的应用内容',input:'原创或获授权的角色设定、文化出处、使用场景，以及希望保留的辨识特征。',steps:['先核对设定和应用场景，列出固定识别项','用复杂动作验证形象，再延展表情和应用版式','检查许可、版本和每个应用中的角色特征'],check:'辨识特征、文化出处、许可与版本关系可核对。',asset:'角色设定页与动作规范',format:'设定页／应用版式',editable:'动作、表情、应用文案和版式；形象核心特征与许可范围单独管理。',condition:'示例为虚构结构，未绑定角色资产、授权文件、可下载素材或制作入口。',issue:'系列动作多了，角色的辨识点丢了',fix:'回到设定页逐项检查固定特征，先修复杂动作，再更新其余应用版本。',evidence:'/community-options/scenarios/ip#evidence',context:'形象设定与应用版本',toolPath:'MakeNow 画布（示例未接入）',toolLabel:'IP项目待绑定'},
];
