
'use client';
/* oxlint-disable next/no-img-element -- Existing local brand and icon assets. */
import {useEffect,useRef,useState,useSyncExternalStore} from 'react';
import {useUnreadMessages,markAllMessagesRead} from './c-prototype/messages';
import {SearchSuggestions,rememberSearch} from './search-suggestions';
import './community-header.css';
import {prototypeStore,pointBalance,followingCount,subscribeAuthorFollowing} from './c-prototype/storage';
import {communityTabs} from './c-prototype/community-navigation';
const icon=(name:string)=><img className="community-icon" src={'/home-prototype/icons/'+name+'-line.svg'} alt=""/>;
export function DesktopHeader({active='home',go,onHome,onModels}:{active?:string;go:(p:string)=>void;onHome?:()=>void;onModels?:()=>void}){
 const unread=useUnreadMessages();
 const followCount=useSyncExternalStore(subscribeAuthorFollowing,followingCount,()=>24);
 const [query,setQuery]=useState(''),[searchOpen,setSearchOpen]=useState(false),[menu,setMenu]=useState(false);
 const area=useRef<HTMLDivElement>(null),userArea=useRef<HTMLDivElement>(null);
 useEffect(()=>{const close=(e:MouseEvent)=>{if(!userArea.current?.contains(e.target as Node))setMenu(false)};const escape=(e:KeyboardEvent)=>{if(e.key==='Escape'){setMenu(false);setSearchOpen(false)}};document.addEventListener('mousedown',close);document.addEventListener('keydown',escape);return()=>{document.removeEventListener('mousedown',close);document.removeEventListener('keydown',escape)}},[]);
 useEffect(()=>{const close=(event:MouseEvent)=>{if(!area.current?.contains(event.target as Node))setSearchOpen(false)};document.addEventListener('mousedown',close);return()=>document.removeEventListener('mousedown',close)},[]);
 useEffect(()=>{const sample=new URLSearchParams(window.location.search).get('reviewOverlay');if(sample==='nav-account')setMenu(true);if(sample==='nav-search')setSearchOpen(true);},[]);
 const navigate=(target:string)=>{setSearchOpen(false);setMenu(false);go(target)};
 const submit=(text:string)=>{const value=text.trim();if(value)rememberSearch(value);setQuery(value);navigate('search?'+(value?'q='+encodeURIComponent(value):'state=idle'))};
 const selected=active==='topic'?'topics':active.startsWith('app')?'apps':['aigc','community','work'].includes(active)?'aigc':['tutorial','tutorials'].includes(active)?'tutorials':['circle','discover-circles','discussion','post'].includes(active)?'circles':active;
 return <header className="community-pc-header"><div className="community-pc-inner">
 <button className="community-logo" aria-label="多元拾光首页" onClick={()=>onHome?onHome():navigate('home')}><img src="/home-prototype/brand-logo.svg" alt="多元拾光"/></button>
 <nav aria-label="主导航" className="community-main-nav">{[['home','首页'],['aigc','AIGC'],['topics','专题'],['apps','AI应用'],['tutorials','教程'],['circles','圈子']].map(([id,label])=><button key={id} aria-current={selected===id?'page':undefined} onClick={()=>id==='home'&&onHome?onHome():navigate(id)}>{label}</button>)}<button onClick={()=>onModels?onModels():window.location.assign('/community-options/home-prototype?open=model-plaza')}>模型广场</button></nav>
 <div className="community-search" ref={area}><form onSubmit={e=>{e.preventDefault();submit(query)}}>{icon('search')}<input aria-label="搜索作品、应用、作者" placeholder="搜索作品、应用、作者" value={query} onChange={e=>setQuery(e.target.value)} onFocus={()=>setSearchOpen(true)} onKeyDown={e=>{if(e.key==='Escape')setSearchOpen(false)}}/>{query&&<button type="button" aria-label="清空搜索" onClick={()=>setQuery('')}>{icon('close')}</button>}</form>{searchOpen&&<div className="community-search-popover"><SearchSuggestions go={navigate} search={submit}/></div>}</div>
 <nav className="community-services" aria-label="账户与服务">{[['activities','gift','活动'],['shop','shopping-bag-3','商城'],['invite','user-add','邀请'],['notifications','notification-3','通知']].map(([id,i,label])=><button key={id} onClick={()=>navigate(id)} aria-label={id==='notifications'&&unread?label+'，有未读消息':label} className={id==='notifications'?'community-notification':''}>{icon(i)}{id==='notifications'&&unread>0&&<i className="community-unread-dot"/>}<span>{label}</span></button>)}<div className="community-account"><button className="community-points" onClick={()=>navigate('points')}>积分 <strong>{pointBalance().toLocaleString('zh-CN')}</strong></button><button className="community-checkin" onClick={()=>navigate('checkin')}>{icon('calendar-check')}<span>签到</span></button></div><div className="community-user" ref={userArea}><button aria-label="我的菜单" aria-expanded={menu} onClick={()=>setMenu(!menu)}><img className="community-avatar" src="/home-prototype/portrait.png" alt=""/>{icon('arrow-down-s')}</button>{menu&&<div className="community-user-menu" aria-label="我的快捷菜单"><button className="community-menu-profile" onClick={()=>navigate('mine')}><span className="community-menu-avatar">{prototypeStore.getItem('cp-profile-avatar')?<img src={prototypeStore.getItem('cp-profile-avatar')||''} alt=""/>:(prototypeStore.getItem('cp-profile-name')||'林间').slice(0,1)}</span><span><strong>{prototypeStore.getItem('cp-profile-name')||'林间'}</strong><small>前往我的主页</small><small className="community-menu-social">关注 {followCount}　粉丝 36</small></span>{icon('arrow-right-s')}</button><div className="community-menu-points"><button onClick={()=>navigate('points')}><small>可用积分</small><span><strong>{pointBalance().toLocaleString('zh-CN')}</strong><small>积分中心 ›</small></span></button><button className="community-menu-checkin" onClick={()=>navigate('checkin')}>{icon('calendar-check')}每日签到</button></div><div className="community-menu-links">{[['content','image','我的内容'],['favorites','star','我的收藏'],['drafts','file-text','草稿箱'],['records','time','生成记录']].map(([id,i,label])=><button key={id} onClick={()=>navigate('mine?panel='+id)}>{icon(i)}<span>{label}</span>{icon('arrow-right-s')}</button>)}</div><div className="community-user-menu-divider"/><button onClick={()=>navigate('mine?panel=submissions')}>{icon('send-plane')}<span>我的投稿</span>{icon('arrow-right-s')}</button><button onClick={()=>navigate('invite')}>{icon('user-add')}<span>邀请有礼</span>{icon('arrow-right-s')}</button><div className="community-user-menu-divider"/><button className="community-menu-logout" onClick={()=>{prototypeStore.removeItem('cp-auth');navigate('login')}}>{icon('logout-box-r')}<span>退出登录</span></button></div>}</div></nav>
 </div></header>
}
export function MobileHeader({topic=false,circle=false,search=false,author,title,back,go,home=false,community=false,communityTab='works',onCommunityTab}:{topic?:boolean;circle?:boolean;search?:boolean;author?:string;communityTab?:string;onCommunityTab?:(tab:string)=>void;title?:string;back?:()=>void;go:(p:string)=>void;home?:boolean;community?:boolean}){
 const unread=useUnreadMessages();
 const followCount=useSyncExternalStore(subscribeAuthorFollowing,followingCount,()=>24);
 const [following,setFollowing]=useState(()=>author?prototypeStore.getItem('cp-following:'+author)==='1':false);
 useEffect(()=>{setFollowing(author?prototypeStore.getItem('cp-following:'+author)==='1':false)},[author]);
 return <header className={'community-mobile-header'+(title==='AI 商城'?' community-shop-header':'')+(author?' community-author-header':'')+(home?' community-mobile-home':community?' community-mobile-community':'')}>
 {title==='我的'?<><span aria-hidden="true"/><h1>我的</h1><div className="community-mobile-actions community-mine-actions"><button className="community-notification" aria-label={unread?'消息中心，有未读消息':'消息中心'} onClick={()=>go('notifications')}>{icon('notification-3')}{unread>0&&<i className="community-unread-dot"/>}</button></div></>:search?<><button className="community-back" onClick={back} aria-label="返回">{icon('arrow-left-s')}</button><div id="community-search-slot"/></>:author?<><button className="community-back" onClick={back} aria-label="返回">{icon('arrow-left-s')}</button><button className="community-nav-author" onClick={()=>go('author?name='+encodeURIComponent(author))}><img src="/home-prototype/portrait.png" alt=""/><span>{author}</span></button><button className="community-nav-follow" aria-pressed={following} onClick={()=>{prototypeStore.setItem('cp-following:'+author,following?'0':'1');setFollowing(!following)}}>{following?'已关注':'关注'}</button></>:community?<><nav className="community-header-tabs" aria-label="社区栏目">{communityTabs.map(([id,label])=><button key={id} aria-current={communityTab===id?'page':undefined} onClick={()=>onCommunityTab?.(id)}>{label}</button>)}</nav><button aria-label="搜索社区" onClick={()=>go('search?state=idle&from=community')}>{icon('search')}</button></>:home?<><img className="community-mobile-brand" src="/home-prototype/brand-logo.svg" alt="多元拾光"/><div className="community-mobile-actions"><button aria-label="搜索" onClick={()=>go('search?state=idle')}>{icon('search')}</button><button className="community-notification" aria-label={unread?'消息中心，有未读消息':'消息中心'} onClick={()=>go('notifications')}>{icon('notification-3')}{unread>0&&<i className="community-unread-dot"/>}</button></div></>:<><button className="community-back" onClick={back} aria-label="返回">{icon('arrow-left-s')}</button><h1>{title}</h1>{['AI 创作','AIGC 生成'].includes(title || '')?<div id="create-tools-slot"/>:topic?<div id="topic-share-slot"/>:circle?<div id="circle-publish-slot"/>:title==='AI 商城'?<button className="community-shop-records" onClick={()=>go('shop-records')}>兑换记录</button>:title==='积分中心'?<button className="community-points-detail" onClick={()=>go('points?state=records')}>明细</button>:title==='邀请有礼'?<button className="community-points-detail" onClick={()=>go('invite?state=records')}>明细</button>:title==='消息中心'?<button className="community-mark-read" disabled={!unread} onClick={markAllMessagesRead}>全部已读</button>:<span className="community-header-spacer" aria-hidden="true"/>}</>}
 </header>
}
