/* eslint-disable next/no-html-link-for-pages */
import options from '@/lib/community-scenarios.json';
import review from '@/lib/community-scenario-review.json';
import '@/components/market-social.css';
export default function Page(){return <main className="ms-report blueprint-report">
<p><a href="/#strategy">社区方案</a> / 五套方案</p><header className="page-heading"><h1>五套社区方案</h1><p>方案比较 · 以不同重心组织内容、供给、运营与产品</p></header>
<div className="ms-lead"><strong>选择主重心，组合辅助能力。</strong><p>五套方案均服务创作者、实际应用者与学习者。实践主线、创作交流独立入口是比较基准；其他方案用于判断是否调整主次。九主题继续保留，案例中的聚焦任务仅为设计示例。</p></div>
<p className="ms-links"><a href="/community-options/presentation">进入演示版：实践与创作，九个章节 →</a><a href="/community-options/review" target="_blank" rel="noopener noreferrer">竞品、真实任务与反例：查看五套方案的取舍依据 ↗</a></p><nav className="ms-links" aria-label="方案目录">{options.map((o,i)=><a key={o.id} href={'#'+o.id}>{i+1}. {o.name}</a>)}</nav>
<section><h2>先比较重心</h2><div className="ms-table"><table><thead><tr><th>方案</th><th>主要价值</th><th>关键成立条件</th></tr></thead><tbody>{options.map(o=><tr key={o.id}><th><a href={'#'+o.id}>{o.name}</a></th><td>{o.promise}</td><td>{o.condition}</td></tr>)}</tbody></table></div><p className="ms-caption">以下均为设计方案，材料支持程度随任务变化；方案顺序不代表市场机会排名。</p></section>
{options.map((o,i)=><section id={o.id} key={o.id}><h2>{i+1}. {o.name}</h2><p><strong>{o.promise}</strong></p><p>{o.position}</p><p><a href={'/community-options/design/'+o.id} target="_blank" rel="noopener noreferrer">查看详细方案、内容样例与案例图解 ↗</a></p><p className="ms-caption"><strong>评审建议：{review.items.find(x=>x.id===o.id)?.verdict}。</strong> <a href={'/community-options/review#'+o.id} target="_blank" rel="noopener noreferrer">支持、反例与设计调整 ↗</a></p><div className="ms-grid two"><article><h3>服务对象与聚焦任务</h3><p>{o.audience}</p><p>{o.focus}</p></article><article><h3>辅助能力与暂缓部分</h3><p>{o.support}</p><p>暂不重点投入：{o.defer}</p></article><article><h3>内容与供给</h3><p>{o.content}</p><p>{o.supply}</p></article><article><h3>运营与产品路径</h3><p>{o.operation}</p><p>{o.product}</p></article></div><p><strong>主要取舍：</strong>{o.risk}</p><p><strong>调整条件：</strong>{o.signal}</p><p className="ms-caption">研究支持：{o.evidence}</p><p className="ms-links">{o.id==='resource'&&<a href="/#report" target="_blank" rel="noopener noreferrer">15家竞品机制参照 ↗</a>}{o.tasks.map(id=><a key={id} href={'/research-decisions/tasks#'+id} target="_blank" rel="noopener noreferrer">{id} 任务与原始依据 ↗</a>)}</p></section>)}
<section id="combine"><h2>怎样组合，哪些需要分开</h2><p>建议以实践案例型为基准：创作交流保留独立入口，资源附着具体任务，行业应用用于选择深入范围，互助按可提供的能力开放。若改选其他主重心，首页、内容标准和供给组织也需随之调整。</p><div className="ms-grid two"><article><h3>可以共用</h3><p>作者身份、主题标签、收藏、来源与授权、案例和资源之间的关联。</p></article><article><h3>分别设计</h3><p>作品发布与邀请点评；案例描述与专业判断；资源更新责任与自愿回复；公开内容与私密服务材料。</p></article></div><p>决策时先选一个主要价值，再选辅助能力与聚焦任务。五套方案中的合作回报和服务安排均为拟议选项，供给者是否参与、新社区是否改善结果仍待确认。</p><p className="ms-links"><a href="/research-decisions" target="_blank" rel="noopener noreferrer">现有方向简版 ↗</a><a href="/research-status" target="_blank" rel="noopener noreferrer">证据状态 ↗</a></p></section></main>}
