/* eslint-disable next/no-img-element -- Concept artwork and the standalone SVG retain their original pixels and text without image transformation. */
import Link from 'next/link';
import './options.css';
const options=[
 ['a','任务创作','找到方法，完成任务','围绕具体用途整理案例、应用和工作流；从看懂方法到动手制作，再回圈子交流。','/proposal-one/home-v8-card-spacing.png','任务与专题','平台编辑＋实践作者'],
 ['b','项目共学','完成一次有反馈的练习','用完整项目串起材料、步骤、尝试和反馈。学习者留下自己的过程，主理人帮助越过关键难点。','/proposal-options/b-discover.png','练习与项目','主理人＋方法作者＋同伴'],
 ['c','创作者研讨','围绕作品，改进表达','从作品和创作意图开始，邀请相关同行讨论。作者决定采用哪些建议，保留自己的表达。','/proposal-options/c-discover.png','作品与作者','创作者＋相关同行＋策展编辑'],
 ['d','方法共建','让方法随着工具一起更新','把输入条件、版本、复现记录与替代办法放在一起。贡献者共同维护，使用者知道何时适用。','/proposal-options/d-discover-v2.png','方法与版本','维护者＋复现贡献者'],
 ['e','问题互助','解决制作中的具体卡点','围绕目标、材料和已尝试的方法交流。建议附适用条件，提问者补充尝试与采用结果。','/proposal-options/e-discover-v2.png','问题与回应','经验回应者＋圈子主持'],
];
export default function Page(){return <main className="op-shell"><header className="op-top"><Link href="/#overview">多元拾光 / 研究室</Link><div><Link href="/research-achievements">研究成果</Link><Link href="/community-options/presentation">汇报演示 ↗</Link></div></header><section className="op-hero"><span>社区方案</span><h1>五种重心，<br/>五套完整选择。</h1><p>五套方案分别展开产品、内容与运营，可以独立选择，也可以组合。文末给出推荐与取舍。</p><nav><Link href="#options">查看五套方案 ↓</Link><Link href="#compare">比较与组合</Link><Link href="/community-options/library">研究依据</Link></nav></section><section id="options" className="op-grid">{options.map(([id,name,tag,text,image,core,supply],i)=><article key={id}><Link href={'/community-options/proposals/'+id} className="op-cover"><img src={image} alt={name+'首页概念稿'} loading={i>1?'lazy':'eager'}/></Link><div className="op-card-body"><span className="op-code">0{i+1} / 方案 {id.toUpperCase()}</span><h2><Link href={'/community-options/proposals/'+id}>{name} <span>↗</span></Link></h2><h3>{tag}</h3><p>{text}</p><dl><dt>组织核心</dt><dd>{core}</dd><dt>供给基础</dt><dd>{supply}</dd></dl><Link href={'/community-options/proposals/'+id}>概念 · 路径 · 内容 · 运营 →</Link></div></article>)}</section><section id="compare" className="op-section"><span>比较与组合</span><h2>功能可以共用，社区重心要清楚。</h2><div className="op-table"><table><thead><tr><th>方案</th><th>用户期待</th><th>持续组织的重点</th><th>主要成立条件</th></tr></thead><tbody>{options.map(([id,name,tag,,,core,supply])=><tr key={id}><th>{id.toUpperCase()} · {name}</th><td>{tag}</td><td>{core}</td><td>{supply}</td></tr>)}</tbody></table></div><div className="op-callout"><h3>建议组合：A 为主，C 保留独立入口</h3><p>A 承接任务、方法选择与制作；C 留出围绕作品表达的交流空间。B 可先作为专题共学活动，D 作为重点资源的维护方式，E 作为圈子中的问题路径。若主理人、维护者或回应者形成稳定供给，再考虑相应方向独立展开。</p><p>这是一项方案建议。作者参与、内容采用与持续维护仍需实际验证；商业逻辑暂缓。</p></div></section><footer className="op-footer"><p>A 的概念方向已确认；B—E 已补齐评审稿，供并列比较。页面中的人物、数据与生成效果为设计示例。</p><Link href="/community-options/library">查看研究依据与参考材料 →</Link></footer></main>}
