'use client';
import {ResearchOutline,ResearchAppendix} from './research-outline';
import {PlatformReviewDimension} from '@/components/platform-review';
import raw from '@/lib/audience-research.json';
import './audience-research.css';

type Source={id:string;title:string;url:string;publisher:string;date:string;accessedAt:string;type:string;accessNote:string};
type Evidence={id:string;kind:string;claim:string;sourceId:string;publishedAt:string;observedAt:string;limit:string;independenceKey:string;access:string};
type Persona={id:string;name:string;scope:string;status:string;independentUserPoints:number;task:string;trigger:string;desiredOutcome:string;pains:string[];alternatives:string;contentNeeds:string;returnHypothesis:string;returnEvidence:string;payStatus:string;share:null;evidenceIds:string[]};
type ValueMap={personaIds:string[];problem:string;provided:string;contentForm:string;mechanism:string;observedResult:string;resultLevel:string;unresolved:string;evidenceIds:string[]};
type OldSegment={oldIndex:number;name:string;verdict:string;reason:string;evidenceIds:string[]};
type Profile={id:string;name:string;homepage:string;thesis:string;roleMix:{consumer:string;supplier:string;payer:string};personas:Persona[];valueMap:ValueMap[];oldSegmentAudit:OldSegment[];evidence:Evidence[];sources:Source[];contradictions:string[];unknowns:string[];nextEvidence:string[];download:string};
type Data={title:string;date:string;summary:string;scope:string;stats:{platforms:number;originalSegments:number;auditedSegments:number;taskProfiles:number;valueMappings:number;evidenceRecords:number;sourceRecords:number;uniqueSourceUrls:number;underFivePoints:number;zeroPoints:number};profiles:Profile[];method:{title:string;text:string}[];evidenceGuide:{kind:string;supports:string;cannot:string}[];valueLayers:{layer:string;problem:string;provided:string;result:string;remaining:string}[];interpretationRules:string[];communityImplications:{title:string;text:string}[];findings?:{title:string;text:string;platformIds:string[];evidenceRefs:{platformId:string;evidenceId:string}[]}[]};
const data=raw as unknown as Data;

function go(id:string){const el=document.getElementById(id);if(!el)return;if(el instanceof HTMLDetailsElement)el.open=true;for(let node=el.parentElement;node;node=node.parentElement)if(node instanceof HTMLDetailsElement)node.open=true;const motion=window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth';el.scrollIntoView({behavior:motion,block:'start'});el.focus({preventScroll:true});}
function EvidenceRefs({profile,ids}:{profile:Profile;ids:string[]}){return <span className="aud-refs">{ids.map(id=>{const e=profile.evidence.find(x=>x.id===id);return e?<a href={`#aud-${id}`} key={id} onClick={event=>{event.preventDefault();go(`aud-${id}`);}} title={e.claim}>{e.kind}证据{profile.evidence.indexOf(e)+1}</a>:null;})}</span>;}
function SourceLink({profile,id}:{profile:Profile;id:string}){const s=profile.sources.find(x=>x.id===id);return s?<a href={s.url} target="_blank" rel="noreferrer">{s.title} ↗</a>:null;}
function Fields({items}:{items:[string,string][]}){return <dl className="aud-fields">{items.map(([label,text])=><div key={label}><dt>{label}</dt><dd>{text}</dd></div>)}</dl>;}
function BulletList({items}:{items:string[]}){return <ul>{items.map((text,i)=><li key={i}>{text}</li>)}</ul>;}

function ProfileDocument({profile:p,navigate}:{profile:Profile;navigate:(id:string)=>void}){return <details className="aud-platform"><summary><span>{p.name}</span><small>{p.personas.length}类任务</small></summary><div className="aud-profile-body" id={`audience-profile-${p.id}`} tabIndex={-1}>
 <div className="aud-profile-heading"><h2>{p.name}</h2><div className="aud-actions"><a href={p.homepage} target="_blank" rel="noreferrer">官网 ↗</a><a href={p.download} download>下载本平台完整档案</a><button onClick={()=>navigate(p.id)}>功能、内容与截图 →</button></div></div><p className="aud-thesis">{p.thesis}</p>

 <PlatformReviewDimension platformId={p.id} dimension="audience"/><PlatformReviewDimension platformId={p.id} dimension="usage"/><h3>用户、供给者与付款方</h3><Fields items={[["消费与使用",p.roleMix.consumer],["供给与维护",p.roleMix.supplier],["付款与采购",p.roleMix.payer]]}/>
 <h3>任务画像与内容需要</h3>{p.personas.map(person=><article className="aud-persona" key={person.id}><h4>{person.name}</h4><p className="aud-status">{person.status}；可区分用户观察点：{person.independentUserPoints}；群体占比：资料不足</p><p className="aud-task">{person.task}</p><Fields items={[["适用范围",person.scope],["任务触发",person.trigger],["期望结果",person.desiredOutcome],["主要困难",person.pains.join('；')],["替代方法",person.alternatives],["需要的内容",person.contentNeeds],["回访理由（推断）",person.returnHypothesis],["实际持续证据",person.returnEvidence],["付款状态",person.payStatus]]}/><EvidenceRefs profile={p} ids={person.evidenceIds}/></article>)}
 <h3>平台提供什么，问题解决到哪里</h3>{p.valueMap.map((v,i)=><article className="aud-value" key={i}><h4>{v.problem}</h4><p className="aud-status">对应：{v.personaIds.map(id=>p.personas.find(x=>x.id===id)?.name||id).join('、')}</p><Fields items={[["平台提供",v.provided],["内容形态",v.contentForm],["起作用的方式",v.mechanism],["已观察结果",v.observedResult],["解决程度",v.resultLevel],["仍未解决或未证明",v.unresolved]]}/><EvidenceRefs profile={p} ids={v.evidenceIds}/></article>)}

 <h3>使用、失败与持续行为记录</h3>{p.evidence.map((e,i)=><details className="aud-evidence" key={e.id}><summary><span>证据{i+1} · {e.kind}</span><small>{e.claim}</small></summary><div id={`aud-${e.id}`} tabIndex={-1}><p>{e.claim}</p><Fields items={[["发表时间",e.publishedAt||'未确认'],["观察时间",e.observedAt||'未确认'],["访问范围",e.access],["解释边界",e.limit]]}/><p className="aud-source-link"><SourceLink profile={p} id={e.sourceId}/></p></div></details>)}
 <div className="aud-unknown"><h3>相反证据与未决问题</h3><BulletList items={p.contradictions}/><BulletList items={p.unknowns}/><h4>最值得继续补的证据</h4><BulletList items={p.nextEvidence}/></div>
 <details className="aud-sources"><summary>本平台完整来源与访问说明</summary>{p.sources.map(s=><article key={s.id}><h4><a href={s.url} target="_blank" rel="noreferrer">{s.title} ↗</a></h4><p>{s.publisher} · {s.type}</p><p>发表：{s.date||'未标明'}核查：{s.accessedAt||data.date}。</p><p>{s.accessNote}</p></article>)}</details>
 <button className="aud-back" onClick={()=>go('audience-index')}>返回18个平台对照 ↑</button>
 </div></details>;}

export function AudienceResearch({navigate}:{navigate:(id:string)=>void}){return <article className="audience-research">
 <header className="aud-heading"><h1>{data.title}</h1><div className="aud-actions"><a href="/research-kit/audience-research.md" download>下载完整报告 ↗</a><a href="/research-kit/audience-research-data.json" download>下载证据台账 ↗</a><button onClick={()=>go('audience-method')}>研究口径</button><button onClick={()=>go('audience-value-layers')}>产品价值的五个环节</button></div><p className="aud-note">资料截至{data.date}</p></header>
 <ResearchOutline items={[['audience-findings','跨平台发现'],['audience-index','平台用户档案'],['audience-value-layers','产品价值分析'],['audience-method','证据与研究方法']]}/>


 {data.findings&&<section className="aud-synthesis" id="audience-findings"><h2>跨平台发现</h2>{data.findings.map(f=><article key={f.title}><h3>{f.title}</h3><p>{f.text}</p><div className="aud-refs">{f.evidenceRefs.map(ref=>{const p=data.profiles.find(x=>x.id===ref.platformId),e=p?.evidence.find(x=>x.id===ref.evidenceId);return p&&e?<a key={ref.evidenceId} href={`#aud-${e.id}`} onClick={event=>{event.preventDefault();go(`aud-${e.id}`);}} title={e.claim}>{p.name}证据{p.evidence.indexOf(e)+1}</a>:null;})}</div><div className="aud-actions">{f.platformIds.map(id=><button key={id} onClick={()=>go(`audience-profile-${id}`)}>{data.profiles.find(p=>p.id===id)?.name}完整档案</button>)}</div></article>)}</section>}
 <section className="aud-documents" id="audience-index"><h2>各平台用户档案</h2><nav className="aud-compact-index" aria-label="选择平台用户档案">{data.profiles.map(p=><button key={p.id} onClick={()=>go('audience-profile-'+p.id)}>{p.name}</button>)}</nav>{data.profiles.map(p=><ProfileDocument key={p.id} profile={p} navigate={navigate}/>)}</section>
 <section id="audience-value-layers" tabIndex={-1} className="aud-method"><h2>产品价值分析</h2><div className="aud-table-scroll" tabIndex={0} role="region" aria-label="产品价值五个环节"><table><thead><tr><th scope="col">环节</th><th scope="col">用户问题</th><th scope="col">平台提供</th><th scope="col">结果与剩余负担</th></tr></thead><tbody>{data.valueLayers.map(x=><tr key={x.layer}><th scope="row">{x.layer}</th><td>{x.problem}</td><td>{x.provided}</td><td>{x.result}<p className="aud-note">{x.remaining}</p></td></tr>)}</tbody></table></div></section>
 <ResearchAppendix id="audience-method" title="证据与研究方法"><p>55条任务画像中，49条不足5个可区分用户观察点，18条暂无直接用户点；群体占比未取得。</p><p>{data.scope}</p>{data.method.map(x=><article key={x.title}><h3>{x.title}</h3><p>{x.text}</p></article>)}<div className="aud-table-scroll" tabIndex={0} role="region" aria-label="证据类型与边界"><table><thead><tr><th scope="col">证据类型</th><th scope="col">支持什么</th><th scope="col">不能支持什么</th></tr></thead><tbody>{data.evidenceGuide.map(x=><tr key={x.kind}><th scope="row">{x.kind}</th><td>{x.supports}</td><td>{x.cannot}</td></tr>)}</tbody></table></div><BulletList items={data.interpretationRules}/><p className="aud-note">本专题收录{data.stats.evidenceRecords}条证据记录、{data.stats.uniqueSourceUrls}个不同来源URL；引用和跨画像复用不增加独立用户数。定向公开样本不能用于计算任务占比、失败率或留存。</p></ResearchAppendix>
 <section className="aud-method"><h2>内容与运营的适用条件</h2>{data.communityImplications.map(x=><article key={x.title}><h3>{x.title}</h3><p>{x.text}</p></article>)}<div className="aud-actions"><button onClick={()=>navigate('strategy')}>社区方案对照 →</button><button onClick={()=>navigate('content')}>内容形式与截图 →</button><button onClick={()=>navigate('china-users')}>中国AI用户规模与分层 →</button></div></section>
 </article>;}
