'use client';
import {profiles} from '@/lib/profiles';
import {groups} from '@/lib/research-types';
import {comparisonById,DossierLink,EvidenceLinks,TopicCell} from './cross-platform';
import {functionProfiles} from './function-pages';
import traffic from '@/lib/public-data.json';
import samples from '@/lib/content-research.json';
import business from '@/lib/business-data.json';
import './cross-platform.css';
import './competitor-topics.css';
export const topicIds=['audience','content','operations','business','data','tasks','discussion','supplement'];
const topics:Record<string,{title:string;lead:string;points:[string,string][];question:string}>={
 audience:{title:'平台用户与需求',lead:'用户画像首先表现为任务差异：有人来找灵感，有人来制作，有人来学习、接入应用或解决问题。同一人可以在不同时间承担多个角色。',question:'各平台主要服务什么任务？',points:[['浏览与创作分开看','LiblibAI、即梦和吐司都保留观看与继续浏览的路径；查看作品本身可以提供参考价值。'],['同为创作者，交付物不同','商品精修、角色插画、连续镜头、故事和项目资产需要不同的输入与控制方式。'],['学习、开发和讨论有独立价值','Datawhale承接练习与教材修订，Dify承接应用配置，LINUX DO承接问题讨论。职业占比仍需独立的用户数据。']]},
 content:{title:'内容形态与页面',lead:'内容形态决定详情页需要交代什么。作品先展示效果，资源说明使用条件，教材提供练习顺序，讨论保留问题和回复上下文。',question:'分类、详情与下一步如何配合？',points:[['分类不是一张通用标签表','吐司用兴趣聚合作品与工具，RunningHub按用途找流程；模型类型与底模属于另外的使用条件。'],['卡片负责选择，详情承接判断','LiblibAI的资源详情补模型、许可和输入；Leonardo的Blueprint收集任务素材，Runway区分Apps表单与Workflow配置。'],['同一内容存在多条后续路径','用户可以继续看、收藏参考、复制方法或进入制作。Dify工作室里的应用资产与公开模板也有不同边界。']]},
 operations:{title:'平台运营',lead:'平台运营的差异，主要在于组织哪种供给、如何让人发现，以及谁负责发布后的更新、答疑和治理。',question:'供给、平台与使用者各承担什么？',points:[['作者奖励与采购分开','RunningHub奖励资源采用，SeaArt有多类奖励池；OpenArt按帖采购与新增订阅佣金各有目标。'],['精选依赖编辑判断','即梦、可灵和Runway用作者计划、教程和专业案例组织展示；精选案例与普通开放投稿的条件不同。'],['维护工作随内容变化','资源需要版本兼容，教材需要修订，目录需要更新链接，论坛需要回复与治理。发布数量只能说明其中一部分。']]},
 business:{title:'商业模式与规模',lead:'先确定付款人和购买对象，再比较权益范围。会员、计算资源、API、作者回报和采购支出分别记录，规模判断保留披露日期与来源。',question:'谁付费、购买什么、权益覆盖哪里？',points:[['创作权益','模型、速度、积分、订阅和项目协作组合成不同套餐。地区与具体模型会改变权益范围。'],['接入与部署','RunningHub共享API和模型API采用不同单位；Hugging Face、魔搭与Dify还涉及托管、部署和工作空间。'],['规模与经营效果','访问量、注册量和付费人数是不同指标。公开标价可以解释收费结构，不能代替实收、续费与利润。']]},
 data:{title:'访问与渠道数据',lead:'访问数据用于辨认网站使用量级、地区与流量结构。平台档案则解释访问者可能在做什么；两类资料结合阅读，不把会话时长直接解释为内容吸引力。',question:'各平台有哪些可引用的访问观察？',points:[['日期与供应商同时保留','同一网站不同月份、供应商的估计分开列示，不拼成连续趋势。'],['网页与产品总体区分','网站会话可能包含浏览、生成等待和配置操作；网页访问量不能覆盖全部App用户。'],['渠道是访问线索','Direct、搜索和推荐来源帮助理解入口结构，真实获客及回访仍需要用户行为记录。']]},
 tasks:{title:'内容与互动样本',lead:'样本按平台任务组织：既看商品图、角色和短片，也看教材练习、应用配置、技术讨论。详情、操作记录和反馈分别呈现。',question:'有哪些具体任务和结果值得回看？',points:[['制作样本','LiblibAI覆盖商品精修等任务；OpenArt与可灵涉及角色、镜头及故事，SeaArt还包括角色互动。'],['复用结果','Dify的UTM模板有试用与副本保存结果；LibTV画布可找回，Runway复制确认后未见副本保存。'],['学习与问题回应','Datawhale的Issue和PR能追踪修订，LINUX DO的回复链保留排查过程。内容量、互动量与最终解决结果分别判断。']]},
 discussion:{title:'内容与工具关系',lead:'内容可以供观看、讲方法、提供配置，也可以成为可执行资源。工具应承接内容对应的任务；学习、讨论和欣赏都有独立于生成的价值。',question:'内容之后，用户在哪里继续？',points:[['内容连接制作','LiblibAI和RunningHub将作品接到资源或应用；即梦将同款、画布和技能接到作品旁。'],['配置连接运行','Hugging Face、魔搭和Dify交付资源或应用结构，运行仍取决于依赖、权限和计算条件。'],['阅读连接外部行动','WaytoAGI目录常外跳服务，Datawhale连接练习与代码，LINUX DO连接排查和讨论。']]},
 supplement:{title:'经营与使用证据',lead:'产品入口、实际操作、用户反馈和商业规则提供不同证据。本页把已记录的使用结果与经营边界放在一起，方便判断结论支持到哪一步。',question:'各平台的使用和经营判断基于什么？',points:[['入口与结果','按钮存在、复制保存、运行成功和最终交付是不同状态，保留具体样本结果。'],['反馈与维护','作者回复、修改版本和关闭问题有助于理解维护；用户再次确认结果提供另一层证据。'],['规则与实际经营','收费说明、许可与激励可以核对条款。成交、分成到账、持续供给和留存仍需相应记录。']]}
};
function MaterialLink({id,section,label}:{id:string;section:string;label:string}){return <a href={'/platform-evidence?section='+section+'#'+id} target="_blank" rel="noopener noreferrer">{label} ↗</a>;}
function TopicBody({id,topic}:{id:string;topic:string}){const p=comparisonById.get(id)!;if(topic==='audience')return <><p>{p.thesis}</p><div className="topic-role-list">{p.users.map(u=><div key={u.role}><b>{u.role}</b><span>{u.task}<small className="topic-value">{u.value}</small></span></div>)}</div><EvidenceLinks id={id} refs={p.userRefs}/><a href={'/?section=audience-profile-'+id+'#audience'} target="_blank" rel="noopener noreferrer">任务画像与用户案例 ↗</a></>;if(topic==='content')return <><TopicCell id={id} dimension="distribution"/><p className="cross-note">{p.journey.title}</p><a href={'/?section=content-'+id+'#content'} target="_blank" rel="noopener noreferrer">内容专题与页面案例 ↗</a></>;if(topic==='operations')return <><TopicCell id={id} dimension="supply"/><a href={'/?section=operations-'+id+'#operations'} target="_blank" rel="noopener noreferrer">运营专题与来源 ↗</a></>;if(topic==='business')return <><TopicCell id={id} dimension="business"/><div className="topic-scale">{business.find(x=>x.id===id)?.metrics.filter(m=>m.kind!=='资料不足').map((m,i)=><p key={i}><b>{m.label}：{m.value}</b><br/>{m.period} · {m.kind}<br/><small>{m.scope}；{m.limitation}</small></p>)}</div><MaterialLink id={id} section="commercial" label="规模披露与详细条款"/></>;if(topic==='discussion')return <TopicCell id={id} dimension="journey"/>;if(topic==='tasks'){const f=functionProfiles.get(id);const indexes=[...new Set([...p.journey.refs,...p.supply.refs])];return <><p>{p.journey.detail}</p><ul className="topic-samples">{indexes.map(i=><li key={i}><a href={id==='liblib'?'/liblib-evidence?section=liblib-function-'+i:'/platform-evidence?section='+id+'-function-'+i+'#'+id} target="_blank" rel="noopener noreferrer">{f?.sections[i]?.title} ↗</a></li>)}</ul>{samples.platforms.some(p=>p.platformId===id)&&<MaterialLink id={id} section="content-observations" label="内容与互动记录"/>}</>;}
if(topic==='supplement')return <><h4>使用记录</h4><p>{p.journey.detail}</p><EvidenceLinks id={id} refs={p.journey.refs}/><h4>经营范围</h4><p>{p.business.limit}</p><MaterialLink id={id} section="evidence-update" label="经营与使用案例"/><span className="topic-link-space"/><MaterialLink id={id} section="commercial" label="商业规则"/></>;
const d=traffic.find(x=>x.id===id);const observations=d?.observations.filter(x=>['visits','duration_seconds','direct_pct'].includes(x.key)&&x.numericValue!==null&&x.evidenceStatus!=='unavailable')||[];return <>{observations.length?<div className="topic-metrics">{observations.map((m,i)=><div key={i}><strong>{m.value}</strong><b>{m.metric}</b><span>{m.period} · {m.provider}</span><small>{m.scope}</small></div>)}</div>:<p>现有材料没有可明确引用的网站访问量、访问时长或直接流量数值。可查阅其他指标和来源记录。</p>}<p className="cross-note">第三方访问估计；完整指标的设备、地区及方法条件见来源。</p><MaterialLink id={id} section="public-data" label="访问、地区、渠道与来源"/></>;
}
export function CompetitorTopic({topic}:{topic:string}){const t=topics[topic];return <article className="cross-study competitor-topic"><header className="page-heading"><p className="cross-kicker">竞品研究 · 15 家档案</p><h1>{t.title}</h1><p className="topic-lead">{t.lead}</p></header><div className="topic-findings">{t.points.map(([title,text])=><section key={title}><h2>{title}</h2><p>{text}</p></section>)}</div><h2>{t.question}</h2>{topic==='tasks'&&<p className="cross-refs"><a href="/?section=content-ledger#tasks" target="_blank" rel="noopener noreferrer">商品图逐条样本台账 ↗</a><a href="/?section=content-comments#tasks" target="_blank" rel="noopener noreferrer">商品详情页评论与回应 ↗</a></p>}<nav className="topic-toc" aria-label="平台分类章节">{groups.map((g,i)=><a key={g} href={'/#'+topic} onClick={e=>{e.preventDefault();document.getElementById(topic+'-group-'+i)?.scrollIntoView({behavior:'smooth',block:'start'});}}>{g}</a>)}</nav>{groups.map((g,i)=><section className="cross-category" id={topic+'-group-'+i} key={g}><h2>{g}</h2>{profiles.filter(p=>p.group===g).map(p=><div className="cross-row" id={topic+'-profile-'+p.id} key={p.id}><header><h3><DossierLink id={p.id}/></h3><p>{comparisonById.get(p.id)?.tagline}</p></header><div><TopicBody id={p.id} topic={topic}/></div></div>)}</section>)}<footer className="cross-footer"><p>平台角色与机制依据档案归纳，具体观察日期、样本与规则见来源。收费和访问数据按原有统计范围使用。</p><a href="/#report" target="_blank" rel="noopener noreferrer">竞品调研报告 ↗</a></footer></article>;}
