import data from '@/lib/content-presentation.json';
import screenshots from '@/lib/content-screenshots.json';

export function ContentPresentation() {
 const jump=(id:string)=>document.getElementById(id)?.scrollIntoView({behavior:'smooth',block:'start'});
 return <div className="presentation-study">
  <div className="page-heading"><h1>{data.title}</h1></div>
  <nav className="study-actions" aria-label="产品形态讨论目录"><button className="text-button" onClick={()=>jump('presentation-comparison')}>三层对照</button><button className="text-button" onClick={()=>jump('presentation-cases')}>同一案例的三种组织</button><button className="text-button" onClick={()=>jump('presentation-types')}>各种内容怎么展示</button><button className="text-button" onClick={()=>jump('presentation-strategy')}>回看四个方向</button><button className="text-button" onClick={()=>jump('previous-options')}>经营假设</button></nav>

  <section className="study-platform"><h2>少了什么</h2>{data.diagnosis.map(x=><p key={x}>{x}</p>)}<div className="table-wrap"><table><thead><tr><th>层次</th><th>要回答的问题</th><th>具体选择</th><th>常见缺口</th></tr></thead><tbody>{data.layers.map(r=><tr key={r.name}><th>{r.name}</th><td>{r.question}</td><td>{r.decision}</td><td>{r.failure}</td></tr>)}</tbody></table></div><p>{data.classification}</p></section>
  <section className="study-platform" id="presentation-comparison"><h2>相同内容，可以形成怎样不同的体验</h2><p>{data.comparisonIntro}</p><div className="table-wrap"><table><thead><tr><th>比较项</th><th>作品与作者</th><th>方法与资源</th><th>问题与讨论</th></tr></thead><tbody>{data.comparison.map(r=><tr key={r.dimension}><th>{r.dimension}</th><td>{r.works}</td><td>{r.methods}</td><td>{r.discussion}</td></tr>)}</tbody></table></div></section>
  <section className="study-platform" id="presentation-cases"><h2>同一只白杯，从入口到下一步</h2><p className="notice">{data.example}</p>{data.structures.map(s=><article className="presentation-structure" key={s.id}><h3>{s.name}</h3><p className="lead">{s.promise}</p><p><strong>首页怎样组织：</strong>{s.home}</p><div className="study-mechanism"><p><strong>案例标题：</strong>{s.caseTitle}</p><dl className="study-definition"><div><dt>卡片或列表</dt><dd>{s.card}</dd></div><div><dt>详情顺序</dt><dd>{s.detail}</dd></div><div><dt>后续动作</dt><dd>{s.action}</dd></div></dl></div><p><strong>布局、密度与交互：</strong>{s.visual}</p><p><strong>内容供给的代价：</strong>{s.supply}</p><p><strong>工具与收入的关系：</strong>{s.business}</p><p><strong>较轻的起步范围：</strong>{s.minimum}</p><details className="content-pair"><summary>对应竞品截图与观察边界</summary><p>{s.boundary}</p>{s.evidenceIds.map(id=>{const p=screenshots.pairs.find(x=>x.id===id)!;return <div key={id}><p><strong>{p.platform} · {p.title}</strong>采集于{screenshots.capturedAt}</p><div className="content-pair-images">{[p.card,p.detail].map((im,i)=><figure className="content-evidence-figure" key={im.src}><div className="content-image-label">{i===0?'卡片 / 列表入口':'对应详情'}</div><a href={im.src} target="_blank" rel="noreferrer"><img src={im.src} width={im.width} height={im.height} alt={`${p.platform}：${im.caption}`} loading="lazy"/></a><figcaption>{im.caption}</figcaption><a href={im.url} target="_blank" rel="noreferrer">来源页面 ↗</a></figure>)}</div><p className="muted">{p.limits}</p></div>;})}</details></article>)}</section>
  <section className="study-platform" id="presentation-types"><h2>保留多种内容，也保留各自的阅读方式</h2><p>下表是组织建议，不是已经确认的频道或功能清单。</p><div className="table-wrap"><table><thead><tr><th>内容</th><th>入口先交代什么</th><th>详情交付什么</th><th>主要动作</th></tr></thead><tbody>{data.formMapping.map(r=><tr key={r.form}><th>{r.form}</th><td>{r.entry}</td><td>{r.detail}</td><td>{r.action}</td></tr>)}</tbody></table></div>{data.organization.map(x=><div key={x.name}><h3>{x.name}</h3><p>{x.text}</p></div>)}</section>
  <section className="study-platform" id="presentation-strategy"><h2>这些讨论怎样改变四个方向的比较</h2><div className="table-wrap"><table><thead><tr><th>方向</th><th>可采用的产品形态</th><th>需要拆开重算的选择</th></tr></thead><tbody>{data.strategyMapping.map(x=><tr key={x.option}><th>{x.option}</th><td>{x.fit}</td><td>{x.change}</td></tr>)}</tbody></table></div><div className="notice"><strong>判断</strong><p>{data.conclusion}</p></div><h3>下一份完整方案需要包含什么</h3><ul>{data.next.map(x=><li key={x}>{x}</li>)}</ul><p className="muted">{data.evidenceNote}</p></section>
 </div>;
}
