'use client';
import d from '@/lib/content-demand-cases.json';
import './content-demand-cases.css';
const base='/research-kit/douyin-case-review-2026-09-13/';
function Link({url,children}:{url:string;children:React.ReactNode}){return <a href={url} target="_blank" rel="noreferrer">{children} ↗</a>}
function Table({heads,rows}:{heads:string[];rows:React.ReactNode[][]}){return <div className="cr-table"><table><thead><tr>{heads.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j}>{c}</td>)}</tr>)}</tbody></table></div>}
export function DouyinCases(){return <section className="cr-research" id="cr-research">
 <header><h2>{d.title}</h2></header>
 <div className="cr-findings">{d.findings.map(f=><article key={f.title}><h3>{f.title}</h3><p>{f.text}</p></article>)}</div>
 {d.cases.map(c=><article className="cr-case" key={c.id} id={'cr-'+c.id}><h3>{c.title}</h3><p className="cr-meta"><Link url={c.url}>{c.author} · 作品</Link>{c.secondUrl&&<> · <Link url={c.secondUrl}>另一发布入口</Link></>} · {c.read}</p><p>{c.fact}</p><div className="cr-gallery">{c.images.map(name=>{const f=d.frames.find(f=>f.file==='frames/'+name+'.png')!;return <figure key={name}><a href={base+f.publicFile} target="_blank" rel="noreferrer"><img src={base+f.publicFile} alt={f.observation} width="1280" height="720" loading="lazy"/></a><figcaption>{Math.floor(f.currentTime/60)}分{(f.currentTime%60).toFixed(1)}秒 · {f.observation}</figcaption></figure>})}</div><p>{c.interpretation}</p><details><summary>阅读范围与待核部分</summary><p>{c.open}</p></details></article>)}
 <section id="cr-claims"><h3>历史主张与原文对照</h3><Table heads={['片内或作者说明','核对结果','依据']} rows={d.claims.map(x=>[x.claim,x.verdict,<span key={x.claim}>{x.sourceUrls.map((u,i)=><Link key={u} url={u}>来源{i+1}</Link>)}</span>])}/><p>事件引用、作者解释和视觉再现分别判断。对服饰的评论保留为质疑，现有资料不足以裁定具体帽款错误。</p></section>
 <section id="cr-delivery"><h3>五个具体资源的复用条件</h3><Table heads={['对象','已提供','缺少什么','用户会卡在哪里']} rows={d.delivery.rows.map(x=>[<Link key={x.id} url={x.url}>{x.title}</Link>,x.available,x.missing,x.consequence])}/><details><summary>配置里能直接定位的差异</summary>{d.delivery.configurationFindings.map(x=><div key={x.title}><h4>{x.title}</h4><p>{x.text}</p>{x.sourceUrls.map((u,i)=><Link key={u} url={u}>配置来源{i+1}</Link>)}</div>)}</details><p className="cr-meta">{d.delivery.readScope}</p></section>
 <section id="cr-cost"><h3>制作这些内容需要哪些工作</h3><Table heads={['项目','公开投入信息','信息来自谁','对供给安排的影响']} rows={d.economics.map(x=>[<span key={x.id}><b>{x.title}</b>{x.urls.map((u,i)=><p key={u}><Link url={u}>项目来源{i+1}</Link></p>)}</span>,x.evidence,x.attribution,x.implication])}/><p>这些材料未提供可核实的付款凭据或完整人时，不能计算统一稿费、每分钟成本或作者周产能。制作历时、实际人时、额度和支出的口径不同，需分别判断。</p></section>
 <details className="cr-method"><summary>画面抽查范围与来源记录</summary><p>{d.scope}</p><p>截图仅选择8个分析所需画面；播放位置以记录时的实际时间为准。研究日期为2026年9月13日；历史互动快照不被画面核对覆盖。</p><div className="cr-downloads">{[['frame-analysis.json','时间点记录'],['claim-sources.md','历史主张核对'],['delivery-readiness.md','材料交付核查'],['production-economics.md','制作投入全文']].map(([f,t])=>null)}</div></details>
</section>}

export function CasesPlanning(){return <div>{d.cases.map(c=><section key={c.id}><h3>{c.title}</h3><p>{c.community}</p><Link url={c.url}>作品依据</Link></section>)}<Table heads={['消费任务','内容安排','供给分工','回访假设']} rows={d.productRows}/>{d.cooperation.map(x=><section key={x.id}><h3>{x.title}</h3><p>{x.requirement}</p><p className="muted">{x.doNotAssume}</p></section>)}{d.next.map(x=><section key={x.title}><h3>{x.title}</h3><p>{x.text}</p></section>)}</div>;}
