'use client';
import data from '@/lib/content-demand-comparison.json';
import {DouyinCases} from './content-demand-cases';
import './content-demand-comparison.css';
const d=data,base='/research-kit/douyin-comparison-2026-09-13/';
const fmt=(n:number|null)=>n==null?'—':n.toLocaleString('zh-CN',{maximumFractionDigits:1});
function Link({url,children}:{url:string;children:React.ReactNode}){return <a href={url} target="_blank" rel="noreferrer">{children} ↗</a>}
function Jump({id,children}:{id:string;children:React.ReactNode}){return <button type="button" className="dc-jump" data-jump={id} onClick={()=>{const el=document.getElementById(id);for(let p=el;p;p=p.parentElement)if(p instanceof HTMLDetailsElement)p.open=true;el?.scrollIntoView({block:'start'});}}>{children}</button>}
function Table({heads,rows}:{heads:string[];rows:React.ReactNode[][]}){return <div className="dc-table"><table><thead><tr>{heads.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((v,j)=><td key={j}>{v}</td>)}</tr>)}</tbody></table></div>}
function WorkRefs({ids}:{ids:string[]}){return <div className="dc-refs">{ids.map(id=>{const w=d.works.find(w=>w.id===id);return w?<Link key={id} url={w.url}>{id} · {w.author}</Link>:null;})}</div>}
function Evidence({refs}:{refs:string[]}){return <details className="dc-evidence"><summary>查看对应作品与评论（{refs.length}处）</summary>{refs.map(ref=>{const e=d.topicEvidence.find(x=>x.ref===ref);return e?<div key={ref}><Link url={e.sourceUrl}>{ref}</Link><span className="dc-meta"> · {e.publishedAt} · {e.window}</span><p>{e.text}</p></div>:null;})}</details>}
export function DouyinComparison(){return <section className="dc-research" id="dc-research">
 <div className="dc-heading"><h2>{d.title}</h2><p>{d.verdict}</p><div className="cd-downloads"><a href={base+'report.html'} target="_blank" rel="noreferrer">独立阅读</a><a href={base+'report.md'} download>下载分析</a><a href={base+'works.csv'} download>连续作品数据</a><a href={base+'data.json'} download>全部分析依据</a></div></div>
 <nav className="dc-nav" aria-label="内容消费深度分析">{[['dc-conclusions','主要发现'],['cr-research','成片与交付'],['dc-themes','六类消费需求'],['dc-authors','作者与连续作品'],['dc-new-comments','生产约束与反馈'],['dc-supply','需求对应现有供给'],['dc-next','待补证据']].map(([id,label])=><Jump key={id} id={id}>{label}</Jump>)}</nav>
 <section id="dc-conclusions" className="dc-findings">{d.findings.map((f,i)=><article key={f.title}><span className="dc-index">{String(i+1).padStart(2,'0')}</span><h3>{f.title}</h3><p>{f.text}</p><WorkRefs ids={f.refs}/>{i===3&&<Jump id="dc-supply">查看逐项供给对照</Jump>}</article>)}</section>
 <DouyinCases />
 <section id="dc-themes"><h2>六类消费需求，各自需要什么内容</h2><Table heads={['主题','用户要得到什么','明确的需求线索','仍未闭合的部分','持续供给工作']} rows={d.topicComparison.map(x=>{const t=d.topics.find(t=>t.id===x.topicId)!;return [<Jump key={x.topicId} id={'dc-topic-'+x.topicId}>{t.name.split('：')[0]}</Jump>,x.value,x.strongEvidence,x.unresolved,x.supplyBurden];})}/>
 {d.topics.map(t=><details className="dc-dossier" id={'dc-topic-'+t.id} key={t.id}><summary><b>{String(t.number).padStart(2,'0')}</b><strong>{t.name}</strong><span>{t.counts.primaryWorks}件作品</span></summary><div className="dc-dossier-body"><p className="dc-lead">{t.conclusion}</p><p className="dc-meta">主归属{t.counts.primaryWorks}件：窗口内{t.counts.inWindowWorks}、更早{t.counts.beforeWindowWorks}、更晚{t.counts.afterWindowWorks}；{t.counts.readableRoot}条顶层文字（含作者{t.counts.authorRoot}条），{t.counts.originalReadableReplies}条已读回复。{t.counts.additionalReadableFollowupReplies>0?`另有${t.counts.additionalReadableFollowupReplies}条专项补读。`:''}</p>
 {t.sections.map(s=><section key={s.key}><h3>{s.title}</h3>{s.items.map((item,i)=><div className="dc-point" key={i}><p>{item.text}</p><Evidence refs={item.refs}/></div>)}</section>)}
 <details className="dc-evidence"><summary>本专题的作品来源</summary><Table heads={['作品','发布','样本位置']} rows={t.primaryWorks.map(w=>[<Link key={w.id} url={w.url}>{w.id} · {w.label}</Link>,w.publishedAt,w.window])}/></details></div></details>)}
 </section>
 <section id="dc-authors"><h2>从一条作品，看到同作者的连续发布</h2><p>比较窗口：{d.window}。新核对溯明42件、八宝动物园112件公开作品的全部日期；另对四位作者的58个已读详情重新分组。表中互动是9月12日至13日读取时的累计显示，含“万”的数值按近似值换算。</p>
 <Table heads={['作者','日期覆盖','窗口内条目','点赞中位数','点赞范围','收藏中位数','读取时作品龄']} rows={d.authors.map(a=>[<Jump key={a.name} id={'dc-author-'+a.name}>{a.name}</Jump>,a.complete?`${a.details}/${a.listed} 可见条目全核`:`${a.details}件部分样本`,a.n,fmt(a.like.median),`${fmt(a.like.min)}—${fmt(a.like.max)}`,fmt(a.collect.median),`${fmt(a.age.min)}—${fmt(a.age.max)}天`])}/>
 <figure className="dc-calendar"><figcaption>八周发布分布</figcaption><div className="dc-table"><table><thead><tr><th>作者 / 覆盖</th>{['7.13','7.20','7.27','8.03','8.10','8.17','8.24','8.31'].map(t=><th key={t}>{t}起</th>)}</tr></thead><tbody>{[...d.authors].sort((a,b)=>Number(b.complete)-Number(a.complete)).map(a=><tr key={a.name}><th>{a.name}<small>{a.complete?'公开列表日期齐全':'只列已读记录'}</small></th>{a.weeks.map((n,i)=><td key={i} className={n==null?'dc-unknown':n===0?'dc-zero':'dc-active'}><span>{n==null?'—':n}</span></td>)}</tr>)}</tbody></table></div><p className="dc-meta">上方三位的0表示本次完整可见列表在该周没有条目，不包含已删除或私密作品；其余三位的空白表示未读到，不能按零发布解释。条目数量未去重为独立成片。</p></figure>
 <h3>同作者对照后，哪些判断发生了变化</h3>{d.authorFindings.map(f=><details className="dc-dossier" key={f.id}><summary><strong>{f.title}</strong></summary><div className="dc-dossier-body"><p>{f.fact}</p><p>{f.interpretation}</p><p><b>对照结果：</b>{f.counterEvidence}</p><p className="dc-meta">{f.notSupported}</p><WorkRefs ids={f.evidenceIds}/></div></details>)}
 <Table heads={['同作者比较组','条目数','点赞中位数','收藏／点赞中位','分享／点赞中位']} rows={d.focusedGroups.map(g=>[g.name,g.n,fmt(g.like.median),fmt((g.collectLike.median??0)*100)+'%',fmt((g.shareLike.median??0)*100)+'%'])}/><p className="dc-meta">比值按每件作品分别计算后取中位数；没有播放量分母，因此不是观看互动率、复用率或留存率。</p>
 {d.authors.map(a=><details className="dc-dossier" key={a.name} id={'dc-author-'+a.name}><summary><strong>{a.name} · 发布条目与指标</strong><span>{a.details}件</span></summary><div className="dc-dossier-body"><p>{a.coverage}</p><Table heads={['作品','发布时间','窗口','赞 / 评 / 藏 / 转','读取时间']} rows={d.works.filter(w=>w.author===a.name).sort((a,b)=>b.publishedAt.localeCompare(a.publishedAt)).map(w=>[<span key={w.id}><Link url={w.url}>{w.title}</Link><small className="dc-meta">{w.id}{w.pinned?' · 主页置顶':''} · {w.kind}</small></span>,w.publishedAt,w.window,['like','comment','collect','share'].map(k=>w.metricsRaw[k as keyof typeof w.metricsRaw]??'未显示').join(' / '),w.observedAt.slice(0,19)+' UTC'])}/></div></details>)}
 </section>
 <section id="dc-new-comments"><h2>把作者生产约束与观众反馈放在一起</h2>{d.newComments.map(c=><article className="dc-case" key={c.id}><h3><Link url={c.url}>{c.title}</Link></h3><p>{c.summary}</p><Table heads={['评论位置','匿名转述','能说明什么']} rows={c.comments.map(x=>[x.position,x.text,x.meaning])}/><p className="dc-implication">{c.implication}</p><p className="dc-meta">{c.id} · 发布{c.publishedAt} · 读取{c.observedAt.slice(0,19)} UTC。位置为当次可见排序。</p></article>)}</section>
 <section id="dc-supply"><h2>评论里的需求，现有平台解决到了哪里</h2><p>四条具体诉求，对照十二条供给路径。先看已提供的材料和方法，再判断剩余问题属于使用条件、资源权限、信息发现还是结果核验。</p>
 {d.supply.demands.map((x,i)=><details className="dc-dossier" key={x.id} id={'dc-demand-'+x.id} open={i===0}><summary><b>{String(i+1).padStart(2,'0')}</b><strong>{x.title}</strong></summary><div className="dc-dossier-body"><p className="dc-lead">{x.counterexample}</p><details className="dc-evidence"><summary>提出问题的评论</summary>{x.evidence.map(e=><p key={e.position}><Link url={e.workUrl}>{e.workId} · 顶层{e.position}</Link>：{e.paraphrase}</p>)}<p>{x.signalBoundary}</p></details><Table heads={['平台与具体对象','已经提供','对应关系','适用条件与剩余问题']} rows={x.supplyPaths.map(p=>[<div key={p.id}><b>{p.label}</b>{p.sourceIds.map(id=>{const s=d.supply.sources.find(s=>s.id===id)!;return <p key={id}><Link url={s.url}>{s.title}</Link></p>;})}</div>,p.provided.join(' '),p.matchToDemand,p.gapsOrConditions.join(' ')])}/><p><b>剩余问题：</b>{x.remainingGapType}</p><p><b>社区可能增加的内容：</b>{x.additionalValueHypothesis}</p><p><b>如何核实：</b>{x.nextCheck}</p></div></details>)}
 <details className="dc-evidence"><summary>16个供给来源的阅读范围与时间</summary><Table heads={['来源','发布／修改','读取日期','实际读到的部分']} rows={d.supply.sources.map(s=>[<Link key={s.id} url={s.url}>{s.id} · {s.title}</Link>,s.dateLabel,s.accessedOnLocal,s.readScope])}/></details></section>
 <section id="dc-next"><h2>下一步优先补哪条证据</h2><div className="dc-next">{d.next.map((n,i)=><article key={n.question}><span className="dc-index">{i+1}</span><h3>{n.question}</h3><p>{n.action}</p></article>)}</div></section>
 <details className="dc-evidence" id="dc-method"><summary>数据覆盖与计算口径</summary><p>六作者212个详情中，70个条目在固定八周窗口；与63件评论样本合并按作品URL去重后共{d.counts.totalDetailUrls}件。154个新增日期核对中，有3个URL已在评论样本，新增作品151件；这两位作者已在51位作者中，不增加作者人数。</p><p>六专题沿用63件评论样本，467条顶层与247条回复、13条专项补读分别计量。本次另补两件作品的20个顶层位置，18条有文字，其中1条作者说明；六个楼层共10条已读回复，单列于生产约束案例。评论未按独立用户去重。</p><p>完整可见列表不包括已删除或私密内容。所有作品均未完整观看；评论中的技术失败、历史错误、产品效果均保留为主张。没有全站供给分母、播放量、同龄曝光或跨周用户回访，因此不计算行业供需比、不排赛道规模，也不把付费工具当社区必经路径。</p><p><a href={base+'coverage.csv'} download>日期覆盖表</a> · <a href={base+'theme-analysis.md'} download>六专题全文</a> · <a href={base+'supply-matches.md'} download>供给对照全文</a> · <a href={base+'author-analysis.md'} download>作者比较与复算</a></p></details>
 </section>}
