'use client';
/* oxlint-disable next/no-img-element -- Read the same unedited evidence media in each arrangement. */
import { useEffect, useRef, useState, type ReactNode } from 'react';
export type PoolItem={id:string;type:string;title:string;summary:string;sourceStatus:string;media:{src:string;alt:string;evidenceScope:string}|null;detail:{heading:string;text:string}[];primaryAction:{label:string;kind:string;target:string};relatedIds:string[];readerValue:string;operatorWork:string;readiness:string;sourceIds:string[]};
export type Arrangement={id:string;label:string;promise:string;headline:string;layout:string;groups:{title:string;description:string;ids:string[]}[];why:string;tradeoff:string;returnPath:string;supplyWork:string;mobile:string;representationLimit?:string};
export function ContentArrangementLab({items,modes,scope,limit,activeMode,onMode,refs}:{items:PoolItem[];modes:Arrangement[];scope:string;limit:string;activeMode:string;onMode:(id:string)=>void;refs:(ids:string[])=>ReactNode}){
 const [stage,setStage]=useState<'discover'|'detail'|'return'>('discover'),[selected,setSelected]=useState(items[0].id),[filter,setFilter]=useState('全部'),[saved,setSaved]=useState<string[]>([]),[history,setHistory]=useState<string[]>([]);
 const focus=useRef<HTMLHeadingElement>(null),mode=modes.find(m=>m.id===activeMode)??modes[0],item=items.find(i=>i.id===selected)??items[0];
 const types=['全部',...new Set(items.map(i=>i.type))];
 useEffect(()=>{if(stage!=='discover')focus.current?.focus();},[stage,selected]);
 const open=(id:string)=>{if(!items.some(i=>i.id===id))return;setSelected(id);setHistory(h=>[id,...h.filter(v=>v!==id)]);setStage('detail');};
 const save=(id:string)=>setSaved(s=>s.includes(id)?s.filter(v=>v!==id):[id,...s]);
 const card=(record:PoolItem,index:number)=><article key={record.id} className={`v23-item v23-item-${mode.layout}`}>
  {record.media&&<button className="v23-image-button" onClick={()=>open(record.id)} aria-label={`阅读${record.title}`}><img src={record.media.src} alt={record.media.alt} loading="lazy"/></button>}
  <div className="v23-item-copy"><span className="v23-type">{mode.layout==='topics'?`${index+1}. `:''}{record.type}</span><h4><button onClick={()=>open(record.id)}>{record.title}</button></h4><p>{record.summary}</p><p className="v23-provenance">{record.sourceStatus}</p><div className="v23-card-actions"><button onClick={()=>open(record.id)}>阅读全文</button><button onClick={()=>save(record.id)} aria-pressed={saved.includes(record.id)}>{saved.includes(record.id)?'取消保存':'保存到本页'}</button></div></div>
 </article>;
 const action=()=>{const a=item.primaryAction;if(a.kind==='read-related')return <button className="v23-action" onClick={()=>open(a.target)}>{a.label}</button>;if(['view-source','view-image','download-local'].includes(a.kind)&&a.target)return null;return <p>{a.label}</p>;};
 return <section className="v23-lab">
  <h2>同一组材料的四种浏览编排</h2><p>{scope}</p>
  <fieldset className="v23-controls" aria-label="切换内容组织方式">{modes.map(m=><button key={m.id} aria-pressed={m.id===mode.id} className={m.id===mode.id?'is-active':''} onClick={()=>{onMode(m.id);setStage('discover');}}>{m.id} · {m.label}</button>)}</fieldset>
  <p className="v23-lab-note">内容编排示意。阅读与保存记录仅在本页临时保留，切换研究页或标签后重置。</p>
  {mode.representationLimit&&<p className="v23-reading-boundary">{mode.representationLimit}</p>}
  <div className="v23-surface">
   <header className="v23-surface-header"><strong>多元拾光 · 内容编排示意</strong><nav aria-label="示意浏览路径"><button aria-current={stage==='discover'?'page':undefined} onClick={()=>setStage('discover')}>发现内容</button><button aria-current={stage==='return'?'page':undefined} onClick={()=>setStage('return')}>再次访问 · 已保存 {saved.length}</button></nav></header>
   {stage==='discover'&&<div className={`v23-discover v23-layout-${mode.layout}`}><div className="v23-discover-heading"><h3>{mode.headline}</h3><p>{mode.promise}</p><label>内容形态 <select aria-label="筛选示意内容形态" value={filter} onChange={e=>setFilter(e.target.value)}>{types.map(t=><option key={t}>{t}</option>)}</select></label></div>{mode.groups.map(g=>{const visible=g.ids.map(id=>items.find(x=>x.id===id)!).filter(x=>filter==='全部'||x.type===filter);return visible.length?<section key={g.title} className="v23-content-group"><h3>{g.title}</h3><p className="muted">{g.description}</p><div className="v23-content-items">{visible.map(card)}</div></section>:null;})}<p className="v23-provenance">共 {items.filter(i=>filter==='全部'||i.type===filter).length} 条研究整理内容 · 每种组织方式均可访问同一内容池</p></div>}
   {stage==='detail'&&<article className="v23-reader"><button className="text-button" onClick={()=>setStage('discover')}>← 返回{mode.label}保留当前筛选</button><p className="v23-type">{item.type}</p><h3 tabIndex={-1} ref={focus}>{item.title}</h3><p>{item.summary}</p><p className="v23-provenance">{item.sourceStatus}</p>{item.media&&<figure><a href={item.media.src} target="_blank" rel="noreferrer"><img src={item.media.src} alt={item.media.alt}/></a><figcaption>{item.media.evidenceScope}</figcaption></figure>}{item.detail.map(d=><section key={d.heading}><h4>{d.heading}</h4><p style={{whiteSpace:'pre-wrap'}}>{d.text}</p></section>)}<p className="v23-reading-boundary">{item.readiness}</p><div className="v23-card-actions">{action()}<button aria-pressed={saved.includes(item.id)} onClick={()=>save(item.id)}>{saved.includes(item.id)?'取消保存':'保存到本页，稍后再读'}</button></div>{refs(item.sourceIds)}<section className="v23-related"><h4>接着看</h4>{item.relatedIds.map(id=>{const related=items.find(i=>i.id===id);return related?<button key={id} onClick={()=>open(id)}><span>{related.type}</span>{related.title} →</button>:null;})}</section><p className="muted">这条内容的价值：{item.readerValue}</p></article>}
   {stage==='return'&&<section className="v23-return"><h3 tabIndex={-1} ref={focus}>回到已有内容</h3><p>{mode.returnPath}</p><h4>本页保存</h4>{saved.length?<div className="v23-content-items">{saved.map(id=>items.find(i=>i.id===id)!).map(card)}</div>:<div className="v23-empty"><p>本页还没有保存内容。可以先打开一条内容，再保存并回到这里查看。</p><button onClick={()=>setStage('discover')}>回到发现内容</button></div>}<h4>本页刚读过</h4>{history.length?<div className="v23-reading-history">{history.map(id=><button key={id} onClick={()=>open(id)}>{items.find(i=>i.id===id)!.title} →</button>)}</div>:<p>尚未打开内容详情。</p>}<p className="v23-provenance">这里只展示本页操作结果，没有模拟新回复、通知或用户留存。</p></section>}
  </div>
  <aside className="v23-design-reading" aria-label="当前编排的研究解释"><h3>这一种编排改变了什么</h3><dl><div><dt>选择理由</dt><dd>{mode.why}</dd></div><div><dt>需要承担</dt><dd>{mode.tradeoff}</dd></div><div><dt>运营工作</dt><dd>{stage==='detail'?item.operatorWork:mode.supplyWork}</dd></div><div><dt>移动端顺序</dt><dd>{mode.mobile}</dd></div></dl><p>{limit}</p></aside>
 </section>;
}
