'use client';
import {profiles} from '@/lib/profiles';
import {groups} from '@/lib/research-types';
import raw from '@/lib/platform-digests.json';
import './cross-platform.css';
const liblib={id:'liblib',tagline:'以模型和工作流共享为基础的 AI 创作平台',thesis:'把创作效果和制作方法放在一起：用户从发现效果，进入方法和实际制作。',users:[{role:'灵感浏览者',task:'找风格、看效果',value:'作品与作者提供参考。'},{role:'任务使用者',task:'商品精修、换背景、材质处理',value:'按任务找模型和工作流。'},{role:'资源作者',task:'发布方法、维护版本',value:'获得分发与作者激励。'},{role:'进阶创作者',task:'调整效果、组合方法与控制制作过程',value:'选择模型和参数、编辑节点，通过LibTV复制画布继续制作。'},{role:'API接入方',task:'把生成能力接入自己的产品',value:'使用独立API服务与计费体系。'}],userRefs:[1,5,6,11,13],distribution:{title:'用途、资源类型与兼容条件分层',items:[{label:'用途',text:'电商营销、风格插画等任务分类。'},{label:'条件',text:'模型类型、底模、许可与使用筛选。'},{label:'发现',text:'作品、精选与季节专题提供入口。'}],refs:[1]},journey:{title:'作品连接资源与制作',steps:['看作品或选任务','核对资源与输入条件','进入生成器或项目','保存并继续编辑'],detail:'LibTV 画布样本可复制并刷新找回；整套运行、成片一致性与导出未验证。',refs:[0,5]},supply:{title:'作者提供方法并维护，平台分发和激励',items:[{label:'作者',text:'模型、模板、工作流、作品和版本维护。'},{label:'平台',text:'推荐、专题、作者计划与在线工具。'},{label:'反馈',text:'讨论、返图和作者回复形成改进线索。'}],refs:[6,13,15]},business:{rows:[{payer:'创作使用者',offer:'会员、积分与资源许可',condition:'资源许可与平台会员分别核对。'},{payer:'API接入方',offer:'独立API服务',condition:'与网页生成分开计费。'},{payer:'资源作者',offer:'作者激励',condition:'实际收入与维护成本未公开。'}],limit:'社区对收入与回访的贡献未单独披露。',refs:[11,13]}};
export const comparisonProfiles=[liblib,...raw];
export const comparisonById=new Map(comparisonProfiles.map(p=>[p.id,p]));
export const dimensions=[['users','用户与价值'],['distribution','分类与分发'],['journey','使用路径'],['supply','供给与运营'],['business','商业机制']] as const;
type Dimension=typeof dimensions[number][0];
export function DossierLink({id,children}:{id:string;children?:React.ReactNode}){return <a href={'/#'+id} target="_blank" rel="noopener noreferrer">{children||profiles.find(p=>p.id===id)?.name} ↗</a>;}
export function EvidenceLinks({id,refs,label='依据'}:{id:string;refs:number[];label?:string}){return <div className="cross-refs">{refs.map((r,i)=><a key={r} href={id==='liblib'?'/liblib-evidence?section=liblib-function-'+r:'/platform-evidence?section='+id+'-function-'+r+'#'+id} target="_blank" rel="noopener noreferrer">{label}{refs.length>1?' '+(i+1):''} ↗</a>)}</div>;}
export function PlatformGroups(){return <div className="cross-groups">{groups.map((g,i)=><section key={g}><span className="cross-number">0{i+1}</span><h3>{g}</h3><p>{['比较可复用资源如何被发现和采用','比较作品、教程与制作工具如何衔接','比较学习材料如何进入共学与贡献','比较依赖、配置与应用交付','比较讨论、回应与成员治理'][i]}</p><div>{profiles.filter(p=>p.group===g).map(p=><DossierLink key={p.id} id={p.id}/>)}</div></section>)}</div>;}
export function TopicCell({id,dimension}:{id:string;dimension:Dimension}){const p=comparisonById.get(id)!;if(dimension==='users')return <><ul>{p.users.map(u=><li key={u.role}><b>{u.role}</b><span>{u.task}；{u.value}</span></li>)}</ul><EvidenceLinks id={id} refs={p.userRefs}/></>;if(dimension==='journey')return <><ol className="cross-path">{p.journey.steps.map(s=><li key={s}>{s}</li>)}</ol><p className="cross-note">{p.journey.detail}</p><EvidenceLinks id={id} refs={p.journey.refs}/></>;if(dimension==='business')return <><ul>{p.business.rows.map(r=><li key={r.payer}><b>{r.payer} · {r.offer}</b><span>{r.condition}</span></li>)}</ul><p className="cross-note">{p.business.limit}</p><a href={'/platform-evidence?section=commercial#'+id} target="_blank" rel="noopener noreferrer">商业规则与来源 ↗</a></>;const block=p[dimension];return <><h4>{block.title}</h4><ul>{block.items.map(x=><li key={x.label}><b>{x.label}</b><span>{x.text}</span></li>)}</ul><EvidenceLinks id={id} refs={block.refs}/></>;}
