import interest from '@/lib/p1-interest.json';
import practical from '@/lib/p1-practical.json';
type Source={title:string;url:string;date:string|null;kind:string;readScope:string;fact:string;limit:string;isNew:boolean};
type Domain={display?:Partial<Domain>;id:string;name:string;user:string;trigger:string;consumes:string;aiRole:string;suppliers:string;existing:string;gap:string;evidenceStatus:string;sources:Source[]};
function Compare({title,id,domains}:{title:string;id:string;domains:Domain[]}){return <section id={id}><h2>{title}</h2><div className="ms-table"><table><thead><tr><th>领域与使用者</th><th>需要什么，AI做什么</th><th>供给与已有满足</th><th>证据与待核问题</th></tr></thead><tbody>{domains.map(item=>{const d={...item,...item.display};return <tr key={d.id}><th scope="row"><h3>{d.name}</h3><p>{d.user}</p><small>{d.trigger}</small><p><a href={'#p1-source-'+d.id}>查看依据 ↓</a></p></th><td><p>{d.consumes}</p><p><strong>AI作用：</strong>{d.aiRole}</p></td><td><p>{d.suppliers}</p><p>{d.existing}</p></td><td><p><strong>{d.evidenceStatus}</strong></p><p>{d.gap}</p></td></tr>})}</tbody></table></div></section>}
export function DomainBaseline(){const a=interest.domains as Domain[],b=practical.domains as Domain[];return <div className="domain-baseline" id="domain-baseline">
<section><h2>14个领域的需求与供给比较</h2><p>按使用者、任务、AI作用及现有内容与工具比较。兴趣消费重点看作品和讨论，实际应用同时看成果怎样使用、方法与经验是否有人查阅。各领域的证据状态单列。兴趣消费作为创作者市场与选题依据，实际应用用于设计任务支持；下表的社媒观众属于研究对象，不属于多元拾光服务对象。</p><nav className="ms-links" aria-label="领域比较目录"><a href="#p1-interest">兴趣消费六类</a><a href="#p1-practical">实际应用八类</a><a href="#p1-evidence">案例与依据</a></nav></section>
<div className="ms-grid three"><article><h3>观看者关注具体作品</h3><p>故事样本围绕剧情和角色展开讨论，音乐样本出现找版本和重复收听。观看者与制作学习者需要分别理解。</p><a href="#p1-interest">查看兴趣消费比较 ↓</a></article><article><h3>使用成果与查阅经验是两种需要</h3><p>商家使用或弃用AI图已有实例。执行者是否需要持续阅读教程、修改记录和同行经验，仍需直接反馈支持。</p><a href="#p1-practical">查看实际应用比较 ↓</a></article><article><h3>先核已有满足，再找剩余问题</h3><p>合集、音乐曲目页、原作者回复和官方教程已承接部分需要。研究重点是具体用户在这些路径上还遇到什么问题。</p><a href="#p1-evidence">查看案例与依据 ↓</a></article></div>
<Compare title="兴趣消费六类" id="p1-interest" domains={a}/><Compare title="实际应用八类" id="p1-practical" domains={b}/>
<section id="p1-evidence"><h2>案例与依据</h2><p>原页观察、作者或客户自述、机构研究分别标注。公开评论反映所读讨论；厂商介绍说明产品定位。资料沿用原观察日期，报告和案例不合并计为用户人数。</p>{[...a,...b].map(d=><section key={d.id} id={'p1-source-'+d.id}><h3>{d.name}</h3><ol className="ms-sources">{d.sources.map((s,i)=><li key={s.url+i}><a href={s.url} target="_blank" rel="noopener noreferrer">{s.title} ↗</a><small>{s.kind} · {s.date||'日期未标明'}</small><p>{s.fact}</p><small>{s.limit}</small><small>阅读范围：{s.readScope.replace(/本次|本轮/g, "")}</small></li>)}</ol><a href={a.some(x=>x.id===d.id)?'#p1-interest':'#p1-practical'}>返回比较表 ↑</a></section>)}</section>
</div>}
