'use client';
/* oxlint-disable next/no-img-element -- Research images preserve original bytes and link to the full evidence. */
import data from '@/lib/evidence-synthesis.json';

function jump(id:string) {
 const target=document.getElementById(`v20-${id}`);
 for(let node=target?.parentElement;node;node=node.parentElement){if(node instanceof HTMLDetailsElement)node.open=true;}
 target?.scrollIntoView({behavior:'smooth',block:'start'});
}
function Refs({ids}:{ids:string[]}) {
 return <div className="study-refs">{ids.map(id=><a key={id} href={`#v20-${id}`} onClick={e=>{e.preventDefault();jump(id);}}>〔{id}〕</a>)}</div>;
}
function EvidenceImage({index}:{index:number}) {
 const im=data.images[index];
 return <figure className="content-evidence-figure" style={{margin:'1.5rem 0'}}><a href={im.src} target="_blank" rel="noreferrer" aria-label={`查看${im.title}原图`}><img src={im.src} alt={im.title} width={im.width} height={im.height} loading="lazy"/></a><figcaption><strong>{im.title}</strong> · {im.kind}<p>{im.caption}</p></figcaption></figure>;
}
function Bullets({items}:{items:string[]}) {return <ul>{items.map(x=><li key={x}>{x}</li>)}</ul>;}

export function EvidenceSynthesis({navigate,embedded=false}:{navigate:(id:string)=>void;embedded?:boolean}) {
 const m=data.makenow,v=data.value,s=data.supply,a=data.api;
 return <div className="framework-study">
  <div className="page-heading">{embedded?<h2>{data.title}</h2>:<h1>{data.title}</h1>}</div>
  <div className="study-actions"><button className="text-button" onClick={()=>navigate('makenow')}>MakeNow 入口研究</button></div>
  <nav className="study-actions" aria-label="目录">{[['findings','判断更新'],['questions','八项进展'],['forms','承载形式'],['makenow','副本交接'],['value','消费与回应'],['supply','跨时间维护'],['work','供给工作'],['api','API材料'],['remaining','剩余缺口'],['sources','来源与日期']].map(([id,label])=><button key={id} className="text-button" onClick={()=>jump(id)}>{label}</button>)}</nav>

  <section id="v20-findings" className="study-platform"><h2>这次改变了哪些判断</h2>{data.findings.map(f=><article key={f.title}><h3>{f.title}</h3><p><strong>事实：</strong>{f.fact}</p><p><strong>分析：</strong>{f.analysis}</p><Refs ids={f.refs}/></article>)}</section>
  <section id="v20-questions" className="study-platform"><h2>八项进展：补了什么，还缺什么</h2><div className="table-wrap"><table><thead><tr><th>问题与状态</th><th>增补</th><th>未解决</th><th>继续核对</th></tr></thead><tbody>{data.questions.map(q=><tr key={q.id}><th>{q.id} {q.title}<p className="muted">{q.status}</p></th><td>{q.change}</td><td>{q.missing}</td><td>{q.next}</td></tr>)}</tbody></table></div></section>
  <section id="v20-forms" className="study-platform"><h2>内容承载：先看用户需要判断什么</h2><div className="table-wrap"><table><thead><tr><th>内容／用户问题</th><th>列表与详情分别承载什么</th><th>为什么这样组织</th><th>质量与持续工作</th></tr></thead><tbody>{data.valueMatrix.map(f=><tr key={f.form}><th>{f.form}<p>{f.question}</p><p className="muted">{f.sample}</p><Refs ids={f.refs}/></th><td><p><strong>列表：</strong>{f.list}</p><p><strong>详情：</strong>{f.detail}</p></td><td>{f.why}</td><td><p>{f.quality}</p><p className="muted">工作：{f.work}</p></td></tr>)}</tbody></table></div></section>

  <section id="v20-makenow" className="study-platform"><h2>MakeNow：从公开案例到自己的副本</h2><p>{m.summary}</p><p className="muted">{m.sampleBoundary}</p><a href={m.sourceUrl} target="_blank" rel="noreferrer">公开原件：{m.sourceTitle}</a><div className="table-wrap"><table><thead><tr><th>步骤／操作</th><th>实际观察</th><th>证据边界</th></tr></thead><tbody>{m.records.map(r=><tr id={`v20-${r.id}`} key={r.id}><th>{r.id} {r.step}<p className="muted">{r.action}</p></th><td><strong>{r.status}</strong><p>{r.result}</p></td><td>{r.limit}</td></tr>)}</tbody></table></div><EvidenceImage index={0}/><h3>交接不能只记一个成功状态</h3><div className="table-wrap"><table><thead><tr><th>层级</th><th>本样本结果</th><th>状态</th></tr></thead><tbody>{m.deliveryLevels.map(l=><tr key={l.level}><th>{l.level}</th><td>{l.result}</td><td>{l.status}</td></tr>)}</tbody></table></div><p><strong>生成：{m.generation.status}提交 {m.generation.submissions} 次。</strong>{m.generation.reason}</p><p className="muted">保留的改动：{m.sideEffect}</p><p>{m.interpretation}</p><details className="study-sources"><summary>这个样本还涉及哪些内容工作</summary>{m.supplyWork.map(w=><article key={w.work}><h3>{w.work}</h3><p>{w.evidence}</p><p>{w.needed}</p><p className="muted">{w.type}</p></article>)}</details></section>

  <section id="v20-value" className="study-platform"><h2>消费与回应：四个具体对象</h2><p>{v.summary}</p><p className="muted">{v.method.selection}</p>{v.samples.map(x=><article id={`v20-${x.id}`} key={x.id}><h3><a href={x.url} target="_blank" rel="noreferrer">{x.name}</a></h3><p><strong>用户价值：</strong>{x.userValue}</p><p className="muted">{x.sampleRole} {x.pageDate}</p><div className="table-wrap"><table><tbody><tr><th>列表／发现入口</th><td>{x.cardOrList.observed}<p className="muted">{x.cardOrList.status}</p></td></tr><tr><th>详情实际提供</th><td>{x.detail}</td></tr><tr><th>接下来能做什么</th><td>{x.nextActions}</td></tr><tr><th>已见回应或结果</th><td>{x.actualResponse}</td></tr></tbody></table></div><p>{x.analysis}</p><p><strong>质量问题：</strong>{x.qualityQuestion}</p><p className="muted">{x.notDerivable}</p><Refs ids={x.sourceIds}/><details className="study-sources"><summary>供给角色、可安排的工作与增补</summary><p>{x.supplyAndMaintenance.observedRoles}</p><p>以下是从交付要求推导的工作，不是竞品内部流程记录：</p><Bullets items={x.supplyAndMaintenance.proposedWork}/><p className="muted">{x.supplyAndMaintenance.costBoundary}</p><p>{x.updateComparedToV18}</p></details></article>)}<details className="study-sources"><summary>跨样本比较与研究方法</summary>{v.comparisons.map(c=><article key={c.dimension}><h3>{c.dimension}</h3><p>{c.finding}</p><p className="muted">{c.limit}</p><Refs ids={c.evidenceIds}/></article>)}<p>{v.method.verification}</p><p>{v.method.visualBoundary}</p><p>{v.method.dateBoundary}</p></details></section>

  <section id="v20-supply" className="study-platform"><h2>发布以后：谁接着处理问题</h2><p>{s.summary}</p><p className="muted">{s.method.selection}</p>{s.cases.map(c=><article key={c.id} id={`v20-${c.id}`}><h3><a href={c.resourceUrl} target="_blank" rel="noreferrer">{c.name}</a></h3><p>{c.deltaFromV18}</p><div className="table-wrap"><table><thead><tr><th>时间</th><th>发生了什么</th><th>证据层级</th></tr></thead><tbody>{c.timeline.map((t,i)=><tr key={`${c.id}-${i}`}><th>{t.date}</th><td>{t.event}</td><td>{t.status}<Refs ids={t.sourceIds}/></td></tr>)}</tbody></table></div><h4>可见的实际分工</h4><div className="table-wrap"><table><thead><tr><th>参与者</th><th>工作</th><th>发生条件与来源</th></tr></thead><tbody>{c.actualWork.map(w=><tr key={w.role}><th>{w.role}</th><td>{w.work}</td><td>{w.frequency}<Refs ids={w.sources}/></td></tr>)}</tbody></table></div><p><strong>平台：</strong>{c.platformAndCommunity.platform}</p><p><strong>成员：</strong>{c.platformAndCommunity.community}</p><p>{c.platformAndCommunity.distinction}</p><p><strong>分析：</strong>{c.implication}</p><p className="muted">{c.limits}</p><details className="study-sources"><summary>成本缺口与可采用的工作安排</summary><p>{c.costs.observed}</p><p>尚缺：{c.costs.unknown.join('、')}。</p><p>{c.costs.doNotCompute}</p><p>以下安排尚未执行：</p><Bullets items={c.proposedWork}/></details></article>)}<details className="study-sources"><summary>如何区分修复声明、版本变化与实际可用</summary><p>{s.method.inferenceLimits}</p><p>{s.method.timeBoundary}</p><p>{s.method.integrity}</p></details></section>
  <section id="v20-work" className="study-platform"><h2>招聘或合作前，先明确要交付哪些工作</h2><p>以下按内容承诺拆分首次交付与后续工作。它们是待执行的工作清单；当前没有足够工时、价格和供给频率数据，不能据此决定招聘人数。</p>{s.formWorklists.map(w=><article key={w.form}><h3>{w.form}</h3><p>{w.definition}</p><div className="table-wrap"><table><thead><tr><th>首次交付</th><th>后续维护</th></tr></thead><tbody><tr><td><Bullets items={w.initialWork}/></td><td><Bullets items={w.continuingWork}/></td></tr></tbody></table></div><p>{w.possibleRoles}</p><p>{w.burdenBoundary}</p><p className="muted">{w.evidenceStatus} {w.cost}</p></article>)}</section>

  <section id="v20-api" className="study-platform"><h2>API：一次历史成功，还需要检查什么</h2><p>{a.summary}</p><p className="muted">{a.task.whyThisSample}</p><EvidenceImage index={1}/><div className="table-wrap"><table><thead><tr><th>任务环节</th><th>已有</th><th>缺口／状态</th></tr></thead><tbody>{a.taskChain.map(t=><tr key={t.step}><th>{t.step}</th><td>{t.available}</td><td>{t.missing}<p className="muted">{t.status}</p></td></tr>)}</tbody></table></div><details className="study-sources"><summary>展开10项核对：规格、模型名、异步说明、编辑与费用</summary>{a.records.map(r=><article key={r.id} id={`v20-${r.id}`}><h3>{r.id} · {r.topic}</h3><p className="muted">{r.status}</p><p><strong>事实：</strong>{r.fact}</p><p><strong>分析：</strong>{r.interpretation}</p><p><strong>内容工作：</strong>{r.supports}</p><p className="muted">未知：{r.unknown}</p><Refs ids={r.sourceIds}/></article>)}</details><h3>三项产品能力，分别看交付证据</h3><div className="table-wrap"><table><thead><tr><th>产品</th><th>已有／当前可用</th><th>仍缺</th><th>边界</th></tr></thead><tbody>{a.threeProducts.map(p=><tr key={p.product}><th>{p.product}</th><td><p>{p.existing}</p><p>{p.usableNow}</p></td><td>{p.unknown}</td><td>{p.boundary}<Refs ids={p.sourceIds}/></td></tr>)}</tbody></table></div><details className="study-sources"><summary>费用为什么还不能计算</summary><h4>已有</h4><Bullets items={a.costBoundary.known}/><h4>缺少</h4><Bullets items={a.costBoundary.unknown}/><p>{a.costBoundary.calculationRule}</p><p className="muted">{a.costBoundary.limit}</p></details></section>
  <section id="v20-remaining" className="study-platform"><h2>还需要哪些依据，才能比较方向</h2><div className="table-wrap"><table><thead><tr><th>工作</th><th>需要记录</th><th>当前边界</th></tr></thead><tbody>{data.costFields.map(c=><tr key={c.field}><th>{c.field}</th><td>{c.record}</td><td>{c.boundary}</td></tr>)}</tbody></table></div><Bullets items={data.decisionsNotReady}/><p>下一组公开补证优先查看国内工作流平台的普通内容：从列表进入、实际交付说明、问题回应，到跨版本维护。已有的两个 Hugging Face 案例不足以代表其他平台。</p><div className="study-actions"><button className="text-button" onClick={()=>navigate('content')}>对照完整内容形态研究</button><button className="text-button" onClick={()=>navigate('strategy')}>查看尚未排序的方案</button></div></section>
  <details id="v20-sources" className="study-sources"><summary>来源、日期与访问限制</summary><p>外部页面、历史材料与现场操作分开记录。M20为操作记录，API20为材料核对项；都不能当作独立用户或完整成功任务。</p><p>{v.method.dataBoundary}</p><p>{s.method.integrity}</p>{v.accessAttempts.map(x=><p key={x.url}><a href={x.url} target="_blank" rel="noreferrer">访问记录</a>：{x.result} {x.relationship}</p>)}{data.sources.map(x=><article id={`v20-${x.id}`} key={x.id}><h3>{x.id} · {x.title}</h3>{x.url?<a href={x.url} target="_blank" rel="noreferrer">查看来源</a>:<p className="muted" style={{overflowWrap:'anywhere'}}>本地材料：{x.path}{x.lines&&`；行 ${x.lines}`}</p>}<p className="muted">核对：{x.accessedAt}{x.publishedAt&&`；原事件／修改：${x.publishedAt}`}</p><p>{x.scope}</p>{x.access&&<p>{x.access}</p>}</article>)}</details>
 </div>;
}
