'use client';
import data from '@/lib/market-research.json';
import {ResearchOutline} from './research-outline';
import './market-social.css';
function Link({href,children}:{href:string;children:React.ReactNode}){return <a href={href} target="_blank" rel="noopener noreferrer">{children} ↗</a>}
function Refs({ids}:{ids:string[]}){return <p className="ms-caption ms-links">{ids.map(id=>{const s=data.sources.find(s=>s.id===id);return s?<Link key={id} href={s.url}>{s.title}</Link>:null})}</p>}
export function IndustryResearch(){const purposes=data.metrics.filter(m=>m.group==='国内生成式AI使用目的');return <article className="ms-report">
 <header className="page-heading"><h1>行业与用户</h1><p>从 AI 能力、创作资源到内容消费，分别理解供给与需求。</p></header>
 <div className="ms-lead"><strong>AI 使用规模扩大，社区需求仍需按具体任务判断。</strong><p>行业同时发展生成编辑工具、可复用资源和内容分发。社媒中有人只为观看故事而来，这一事实用于观察创作者面对的市场需求；多元拾光服务创作者、实际应用者、学习者、资源贡献者和协作者，不触达或服务纯娱乐观众。不同角色会重叠，发布不是所有服务对象的前提。</p></div>
 <p className="ms-links"><Link href="/domain-research#research-conclusions">行业与社媒综合判断</Link><Link href="/task-research">具体任务、已有满足与结果</Link></p>
 <ResearchOutline items={[["mi-chain","行业结构"],["mi-roles","用户与任务"],["mi-purpose","使用数据"],["mi-change","关键变化"],["mi-evidence","来源"]]}/>
 <section id="mi-chain"><h2>三个环节，各自解决什么问题</h2><p>这是按任务划分的行业结构。同一平台可以跨越多个环节。</p>{data.industryLayers.map((l,i)=><div className="ms-layer" key={l.name}><div><small>0{i+1}</small><h3>{l.name}</h3></div><div><strong>提供的价值</strong><p>{l.value}</p><small>{l.serves}</small></div><div><strong>典型产品与平台</strong><p>{l.examples.domestic.join('；')}</p><small>{l.examples.overseas.join('；')}</small></div></div>)}<Refs ids={['M26-SEED25','M26-RH','M26-COMFY-T','M26-HF-CARD','S01']}/><h3>已研究平台的供给更多围绕创作与应用任务组织</h3><p>15家档案中的模型、工作流、教程和运行入口，显示平台围绕创作任务组织供给。这能说明平台导向；用户构成还要看实际使用和消费。作品观众、偶尔尝试的人与持续作者应分别识别，其中观众观察不等于多元拾光的服务规划。</p><p><Link href="/#audience">15家平台的用户与需求</Link> · <Link href="/#content">内容形态与页面承接</Link></p></section>
 <section id="mi-roles"><h2>身份按行为识别，专业程度单独判断</h2><div className="ms-grid two">{data.roles.map(r=><article key={r.name}><h3>{r.name}</h3><strong>{r.trigger}</strong><p>{r.consumes}</p><small>{r.overlap}</small></article>)}</div><div className="ms-lead"><strong>公开发布与自用需要分开统计。</strong><p>自己生成一张图、处理一份工作材料，是工具使用；公开发布作品、分享可用资源或持续答疑，才形成社区供给。多元拾光也服务不发布的实际应用者与学习者；专业人员可能只使用工具，爱好者也可能持续贡献。</p></div><Refs ids={['N24-S02','S01','M26-COMFY-S']}/></section>
 <section id="mi-purpose"><h2>全国使用数据说明任务基础</h2><figure><figcaption>2025年12月，中国生成式AI用户的使用目的 · 多选题</figcaption><div className="ms-bars">{purposes.map(m=><div className="ms-bar-line" key={m.id}><span>{m.label}</span><div className="ms-bar-track"><span style={{width:m.value+'%'}}/></div><strong>{m.value}%</strong></div>)}</div><p className="ms-caption">分母为调查中的生成式AI用户；图像与视频合并统计并包含处理。各用途可重叠，公开投稿与持续供给需另行观察。</p><Refs ids={['N24-S02']}/></figure><p>规模判断采用全国调查与移动应用监测两套口径。它们分别回答“多少人用过”和“应用有多少月活”，为市场背景提供依据。</p><p><Link href="/?section=cn-answer#china-users">全国规模、使用与付费数据</Link> · <Link href="/?section=cn-ledger#china-users">逐项指标与方法</Link></p></section>
 <section id="mi-change"><h2>影响社区研究的三项变化</h2><div className="ms-grid three"><article><h3>从生成到修改</h3><p>公开产品更新把参考素材、编辑和连续叙事纳入工具任务。供给研究要看能否做出可用结果，以及修改和维护所需的投入。</p><Refs ids={['M26-SEED25','M26-QWEN']}/></article><article><h3>从文件到可复用方法</h3><p>模板、模型卡与工作流说明帮助用户选方法、备素材和排错。资源价值包含说明与后续维护。</p><Refs ids={['M26-COMFY-T','M26-HF-CARD','M26-HF-REUSE']}/></article><article><h3>创作与观看有不同诉求</h3><p>海外创作者调查涉及成本、质量与工具选择；消费研究还涉及内容兴趣和信任，作为创作者市场需求、选题与合作对象依据。国内题材偏好需要具体作品与评论补足。</p><Refs ids={['I03','I04']}/></article></div><h3>国内与海外资料分开使用</h3><p>Adobe调查覆盖八个海外市场的活跃创作者；Reuters调查覆盖六国的新闻与AI使用。它们帮助发现研究问题，国内人群规模与题材选择仍以国内来源和实际观察判断。</p><p><Link href="/#content-demand">内容需求与社媒生态</Link></p></section>
 <section id="mi-evidence"><h2>原始资料与适用范围</h2><p>资料截至2026年9月16日；各来源的观察期、样本和阅读范围分别保留。厂商功能说明、用户调查与平台经营披露分别说明能力、使用情况和经营情况。</p><ol className="ms-sources">{data.sources.map(s=><li key={s.id}><Link href={s.url}>{s.title}</Link><small>{s.date||'未标明发布日期'} · {s.scope}</small><small>{s.method}</small></li>)}</ol></section>
 </article>}
