'use client';
/* oxlint-disable next/no-img-element -- Original research screenshots link to the full evidence. */
import data from '@/lib/makenow-study.json';
import latest from '@/lib/platform-supply.json';
import delivery from '@/lib/evidence-synthesis.json';

export function MakeNowStudy({navigate}:{navigate:(id:string,anchor?:string)=>void}) {
 const jump=(id:string)=>document.getElementById(`makenow-${id}`)?.scrollIntoView({behavior:'smooth',block:'start'});
 const refs=(ids:string[])=><div className="study-refs">{ids.map(id=><a key={id} href={`#makenow-${id}`} onClick={e=>{e.preventDefault();const target=document.getElementById(`makenow-${id}`);for(let node=target?.parentElement;node;node=node.parentElement){if(node instanceof HTMLDetailsElement)node.open=true;}target?.scrollIntoView({behavior:'smooth',block:'start'});}}>〔{id}〕</a>)}</div>;
 return <div className="framework-study">

  <div className="page-heading"><h1>MakeNow与素材交接</h1></div>
  <section id="makenow-current" className="study-platform" tabIndex={-1}><h2>复制、保存与素材检查</h2><p className="muted">观察日期：{latest.makenow.date}</p><p>{delivery.makenow.summary}</p><p>{latest.makenow.summary}</p><p className="muted">{latest.makenow.sampleBoundary}</p><div className="table-wrap"><table><thead><tr><th>检查步骤</th><th>实际结果</th><th>未确认的部分</th></tr></thead><tbody>{latest.makenow.records.map(r=><tr key={r.id}><th>{r.step}<p className="muted">{r.status}</p></th><td>{r.result}</td><td>{r.limit}</td></tr>)}</tbody></table></div><p>{latest.makenow.generation.remaining}</p><div className="study-actions"><a href={latest.makenow.sourceUrl} target="_blank" rel="noreferrer">公开案例：{latest.makenow.sourceTitle}</a><button className="text-button" onClick={()=>navigate('progress','v20-makenow')}>复制与文本保存记录</button><button className="text-button" onClick={()=>navigate('progress','v22-makenow')}>素材截图与费用检查来源</button></div></section>
  <details className="study-sources"><summary>入口、技能与公开案例观察（复制测试前）</summary><p className="muted">记录日期：{data.date}。下列未执行项保留观察当时状态，复制、保存与素材结果见上方检查。</p>
  <div className="study-actions"><a href="/research-kit/makenow-login-study.md" download>下载入口与案例观察记录</a><a href="https://dream.ai666.net/" target="_blank" rel="noreferrer">MakeNow官网</a><button className="text-button" onClick={()=>navigate('progress')}>返回自身条件与待解问题</button></div>
  <nav className="study-actions" aria-label="MakeNow研究目录">{[['findings','判断更新'],['traces','实际路径'],['cases','案例与截图'],['carriers','内容形态'],['comparison','社区还能补什么'],['supply','供给与维护'],['next','待补证据']].map(([id,label])=><button key={id} className="text-button" onClick={()=>jump(id)}>{label}</button>)}</nav>
  <section id="makenow-findings" className="study-platform"><h2>这次改变了哪些判断</h2>{data.findings.map(f=><article key={f.title}><h3>{f.title}</h3><p><strong>已确认：</strong>{f.fact}</p><p><strong>分析：</strong>{f.analysis}</p><p className="muted">{f.limit}</p>{refs(f.refs)}</article>)}</section>
  <section id="makenow-traces" className="study-platform"><h2>实际路径与停止位置</h2>{data.traces.map(t=><article key={t.title}><h3>{t.title}</h3><ol>{t.steps.map(s=><li key={s}>{s}</li>)}</ol><p><strong>到达：</strong>{t.reached}</p><p className="muted">{t.unproven}</p>{refs(t.refs)}</article>)}<details className="study-sources"><summary>查看本次11项精选技能名称</summary><p>{data.skillNames.join('、')}。</p><p className="muted">列表观察范围内均标官方；仅“画面提示词导演”完成详情与进入Agent路径抽查。其余名称不代表功能已验收。</p></details></section>
  <section id="makenow-cases" className="study-platform"><h2>两条作品，各自交付了什么</h2><p>以下数字来自页面节点分类，只描述样本结构。截图保留当时未显示的图片，不补画、不替换为成功素材。</p>{data.cases.map(c=><article key={c.url}><h3><a href={c.url} target="_blank" rel="noreferrer">{c.title}</a></h3><p><strong>{c.counts}</strong></p><p>{c.observation}</p><p><strong>内容判断：</strong>{c.reading}</p><figure style={{margin:'1.5rem 0'}}><a href={c.image} target="_blank" rel="noreferrer" aria-label={`查看${c.title}完整截图`}><img src={c.image} alt={`${c.title}公开画布节点清单与内容，部分图片未显示`} width={1274} height={884} loading="lazy" style={{width:'100%',height:'auto',borderRadius:12,border:'1px solid var(--border)'}}/></a><figcaption className="muted">{c.caption}</figcaption></figure><p className="muted">{c.limit}</p>{refs(c.refs)}</article>)}</section>
  <section id="makenow-carriers" className="study-platform"><h2>内容形态：看见什么、怎样用、谁提供</h2><p>下面把页面观察与设计原因放在一起比较。设计原因是基于路径的分析，并非用户研究已经证明的偏好。</p>{data.carriers.map(c=><article key={c.form}><h3>{c.form}</h3><p><strong>用户看见：</strong>{c.see}</p><p><strong>怎样使用：</strong>{c.use}</p><p><strong>为什么这样承载：</strong>{c.why}</p><p><strong>谁持续提供：</strong>{c.supply}</p><p className="muted">待补：{c.missing}</p><p className="muted">依据：{c.basis}</p></article>)}</section>
  <section id="makenow-comparison" className="study-platform"><h2>社区还能补什么：先比较，不选方向</h2><p>MakeNow已覆盖一些内容消费和使用环节。社区的价值需要说明新增信息、交流或服务是什么，也要计算多一个承接位置的维护负担。</p><div className="table-wrap"><table><thead><tr><th>比较问题</th><th>已有承接</th><th>可以继续研究的增量</th><th>取舍与负担</th></tr></thead><tbody>{data.comparisons.map(c=><tr key={c.question}><th>{c.question}</th><td>{c.existing}</td><td><p>{c.possible}</p><p className="muted">接着核对：{c.test}</p></td><td>{c.cost}</td></tr>)}</tbody></table></div></section>
  <section id="makenow-supply" className="study-platform"><h2>供给不止交一条视频</h2><p>以下是按交付环节拆出的职责，并非建议立即增加四个岗位。现有可稳定调用的人手仍按两名全栈、一名产品、一名运营计算，实际分工和工时待核实。</p><div className="table-wrap"><table><thead><tr><th>责任</th><th>要交什么</th><th>已有依据</th><th>仍缺什么</th></tr></thead><tbody>{data.maintenance.map(r=><tr key={r.role}><th>{r.role}</th><td>{r.responsibility}</td><td>{r.evidence}</td><td>{r.unknown}</td></tr>)}</tbody></table></div></section>

  <section id="makenow-next" className="study-platform"><h2>八项研究接着补哪里</h2>{data.next.map(n=><article key={n.question}><h3>{n.question}</h3><p className="muted">{n.status}</p><p><strong>已有：</strong>{n.known}</p><p><strong>待补：</strong>{n.need}</p><p><strong>影响的判断：</strong>{n.judgment}</p></article>)}<div className="study-actions"><button className="text-button" onClick={()=>navigate('progress')}>回到八项研究</button><button className="text-button" onClick={()=>navigate('content')}>对照竞品内容形态</button><button className="text-button" onClick={()=>navigate('discussion')}>对照社区与工具关系</button></div></section>
  <details className="study-sources"><summary>展开10项观察记录、页面与边界</summary>{data.observations.map(o=><article id={`makenow-${o.id}`} key={o.id}><h3>{o.id} · {o.title}</h3><p className="muted">{o.level} · {data.date}</p><p>{o.fact}</p><p className="muted">{o.limit}</p><a href={o.url} target="_blank" rel="noreferrer">查看相关页面</a></article>)}</details>
 </details>
 </div>;
}
