'use client';
/* oxlint-disable next/no-img-element -- Preserve the original research screenshot. */
import data from '@/lib/platform-supply.json';
function jump(id:string){const target=document.getElementById(`v22-${id}`);if(target instanceof HTMLDetailsElement)target.open=true;for(let node=target?.parentElement;node;node=node.parentElement){if(node instanceof HTMLDetailsElement)node.open=true;}target?.scrollIntoView({behavior:'smooth',block:'start'});}
function Refs({ids}:{ids:string[]}){return <div className="study-refs">{ids.map(id=><a key={id} href={`#v22-${id}`} onClick={e=>{e.preventDefault();jump(id);}}>〔{id}〕</a>)}</div>;}
export function PlatformSupply({navigate,embedded=false}:{navigate:(id:string)=>void;embedded?:boolean}){
 const c=data.content,o=data.operating,m=data.makenow;
 return <article className="framework-study">
  <div className="page-heading">{embedded?<h2>{data.title}</h2>:<h1>{data.title}</h1>}</div>

  <nav className="study-actions" aria-label="目录">{[['premise','供给前提'],['content','内容与页面'],['samples','六份编辑样例'],['data','已有经营数值'],['measurement','来源与口径'],['makenow','MakeNow检查'],['work','持续工作'],['sources','来源']].map(([id,title])=><button key={id} className="text-button" onClick={()=>jump(id)}>{title}</button>)}</nav>
  <section id="v22-premise" className="study-platform"><h2>谁来供给已明确，需求仍要另看</h2><p>{data.assumption.accountMeaning}</p><div className="table-wrap"><table><thead><tr><th>已有判断</th><th>当前判断</th><th>证据依据</th></tr></thead><tbody>{data.changedDecisions.map(r=><tr key={r.before}><td>{r.before}</td><td>{r.now}</td><td>{r.why}</td></tr>)}</tbody></table></div><p>{data.assumption.trust}</p></section>
  <section id="v22-content" className="study-platform"><h2>第一项：六种内容，分别怎样承载</h2><p>下面比较读者实际得到什么，以及平台要做什么。作品、教程、闪念已有局部代码依据；资源专用详情仍属冻结原型。六种形式不是新增六个频道的排期。</p><p className="muted">{c.scope.codeBoundary}</p>{c.rows.map(r=><article key={r.id} id={`v22-${r.id}`}><h3>{r.form}</h3><p>{r.consumerValue}</p><div className="table-wrap"><table><tbody><tr><th>列表卡片</th><td>{r.list}</td></tr><tr><th>进入详情</th><td>{r.detail}</td></tr><tr><th>怎样使用</th><td>{r.use}</td></tr><tr><th>为何这样组织</th><td>{r.whyThisForm}</td></tr><tr><th>现有承载</th><td>{r.current}<p className="muted">{r.gap}</p></td></tr><tr><th>供给与维护</th><td>{r.supply}<p>{r.maintenance}</p></td></tr></tbody></table></div><Refs ids={r.sourceIds}/><button className="text-button" onClick={()=>jump(r.sampleId)}>查看填好文字的研究草案 →</button></article>)}</section>
  <section id="v22-samples" className="study-platform"><h2>六份编辑样例：让内容形式有具体内容</h2><p>{c.scope.sampleBoundary}</p><p>同一蓝杯主题用来比较作品、教程和短表达，节省重复背景；它们不是三个独立需求样本。MakeNow案例沿用真实公开来源，其余资源示例仍只是结构草案。</p><div className="integrated-cards">{data.samples.map(s=><section key={s.id} className="integrated-card"><span>{s.form}研究草案</span><h3>{s.title}</h3><p>{s.status}</p><button className="text-button" onClick={()=>jump(s.id)}>阅读草案与交付要求 →</button></section>)}</div>{data.samples.map(s=><details key={s.id} id={`v22-${s.id}`} className="study-sources"><summary>{s.form} · {s.title}</summary><p><strong>{s.status}</strong></p>{s.currentUpdate&&<p className="notice">{s.currentUpdate}</p>}{s.sections.map((p,i)=><section key={`${s.id}-${i}`}><h3>{p.label}</h3>{p.paragraphs.map((x,j)=><p key={j} style={{whiteSpace:'pre-line'}}>{x}</p>)}</section>)}<h3>成为正式内容之前</h3><ul>{s.qualityCheck.map(x=><li key={x}>{x}</li>)}</ul><p><strong>谁来做：</strong>{s.ownerWork}</p><p><strong>当前承载：</strong>{s.currentCarrier}</p><Refs ids={s.sourceIds}/></details>)}</section>
  <section id="v22-data" className="study-platform"><h2>第二项：已有历史实数，尚缺当前经营结果</h2><p>{o.conclusion}</p><p className="muted">{o.scope.method}</p><div className="table-wrap"><table><thead><tr><th>记录与日期</th><th>已取得数值</th><th>统计对象与限制</th></tr></thead><tbody>{o.records.map(r=><tr key={r.id}><th>{r.topic}<p className="muted">{r.period}</p></th><td>{r.observed}<Refs ids={r.sourceIds}/></td><td>{r.denominator}<p className="muted">{r.cannotConclude}</p></td></tr>)}</tbody></table></div><p>这些历史总数没有附上已经排除运营、测试或机器流量的结果，不能直接称为清洗后的外部用户数据。渠道新访客曾出现失效的0值，也不能据此认定渠道没有带来新人。</p><details className="study-sources"><summary>这些数分别能用于什么判断</summary>{o.records.map(r=><article key={r.id}><h3>{r.topic}</h3><p>{r.use}</p><p>{r.segmentation}</p><Refs ids={r.sourceIds}/></article>)}</details></section>
  <section id="v22-measurement" className="study-platform"><h2>把供给来源和行为来源分开</h2><div className="table-wrap"><table><thead><tr><th>内容来源</th><th>行为主体</th><th>可以说明什么</th></tr></thead><tbody>{data.measurementAxes.map(r=><tr key={r.content+r.actor}><th>{r.content}</th><td>{r.actor}</td><td>{r.meaning}</td></tr>)}</tbody></table></div>{o.supplySegmentation.map(r=><article key={r.id}><h3>{r.issue}</h3><p>{r.finding}</p><p>{r.adjustment}</p><p className="muted">{r.boundary}</p><Refs ids={r.sourceIds}/></article>)}<h3>已有口径怎样继续使用</h3><div className="table-wrap"><table><thead><tr><th>问题</th><th>最小汇总</th><th>当前已有与尚缺</th></tr></thead><tbody>{o.availability.map(r=><tr key={r.id}><th>{r.question}</th><td>{r.minimumUsableOutput}<p className="muted">{r.decisionUse}</p></td><td>{r.availableNow}<p>仍缺：{r.missing}</p><Refs ids={r.sourceIds}/></td></tr>)}</tbody></table></div><details className="study-sources"><summary>不能从现有材料恢复的部分</summary><ul>{o.unrecoverable.map(x=><li key={x}>{x}</li>)}</ul></details></section>
  <section id="v22-makenow" className="study-platform"><h2>第三项：MakeNow原件与副本都出现素材显示问题</h2><p>{m.summary}</p><p className="muted">{m.sampleBoundary}</p><a href={m.sourceUrl} target="_blank" rel="noreferrer">查看公开原件：{m.sourceTitle}</a><figure className="content-evidence-figure" style={{margin:'1.5rem 0'}}><a href={m.screenshot.src} target="_blank" rel="noreferrer"><img src={m.screenshot.src} width={1274} height={884} loading="lazy" alt="MakeNow公开原件公交站台图片未显示，列表保留图片节点"/></a><figcaption>{m.screenshot.caption}</figcaption></figure><div className="table-wrap"><table><thead><tr><th>检查</th><th>看到什么</th><th>还不能确认什么</th></tr></thead><tbody>{m.records.map(r=><tr key={r.id}><th>{r.step}<p className="muted">{r.status}</p></th><td>{r.result}</td><td>{r.limit}</td></tr>)}</tbody></table></div><p><strong>生成提交{m.generation.submissions}次，API调用{m.generation.apiCalls}次。</strong>{m.generation.reason}</p><p>还需完成：{m.generation.remaining}</p><p className="muted">{m.sideEffect}</p><Refs ids={['M22-S01','M22-S02','M22-S03']}/><h3>对平台内容供给的影响</h3><ul>{m.implications.map(x=><li key={x}>{x}</li>)}</ul></section>
  <section id="v22-work" className="study-platform"><h2>平台长期供给，需要一起计算哪些工作</h2>{data.workload.map(w=><article key={w.work}><h3>{w.work}</h3><p>{w.example}</p><p>{w.cost}</p></article>)}<details className="study-sources"><summary>来源、合作与维护的进一步分析</summary>{c.supplyImplications.map(s=><article key={s.topic}><h3>{s.topic}</h3><p>{s.judgment}</p><p>{s.minimumPractice}</p><p className="muted">{s.boundary}</p></article>)}</details><p>{data.decisionBoundary}</p><div className="study-actions"><button className="text-button" onClick={()=>navigate('content')}>回看竞品的内容形式与截图</button><button className="text-button" onClick={()=>navigate('strategy')}>回看仍待比较的整体方案</button></div></section>
  <details id="v22-sources" className="study-sources"><summary>来源、日期和检索范围</summary><p>{o.scope.searchMethod}</p><p>{o.scope.limits}</p><p>{c.scope.competitorBoundary}</p>{data.sources.map(s=><article key={s.id} id={`v22-${s.id}`}><h3>{s.id} · {s.title}</h3>{s.url&&<a href={s.url} target="_blank" rel="noreferrer">查看来源或访问入口</a>}{s.path&&<p className="muted" style={{overflowWrap:'anywhere'}}>{s.path} · {s.lines}</p>}<p>{s.date}</p><p>{s.scope}</p></article>)}</details>
 </article>;
}
