import {useState} from 'react';
import data from '@/lib/platform-digests.json';
import {functionProfiles} from './function-pages';
import './platform-digest.css';
type Digest={id:string;tagline:string;thesis:string;users:{role:string;task:string;value:string}[];userRefs:number[];distribution:{title:string;items:{label:string;text:string}[];refs:number[]};journey:{title:string;steps:string[];detail:string;refs:number[]};supply:{title:string;items:{label:string;text:string}[];refs:number[]};business:{anchors?:{id:string;label:string}[];rows:{payer:string;offer:string;condition:string}[];limit:string;refs:number[]};chart?:{title:string;unit:string;rows:{label:string;value:number}[];note:string;refs:number[]}};
export const digestById=new Map((data as Digest[]).map(p=>[p.id,p]));
const chapters=[['users','用户与价值'],['distribution','分类与内容'],['journey','使用路径'],['supply','供给与运营'],['business','商业机制']];
function jump(id:string){document.getElementById(id)?.scrollIntoView({block:'start',behavior:'smooth'});}
export function PlatformDigestNav({id}:{id:string}){const [open,setOpen]=useState(false);return <nav className={'digest-nav '+(open?'is-open':'')} aria-label="档案章节"><button onClick={()=>setOpen(!open)} aria-expanded={open}>章节目录 · {open?'收起':'展开'}</button><ol>{chapters.map(([key,title],i)=><li key={key}><a href={'?section='+id+'-digest-'+key+'#'+id} onClick={e=>{e.preventDefault();jump(id+'-digest-'+key);setOpen(false);}}><small>{String(i+1).padStart(2,'0')}</small>{title}</a></li>)}</ol></nav>;}
function Refs({id,refs,label="详细依据"}:{id:string;refs:number[];label?:string}){return <div className="digest-refs">{refs.map((i,j)=><a key={i} title={functionProfiles.get(id)?.sections[i]?.title} href={'/platform-evidence?section='+id+'-function-'+i+'#'+id} target="_blank" rel="noopener noreferrer">{label}{refs.length>1?` ${j+1}`:""} ↗</a>)}</div>;}
export function PlatformDigest({id}:{id:string}){const p=digestById.get(id);if(!p)return null;const section=(key:string)=>id+'-digest-'+key;return <div className="platform-digest">
 <section id={section('users')}><h2>用户与产品价值</h2><p className="digest-thesis">{p.thesis}</p><div className="table-wrap"><table><thead><tr><th>用户角色</th><th>主要需求</th><th>平台提供的价值</th></tr></thead><tbody>{p.users.map(u=><tr key={u.role}><th>{u.role}</th><td>{u.task}</td><td>{u.value}</td></tr>)}</tbody></table></div><Refs id={id} refs={p.userRefs} label="用户与任务依据"/></section>
 <section id={section('distribution')}><h2>{p.distribution.title}</h2><div className="digest-columns">{p.distribution.items.map(x=><div key={x.label}><h3>{x.label}</h3><p>{x.text}</p></div>)}</div><Refs id={id} refs={p.distribution.refs} label="分类与详情"/></section>
 <section id={section('journey')}><h2>{p.journey.title}</h2><ol className="digest-path">{p.journey.steps.map((s,i)=><li key={s}><small>{String(i+1).padStart(2,'0')}</small><strong>{s}</strong></li>)}</ol><p>{p.journey.detail}</p><Refs id={id} refs={p.journey.refs} label="操作记录"/></section>
 <section id={section('supply')}><h2>{p.supply.title}</h2><div className="digest-columns">{p.supply.items.map(x=><div key={x.label}><h3>{x.label}</h3><p>{x.text}</p></div>)}</div><Refs id={id} refs={p.supply.refs} label="供给与运营"/>{'chart' in p&&p.chart&&<figure className="digest-chart"><figcaption>{p.chart.title}</figcaption>{p.chart.rows.map(r=><div key={r.label}><span>{r.label}</span><div><i style={{width:(r.value/Math.max(...p.chart!.rows.map(x=>x.value))*100)+'%'}}/></div><b>{r.value} {p.chart!.unit}</b></div>)}<p>{p.chart.note}</p><Refs id={id} refs={p.chart.refs}/></figure>}</section>
 <section id={section('business')}><h2>收费与经营方式</h2><div className="table-wrap"><table><thead><tr><th>参与方／收费对象</th><th>提供什么</th><th>主要条件</th></tr></thead><tbody>{p.business.rows.map(r=><tr key={r.payer}><th>{r.payer}</th><td>{r.offer}</td><td>{r.condition}</td></tr>)}</tbody></table></div>{p.business.limit&&<p>{p.business.limit}</p>}<Refs id={id} refs={p.business.refs} label="经营依据"/><div className="digest-refs">{(p.business.anchors||[]).map(a=><a key={a.id} href={"/platform-evidence?section="+a.id+"#"+id} target="_blank" rel="noopener noreferrer">{a.label} ↗</a>)}<a href={"/platform-evidence?section=commercial#"+id} target="_blank" rel="noopener noreferrer">商业规则与来源 ↗</a></div></section>
 <nav className="digest-resources" aria-label="详细资料"><h2>研究资料</h2><a href={'/platform-evidence#'+id} target="_blank" rel="noopener noreferrer">功能、样本与截图 ↗</a><a href={'/?section=audience-profile-'+id+'#audience'} target="_blank" rel="noopener noreferrer">用户案例与价值依据 ↗</a></nav>
 </div>;}
