import data from '@/lib/platform-review.json';
import './research-completion.css';
const dimensionTitles={audience:'用户与任务',content:'内容与交付',operations:'供给与维护',commercial:'付款与权益',usage:'使用过程',alternatives:'替代路径'};
function text(value:string|string[]){return Array.isArray(value)?value.join('；'):value;}
export function PlatformReview({platformId,compact=false}:{platformId?:string;compact?:boolean}){
 const items=platformId?data.platforms.filter(p=>p.id===platformId):data.platforms;
 return <section className="platform-review" id={platformId?`current-review-${platformId}`:'current-platform-review'}><h3>{platformId?'用户经历、服务条件与维护':'15个平台的使用与服务条件'}</h3>
 {!platformId&&<><p className="review-meta">核查日期：{data.reviewedAt}。{data.countingRule}</p><div className="table-wrap"><table><thead><tr><th>平台</th><th>可支持的判断</th><th>仍需证据</th></tr></thead><tbody>{items.map(p=><tr key={p.id}><th><a href={`#${p.id}`}>{p.name}</a></th><td>{p.assessment}</td><td>{p.dimensions.usage.unknown}</td></tr>)}</tbody></table></div></>}
 {!compact&&items.map(p=><div key={p.id}>{platformId&&<p>{p.assessment}</p>}<details open={!!platformId}><summary>{platformId?'六项条件与案例经过':`${p.name}：六项条件与案例经过`}</summary><dl>{Object.entries(p.dimensions).map(([key,d])=><div key={key}><dt>{dimensionTitles[key as keyof typeof dimensionTitles]}</dt><dd><p>{d.finding}</p><p className="review-meta">{d.unknown}</p><Refs ids={d.sourceIds} sources={p.sources}/></dd></div>)}</dl>{p.cases.map(c=><article className="review-case" key={c.id} id={c.id}><h4>{c.title}</h4><p className="review-meta">{c.actorType}</p><p><strong>任务：</strong>{c.task}</p><p><strong>困难：</strong>{c.problem}</p><ol>{c.timeline.map((t,i)=><li key={i}><b>{t.date}</b>：{t.event}</li>)}</ol><p><strong>结果：</strong>{c.observedOutcome}</p><p><strong>尚缺：</strong>{c.unresolved}</p><Refs ids={c.sourceIds} sources={p.sources}/></article>)}<h4>仍需什么材料</h4><ul>{p.unresolved.map(u=><li key={u.question}><b>{u.question}</b><p>{u.whyItMatters}</p><p>{u.nextEvidence}</p></li>)}</ul><details><summary>来源、访问结果与检索记录</summary>{p.sources.map(s=><article key={s.id}><h4><a href={s.url} target="_blank" rel="noreferrer">{s.title}</a></h4><p className="review-meta">{s.type} · 发布：{s.publishedAt||'未标'} · 读取：{s.accessedAt}</p><p>{s.accessResult}</p><p>{s.supports}</p></article>)}{p.searchLog.map((l,i)=><p key={i}><b>{l.question}</b>：{text(l.checked)}；{l.outcome}</p>)}</details></details></div>)}
 </section>;
}
function Refs({ids,sources}:{ids:string[];sources:{id:string;title:string;url:string}[]}){return <div className="completion-links">{ids.map(id=>{const s=sources.find(x=>x.id===id);return s?<a key={id} href={s.url} target="_blank" rel="noreferrer">{s.title} ↗</a>:null;})}</div>;}
export function PlatformReviewDimension({platformId,dimension}:{platformId:string;dimension:keyof typeof dimensionTitles}){const p=data.platforms.find(p=>p.id===platformId);if(!p)return null;const d=p.dimensions[dimension];return <section className="platform-review"><h4>{dimensionTitles[dimension]} · 2026-09-11核查</h4><p>{d.finding}</p><p className="review-meta">{d.unknown}</p><Refs ids={d.sourceIds} sources={p.sources}/><a href={`#${platformId}`}>查看完整过程与适用条件 →</a></section>;}
