'use client';
import {PlatformGroups,DossierLink,EvidenceLinks} from './cross-platform';
import './cross-platform.css';
const chapters=[['scope','平台格局'],['content','内容与分发'],['paths','从浏览到使用'],['supply','供给与运营'],['business','商业机制'],['gaps','研究结论']];
function Links({ids}:{ids:string[]}){return <div className="report-reading-links">{ids.map(id=><DossierLink key={id} id={id}/>)}</div>;}
export function ResearchBrief(_props:{navigate:(id:string,anchor?:string)=>void;standalone?:boolean}){return <article className="cross-study cross-report"><header className="page-heading" id="report-top"><p className="cross-kicker">多元拾光研究室 · 竞品研究</p><h1>AI社区竞品调研报告</h1><p className="report-lead">15 家平台的差异，集中在内容提供什么、用户如何继续使用，以及谁负责持续供给和维护。</p><p>作品、模型、工作流、教材和讨论承接不同任务：发现创作效果、传递制作方法，或组织学习与协作。</p><p className="cross-note">资料截至2026-09-16；具体日期、地域与条件见平台档案。</p><div className="report-reading-links"><a href="/#audience" target="_blank" rel="noopener noreferrer">平台用户与需求 ↗</a><a href="/#evidence" target="_blank" rel="noopener noreferrer">来源与研究方法 ↗</a></div></header><nav className="report-outline" aria-label="主报告章节">{chapters.map(([id,label],i)=><a key={id} href={'/#report'} onClick={e=>{e.preventDefault();document.getElementById('report-'+id)?.scrollIntoView({block:'start',behavior:'smooth'});}}>{String(i+1).padStart(2,'0')} {label}</a>)}</nav>
<section id="report-scope"><h2>五类平台，五种比较重点</h2><p>按主要组织方式分组；同一平台的作品、工具与讨论能力可交叉出现。</p><div id="report-classification"><PlatformGroups/></div><div id="report-representatives" className="report-mechanisms" role="list" aria-label="五类平台代表路径">{[
['创作与资源','LiblibAI / RunningHub','效果或任务 → 模型、工作流 → 在线制作'],['工具与作者生态','即梦 / OpenArt','作品或用途模板 → 制作与修改 → 项目资产'],['学习与共建','Datawhale','章节 → 练习与问题 → 修订教材'],['开发与应用','Dify','模板与插件 → 配置与运行 → 日志和维护'],['技术讨论','LINUX DO','问题条件 → 成员回复 → 补充与结果回报']].map(r=><div key={r[0]} role="listitem"><h3>{r[0]}</h3><p>{r[1]}</p><p>{r[2]}</p></div>)}</div><p className="cross-note">操作范围与结果见各平台档案。</p></section>
<section id="report-content"><h2>分类帮助用户作不同的选择</h2><p>兴趣、用途、资源类型和技术条件可同时出现。分层后，用户先找内容，再判断是否适用于任务。</p><div className="report-pair"><div><h3>围绕题材聚合不同内容</h3><p>吐司的兴趣频道连接作品、模型、知识与小工具；SeaArt 在图像资源之外还有角色互动。前者把不同供给放到同一主题下，后者还承接与角色持续互动的玩法。</p><EvidenceLinks id="tusi" refs={[0,2]}/><EvidenceLinks id="seaart" refs={[0,1,5,8]}/></div><div><h3>把用途和兼容条件分开</h3><p>LiblibAI 的电商资源进一步细分到商品精修、背景替换和文字保护；RunningHub 的工作流按任务组织，模型另按类型与底模筛选。Hugging Face 和魔搭还需要借助模型卡、文件、依赖与许可判断接入条件。</p><Links ids={['liblib','runninghub','huggingface','modelscope']}/></div><div><h3>按制作阶段收集输入</h3><p>Leonardo 的 Blueprint 把任务材料收敛为分步输入；OpenArt 从用途模板延伸到角色、镜头与故事；可灵将参考、人物和镜头制作接到项目画布与资产库。</p><Links ids={['leonardo','openart','kling']}/></div><div><h3>为学习与讨论组织上下文</h3><p>WaytoAGI 用工具目录、学习路径与活动帮助选择；Datawhale 用章节、代码和练习组织学习。LINUX DO 的分类与标签则将相关问题和后续回复聚合起来。</p><Links ids={['waytoagi','datawhale','linuxdo']}/></div></div></section>
<section id="report-paths"><h2>详情页之后，观看、复用和交付走向不同</h2><p>观看者继续发现内容，创作者取得素材、参数与方法，项目使用者处理依赖、测试和后续修改；</p><div className="report-mechanisms" aria-label="用户路径比较">{[
['继续消费','即梦：作品与短片浏览；吐司：相关作品','继续发现值得观看的内容。'],['启动制作','LiblibAI：资源与生成器；Leonardo：Blueprint','明确已带入内容和仍需准备的输入。'],['接续项目','OpenArt：角色与故事；Runway：Workflow、Apps、Projects','需要保存资产、流程配置与团队制作上下文。'],['配置应用','Dify：模板、插件与日志；魔搭：模型与创空间','能否运行取决于依赖、部署、权限与资源条件。']].map(r=><div key={r[0]}><h3>{r[0]}</h3><p>{r[1]}</p><p>{r[2]}</p></div>)}</div><div className="report-pair"><div><h3>可复制，仍要检查复制了什么</h3><p>LiblibAI 的字体作品样本带入了提示词与模型，但编辑器的画幅、张数与原作品不同；SeaArt 的 Remix 样本仍需重新上传素材。</p><EvidenceLinks id="liblib" refs={[3]}/><EvidenceLinks id="seaart" refs={[4]}/><p>LiblibAI 的 LibTV 画布样本可复制，刷新后可找回；Runway 的 Workflow 样本已提交复制确认，回到列表后未见副本保存成功。</p><EvidenceLinks id="liblib" refs={[5]}/><EvidenceLinks id="runway" refs={[0,1,5]}/></div><div><h3>运行结果必须落到具体任务</h3><p>Dify 的 UTM 模板样本完成了试用、创建副本和刷新重开。该结果属于无模型代码模板，含模型或知识库的应用仍有配置与测试要求。</p><EvidenceLinks id="dify" refs={[12,15,16,17]}/></div></div><p>连续浏览也有具体限制：即梦剧集样本的队列混合其他作者和题材，未见专属选集；WaytoAGI 的相关推荐包含当前条目。浏览入口存在，仍需检验它是否持续提供相关的新内容。</p><EvidenceLinks id="jimeng" refs={[0]}/><EvidenceLinks id="waytoagi" refs={[0]}/><p className="cross-note">跨平台尚无统一任务、输入和成本条件下的成功率数据；现有路径记录只比较产品怎样承接任务。</p></section>
<section id="report-supply"><h2>供给方式决定平台要维护什么</h2><p>供给包括新内容、输入说明、版本兼容、答疑和修订；不同平台承担的组织工作不同。</p><div className="report-mechanisms" aria-label="供给与维护关系"><div><h3>作者资源</h3><p>LiblibAI、RunningHub、吐司、SeaArt：模型、工作流、应用与作品。</p><p>平台提供分发和激励；作者维护方法、条件与反馈。</p></div><div><h3>平台策选与合作</h3><p>即梦、可灵、Runway：作者故事、专业作品、教程与案例。</p><p>编辑选择和合作组织影响可见内容，精选案例需要与普通用户经历分开解释。</p></div><div><h3>采购与推广</h3><p>OpenArt：OpenArtist 内容采购、CPP 合作资源、联盟推广。</p><p>内容采购与新增订阅佣金的回报规则分别核对。</p></div><div><h3>共建与修订</h3><p>Datawhale、WaytoAGI、LINUX DO：教材、目录、经验与讨论。</p><p>编辑、贡献审核、问题回应与治理决定资料能否持续更新。</p></div><div><h3>技术维护</h3><p>Hugging Face、魔搭、Dify：模型、应用、插件与依赖。</p><p>文件可取得之后，还需要兼容、配置、运行和版本维护。</p></div></div><Links ids={['openart','datawhale','dify','linuxdo']}/><div className="report-pair"><div><h3>补贴会变，供给机制不能只看奖励入口</h3><p>吐司停止旧上传激励后仍保留资源及直接付费；Tensor.Art 的部分奖励按 Pro 使用计算。SeaArt 分设模型、应用和角色奖励；RunningHub 的规则关注有效运行、收藏和原创。不同规则对应不同的供给采用信号。</p><Links ids={['tusi','seaart','runninghub']}/></div><div><h3>发布入口与开放供稿是两回事</h3><p>Leonardo 主要呈现平台组织的预制蓝图，合作作者计划有申请状态；OpenArt 的模板使用路径较清楚，开放发布机制仍缺充分依据。LINUX DO 对直接发布 AI 生成或润色文字设有限制，供给也受讨论规则约束。</p><Links ids={['leonardo','openart','linuxdo']}/></div></div></section>
<section id="report-business"><h2>收费对象要与社区参与者分开看</h2><p>观看者、资源作者、工具使用者、团队采购者和 API 接入方可能不是同一人；商业比较据此区分付款人、购买对象和权益范围。</p><div className="report-pair"><div><h3>生成与制作</h3><p>LiblibAI、即梦、可灵、Leonardo、Runway 等提供会员或生成资源；模型、速度、使用量与团队权益形成条件差异。Leonardo 的 Relax 限定模型与优先级，可灵所列积分规则来自国际站。</p><Links ids={['jimeng','kling','leonardo','runway']}/></div><div><h3>API、托管与工作空间</h3><p>RunningHub 区分共享 API 与模型 API 的计费单位；Hugging Face、魔搭和 Dify 的接入还涉及计算资源、部署或工作空间。网页订阅与业务接入的权益需要单独判断。</p><Links ids={['runninghub','huggingface','modelscope','dify']}/></div><div><h3>作者回报与内容采购</h3><p>激励、资源交易、作者订阅、内容采购和联盟佣金的收入条件分别记录；例如 OpenArt 的按帖采购与联盟佣金、SeaArt 的作者订阅。</p><Links ids={['openart','seaart','liblib','tusi']}/></div><div><h3>学习和讨论的经营资料较少</h3><p>WaytoAGI 的活动与合作、Datawhale 的学习组织、LINUX DO 的订阅及推广安排，可以说明参与方式。实际收入、贡献者回报和组织投入仍缺可比较数据。</p><Links ids={['waytoagi','datawhale','linuxdo']}/></div></div><p className="cross-note">各平台套餐、地区、计费单位与观察日期不同，因此不合并成价格排名。现有资料支持收费结构比较，尚不足以比较盈利能力。</p></section>
<section id="report-gaps"><h2>可以判断产品取向，效果还需行为证据</h2><p>这组平台呈现出三种反复出现的价值：帮助用户发现内容，帮助用户复用方法，帮助用户接续学习或协作。分类、详情与后续动作共同体现平台优先服务哪一种需求；供给机制则决定内容发布之后由谁继续维护。</p><p>持续观看和回访、方法复用成功率、稳定供稿和维护投入，是判断这些机制实际效果的关键数据。公开样本已能呈现具体任务与问题，但各平台尚无统一口径支持效果排名。</p><div className="report-end"><p>平台比较与各家档案用于解释已有做法。多元拾光的方向取舍、运营落地与产品承接，集中在“社区方案”。</p><div className="report-reading-links"><a href="/#audience" target="_blank" rel="noopener noreferrer">查看平台用户与需求 ↗</a><a href="/community-options" target="_blank" rel="noopener noreferrer">社区方案 ↗</a></div></div></section></article>;}
