'use client';
import data from '@/lib/research-progress.json';
import { EvidenceSynthesis } from '@/components/evidence-synthesis';
import { ResearchReconciliation } from '@/components/research-reconciliation';
import { PlatformSupply } from '@/components/platform-supply';

export function ResearchProgress({navigate}:{navigate:(id:string)=>void}) {
 const jump=(target:string)=>document.getElementById(`progress-${target}`)?.scrollIntoView({behavior:'smooth',block:'start'});
 const refs=(ids:string[])=>ids.map(id=>{const s=data.needs.sources.find(x=>x.id===id);return s?<a key={id} href={s.url} target="_blank" rel="noreferrer">〔{s.title}〕</a>:null;});
 return <><section className="framework-study"><div className="page-heading"><h1>自身条件与待解问题</h1></div><p>内容示例来自两个素材样本，偏向技术记录。视觉方案缺少丰富作品，练习方案缺少点评与修订案例。</p><div className="study-actions"><button className="primary-button" onClick={()=>navigate('strategy')}>阅读最新方案与内容对照 →</button><a href="/research-kit/strategy-comparison.md" download>下载完整比较</a></div><p>待补：内容制作与维护工时、工具完整交付、外部用户消费与回访数据、可用预算。</p></section><details className="study-sources"><summary>平台供给、经营数据与MakeNow素材</summary><PlatformSupply navigate={navigate}/></details><details className="study-sources"><summary>社区内容承载与资源维护</summary><ResearchReconciliation navigate={navigate}/></details><details className="study-sources"><summary>内容案例、画布交接与维护记录</summary><EvidenceSynthesis navigate={navigate}/></details><details className="study-sources"><summary>社区与API材料核查记录</summary><div className="framework-study">
  <div className="page-heading"><h1>{data.headline}</h1></div>
  <div className="study-actions"><a href="/research-kit/research-progress.md" download>下载完整记录</a></div>
  <section className="study-platform"><h2>八个问题：基线与本次增补</h2><p>本次主要补入01自身事实、02内容交付、04替代方式、06供给职责和07工具成本边界。具体更新见上方独立研究；其余缺口继续保留。</p><div className="table-wrap"><table><thead><tr><th>问题 / 状态</th><th>依据</th><th>还不能得出的结论</th><th>原定继续研究项</th></tr></thead><tbody>{data.questions.map(q=><tr key={q.id}><th><button className="text-button" onClick={()=>jump(q.target)}>{q.id} {q.title}</button><p className="muted">{q.status}</p></th><td>{q.finding}</td><td>{q.boundary}</td><td>{q.next}</td></tr>)}</tbody></table></div></section>
  <nav className="study-actions" aria-label="证据目录">{[['own','自身材料'],['content','公开内容抽检'],['capabilities','MakeNow与API'],['lifecycle','普通讨论与维护'],['needs','需要什么'],['alternatives','替代路径'],['supply','作者供给'],['economics','成本与产能'],['next','下一段研究']].map(([id,title])=><button key={id} className="text-button" onClick={()=>jump(id)}>{title}</button>)}</nav>

  <section id="progress-own" className="study-platform"><h2>自身材料：已有，只是证据层级不同</h2><p>{data.own.summary}</p><p className="muted">以下是本地材料核对记录；之后取得的公开页面和用户更新在后续两节补充。历史文档不能直接作为今天的运行状态。</p><div className="table-wrap"><table><thead><tr><th>材料</th><th>能用来做什么</th><th>不能当成什么</th></tr></thead><tbody>{data.own.materials.map(m=><tr key={m.item}><th>{m.item}<p className="muted">{m.status}</p></th><td>{m.readyFor}</td><td>{m.notFor}</td></tr>)}</tbody></table></div><details className="study-sources"><summary>展开18项事实、证据路径和时效</summary>{data.own.facts.map(f=><article key={f.id}><h3>{f.id} · {f.topic}</h3><p className="muted">{f.status} · {f.asOf}</p><p>{f.fact}</p><p><strong>边界：</strong>{f.limit}</p><p><strong>继续核对：</strong>{f.next}</p><p className="muted" style={{overflowWrap:'anywhere'}}>来源：{f.evidence}</p></article>)}</details></section>

  <section id="progress-content" className="study-platform"><h2>公开内容抽检：具体问题，分别判断</h2><p>{data.content.method}</p>{data.content.samples.map(s=><article key={s.id}><h3>{s.id} · {s.title}</h3><p className="muted">{s.location} · <a href={s.url} target="_blank" rel="noreferrer">查看原页</a></p><p><strong>观察：</strong>{s.observation}</p><p><strong>分析：</strong>{s.interpretation}</p><p className="muted">{s.limit}</p></article>)}</section>

  <section id="progress-capabilities" className="study-platform"><h2>MakeNow与API的能力与缺口</h2><p>{data.capabilities.summary}</p>{data.capabilities.corrections.map(c=><p key={c.previous}>{c.update}</p>)}<div className="study-actions"><a href="https://dream.ai666.net/" target="_blank" rel="noreferrer">MakeNow官网</a><a href="https://s.apifox.cn/ec36f88d-4e3d-4790-98e5-c1532253c7fb/207283265e0" target="_blank" rel="noreferrer">API文档</a></div>
   <h3>MakeNow公开入口的早期观察</h3><p className="muted">下列记录保留登录前的访问情况。后续已完成登录检查、单案例副本创建和文本保存重开；素材与完整生成仍未验证。</p><button className="text-button" onClick={()=>navigate('makenow')}>查看入口、复制和保存记录</button>{data.content.makenow.map(s=><article key={s.id}><h4>{s.title}</h4><p>{s.observation}</p><p>{s.interpretation}</p><p className="muted">{s.limit}</p></article>)}
   <div className="table-wrap"><table><thead><tr><th>能力与证据层级</th><th>已知</th><th>对内容交付的意义</th><th>继续核对</th></tr></thead><tbody>{data.capabilities.capabilities.map(c=><tr key={c.id}><th>{c.capability}<p className="muted">{c.level}</p></th><td>{c.confirmed}</td><td>{c.communityDelivery}</td><td>{c.unknown}</td></tr>)}</tbody></table></div>
   <h3>API五页文档：使用过程的差别</h3><p>{data.api.scope}</p>{data.api.observations.map(a=><article key={a.id}><h4><a href={a.url} target="_blank" rel="noreferrer">{a.title}</a></h4><p><strong>文档可见：</strong>{a.fact}</p><p><strong>对内容的要求：</strong>{a.analysis}</p><p className="muted">{a.limit}</p></article>)}{data.api.unavailable.map(a=><p className="muted" key={a.url}><a href={a.url} target="_blank" rel="noreferrer">{a.title}</a>：{a.result}</p>)}
   <h3>公开报价：相近名称，未必是同一种交付</h3><p><a href={data.api.pricing.url} target="_blank" rel="noreferrer">价格页 · {data.api.pricing.observedAt}</a></p><p className="muted">{data.api.pricing.scope}</p>{data.api.pricing.observations.map(x=><p key={x}>{x}</p>)}<div className="table-wrap"><table><thead><tr><th>调用名 / 单位</th><th>本次公开展示</th><th>解释边界</th></tr></thead><tbody>{data.api.pricing.rows.map(r=><tr key={r.name}><th>{r.name}<p>{r.billing}</p></th><td>{r.display}</td><td>{r.limit}</td></tr>)}</tbody></table></div><p>{data.api.pricing.next}</p>
   <details className="study-sources"><summary>六个交付缺口与材料来源</summary>{data.capabilities.deliveryGaps.map(g=><article key={g.gap}><h4>{g.gap}</h4><p>已有：{g.existing}</p><p>待补：{g.need}</p><p>{g.changesJudgment}</p></article>)}{data.capabilities.entries.map(e=><p key={e.id} className="muted" style={{overflowWrap:'anywhere'}}>{e.product} · {e.kind} · {e.path} · {e.evidence}<br/>{e.use}</p>)}</details>
  </section>

  <section id="progress-lifecycle" className="study-platform"><h2>普通内容：谁回应，谁修复，后来怎样</h2><p>{data.lifecycle.summary}</p><details className="study-sources"><summary>样本选择、日期与读取限制</summary>{data.lifecycle.method.selectionRules.map(x=><p key={x}>{x}</p>)}<p>{data.lifecycle.method.timeBoundary}</p><p>{data.lifecycle.method.inferenceLimits}</p></details>
   <div className="table-wrap"><table><thead><tr><th>样本与原页</th><th>问题和回应</th><th>后续与责任</th><th>能说明什么</th></tr></thead><tbody>{data.lifecycle.samples.map(s=><tr key={s.id}><th><a href={s.url} target="_blank" rel="noreferrer">{s.id} · {s.title}</a><p className="muted">{s.platform} · {s.kind}<br/>{s.publishedAt||'未取得日期'}</p></th><td><p>{s.observation}</p>{s.interaction&&<p>{s.interaction}</p>}</td><td>{s.maintenance||"未取得正文，不补推后续"}</td><td><p>{s.interpretation}</p><p className="muted">{s.limits}</p></td></tr>)}</tbody></table></div>
  </section>

  <section id="progress-needs" className="study-platform"><h2>需要什么：保留欣赏、表达和关系</h2><p>{data.needs.summary}</p>{data.needs.needs.map(n=><article key={n.need}><h3>{n.need}</h3><p><strong>可见依据：</strong>{n.visibleEvidence}</p><p><strong>分析：</strong>{n.interpretation}</p><p className="muted">{n.unknown}</p><div className="study-refs">{refs(n.sourceIds)}</div></article>)}</section>
  <section id="progress-alternatives" className="study-platform"><h2>同一个内容，是否已有足够好的承接方式</h2>{data.needs.alternatives.map(a=><article key={a.task}><h3>{a.task}</h3><p><strong>平台路径：</strong>{a.communityPath}</p><p><strong>已有替代路径：</strong>{a.alternativePath}</p><p><strong>共同能力、额外价值与负担：</strong>{a.comparison}</p><p className="muted">{a.limits}</p><div className="study-refs">{refs(a.sourceIds)}</div></article>)}</section>
  <section id="progress-supply" className="study-platform"><h2>作者供给：分发、回报和维护分开查</h2><p>{data.supply.method}</p>{data.supply.items.map(s=><article key={s.id}><h3><a href={s.url} target="_blank" rel="noreferrer">{s.title}</a></h3><p><strong>已确认规则：</strong>{s.fact}</p><p><strong>分析：</strong>{s.inference}</p><p className="muted">{s.unknown}</p><p className="muted">{s.change}</p></article>)}</section>
  <section id="progress-economics" className="study-platform"><h2>成本与产能：产品材料不能替代经营数字</h2><p>资料不足。先复用已有材料，把真正影响比较的参数列清；不预填毛利、内容产量或用户增长。</p><div className="table-wrap"><table><thead><tr><th>要判断什么</th><th>已知</th><th>待补</th><th>为什么影响判断</th></tr></thead><tbody>{data.economics.map(e=><tr key={e.name}><th>{e.name}</th><td>{e.known}</td><td>{e.missing}</td><td>{e.why}</td></tr>)}</tbody></table></div></section>
  <section id="progress-next" className="study-platform"><h2>下一段研究，按缺口继续</h2><ol>{data.next.map(n=><li key={n}>{n}</li>)}</ol><p>{data.api.next}</p><div className="study-actions"><button className="text-button" onClick={()=>navigate('strategy')}>查看尚未排序的四份方案</button><button className="text-button" onClick={()=>navigate('content')}>返回内容形态研究</button></div></section>
  <details className="study-sources"><summary>外部来源、日期及未取得页面</summary>{[...data.needs.sources,...data.lifecycle.sources].map(s=><p key={s.id}><a href={s.url} target="_blank" rel="noreferrer">{s.title}</a> · {s.accessedAt}<br/>{s.scope}</p>)}</details>
 </div></details></>;
}
