'use client';
/* oxlint-disable next/no-img-element -- Reuses archived evidence images. */
import raw from '@/lib/research-brief.json';
import screenshots from '@/lib/content-screenshots.json';
import {PlatformReview} from '@/components/platform-review';
import {RepresentativeEvidence} from '@/components/representative-evidence';
import {StrategyConditionsSummary} from '@/components/strategy-conditions';
import {RepresentativeComparison,CrossPlatformComparison,ReportSources,type Representative,type ReportComparison,type ReportSource} from '@/components/report-comparisons';
import './research-structure.css';
import './report-delivery.css';
type TableData={headers:string[];rows:string[][]};
type Source={id:string;title:string;url:string;date:string;accessedAt:string|null;dataFile:string};
type Claim={title:string;text:string;examples:{platform:string;text:string}[];basis:string;sources:Source[]};
type Chapter={id:string;title:string;answer:string;assessment:string;table:TableData|null;classificationTable?:TableData;evidence?:{platformIds?:string[];scope:string}[];claims:Claim[];comparisons?:ReportComparison[];limit:string;links:{view:string;label:string;anchor?:string}[];screenshotIds?:string[]};
const findingLabels:Record<string,string>={content:'内容形态',business:'工具与商业化',supply:'持续供给'};
const coverExamples=[['liblib-template','LiblibAI · 模板'],['runninghub-workflow','RunningHub · 工作流'],['runway-course','Runway · 课程']];
const data=raw as unknown as {title:string;date:string;sections:Chapter[];depth:{judgment:string;rows:string[][]};representatives?:Representative[];keyFindings?:{view:string;text:string}[];delivery?:{date:string;preparedAt:string;html:string;zip:string};discussionQuestions?:string[];toolCensus?:{conclusion:string;unit:string;countLimitations:string[];categories:{label:string;count:number;platformIds:string[];definition:string;limitation:string}[];platforms:{id:string;name:string;execution:string;limit:string;sources:ReportSource[]}[]}};
function Table({data}:{data:TableData}){return <div className="table-wrap"><table className="brief-table"><thead><tr>{data.headers.map(h=><th scope="col" key={h}>{h}</th>)}</tr></thead><tbody>{data.rows.map((r,i)=><tr key={i}>{r.map((v,j)=>j===0?<th scope="row" key={j}>{v}</th>:<td key={j}>{v}</td>)}</tr>)}</tbody></table></div>;}
function jump(id:string){const target=document.getElementById(`report-${id}`);target?.scrollIntoView({behavior:'smooth',block:'start'});target?.focus({preventScroll:true});}
export function ResearchBrief({navigate,standalone=false}:{navigate:(id:string,anchor?:string)=>void;standalone?:boolean}){return <article className="research-brief">
 <header className="report-cover" id="report-top">
  <div className="report-cover-meta"><span>多元拾光 <b aria-hidden="true">／</b> 研究报告</span><span>{data.delivery?.date}</span></div>
  <div className="report-cover-grid"><div className="report-cover-title"><h1><span>AI社区</span><br/>竞品调研报告</h1><p className="brief-meta">资料截至 {data.date}</p><div className="brief-links"><a href="/research-kit/community-research-report.md" download>下载正文</a>{!standalone&&data.delivery&&<><a href={data.delivery.html} target="_blank" rel="noreferrer">汇报版网页 ↗</a><a href={data.delivery.zip} download>完整资料包 ↓</a></>}<a href={standalone?'#appendix':'#matrix'} onClick={standalone?undefined:e=>{e.preventDefault();navigate('matrix');}}>平台档案 ↗</a></div><div className="report-cover-examples">{coverExamples.map(([id,label])=>{const pair=screenshots.pairs.find(p=>p.id===id)!;return <figure key={id}><a href={pair.card.src} target="_blank" rel="noreferrer"><img src={pair.card.src} width={pair.card.width} height={pair.card.height} alt={pair.card.caption}/></a><figcaption>{label}</figcaption></figure>;})}</div></div>
  {data.keyFindings&&<ol className="brief-findings">{data.keyFindings.map((f,i)=><li key={f.view}><a href={`#report-${f.view}`} onClick={e=>{e.preventDefault();jump(f.view);}}><span className="finding-number">{String(i+1).padStart(2,'0')}</span><div><h2>{findingLabels[f.view]}</h2><p>{f.text}</p></div></a></li>)}</ol>}</div>
 </header>
 <nav className="report-chapter-nav" aria-label="主报告章节"><ol className="brief-toc">{data.sections.map((s,i)=><li key={s.id}><a href={`#report-${s.id}`} onClick={e=>{e.preventDefault();jump(s.id);}}><span>{String(i+1).padStart(2,'0')}</span>{s.title}</a></li>)}</ol></nav>
 {data.sections.map((s,i)=><section id={`report-${s.id}`} tabIndex={-1} className="brief-section" key={s.id}>
  <div className="report-chapter-heading"><span aria-hidden="true">{String(i+1).padStart(2,'0')}</span><h2>{s.title}</h2></div><p className="chapter-answer">{s.answer}</p>{s.table&&s.id!=='implications'&&<Table data={s.table}/>}
  {s.classificationTable&&<section className="platform-classification" id="report-classification" tabIndex={-1}><h3>全部平台分类</h3><div className="classification-groups">{s.classificationTable.rows.map((row,index)=>{const ids=s.evidence?.filter(e=>e.platformIds)[index]?.platformIds||[];return <article className="classification-group" key={row[0]}><header><span className="classification-index" aria-hidden="true">{String(index+1).padStart(2,'0')}</span><h4>{row[0]}</h4><span className="classification-count">{ids.length}个平台</span></header><div className="classification-platforms">{ids.map((id,j)=><a key={id} href={`#${id}`} onClick={e=>{e.preventDefault();navigate(id);}}>{row[1].split('、')[j]}{data.representatives?.some(r=>r.id===id)&&<small className="classification-role">代表</small>}<span aria-hidden="true"> ↗</span></a>)}</div><p><strong>比较重点</strong>{row[2]}</p></article>;})}</div></section>}
  {s.id==='scope'&&data.representatives&&<RepresentativeComparison items={data.representatives} navigate={navigate}/>}
  {s.id==='business'&&data.toolCensus&&<section className="tool-census"><h3>18个平台的工具支持关系</h3><p>{data.toolCensus.conclusion}</p><div className="tool-map"><div className="tool-map-total"><strong>{data.toolCensus.categories.slice(0,2).reduce((n,c)=>n+c.count,0)}<small> / {data.toolCensus.platforms.length}</small></strong><p><b>有平台执行能力资料的研究样本</b>按主要执行关系分类，逐家依据见下方。</p></div>{data.toolCensus.categories.map(c=><div className="tool-map-group" key={c.label}><h4>{c.label}<span>{c.count}个平台</span></h4><div className="tool-map-names">{c.platformIds.map(id=><a key={id} href={`#${id}`} onClick={e=>{e.preventDefault();navigate(id);}}>{data.toolCensus!.platforms.find(p=>p.id===id)!.name}</a>)}</div></div>)}</div><details className="brief-records"><summary>分类定义与逐家依据</summary><p>{data.toolCensus.unit}</p>{data.toolCensus.categories.map(c=><section key={c.label}><h4>{c.label}</h4><p>{c.definition}</p><p className="brief-limit">{c.limitation}</p></section>)}{data.toolCensus.platforms.map(p=><section key={p.id}><h4>{p.name}</h4><p>{p.execution}</p><p className="brief-limit">{p.limit}</p><ReportSources sources={p.sources}/></section>)}<ul>{data.toolCensus.countLimitations.map(t=><li key={t}>{t}</li>)}</ul></details></section>}
  {s.comparisons?.map(c=><CrossPlatformComparison key={c.id} data={c} navigate={navigate}/>)}
  {s.id==='supply'&&<><RepresentativeEvidence compact/><details className="brief-records"><summary>18个平台的使用与服务条件</summary><PlatformReview compact/></details></>}
  {s.id==='implications'&&<StrategyConditionsSummary/>}
  {s.claims.map(c=><section className="brief-claim" key={c.title}><h3>{c.title}</h3><p>{c.text}</p><ul>{c.examples.map(e=><li key={e.platform}><strong>{e.platform}：</strong>{e.text}</li>)}</ul><p className="brief-limit">{c.basis}</p><div className="brief-evidence">{c.sources.map(source=><a key={source.url} href={source.url} target="_blank" rel="noreferrer" title={`${source.date}${source.accessedAt?` · 查阅：${source.accessedAt}`:''} · ${source.id}`}>{source.title} ↗</a>)}</div></section>)}
  {s.screenshotIds&&<details className="brief-images" open><summary>卡片与详情示例</summary>{s.screenshotIds.map(id=>{const pair=screenshots.pairs.find(p=>p.id===id)!;return <section key={id} id={`report-image-${id}`}><h3>{pair.platform} · {pair.title}</h3><p className="brief-meta">截图日期：{screenshots.capturedAt}</p><div>{[pair.card,pair.detail].map((im,j)=><figure key={im.src}><span className="screenshot-label">{j?'详情页面':'卡片／列表'}</span><a href={im.src} target="_blank" rel="noreferrer"><img src={im.src} width={im.width} height={im.height} alt={`${j?'详情':'卡片或列表'}：${im.caption}`} loading="lazy"/></a><figcaption>{im.caption}</figcaption><a href={im.url} target="_blank" rel="noreferrer">来源页面 ↗</a></figure>)}</div><p className="brief-limit">{pair.limits}</p></section>;})}</details>}
  <p className="brief-limit">{s.limit}</p><nav className="brief-links" aria-label={`${s.title}专题材料`}>{s.links.map(l=><a key={l.view} href={`#${l.view}`} onClick={e=>{e.preventDefault();navigate(l.view,l.anchor);}}>{l.label} →</a>)}</nav>
 </section>)}
 {data.discussionQuestions&&<section className="brief-section" id="report-discussion" tabIndex={-1}><h2>待讨论的问题</h2><ol>{data.discussionQuestions.map(q=><li key={q}>{q}</li>)}</ol></section>}
 <details className="brief-depth"><summary>研究深度与未解问题</summary><p>{data.depth.judgment}</p><Table data={{headers:['方面','已达到的层次','缺口'],rows:data.depth.rows}}/><Table data={{headers:['问题','可回答的范围'],rows:data.sections.map(s=>[s.title,s.assessment])}}/></details>
 </article>;}
