'use client';
import data from '@/lib/research-reconciliation.json';
function jump(id:string){const target=document.getElementById(`v21-${id}`);if(target instanceof HTMLDetailsElement)target.open=true;for(let node=target?.parentElement;node;node=node.parentElement){if(node instanceof HTMLDetailsElement)node.open=true;}target?.scrollIntoView({behavior:'smooth',block:'start'});}
function Refs({ids}:{ids:string[]}){return <div className="study-refs">{ids.map(id=><a href={`#v21-${id}`} key={id} onClick={e=>{e.preventDefault();jump(id);}}>〔{id}〕</a>)}</div>;}
function Paragraphs({items}:{items:string[]}){return <>{items.map(x=><p key={x}>{x}</p>)}</>;}
export function ResearchReconciliation({navigate,embedded=false}:{navigate:(id:string)=>void;embedded?:boolean}){
 return <div className="framework-study">
  <div className="page-heading">{embedded?<h2>{data.title}</h2>:<h1>{data.title}</h1>}</div>
  <div className="study-actions"><button className="text-button" onClick={()=>navigate('strategy')}>查看待比较方案</button></div>
  <nav className="study-actions" aria-label="目录">{[['findings','核心发现'],['own','自身现状'],['data','数据可用性'],['cases','内容维护'],['conditions','经营条件'],['progress','证据状态'],['sources','来源与限制']].map(([id,label])=><button key={id} className="text-button" onClick={()=>jump(id)}>{label}</button>)}</nav>
  <section id="v21-findings" className="study-platform"><h2>内容与使用分析</h2>{data.findings.map(f=><article key={f.title}><h3>{f.title}</h3><p><strong>事实：</strong>{f.fact}</p><p><strong>分析：</strong>{f.analysis}</p><Refs ids={f.sourceIds}/></article>)}</section>

  <section id="v21-own" className="study-platform"><h2>自身内容与产品：已有能力怎样对应缺口</h2><p>{data.own.summary}</p><p className="muted">{data.own.scope.codeIsNotLiveAcceptance}</p>{data.own.rows.map(r=><article id={`v21-${r.id}`} key={r.id}><h3>{r.topic}</h3><div className="table-wrap"><table><thead><tr><th>设计与材料</th><th>代码存在</th><th>已验证范围</th><th>真实使用记录</th></tr></thead><tbody><tr><td>{r.designed}</td><td>{r.implemented}</td><td>{r.verified}</td><td>{r.usage}</td></tr></tbody></table></div><p><strong>现在的内容缺口：</strong>{r.contentGap}</p><details className="study-sources"><summary>可以比较的做法、工作负担与边界</summary><p>{r.possibleChange}</p><p><strong>新增工作：</strong>{r.burden}</p><p className="muted">{r.limits}</p></details><Refs ids={r.sourceIds}/></article>)}</section>
  <section id="v21-data" className="study-platform"><h2>数据可用性：先沿已有口径找汇总</h2><p>这里记录的是资料和字段覆盖，不填未经取得的经营数值。当前快照、期间新增、提交审核与公开发布，以及匿名访问与业务账号，都需要分别解释。</p><div className="table-wrap"><table><thead><tr><th>要回答什么</th><th>已有材料</th><th>未取得</th><th>先查什么</th></tr></thead><tbody>{data.own.dataAvailability.map(d=><tr id={`v21-${d.id}`} key={d.id}><th>{d.question}</th><td>{d.available}<Refs ids={d.sourceIds}/></td><td>{d.notAvailable}</td><td>{d.next}</td></tr>)}</tbody></table></div></section>
  <section id="v21-cases" className="study-platform"><h2>国内工作流的说明与维护，及国际站对照</h2><p>4个主对象包括RunningHub两条工作流、Liblib一组版本、Tensor.Art一个多版本资源。主对象之外另有资源和规则旁证，下节单列。不是全站随机抽样，未确认全部对象的历史精选身份；Tensor.Art也不代表吐司中文站的运营情况。</p>{data.samples.map(s=><article id={`v21-${s.id}`} key={s.id}><h3><a href={s.url} target="_blank" rel="noreferrer">{s.platform} · {s.name}</a></h3><p className="muted">{s.selection}</p><div className="table-wrap"><table><tbody>{s.sections.map(p=><tr key={p.label}><th>{p.label}</th><td><Paragraphs items={p.paragraphs}/></td></tr>)}</tbody></table></div><h4>时间与证据层级</h4><div className="table-wrap"><table><thead><tr><th>时间</th><th>记录</th><th>支持到哪里</th></tr></thead><tbody>{s.timeline.map((t,i)=><tr key={`${s.id}-${i}`}><th>{t.date}</th><td>{t.event}</td><td>{t.status}<Refs ids={t.sourceIds}/></td></tr>)}</tbody></table></div><p><strong>影响的判断：</strong>{s.changesJudgment}</p><Refs ids={s.sourceIds}/><details className="study-sources"><summary>分析与仍未取得的证据</summary><Paragraphs items={s.analysis}/><ul>{s.unknown.map(x=><li key={x}>{x}</li>)}</ul></details></article>)}
   <details className="study-sources"><summary>平台规则与补充旁证：不作为主样本已解决问题的证据</summary>{data.rules.map(r=><article id={`v21-${r.id}`} key={r.id}><h3>{r.title}</h3><p className="muted">{r.type}</p><Paragraphs items={r.facts}/><Paragraphs items={r.analysis}/><Paragraphs items={r.unknown}/><Refs ids={r.sourceIds}/></article>)}</details>
  </section>
  <section id="v21-conditions" className="study-platform"><h2>经营条件：这些问题不能靠竞品替我们回答</h2><p>已有材料先复用；没有找到的数值不等于不存在。下面列的是会改变取舍的条件，不是新增岗位、预算申请或已排期工作。</p><div className="table-wrap"><table><thead><tr><th>条件</th><th>已知</th><th>缺少什么</th><th>影响／可用材料</th></tr></thead><tbody>{data.own.conditions.map(c=><tr key={c.condition}><th>{c.condition}</th><td>{c.known}</td><td>{c.missing}</td><td>{c.why}<p className="muted">可核对：{c.possibleEvidence}</p></td></tr>)}</tbody></table></div><h3>完整工具交付仍未完成</h3><p>{data.deliveryStatus.known}</p><p>仍缺：{data.deliveryStatus.missing}</p><p className="muted">{data.deliveryStatus.constraint}</p><button className="text-button" onClick={()=>navigate('makenow')}>查看MakeNow入口、复制与保存记录</button></section>
  <section id="v21-progress" className="study-platform"><h2>八项问题的证据状态</h2><div className="table-wrap"><table><thead><tr><th>问题</th><th>已有证据</th><th>仍缺</th></tr></thead><tbody>{data.questions.map(q=><tr key={q.id}><th>{q.id} {q.title}</th><td>{q.change}</td><td>{q.remaining}</td></tr>)}</tbody></table></div><h3>证据优先级</h3><div className="table-wrap"><table><thead><tr><th>优先级</th><th>待核问题</th><th>原因</th></tr></thead><tbody>{data.priorities.map(p=><tr key={p.status}><th>{p.status}</th><td>{p.work}</td><td>{p.why}</td></tr>)}</tbody></table></div><p>{data.decisionBoundary}</p></section>
  <details id="v21-sources" className="study-sources"><summary>方法、访问限制与来源</summary>{data.methods.map(m=><article key={m.title}><h3>{m.title}</h3><Paragraphs items={m.paragraphs}/></article>)}<h3>没有取得的页面内容</h3>{data.attempts.map(a=><p key={a.id}><strong>{a.method}：</strong>{a.result} {a.action} {a.urls.map(u=><a key={u} href={u} target="_blank" rel="noreferrer">访问对象 ↗ </a>)}</p>)}{data.sources.map(s=><article id={`v21-${s.id}`} key={s.id}><h3>{s.id} · {s.title}</h3>{s.url?<a href={s.url} target="_blank" rel="noreferrer">查看原页</a>:<p className="muted" style={{overflowWrap:'anywhere'}}>{s.path}行 {s.lines}</p>}<p className="muted">{s.date}查阅 {s.accessedAt}</p><p>{s.scope}</p></article>)}</details>
 </div>;
}
