'use client';
import {VisualLifeCases} from './visual-life-cases';
import {ResearchOutline} from './research-outline';
import closure from '@/lib/content-demand-closure.json';
import inventory from '@/lib/social-inventory-summary.json';
import digests from '@/lib/platform-digests.json';
import {profiles} from '@/lib/profiles';
import './market-social.css';

const themes = [
 ['故事连载','追剧情、记角色、等更新','集序、角色关系、旧版与修正版','已读剧情评论，并核对相邻集与作者合集。','story'],
 ['历史叙事','理解人物和事件，讨论不同解释','事件线、史料出处、画面与史实的对应','已核一件作品的引文与讨论；读者长期查阅仍无行为记录。','history'],
 ['自然科普','弄懂现象、判断解释是否可信','成片解释、补充资料、问题答复','已读一件作品及答复；所读内容已回答部分问题。','science'],
 ['视觉审美','欣赏风格，寻找适合自己的表达','作品、风格系列、收藏与同款入口','两位作者的六件作品显示审美偏好、系列入口与同题重复讨论。',''],
 ['生活兴趣','寻找生活灵感和具体参考','空间、穿搭、宠物、旅行等场景内容','家居组覆盖展示、实物询问与教程；部分问题已有作者答复。',''],
 ['创作学习','完成一项制作，解决卡住的步骤','教程、素材、工作流、条件和答疑','已核教程材料与具体步骤；学习诉求不外推给所有观看者。','tutorial'],
];
function Link({href,children}:{href:string;children:React.ReactNode}){return <a href={href} target="_blank" rel="noopener noreferrer">{children} ↗</a>;}
const deep = (id:string)=>`/?section=${id}#content-demand`;
function InventoryChart(){return <figure className="ms-inventory"><figcaption><h3>抖音存量目录覆盖</h3><p>615个作品链接；293件有明确主题标签，322件待分类。主题可重叠。</p></figcaption><div className="ms-bars">{inventory.sixThemeCoverage.filter(r=>r.id!=='unclassified').map(r=><div className="ms-bar-line" key={r.id}><span>{r.name}</span><div className="ms-bar-track"><span style={{width:r.works/250*100+'%'}}/></div><strong>{r.works}件</strong></div>)}</div><p className="ms-caption">图示存量目录覆盖，横条统一以250件为上限。分类沿用明确的作品分组，宽泛栏目和仅凭作者推断的主题保留待分类。目录卡片、详情与评论阅读深度各异。</p><p className="ms-caption">计数：739条主池记录归并为613个链接；加入13条详情补充和78条主题引用后，830条输入共615个链接。其他平台的原始资料和新增路径观察单列。</p></figure>}
export function SocialResearch(){return <article className="ms-report">
 <header className="page-heading"><h1>内容需求与社媒生态</h1><p>抖音、小红书、B站的作品、反馈与已有服务。</p></header>
 <section><h2>需求、已有满足与剩余问题</h2><p>研究覆盖六类兴趣消费、八类实际应用，按8项用户任务比较具体作品、方法与反馈。故事回看、音乐版本查找、商品图采用与弃用、制作学习及空间还原，分别呈现需求与结果；各领域的证据深度仍不一致。</p><p><Link href="/domain-research#research-conclusions">行业与社媒综合判断</Link> · <Link href="/task-research">用户任务与结果</Link> · <Link href="/media-reports#report-catalog">报告目录与阅读范围</Link></p><p className="ms-caption">44份报告与相关材料中，36份取得公开章节、摘要或转载，8份待获取。报告条数与作品、评论样本分别统计；下方六类消费任务保留原专题口径。</p></section>
 <div className="ms-lead"><strong>社媒观众的观看理由可作为判断创作者内容需求的依据。</strong><p>用户关心故事、知识、审美和生活兴趣。AI是制作手段；具体作品与反馈，帮助判断创作者该做什么内容。</p></div>
 <ResearchOutline items={[["ms-roles","三种AI关联"],["ms-themes","六类消费任务"],["ms-story","连载案例"],["ms-visual-life","审美与家居"],["ms-media","平台承载"],["ms-supply","供给衔接"],["ms-evidence","资料与样本"]]}/>
 <section id="ms-roles"><h2>“AI内容”包含三件不同的事</h2><div className="ms-grid three">{[['讲 AI','新闻、测评、教程、模型经验','观众关心技术信息或怎样使用。'],['用 AI 制作','故事、动画、视觉作品、知识解说','观众可能只关心作品本身。'],['AI 辅助阅读与分发','章节摘要、搜索理解、推荐与匹配','帮助定位内容、理解结构和发现作品。']].map(([h,p,n])=><div key={h}><h3>{h}</h3><p>{p}</p><small>{n}</small></div>)}</div><p className="ms-caption">B站披露的“AI相关内容观看时长增长”属于内容主题统计；作品的AI制作依据另按作者声明和具体内容记录。<Link href="https://www.sec.gov/Archives/edgar/data/1723690/000119312526094863/d119863dex992.htm">B站2025年业绩</Link></p></section>
 <section id="ms-themes"><h2>消费任务标签与领域范围</h2><p>存量样本按六类消费任务归组，同一作品可关联多类。兴趣与实际应用的完整范围见领域比较。</p><div className="ms-grid two">{themes.map(([name,task,carrier,evidence,id])=><article key={name}><h3>{name}</h3><strong>{task}</strong><p>{carrier}</p><small>{evidence}</small>{id&&<p><Link href={deep('closure-'+id)}>具体作品与评论</Link></p>}</article>)}</div></section>
 <section id="ms-story"><h2>连载样本：原平台已经组织了追看和反馈</h2><p>《DEADLY：畸变》把 AI 用在制作上，所读评论主要围绕角色、设定与更新展开。观察范围为2026年9月16日的两集详情、相邻集跳转和作者主页。</p><ol className="ms-journey">{[['发现作品','作品详情旁推荐同类故事，搜索提示围绕剧名与题材。'],['接着看','右侧系列可点击进入相邻集；作者主页另有合集与作品搜索。'],['讨论与反馈','评论引用前集情节、追问角色关系；新集弹幕表达更新期待。'],['修订与再发布','作者说明根据观众反馈重做第三、四集；主页可见两条修正版与上半季整合版。']].map(([h,p],i)=><li key={h}><span>0{i+1}</span><h3>{h}</h3><p>{p}</p></li>)}</ol>
 <div className="ms-grid two"><article><h3>已经有的承接</h3><p>连续观看、系列归组、作品搜索、评论互答，以及作者报告的反馈处理。新社区需要在这些现成路径上判断可改进之处。</p></article><article><h3>具体可检验的问题</h3><p>合集序号与正文集号有偏差；旧版、修正版和整合版同时存在。对创作者而言，这提示发布时需要说明版本和集序，减少观众理解负担；相关经验可整理为创作发布案例。</p><small>修正版已发布；改动是否改善理解，尚无新旧版对照结果。</small></article></div>
 <p className="ms-links"><Link href="https://www.douyin.com/video/7672707173901683995">原集</Link><Link href="https://www.douyin.com/video/7674686865202482467">相邻集</Link><Link href="https://www.douyin.com/video/7676830509116165422">作者修订说明</Link><Link href="https://www.douyin.com/video/7678887101219327286">第三集修正版</Link><Link href="https://www.douyin.com/video/7679070880823135515">第四集修正版</Link></p></section>
 <VisualLifeCases/><section id="ms-feedback"><h2>评论中的问句，有时是在求解，有时是在一起玩</h2><p>相邻集有观众询问怪物弱点。展开后的首批三条回复是玩笑、提及朋友和表情互动，仍有更多回复未读。此处已经产生社交趣味；是否需要严肃的设定解释，要结合问题上下文和实际答复判断。</p><p>评论分析记录求解、评价、期待、讨论与玩笑；只有具体问题反复出现且原内容和已有答复仍难解决，才判断供给缺口。</p></section><section id="ms-media"><h2>同一消费任务，分别看平台怎样承接</h2><div className="ms-table"><table><thead><tr><th>平台与资料</th><th>可确认的承载</th><th>对研究的意义</th></tr></thead><tbody><tr><th>抖音 · 连载实页</th><td>详情旁系列、作者作品搜索、合集、评论与弹幕</td><td>追看和讨论有现成路径。合集卡片在所查网页不可点击，相邻集路径已走通。</td></tr><tr><th>B站 · 同名系列实页</th><td>作品简介、AI标识、收藏、作者页、同系列推荐</td><td>所查第十集右侧混排其他集数；推荐邻接与顺序阅读需分开。跨站署名身份未独立认证。</td></tr><tr><th>小红书 · 热榜规则与空间案例</th><td>搜索、曝光、互动与点击等信号参与排行</td><td>热榜反映关注信号；空间复刻原页已有使用者反馈，同条件比较仍缺。</td></tr></tbody></table></div><p className="ms-links"><Link href="https://www.bilibili.com/video/BV1a5GP6YEfp/">B站同名系列</Link><Link href="https://fe.xiaohongshu.com/ditto/vincent/c45978d1a53d4dec963167ebd6f1802e?fullscreen=true&naviHidden=yes">小红书热榜规则</Link></p><p><Link href="/task-research#task-faithful-expression">小红书空间案例与使用者反馈</Link></p><h3>抖音指数怎样使用</h3><p>先用主题词和用户说法发现候选，再读作品与评论，最后核对原平台已提供的内容。指数用于选择观察方向；供需判断还需同主题的供给质量、更新情况和用户具体问题。</p><p><Link href={deep('de-index')}>关键词、指数与查询记录</Link></p></section>
 <section id="ms-gap"><h2>供给少、消费多，先验证是否真有空缺</h2><div className="ms-table"><table><thead><tr><th>观察到的情况</th><th>还要核查什么</th><th>当前判断</th></tr></thead><tbody><tr><th>相关作品热度高</th><td>是题材长期需求、单个作者影响，还是推荐与事件带来的短期关注？</td><td>可进入选题观察，尚不足以确认缺口。</td></tr><tr><th>用户反复提出具体问题</th><td>原作品、评论回复、合集和同类作者是否已经解答？</td><td>优先核查问题是否仍未解决。</td></tr><tr><th>已有答案但难找</th><td>从作品到答案需经过哪些步骤，是否有集序或版本歧义？</td><td>可能是组织与发现问题，需与现有入口比较。</td></tr><tr><th>确实缺内容或答复</th><td>是否有稳定需求，供给者能否持续交付，创作者、学习者或协作者为何使用新入口？</td><td>进入供给可行性与产品方案阶段。</td></tr></tbody></table></div><p>连载版本、审美差异与实物制作条件，分别提示内容组织、质量和实用信息的改进空间。是否带来持续使用，还需行为验证。</p></section><section id="ms-supply"><h2>社媒作品怎样与 AIGC 社区资源配合</h2><div className="ms-grid three">{[['资源供给','模型、模板、工作流','帮助制作和复用方法。'],['作品供给','成片、图片、故事系列','在社媒承担观看与欣赏；在创作社区提供灵感、能力展示与方法讨论。'],['解释与维护','教程、资料、答疑、修正版','帮助理解、完成任务和继续使用。']].map(([h,p,n])=><article key={h}><h3>{h}</h3><p>{p}</p><small>{n}</small></article>)}</div><p>三种供给的维护责任不同：资源跟进条件与依赖，作品保持质量和更新，解释与维护回应实际问题。以下为15家已复核的平台档案。</p><div className="ms-platforms">{profiles.map(p=><Link key={p.id} href={`/?section=${p.id==='liblib'?'liblib-supply-model':p.id+'-digest-supply'}#${p.id}`}>{p.name}</Link>)}</div><p className="ms-caption">分类依据：{digests.length}家综合档案与LiblibAI专项档案。<Link href="/#content">内容形态横向比较</Link></p></section>
 <section id="ms-evidence"><h2>资料分层：广度、深读与行为结果</h2><InventoryChart/><p>审美与家居组包含10个已读作品页面，其中3个与存量目录重合、7个为新增链接。与615个存量链接合并去重后为622个；上图保留存量分类快照，补充组单列于“审美与家居”。</p><div className="ms-grid three">{[['主题广度','目录、检索与作者作品列表','回答有哪些内容、怎样分组。'],['内容与评论深读','作品详情、画面抽查、根评论与回复','回答内容讲了什么、用户具体在问什么。'],['行为结果','连续观看、实际回访、需求解决','公开评论提供线索；留存与迁移效果需要行为数据。']].map(([h,p,n])=><article key={h}><h3>{h}</h3><strong>{p}</strong><p>{n}</p></article>)}</div><p>另有四件专题核查作品分别覆盖历史、自然科普、连载和教程；它们也包含“原内容已经回答问题”的反例。</p><div className="ms-grid two">{closure.cases.map(c=><article key={c.id}><h3>{c.name}</h3><p>{c.headline}</p><Link href={c.url}>原作品</Link> · <Link href={deep('closure-'+c.id)}>核查记录</Link></article>)}</div><p className="ms-links"><Link href={deep('theme-comparison')}>主题比较与作者样本</Link><Link href={deep('de-evidence')}>作品、评论与采集口径</Link><Link href="/#supply">供给方式参考</Link></p></section>
 </article>}
