'use client';
import {useState} from 'react';
import './app-samples.css';
/* oxlint-disable next/no-img-element -- Existing local sample assets. */

export const appSamples:Record<string,{title:string;summary:string;input:string;output:string;conditions:string;destination:string;kind:string}>={
 suite:{title:'电商套图',summary:'围绕同一款商品，整理主图、场景图与细节图的制作需求。',input:'商品图片、卖点、目标平台与画幅要求',output:'商品套图与配套文案',conditions:'商品素材需有使用授权；导出规格在 MakeNow 中确认。',destination:'https://www.makenow.tv/tools/workspace/ecom-suite',kind:'图片应用'},
 analysis:{title:'选品分析',summary:'从候选商品与经营目标出发，整理比较维度和需要验证的机会。',input:'候选商品、目标市场、成本与调研资料',output:'选品比较报告与验证建议',conditions:'在对应应用内准备材料；市场数据与分析依据需核实。',destination:'',kind:'分析应用'},
 music:{title:'音乐翻唱',summary:'把歌曲、歌词与风格要求整理成清楚的翻唱制作方案。',input:'有权使用的歌曲素材、歌词与风格要求',output:'翻唱音频',conditions:'准备原歌曲素材；可用能力与音频规格在 MakeNow 中确认。',destination:'https://www.makenow.tv/media?tool=music-cover',kind:'音乐应用'},
 storyboard:{title:'分镜一致性质检',summary:'对照角色设定与连续分镜，找出影响叙事连贯的视觉差异。',input:'分镜图片、角色设定与场景说明',output:'一致性检查报告与修改建议',conditions:'在对应应用内准备材料，并提供分镜与角色基准。',destination:'',kind:'检查应用'},
 website:{title:'网页开发',summary:'把页面目标、内容与视觉偏好整理成可交付的网页开发任务。',input:'页面目标、文案、素材与交互需求',output:'网页代码与交付说明',conditions:'在对应应用内准备材料 并确认项目需求；运行与部署需验收。',destination:'',kind:'开发应用'},
};
const sampleGuide:Record<string,{fit:string;steps:string[]}>={
 suite:{fit:'适合已有商品素材，希望统一上新图片风格的商家与内容运营。',steps:['准备商品素材与核心卖点','在 MakeNow 中确认场景、画幅与生成设置','检查商品细节，选取并导出需要的图片']},
 analysis:{fit:'适合有候选商品，需要把资料整理成可比较决策依据的小团队。',steps:['明确目标市场与经营约束','提交候选商品和可核实的调研资料','检查依据，确定下一轮小规模验证']},
 music:{fit:'适合拥有歌曲使用授权，希望探索不同演绎风格的音乐创作者。',steps:['准备授权音源与风格参考','在 MakeNow 中确认歌词、风格及制作设置','试听并检查音质、发音和授权范围']},
 storyboard:{fit:'适合已有连续分镜，需要检查角色、道具和场景是否前后一致的创作者。',steps:['整理分镜顺序与角色基准','在对应应用内提交分镜与角色基准','复核问题位置，修改后再次检查']},
 website:{fit:'适合目标明确，需要把活动页、品牌页或产品展示页做成网页的小团队。',steps:['整理页面目标、内容与素材','在 MakeNow 中创建并确认开发任务','检查页面与交互，完成运行和部署验收']},
};
function SuiteSample(){
 const [selected,setSelected]=useState('perfume');
 return <section className="as-suite"><header className="as-cap"><span>商品视觉方向</span><span>场景示意</span></header><div className="as-suite-photo"><img src={'/home-prototype/'+selected+'.png'} alt={selected==='perfume'?'香水商品场景示意':'杯子商品场景示意'}/><span className="as-photo-mark">{selected==='perfume'?'01 · 香氛':'02 · 日用'}</span></div><div className="as-suite-footer"><div><small>同一商品，一组完整表达</small><h2>{selected==='perfume'?'清新香氛 · 夏日上新':'日常器物 · 生活提案'}</h2><p>主图建立第一印象，场景图传递使用感受，细节图说明商品特点。</p></div><nav aria-label="切换商品场景示意">{['perfume','cup'].map((key)=><button key={key} aria-pressed={selected===key} onClick={()=>setSelected(key)}><img src={'/home-prototype/'+key+'.png'} alt={key==='perfume'?'香水示意':'杯子示意'}/></button>)}</nav></div><p className="as-note">商品场景示意。</p></section>;
}
function AnalysisSample(){return <section className="as-report"><header className="as-cap"><span>选品比较报告</span><span>虚构样例</span></header><div className="as-report-title"><small>任务简述</small><h2>为通勤人群选择一款日常杯</h2><p>比较三类候选商品，先明确取舍，再设计小批量验证。</p></div><div className="as-table-wrap"><table><thead><tr><th>候选方向</th><th>主要价值</th><th>需要验证</th></tr></thead><tbody><tr><td><strong>轻量随行杯</strong><small>优先验证</small></td><td>便携、易清洗</td><td>防漏表现与实际容量</td></tr><tr><td><strong>保温通勤杯</strong><small>备选方向</small></td><td>温度保持、耐用</td><td>重量与售价接受度</td></tr><tr><td><strong>陶瓷咖啡杯</strong><small>场景限定</small></td><td>触感、桌面美感</td><td>运输损耗与复购用途</td></tr></tbody></table></div><div className="as-finding"><span>建议动作</span><p>先用少量样品检查防漏与清洗体验，再访谈目标用户；在获得价格反馈后决定是否采购。</p></div><p className="as-note">虚构报告示例。</p></section>;}
function MusicSample(){return <section className="as-music"><header className="as-cap"><span>翻唱制作方案</span><span>方案示例</span></header><div className="as-music-title"><span className="as-record" aria-hidden="true"><i/></span><div><small>ACOUSTIC SESSION</small><h2>让熟悉的旋律，换一种表达。</h2><p>轻柔人声 / 木吉他 / 克制编曲</p></div></div><dl className="as-music-plan"><div><dt>输入歌曲</dt><dd>用户提供的授权歌曲素材</dd></div><div><dt>演绎方向</dt><dd>自然、温暖，保留旋律与歌词的辨识度</dd></div><div><dt>风格参考</dt><dd>木吉他伴奏，减少厚重效果，突出人声细节</dd></div></dl><div className="as-deliverables"><small>交付结构</small><p><span>翻唱版本</span><span>歌词（按实际设置）</span></p></div><p className="as-note">试听样本未提供。</p></section>;}
function StoryboardSample(){return <section className="as-story"><header className="as-cap"><span>分镜检查报告</span><span>结果示例</span></header><div className="as-report-title"><small>项目任务 · 4 镜头品牌短片</small><h2>同一个角色，贯穿同一段故事。</h2><p>以角色设定为基准，检查外观、关键道具和场景连续性。</p></div><ol className="as-shots"><li><span>01</span><div><strong>街角出场</strong><p>深色短发、米色外套，建立角色基准。</p></div><em>基准镜头</em></li><li><span>02</span><div><strong>走进咖啡店</strong><p>外套颜色一致；手提袋由左手换至右手，建议核对动作衔接。</p></div><em className="as-attention">需核对</em></li><li><span>03</span><div><strong>靠窗落座</strong><p>人物发型出现差异，建议与基准镜头统一。</p></div><em className="as-attention">建议修改</em></li><li><span>04</span><div><strong>窗边特写</strong><p>角色外观与服装一致，光线方向与上一镜头衔接。</p></div><em>符合基准</em></li></ol><p className="as-note">虚构分镜检查报告示例。</p></section>;}
function WebsiteSample(){return <section className="as-website"><header className="as-cap"><span>网页视觉方向</span><span>静态效果示意</span></header><div className="as-web-preview" aria-label="生活方式品牌页静态效果示意"><div className="as-web-nav"><b>FORME</b><span>Objects & Stories</span></div><div className="as-web-hero"><div><small>MADE FOR EVERYDAY</small><h2>留一点空间，<br/>给日常的美好。</h2><p>从一件器物开始，找到自己的生活节奏。</p><span className="as-web-label">探索生活系列 ↗</span></div><div className="as-vase-scene" aria-hidden="true"><i className="as-branch"/><i className="as-vase"/><i className="as-vase-shadow"/></div></div><div className="as-web-bottom"><span>01 / 简洁器物</span><span>02 / 自然材质</span><span>03 / 日常灵感</span></div></div><div className="as-web-brief"><h3>任务：生活方式品牌展示页</h3><p>以品牌故事和产品系列为主线，整理首屏、系列展示和联系入口。</p><div><span>页面代码</span><span>素材与样式</span><span>交付说明</span></div></div><p className="as-note">静态页面示意。</p></section>;}
export function AppSampleContent({sample}:{sample:string}){
 const key=appSamples[sample]?sample:'suite';
 const guide=sampleGuide[key];
 return <div className={'as-content as-'+key+'-content'}>{key==='suite'?<SuiteSample/>:key==='analysis'?<AnalysisSample/>:key==='music'?<MusicSample/>:key==='storyboard'?<StoryboardSample/>:<WebsiteSample/>}<section className="as-guide"><h2>适合什么任务</h2><p>{guide.fit}</p><h2>如何开始</h2><ol>{guide.steps.map((step,index)=><li key={step}><span>{String(index+1).padStart(2,'0')}</span><p>{step}</p></li>)}</ol></section></div>;
}
