'use client';
import {contentCircleId} from './content-data';
import {useSyncExternalStore} from 'react';
import {blankContentDraft,changeContentModel,createContent,readContentModel,contentTime} from '../b-prototype/content-model';
import {readAdminWorks,type Work} from '../b-prototype/work-management';
export type CSubmission={contentId:string;kind:string;title?:string;body?:string;category?:string;circle?:string;circleId?:string;creationPrompt?:string;model?:string;scene?:string;topics?:string[];workType?:string;submittedAt?:number;firstPublishedAt?:number;media?:{name:string;url:string;type:string;size:number}[];status?:string;reason?:string};
const key='ai666-c-submissions-v1';
export async function persistentSubmissionMedia(files:{name:string;url:string;type:string;size:number;source?:File}[]){return Promise.all(files.map(async file=>{let url=file.url;if(url.startsWith('blob:')){if(!file.source)throw new Error('素材未完成保存，请重新选择');url=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>typeof reader.result==='string'?resolve(reader.result):reject(new Error('素材读取失败'));reader.onerror=()=>reject(new Error('素材读取失败'));reader.readAsDataURL(file.source!)});}return {name:file.name,url,type:file.type,size:file.size}}));}
function journal():CSubmission[]{try{return JSON.parse(localStorage.getItem(key)||'[]')}catch{return []}}
export function changeCSubmissionState(id:string,action:'remove'|'restore'|'delete'|'withdraw'){
 if(!journal().some(row=>row.contentId===id))return null;
 const status=action==='remove'?'removed':action==='delete'?'deleted':action==='withdraw'?'withdrawn':'public';
 const post=readContentModel().records.find(r=>r.id===id),time=contentTime(),label=action==='remove'?'用户下架':action==='restore'?'用户恢复公开':action==='delete'?'用户删除':'用户撤回审核';
 if(action==='restore'){const work=post?undefined:readAdminWorks().find(row=>row.id===id);if(post?post.visibility!=='已下架'||!post.published:!work||work.status!=='已下架'||work.submittedWhileDown||(!work.publicSnapshot&&!work.publicAt))return null;}
 if(action==='restore'&&post&&!post.published)throw new Error('内容尚未通过审核，暂不能恢复公开');
 if(post)changeContentModel(db=>{db.records=action==='delete'?db.records.filter(row=>row.id!==id):db.records.map(row=>row.id!==id?row:{...row,pinned:action==='remove'?false:row.pinned,visibility:action==='remove'?'已下架':action==='restore'&&row.published?'已公开':row.visibility,review:action==='withdraw'?'草稿':row.review,submissionId:action==='withdraw'?null:row.submissionId,revision:row.revision+1,updatedAt:time,logs:[{at:time,action:label,reason:'',operator:row.author},...row.logs]});});
 else {let rows=readAdminWorks();const work=rows.find(row=>row.id===id);if(work){if(action==='restore'&&(work.submittedWhileDown||(!work.publicSnapshot&&(work.status!=='已下架'||!work.publicAt))))throw new Error('内容状态已变化，请完成审核后再恢复公开');if(action==='delete')rows=rows.filter(row=>row.id!==id);else if(action==='withdraw')rows=work.publicSnapshot?rows.map(row=>row.id===id?{...work.publicSnapshot!,logs:[{at:time,action:label,reason:''},...work.logs]}:row):rows.filter(row=>row.id!==id);else rows=rows.map(row=>row.id!==id?row:{...row,status:action==='restore'?(row.publicSnapshot?(row.resumeStatus||'待审核'):'已公开'):'已下架',resumeStatus:action==='remove'&&row.publicSnapshot?row.status:undefined,hot:false,publicSnapshot:row.publicSnapshot?{...row.publicSnapshot,hot:false}:undefined,logs:[{at:time,action:label,reason:''},...row.logs]});localStorage.setItem('ai666-work-admin-v3',JSON.stringify(rows));window.dispatchEvent(new Event('ai666-work-admin-change'));}}
 localStorage.setItem(key,JSON.stringify(action==='delete'?journal().filter(row=>row.contentId!==id):journal().map(row=>row.contentId===id?{...row,status}:row)));window.dispatchEvent(new Event('cp-content-change'));return status;
}
export function submitCContent(input:CSubmission,author:string){
 const time=contentTime(),media=input.media||[];
 if(input.kind==='post')changeContentModel(db=>{const previous=db.records.find(r=>r.id===input.contentId);const item=previous||{...createContent('post'),id:input.contentId,official:false,author,authorId:'demo-c-current-user'};const draft={...blankContentDraft('post'),...item.draft,title:input.title||'',body:input.body||'',summary:(input.body||'').slice(0,100),category:input.category||item.draft.category,circle:input.circle||'',circleId:input.circle?contentCircleId(input.circle,input.circleId):undefined,cover:media.find(m=>m.type.startsWith('image/'))?.url||'',media:media.map(m=>m.url).join('|'),source:'用户原创'};const next={...item,draft,official:false,author,review:'待审核' as const,submissionId:crypto.randomUUID(),submittedAt:time,updatedAt:time,revision:item.revision+1,logs:[{at:time,action:'用户提交审核',reason:'',operator:author},...item.logs]};db.records=previous?db.records.map(r=>r.id===item.id?next:r):[next,...db.records]});
 else {const records=readAdminWorks(),previous=records.find(r=>r.id===input.contentId);const submittedWhileDown=previous?.status==='已下架'||!!(previous as (Work&{submittedWhileDown?:boolean})|undefined)?.submittedWhileDown;const publicSnapshot=submittedWhileDown?undefined:previous?.status==='已公开'?structuredClone(previous):previous?.publicSnapshot;const next:Work&{submittedWhileDown?:boolean}={...previous,id:input.contentId,title:input.title||'',author,authorId:'demo-c-current-user',official:false,category:input.category||'',categories:input.category?[input.category]:[],status:'待审核',hot:previous?.hot||false,created:previous?.created||time,publicAt:previous?.publicAt,prompt:input.creationPrompt||'',summary:input.body||'',images:media.filter(m=>m.type.startsWith('image/')).map(m=>m.url),video:media.find(m=>m.type.startsWith('video/'))?.url,textBody:input.workType==='text'?input.body:undefined,mediaType:input.workType==='text'?'文本':input.workType==='video'?'视频':'图片',model:input.model,topics:input.topics||[],scenarios:input.scene?[input.scene]:[],publicSnapshot,submittedWhileDown,logs:[{at:time,action:'用户提交审核',reason:''},...(previous?.logs||[])]};localStorage.setItem('ai666-work-admin-v3',JSON.stringify(previous?records.map(r=>r.id===next.id?next:r):[next,...records]));window.dispatchEvent(new Event('ai666-work-admin-change'));}
 localStorage.setItem(key,JSON.stringify([input,...journal().filter(r=>r.contentId!==input.contentId)]));window.dispatchEvent(new Event('cp-content-change'));
}
function snapshot(){if(typeof window==='undefined')return '[]';const content=readContentModel(),works=readAdminWorks();return JSON.stringify(journal().map(row=>{const post=content.records.find(r=>r.id===row.contentId),work=works.find(r=>r.id===row.contentId);const status=post?post.visibility==='已下架'?'removed':post.review==='待审核'?'review':post.review==='已退回'?'rejected':post.visibility==='已公开'?'public':'withdrawn':work?work.status==='已公开'?'public':work.status==='已下架'?'removed':work.status==='已拒绝'?'rejected':'review':row.status;return {...row,status,reason:post?.logs[0]?.reason||work?.logs[0]?.reason||'',firstPublishedAt:post?.firstPublishedAt?Date.parse(post.firstPublishedAt):work?.publicAt?Date.parse(work.publicAt):row.firstPublishedAt};}));}
const subscribe=(fn:()=>void)=>{const events=['storage','cp-content-change','ai666-content-model-change','ai666-work-admin-change'];events.forEach(e=>window.addEventListener(e,fn));return()=>events.forEach(e=>window.removeEventListener(e,fn))};
export function useCSubmissions():CSubmission[]{return JSON.parse(useSyncExternalStore(subscribe,snapshot,()=> '[]'));}
