'use client';
import {readPublishedEventConfigs} from '../b-prototype/retained-event-config';
import {MediaPreview} from './media-preview';
/* eslint-disable next/no-img-element -- Local prototype assets. */
import {useEffect,useRef,useState} from 'react';
import {ParameterMenu} from './parameter-menu';
import {TransientFeedback} from './transient-feedback';
import {prototypeStore as store,writeTask,pointBalance,currentTarget,type PrototypeTask} from './storage';
import {readCActivities} from './retained-activities';
import './pc-generation.css';
type Mode='image'|'text'|'video';
type VideoTask=PrototypeTask&{resolution?:string;duration?:string;referenceVideoName?:string};
type ReferenceVideo={url:string;name:string};
const config={image:{title:'图片生成',models:['图片模型'],max:4,points:10},text:{title:'剧本创作',models:['Gt5.6-Terra','Gt5.6-Luna','Ds-V4-Flash'],max:0,points:2},video:{title:'视频生成',models:['vo_3_1'],max:1,points:20}};
const asset='/home-prototype/';
const scriptText='把清晨，留给一束光\n\n第一幕 · 海边小镇 / 清晨\n薄雾慢慢散开，主角背着相机走过安静的街道。镜头跟随脚步，掠过窗台上的花与微微晃动的门牌。\n\n第二幕 · 旧码头 / 日出\n第一束光落在翻开的相册上。她抬起相机，又轻轻放下。\n\n“有些风景，记住就好。”';
export function PcGeneration({state,rows,go,resultOnly=false}:{state:string;rows:PrototypeTask[];go:(target:string)=>void;resultOnly?:boolean}){
 const handoffReview=typeof window!=='undefined'&&['result-image','result-video','result-text'].includes(new URLSearchParams(window.location.search).get('handoffReview')||'')&&window.parent!==window;
 const [handoffStage,setHandoffStage]=useState('source');
 const [handoffCanvas,setHandoffCanvas]=useState(false);
 const missingHandoffPrompt=handoffReview&&new URLSearchParams(window.location.search).get('missingPrompt')==='1';
 useEffect(()=>{if(!handoffReview)return;const receive=(event:MessageEvent)=>{if(event.origin!==window.location.origin||event.source!==window.parent||event.data?.type!=='result-handoff-state')return;setHandoffStage(event.data.stage);setHandoffCanvas(!!event.data.hasCanvas);};window.addEventListener('message',receive);return()=>window.removeEventListener('message',receive);},[handoffReview]);
 const sendHandoff=(action:string)=>window.parent.postMessage({type:'result-handoff-action',action,prompt:missingHandoffPrompt?'':preview?.input||'',image:asset+'sea.png',video:asset+'sea-sample.mp4',text:scriptText},window.location.origin);
 const reviewOverlay=typeof window==='undefined'?'':new URLSearchParams(window.location.search).get('reviewOverlay')||'';
 const videoReview=['aigc-video-quality','aigc-video-duration','aigc-reference-video'].includes(reviewOverlay);
 const requestedId=new URLSearchParams(typeof window==='undefined'?'':window.location.search).get('task');
 const requested=rows.find(r=>r.id===requestedId);
 const saved=()=>{try{return JSON.parse(store.getItem('cp-light-create-draft')||'{}');}catch{return {};}};
 const [mode,setMode]=useState<Mode>(()=>videoReview?'video':reviewOverlay?'image':state==='create-image'?'image':state==='create-video'?'video':state==='create-text'?'text':requested?.item?.startsWith('light-')?requested.item.replace('light-','') as Mode:saved().type in config?saved().type:'image');
 const [prompt,setPrompt]=useState(()=>reviewOverlay==='aigc-insufficient'?'海边日落，浪花映着暖金色的光':requested?.input||saved().prompt||'');
 const [quality,setQuality]=useState(()=>videoReview?'720p':(requested as VideoTask)?.resolution||saved().quality||'720p');
 const [duration,setDuration]=useState(()=>videoReview?'5秒':(requested as VideoTask)?.duration||saved().duration||'5秒');
 const [referenceVideo,setReferenceVideo]=useState<ReferenceVideo|null>(()=>reviewOverlay==='aigc-reference-video'?{url:'/home-prototype/sea-sample.mp4',name:'海岸参考视频.mp4'}:null);
 const [historyMedia,setHistoryMedia]=useState<{items:string[];index:number}|null>(null);
 const [imagePreview,setImagePreview]=useState<number|null>(reviewOverlay==='aigc-reference-image'?0:null);
 const [videoPreview,setVideoPreview]=useState(reviewOverlay==='aigc-reference-video');
 const referenceVideos=useRef<Record<string,ReferenceVideo>>({});
 const chooseReferenceVideo=(file?:File)=>{
  if(!file)return;
  if(!['video/mp4','video/webm','video/quicktime'].includes(file.type)||file.size>10*1024*1024){setNotice('请选择不超过 10MB 的 MP4、WebM 或 MOV 参考视频。');return;}
  const url=URL.createObjectURL(file);urls.current.push(url);setReferenceVideo({url,name:file.name});setNotice('');
 };
 const [ratio,setRatio]=useState(()=>requested?.ratio||saved().ratio||'16:9');
 const [model,setModel]=useState(()=>requested?.model||saved().model||'');
 const [refs,setRefs]=useState<string[]>(()=> reviewOverlay==='aigc-reference-image'?[asset+'sea.png',asset+'portrait.png']:(saved().references||[]).map((r:{url:string})=>r.url).filter((url:string)=>url.startsWith(asset)));
 const [activity,setActivity]=useState(()=>store.getItem('cp-activity-code')||'');
 const [preview,setPreview]=useState<PrototypeTask|null>(()=>resultOnly?(requested?.status==='completed'?requested:requestedId?null:rows.find(r=>r.status==='completed'&&r.item==='light-'+(state==='result-text'?'text':state==='result-video'?'video':'image'))||null):null);
 const [notice,setNotice]=useState(()=>!resultOnly&&store.getItem('cp-pc-reference-missing')==='1'?'原参考素材不可用，请重新选择参考图后继续调整。':'');
 const [closed,setClosed]=useState(false);
 const [submitted,setSubmitted]=useState(false);
 const feed=useRef<HTMLDivElement>(null),input=useRef<HTMLTextAreaElement>(null),close=useRef<HTMLButtonElement>(null);
 const urls=useRef<string[]>([]),timers=useRef<ReturnType<typeof setTimeout>[]>([]);
 const references=useRef<Record<string,string[]>>({});
 const cfg=config[mode];
 const insufficient=state==='insufficient'||reviewOverlay==='aigc-insufficient'||pointBalance()<cfg.points;
 const validRatios=mode==='video'?['16:9','9:16']:['1:1','16:9','9:16','4:3','3:4'];
 useEffect(()=>{if(mode!=='text'&&!validRatios.includes(ratio))setRatio(validRatios[0]);},[mode,ratio]);
 const activeModel=cfg.models.includes(model)?model:cfg.models[0];
 const activities=readCActivities().filter(a=>{const p=readPublishedEventConfigs().find(c=>c.code===a.code)?.extra_config.publish_config;return a.status==='进行中'&&!a.locked&&a.publishKind==='work'&&a.tasks.some(t=>t.action?.includes('发布'))&&(!p?.content_types.length||p.content_types.includes(mode==='image'?2:mode==='video'?3:4));});
 const stream=rows.filter(r=>r.item==='light-'+mode).sort((a,b)=>(a.createdAt||0)-(b.createdAt||0));
 useEffect(()=>()=>{urls.current.forEach(u=>URL.revokeObjectURL(u));timers.current.forEach(clearTimeout);},[]);
 useEffect(()=>{if(resultOnly)return;store.setItem('cp-light-create-draft',JSON.stringify({type:mode,prompt,model:activeModel,ratio,quality,duration,references:refs.filter(url=>url.startsWith(asset)).map(url=>({url}))}));},[mode,prompt,activeModel,ratio,quality,duration,refs,resultOnly]);
 useEffect(()=>{const target=requested?feed.current?.querySelector<HTMLElement>('[data-task="'+requested.id+'"]'):null;feed.current?.scrollTo({top:target?target.offsetTop-80:feed.current.scrollHeight});},[mode,rows.length,submitted]);
 useEffect(()=>{if(preview)close.current?.focus();},[preview]);
 useEffect(()=>{if(!resultOnly)store.removeItem('cp-pc-reference-missing');},[resultOnly]);
 const media=(r:PrototypeTask)=>r.item==='light-text'?<div className="pg-script"><span>短片剧本 · 寻找晨光</span><h2>把清晨，留给一束光</h2><p>第一幕 · 海边小镇 / 清晨</p><p>薄雾慢慢散开，主角背着相机走过安静的街道。镜头跟随脚步，掠过窗台上的花与微微晃动的门牌。</p><p>第二幕 · 旧码头 / 日出</p><p>第一束光落在翻开的相册上。她抬起相机，又轻轻放下。</p><blockquote>“有些风景，记住就好。”</blockquote></div>:r.item==='light-video'?<video controls src={asset+'sea-sample.mp4'} playsInline/>:<img src={asset+'sea.png'} alt="海岸日落创作结果"/>;
 const rowRefs=(r:PrototypeTask)=>references.current[r.id||'']||(['sample-light-image-complete','sample-light-video-running'].includes(r.id||'')?[asset+'sea.png']:[]);
 const restore=(r:PrototypeTask)=>{if(resultOnly){if(r.referenceName&&!rowRefs(r).length||(r as VideoTask).referenceVideoName&&!referenceVideos.current[r.id||''])store.setItem('cp-pc-reference-missing','1');['cp-activity','cp-activity-code','cp-activity-name','cp-activity-task'].forEach(k=>store.removeItem(k));if(r.activityCode){store.setItem('cp-activity','1');store.setItem('cp-activity-code',r.activityCode);store.setItem('cp-activity-name',r.activityName||'');if(r.activityTask)store.setItem('cp-activity-task',r.activityTask);}store.setItem('cp-light-create-draft',JSON.stringify({type:r.item?.replace('light-','')||'image',prompt:r.input||'',ratio:r.ratio||'16:9',quality:(r as VideoTask).resolution||'720p',duration:(r as VideoTask).duration||'5秒',model:r.model?.split(' · ')[0]||'',references:rowRefs(r).map(url=>({url}))}));go('create');return;}const kind=r.item?.replace('light-','') as Mode;setMode(kind);setPrompt(r.input||'');setRatio(r.ratio||'16:9');setModel(r.model?.split(' · ').pop()||'');setRefs(rowRefs(r).slice(0,config[kind].max));setActivity(r.activityCode||'');store.removeItem('cp-activity-task');if(r.activityTask)store.setItem('cp-activity-task',r.activityTask);setQuality((r as VideoTask).resolution||'720p');setDuration((r as VideoTask).duration||'5秒');setReferenceVideo(referenceVideos.current[r.id||'']||null);setPreview(null);setNotice((r.referenceName&&!rowRefs(r).length||(r as VideoTask).referenceVideoName&&!referenceVideos.current[r.id||''])?'原参考素材不可用，请重新选择参考图后继续调整。':'');input.current?.focus();};
 const publish=(r:PrototypeTask)=>{const kind=r.item?.replace('light-','')||'image';store.setItem('cp-post-kind','work');store.removeItem('cp-circle');store.setItem('cp-source','light-result');store.setItem('cp-task',JSON.stringify(r));['cp-activity','cp-activity-code','cp-activity-name','cp-activity-task'].forEach(k=>store.removeItem(k));if(r.activityCode){store.setItem('cp-activity','1');store.setItem('cp-activity-code',r.activityCode);store.setItem('cp-activity-name',r.activityName||'');if(r.activityTask)store.setItem('cp-activity-task',r.activityTask);}store.setItem('cp-result',JSON.stringify({kind,prompt:r.input,model:r.model,title:'我的创作',image:asset+'sea.png',video:kind==='video'?asset+'sea-sample.mp4':undefined,text:kind==='text'?scriptText:undefined,taskId:r.id}));go('post-edit');};
 const download=(r:PrototypeTask)=><a download href={r.item==='light-text'?'data:text/plain;charset=utf-8,'+encodeURIComponent(scriptText):asset+(r.item==='light-video'?'sea-sample.mp4':'sea.png')}>下载</a>;
 const submit=()=>{if(!prompt.trim()||submitted||insufficient)return;if(store.getItem('cp-auth')!=='1'){store.setItem('cp-login-background',currentTarget());store.setItem('cp-return',currentTarget());go('login');return;}if(activity&&!activities.some(a=>a.code===activity)){setNotice('当前活动已失效或不支持此类型，请重新选择活动或取消关联。');return;}setNotice('');const r:VideoTask={id:'pc-generation-'+Date.now(),item:'light-'+mode,input:prompt,model:activeModel,ratio:mode==='text'?undefined:ratio,resolution:mode==='video'?quality:undefined,duration:mode==='video'?duration:undefined,referenceVideoName:mode==='video'?referenceVideo?.name:undefined,points:cfg.points,status:'running',createdAt:Date.now(),referenceName:refs.length?'参考素材':undefined,activityCode:activity||undefined,activityTask:activity?store.getItem('cp-activity-task')||undefined:undefined,activityName:activities.find(a=>a.code===activity)?.name};references.current[r.id!]=[...refs];if(mode==='video'&&referenceVideo)referenceVideos.current[r.id!]=referenceVideo;writeTask(r);setSubmitted(true);timers.current.push(setTimeout(()=>{writeTask({...r,status:'completed'});setSubmitted(false);},2200));};
 const switchMode=(value:string)=>{setMode((Object.keys(config) as Mode[]).find(k=>config[k].title===value)!);setRefs([]);setReferenceVideo(null);setModel('');};
 const resultView=preview&&<div className="pg-preview" role="dialog" aria-modal="true" aria-label="生成结果" onKeyDown={e=>{if(e.key==='Escape')resultOnly?go('create'):setPreview(null);}}><button ref={close} className="pg-preview-close" onClick={()=>resultOnly?go('create'):setPreview(null)} aria-label="返回生成记录"><img src={asset+'icons/close-line.svg'} alt=""/></button><div className="pg-preview-media">{media(preview)}</div><aside><header><span className="pg-success">生成成功</span><h2>{config[preview.item?.replace('light-','') as Mode].title}</h2></header><section><h3>生成参数</h3><dl><dt>模型</dt><dd>{preview.model}</dd>{preview.ratio&&<><dt>比例</dt><dd>{preview.ratio}</dd></>}{preview.item==='light-video'&&<><dt>画质</dt><dd>{(preview as VideoTask).resolution||'未记录'}</dd><dt>时长</dt><dd>{(preview as VideoTask).duration||'未记录'}</dd></>}{preview.activityName&&<><dt>投稿活动</dt><dd>{preview.activityName}</dd></>}</dl></section><section><header><h3>提示词</h3>{!missingHandoffPrompt&&<button onClick={async()=>{try{await navigator.clipboard.writeText(preview.input||'');setNotice('提示词已复制');}catch{setNotice('请手动选择提示词复制');}}}>复制</button>}</header><p>{missingHandoffPrompt?'未记录':preview.input}</p></section>{(preview as VideoTask).referenceVideoName&&<section><h3>参考视频</h3>{referenceVideos.current[preview.id||'']?<video controls playsInline src={referenceVideos.current[preview.id||''].url}/>:<p>原参考视频不可用，请重新选择后继续调整。</p>}</section>}{preview.referenceName&&!rowRefs(preview).length&&<p role="status">原参考素材不可用，请重新选择参考图后继续调整。</p>}{rowRefs(preview).length>0&&<section><h3>参考素材</h3><div className="pg-preview-refs">{rowRefs(preview).map((u,i)=><button className="pg-history-reference" key={u} aria-label={'预览结果参考图 '+(i+1)} onClick={()=>setHistoryMedia({items:rowRefs(preview),index:i})}><img src={u} alt="参考素材"/></button>)}</div></section>}{handoffReview?<div className="pg-makenow">{['connection','media'].includes(handoffStage)?<div role="alert"><p>{handoffStage==='connection'?'暂时无法连接 MakeNow':'素材未能加入画布'}，当前结果已保留。</p><button onClick={()=>sendHandoff('start')}>重试</button><button onClick={()=>sendHandoff('return')}>返回结果</button></div>:<button disabled={handoffStage==='pending'} onClick={()=>sendHandoff('start')}>{handoffStage==='pending'?'正在连接并准备素材…':handoffCanvas?'打开本次 MakeNow 画布':'前往 MakeNow 继续创作'}</button>}</div>:<div className="pg-makenow"><a href="https://www.makenow.tv/" target="_blank" rel="noopener noreferrer">前往 MakeNow 继续创作<img src={asset+'icons/arrow-right-line.svg'} alt=""/></a><p>使用当前账号继续；素材、参数与费用在 MakeNow 中确认。</p></div>}<footer><button onClick={()=>restore(preview)}>继续调整</button><button className="pg-primary" onClick={()=>publish(preview)}>发布作品</button>{download(preview)}</footer></aside></div>;
 const historyPreview=<MediaPreview title="参考素材预览" items={(historyMedia?.items||[]).map((src,i)=>({src,name:"参考图 "+(i+1)}))} index={historyMedia?.index??null} onIndexChange={index=>setHistoryMedia(previous=>previous?{...previous,index}:null)} onClose={()=>setHistoryMedia(null)}/>;
 if(resultOnly)return <>{historyPreview}{resultView||<div className="pg-resume"><h2>暂时无法查看此结果</h2><p>请返回生成记录，查看任务当前进度。</p><button onClick={()=>go('create')}>返回 AIGC 生成</button></div>}{notice&&notice!=='提示词已复制'&&<p className="pg-task-feedback" role="alert">{notice}</p>}<TransientFeedback message={notice==='提示词已复制'?notice:''} onClear={()=>setNotice('')}/></>;
 if(closed)return <div className="pg-resume"><h2>继续你的创作</h2><button onClick={()=>setClosed(false)}>打开 AIGC 工作台</button><button onClick={()=>go('aigc')}>浏览作品</button></div>;
 return <section className="pg-workspace" role="dialog" aria-modal="true" aria-label="AIGC 生成工作台">
  <header className="pg-header"><div><img src={asset+'icons/sparkling-line.svg'} alt=""/><strong>AIGC 生成</strong><span>让灵感成为作品</span></div><button aria-label="收起 AIGC 生成工作台" onClick={()=>setClosed(true)}><img src={asset+'icons/arrow-down-s-line.svg'} alt=""/></button></header>
  <div className="pg-feed" ref={feed}><div className="pg-feed-inner">{stream.length?stream.map(r=><article className="pg-task" data-kind={r.item} data-task={r.id} key={r.id}><header><time>{r.createdAt?new Date(r.createdAt).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}):'时间未记录'}</time><span>{r.model?.replace(' · 标准模型','')} {r.ratio&&' · '+r.ratio}</span>{r.activityName&&<span>{r.activityName}</span>}</header><p className="pg-prompt">{r.input}</p>{rowRefs(r).length>0&&<div className="pg-reference-line"><span>参考素材</span>{rowRefs(r).map((u,i)=><button className="pg-history-reference" key={u} aria-label={'预览历史参考图 '+(i+1)} onClick={()=>setHistoryMedia({items:rowRefs(r),index:i})}><img src={u} alt="参考素材"/></button>)}</div>}{r.status==='completed'?<><div className={'pg-output '+(r.item==='light-text'?'is-text':'')}>{media(r)}<button aria-label="查看生成结果" onClick={()=>setPreview(r)}>查看结果</button></div><footer><span className="pg-success"><img src={asset+'icons/check-line.svg'} alt=""/>已完成</span>{download(r)}<button onClick={()=>restore(r)}>继续调整</button><button onClick={()=>publish(r)}>发布作品</button></footer></>:r.status==='failed'?<div className="pg-task-feedback"><strong>本次生成未完成</strong><span>请调整提示词或稍后重试</span><button onClick={()=>restore(r)}>重新编辑</button></div>:<div className="pg-task-feedback"><strong>正在生成</strong><b className="pg-progress-value">65%</b><span>结果将在这里展示，你可以继续浏览已有作品。</span><progress aria-label="生成进度" value={65} max={100}/></div>}</article>):<div className="pg-empty"><img src={asset+'icons/sparkling-line.svg'} alt=""/><h2>输入提示词，生成你想要的内容</h2><p>图片、剧本与视频，从一个想法开始</p></div>}</div></div>
  <div className="pg-composer-wrap"><div className="pg-composer"><div className="pg-materials">{cfg.max>0&&<div className="pg-refs">{refs.map((u,i)=><div key={u}><button type="button" className="pg-reference-thumb" aria-label={'预览参考图 '+(i+1)} onClick={()=>setImagePreview(i)}><img src={u} alt={'参考图 '+(i+1)}/></button><button aria-label={'移除参考图 '+(i+1)} onClick={()=>setRefs(refs.filter((_,n)=>n!==i))}><img src={asset+'icons/close-line.svg'} alt=""/></button></div>)}{refs.length<cfg.max&&<label className="pg-upload"><span>＋</span><small>{refs.length}/{cfg.max}</small><input type="file" accept="image/*" multiple={cfg.max>1} aria-label="添加参考图片" onChange={e=>{const files=Array.from(e.target.files||[]);e.target.value='';if(files.some(f=>!f.type.startsWith('image/'))||files.length+refs.length>cfg.max){setNotice('请选择图片，最多 '+cfg.max+' 张');return;}const next=files.map(f=>URL.createObjectURL(f));urls.current.push(...next);setRefs([...refs,...next]);}}/></label>}</div>}
  {mode==='video'&&<div className="pg-video-reference">{referenceVideo?<><button type="button" className="pg-video-reference-open" onClick={()=>setVideoPreview(true)}><img src={asset+'icons/play-circle-line.svg'} alt=""/><span>{referenceVideo.name}<small>点击预览参考视频</small></span></button><button type="button" aria-label="移除参考视频" onClick={()=>{setReferenceVideo(null);setVideoPreview(false);}} data-dismiss-icon="true"><img src="/home-prototype/icons/close-line.svg" alt="" /></button></>:<label className="pg-video-upload" title="添加参考视频（可选）：MP4、WebM、MOV，单条不超过 10MB"><img src={asset+'icons/play-circle-line.svg'} alt=""/><span>添加参考视频</span><input type="file" accept="video/mp4,video/webm,video/quicktime" aria-label="添加参考视频" onChange={e=>{chooseReferenceVideo(e.target.files?.[0]);e.target.value='';}}/></label>}</div>}
  </div><textarea ref={input} aria-label="创作提示词" placeholder={mode==='text'?'描述故事主题、人物与情节…':mode==='video'?'描述画面、镜头运动和氛围…':'描述你想生成的画面，也可以添加参考图…'} value={prompt} onChange={e=>setPrompt(e.target.value)}/>
  <div className="pg-toolbar"><div><ParameterMenu label="创作类型" value={cfg.title} options={Object.values(config).map(c=>c.title)} onChange={switchMode} initialOpen={reviewOverlay==='aigc-type'}/><ParameterMenu label="生成模型" value={activeModel} options={cfg.models} onChange={setModel} initialOpen={reviewOverlay==='aigc-model'}/>{mode!=='text'&&<ParameterMenu label="画面比例" value={ratio} options={mode==='video'?['16:9','9:16']:['1:1','16:9','9:16','4:3','3:4']} onChange={setRatio} initialOpen={reviewOverlay==='aigc-ratio'}/>}{mode==='video'&&<><ParameterMenu label="视频画质" value={quality} options={['720p','1080p']} onChange={setQuality} initialOpen={reviewOverlay==='aigc-video-quality'}/><ParameterMenu label="视频时长" value={duration} options={['5秒','10秒']} onChange={setDuration} initialOpen={reviewOverlay==='aigc-video-duration'}/></>}<ParameterMenu label="投稿活动" value={activities.find(a=>a.code===activity)?.name||(activity?'原活动不可用，请重新选择':'不参与活动')} options={['不参与活动',...activities.map(a=>a.name)]} onChange={name=>{setActivity(activities.find(a=>a.name===name)?.code||'');store.removeItem('cp-activity-task');}} initialOpen={reviewOverlay==='aigc-activity'}/></div><button className="pg-generate" disabled={!prompt.trim()||submitted||insufficient} onClick={submit}>{submitted?'生成中':insufficient?'积分不足':cfg.points+' 积分'}<img src={asset+'icons/arrow-up-line.svg'} alt="生成"/></button></div>
  </div><small className="pg-disclaimer">内容由 AI 生成</small></div>
  <MediaPreview title="参考素材预览" items={videoPreview&&referenceVideo?[{src:referenceVideo.url,type:"video",name:referenceVideo.name}]:refs.map((src,i)=>({src,name:"参考图 "+(i+1)}))} index={videoPreview?0:imagePreview} onIndexChange={setImagePreview} onClose={()=>{setVideoPreview(false);setImagePreview(null)}}/>
  {resultView}{historyPreview}
  {notice&&notice!=='提示词已复制'&&<p className="pg-task-feedback" role="alert">{notice}</p>}<TransientFeedback message={notice==='提示词已复制'?notice:''} onClear={()=>setNotice('')}/>
 </section>;
}