"use client";
/* oxlint-disable next/no-img-element -- Local prototype artwork. */
import {SearchHighlight} from './search-highlight';
import {hiddenPublicTarget} from './content-visibility';
import '../content-card-tokens.css';
import './work-feed.css';
export const workRatios:Record<string,string>={girl:'3/4',cat:'1/1',perfume:'4/3',portrait:'2/3',anime:'3/2',sea:'16/9',cup:'1/1',underwater:'9/16',interior:'4/3',dog:'4/5',restore:'3/2',letter:'4/5',writing:'4/3',headphones:'1/1',tram:'16/9'};
export type FeedWork={id:string;title:string;author:string;avatar?:string;image?:string;likes?:string|number;type?:string;ratio?:string;target?:string;summary?:string};
const authorAvatars:Record<string,string>={'周与斯':'girl','Tide':'anime','陈屿':'sea','林间':'portrait','小鹿':'cat','鹿与光':'perfume','拾光':'underwater','夏目川':'portrait'};
export function WorkFeed({items,go,searchQuery=''}:{items:FeedWork[];go:(target:string)=>void;searchQuery?:string}){return <div className="wf-grid">{items.filter(w=>!hiddenPublicTarget(w.target||'work?item='+w.id)).map(w=><button className={'wf-card'+(w.type==='文字'?' wf-text':'')} key={w.id} style={{aspectRatio:w.ratio||workRatios[w.id]||'1/1'}} onClick={()=>go(w.target||'work?item='+w.id)} aria-label={'查看作品：'+w.title}>{w.type==='文字'?<div className="wf-poem"><small>文字</small><h3>{<SearchHighlight text={w.title} query={searchQuery}/>}</h3><p>海风穿过街角，<br/>把普通的下午写成故事。</p></div>:w.image===''?<span>封面暂不可用</span>:<img src={w.image||'/home-prototype/'+w.id+'.png'} alt={w.title}/ >}{w.type==='视频'&&<span className="wf-video">视频 · 00:03</span>}<div className="wf-caption"><strong><SearchHighlight text={w.title} query={searchQuery}/></strong>{w.summary&&<small className="search-match-summary"><SearchHighlight text={w.summary} query={searchQuery}/></small>}<div><span className="wf-author"><img className="wf-avatar" src={w.avatar||'/home-prototype/'+(authorAvatars[w.author]||'portrait')+'.png'} alt=""/><span>{w.author}</span></span><span><img className="wf-heart" src="/home-prototype/icons/heart-line.svg" alt="喜欢"/> {w.likes||0}</span></div></div></button>)}</div>}
