import Link from 'next/link';
import {notFound} from 'next/navigation';
import options from '@/lib/options-expanded.json';
import versions from '@/lib/concept-versions.json';
import evidence from '@/lib/proposal-evidence.json';
import OptionGallery from '@/components/option-gallery';
import OptionOperations from '@/components/option-operations';
import '../../options.css';
import '../proposal.css';
const imageKeys:Record<string,string[]>={b:['discover','project','submit','feedback','review'],c:['discover','work','discussion','versions','collection'],d:['discover','method','versions','reproduce','maintain'],e:['discover','ask','question','compare','result']};
const names:Record<string,string>={a:'任务创作',b:'项目共学',c:'创作者研讨',d:'方法共建',e:'问题互助'};
const aImages=[['home-v8-card-spacing','发现首页'],['topics-index-v1','专题首页'],['topic-ecommerce-v1','电商营销专题'],['ai-apps-v3-combined','AI应用列表'],['app-product-scene-before-v1','表单生成'],['app-local-edit-selection-v1','局部编辑'],['app-writing-input-v1','文字文档'],['app-batch-scene-before-v1','批量处理'],['app-video-input-v1','音视频'],['app-steps-input-v1','分步任务'],['app-product-scene-result-v1','生成结果'],['work-case-detail-v1','作品详情'],['workflow-detail-v1','工作流详情'],['circles-index-v1','圈子首页'],['circle-home-v1','电商圈子'],['circle-post-detail-v1','帖子详情']];
const packages:Record<string,string[][]>={
 b:[['项目说明','目标成果、先修条件、素材与检查点'],['过程教程','每步示例与常见卡点'],['个人尝试','草稿、自检与求反馈的问题'],['共学复盘','采用反馈、修改结果与后续练习']],
 c:[['作品与意图','作品本身、表达目标、开放讨论范围'],['具体研讨','引用画面或句段，提出有依据的回应'],['版本对照','作者采用、保留和放弃的选择'],['主题选集','多位作者的不同表达与讨论回顾']],
 d:[['方法条目','输入、依赖、许可、输出示例'],['版本说明','变化、适配条件与旧版入口'],['复现记录','不同素材下的结果和失败条件'],['维护提案','改进内容、贡献者与候选替代']],
 e:[['问题材料','目标、原素材、结果与已尝试做法'],['经验回应','建议依据、适用条件与需要补充的信息'],['尝试对照','几种办法的差异与实际尝试'],['采用反馈','提问者选择、仍有问题与相关讨论']],
};
export default async function Page({params}:{params:Promise<{id:string}>}){const {id}=await params;if(!names[id])notFound();const o=options.find(x=>x.code.toLowerCase()===id);const ev=evidence.find(x=>x.id===id);return <main className="op-shell pg-page"><header className="op-top"><Link href="/community-options">← 五套方案</Link><div><Link href="/research-achievements">研究成果</Link><Link href="/community-options/presentation">汇报演示</Link></div></header><nav className="pg-option-nav" aria-label="切换方案">{Object.entries(names).map(([key,name])=><Link key={key} href={'/community-options/proposals/'+key} aria-current={id===key?'page':undefined}>{key.toUpperCase()} · {name}</Link>)}</nav><section className="op-hero"><span>方案 {id.toUpperCase()} / {id==='a'?'概念方向已确认':'完整评审稿'}</span><h1>{names[id]}</h1><p>{o?.core_task||'围绕任务整理案例、方法与工具，让用户找到做法、尝试制作，再交流具体经验。'}</p><nav><Link href="#concepts">产品概念</Link><Link href="#journeys">用户路径</Link><Link href="#content">内容组织</Link><Link href="#operations">运营方式</Link><Link href="#choice">取舍与依据</Link></nav></section>
 <section id="concepts" className="op-section"><span>产品概念</span><h2>{id==='a'?'从发现到制作与交流':'围绕'+names[id]+'组织页面'}</h2><OptionGallery key={id} images={id==='a'?aImages.map(([key,title])=>({src:'/proposal-one/'+key+'.png',title,purpose:'已认可的方案一概念方向；图中数据与效果为设计示例。'})):o!.page_briefs.map((p,i)=>({src:'/proposal-options/'+((versions as Record<string,string>)[id+'-'+imageKeys[id][i]]||id+'-'+imageKeys[id][i])+'.png',title:p.page,purpose:p.purpose}))}/><p className="pg-caption">概念稿表达信息架构与使用方式。共同导航、六类应用详情、模型广场及个人入口沿用已确认基线；图片中的示例数据和效果不代表已上线能力。</p>{id!=='a'&&<Link href="/community-options/concept-overview" target="_blank" rel="noopener noreferrer">查看共用应用与基础页面 ↗</Link>}</section>
 <section id="journeys" className="op-section"><span>用户与路径</span><h2>{o?'为什么来，怎样继续':'三种起点，三条路径'}</h2>{o&&<p>{o.positioning}</p>}<div className="pg-three">{(o?.three_journeys||[{user:'不知道怎么做',path:'选择专题 → 看案例与做法 → 选择方法 → 进入制作',success:'根据自己的材料和用途找到适合的路径。'},{user:'知道要做什么',path:'找到应用 → 提供素材 → 生成与检查 → 保存成果',success:'直接完成制作，必要时继续编辑。'},{user:'做过但遇到问题',path:'查看相关教程 → 进入圈子 → 补充卡点 → 交流后继续尝试',success:'问题与原任务关联，用户决定是否采用建议。'}]).map(j=><article key={j.user}><h3>{j.user}</h3><ol>{j.path.split('→').map(step=><li key={step}>{step.trim()}</li>)}</ol><p>{j.success}</p></article>)}</div>{o&&<div className="op-table"><table><thead><tr><th>信息架构</th><th>承载内容</th></tr></thead><tbody>{o.information_architecture.map(([name,body])=><tr key={name}><th>{name}</th><td>{body}</td></tr>)}</tbody></table></div>}</section>
 <section id="content" className="op-section"><span>内容组织</span><h2>{id==='a'?'九类场景，先深入三类':names[id]+'需要哪些内容'}</h2>{o?<><div className="pg-four">{packages[id].map(([title,body])=><article key={title}><h3>{title}</h3><p>{body}</p></article>)}</div><div className="pg-samples">{Object.entries(o.content_samples).map(([key,body])=><article key={key}><span>{({ecommerce:'电商营销',writing:'写作编辑',creative:'创作表达'} as Record<string,string>)[key]}</span><p>{body}</p></article>)}</div><div className="op-table"><table><thead><tr><th>场景</th><th>组织建议</th></tr></thead><tbody>{o.nine_scene_strategy.map(([name,body])=><tr key={name}><th>{name}</th><td>{body}</td></tr>)}</tbody></table></div></>:<><p>电商营销、视觉设计和写作编辑优先主动编排，其余场景继续开放。电商专题串起案例、应用、教程、画布、工作流与讨论；写作则以原文、改动和作者取舍为中心。</p><div className="pg-four">{['案例：判断是否适合','方法：知道怎样做','工具：继续制作','讨论：交流具体卡点'].map(t=><article key={t}><h3>{t}</h3></article>)}</div><Link href="/community-options/content-plan">查看九类布局与内容样板 →</Link></>}</section>
 <section id="operations" className="op-section"><span>运营方式</span><h2>{id==='a'?'平台编排，作者贡献，圈子交流':'谁提供，谁组织，谁维护'}</h2><p>{o?.author_supply||'平台编辑负责选题、邀请与专题编排；作者提供专业内容；应用维护者处理资源问题；圈子主持人整理问题并邀请相关回应。实际承接范围由人员和合作约定决定。'}</p>{o?<OptionOperations id={id}/>:<Link href="/community-options/operation-plan">查看供给、参与与维护建议 →</Link>}<p className="pg-caption">这里描述建议分工，具体合作、回应范围与维护承诺须由实际承接者确认。商业逻辑暂缓。</p></section>
 <section id="choice" className="op-section"><span>取舍与依据</span><h2>选择这套方案，意味着什么</h2><div className="op-callout"><p>{o?.tradeoffs||'优先把任务、案例和制作资源组织清楚，需要编辑与实践作者持续供给。若内容只重复原工具教程，应减少重复整理，转向具体品类与条件比较。'}</p></div>{o&&<ul className="pg-checks">{o.key_validations.map(text=><li key={text}>{text}</li>)}</ul>}{o&&<><h3>怎样检验这个选择</h3><p>{o.decision_record}</p></>}{ev&&<><h3>已有研究提供的参照</h3><p>{ev.evidence}</p><p className="pg-caption">{ev.limit}</p><div className="pg-links">{ev.sources.map(s=><Link key={s.href} href={s.href} target="_blank" rel="noopener noreferrer">{s.label} ↗</Link>)}</div></>}</section><footer className="op-footer"><Link href="/community-options#compare">回到五套方案比较 →</Link> · <Link href="/community-options/library">研究依据 →</Link></footer></main>}
