import type { Profile, Source } from './research-types';
const s=(title:string,url:string,date:string,note:string,type='官方'):Source=>({title,url,date,note,type});
export const globalProfiles: Profile[] = [
{
 id:'civitai',name:'Civitai',group:'创作与资源',focus:'资源归因 · 作者回报与分配争议',thesis:"Civitai通过作品关联模型与参数，并提供作者回报机制。资源能否复用、收益如何分配，以及维护成本，需分别核对。",
 job:'模型／LoRA 作者分发资源；创作者复现风格并展示衍生作品。',object:'模型、作品、参数关联、文章、合集和挑战',first:'发现作品或模型 → 理解参数 → 兼容生成／下载 → 发布并归因',supply:'使用补偿、打赏、许可费、付费访问和抢先体验；条件各不相同',repeat:'资源更新、创作任务、协作策展与主题挑战（机制推断）',business:'计算与会员；部分 Buzz 可进入作者收益池，非固定兑换率',relevance:"原作、资源版本、复用结果与作者归因",notCopy:'多种积分、动态结算池及多重付费墙。',experiment:"围绕一种风格组织作品、资源和版本说明，记录收藏回看、讨论与复用；作者报酬和维护约定单列，不以下载或付款作为社区活跃门槛。",access:'官方公告已由游客浏览器读取并确认 Official 标识；其他部分依据官方 GitHub 实现文档，不等于已测所有线上账户。',
 sections:[
 {title:'核心对象不是一篇普通帖子',status:'事实',paragraphs:['官方仓库将模型分享、发现和交流改进写为产品目标。资源关联文档说明作品可以关联所用模型与 LoRA，支持归因和按资源找作品。公开导航还包括图像、视频、文章、合集及挑战。','因此结果既是内容，也是资源适用性的证据。首次生成与 Remix 有引导，但只在支持的媒体和资源组合上出现；没有验证所有作品都能一键重现。'],refs:[1,3,4]},
 {title:'作者价值与收费对象',status:'事实',paragraphs:['官方资料区分在线使用补偿、打赏、每次生成的许可费、解锁模型的付费访问，以及到期后开放的抢先体验。这些行为对应不同价值，不应合成“发图分成”。','Creator Program 文档描述合格作者按月将可结算 Buzz 存入收益池，再按份额分配。不同 Buzz 用途和可结算资格不同，免费奖励不能直接视为可提现收入；代码中的默认资金池值也不是实际发放规模。'],refs:[5,6,7]},
 {title:'收益规则的公开争议',status:'边界',paragraphs:['8 月官方提案坦承计算补偿时曾把部分附加收费纳入，提出调整并改变许可费限制。浏览器页面明确标为提案，不能将全文当成已生效政策。9 月更新的实现文档只交叉确认部分许可费规则已调整。','提案解释了共享池对作者回报的影响；另有作者公开抱怨收入下降，但只是个案。两类材料都提醒我们关注作者可预测收入，无法计算作者流失或实际平均收益。'],refs:[2,5,10]},
 {title:'协作和再创作的运营路径',status:'事实',paragraphs:['8 月 Creator Collab 公告确认协作合集、改作投稿等机制：作者可以审核，投稿被采用后获得面向原作者受众的展示。双倍奖励是有期限的活动，不宜当永久权益。','官方挑战文档还区分系统、运营与用户发起的挑战；用户创建部分仍受分批开放控制。功能存在与全量开放、形成留存是三个不同判断。'],refs:[8,9,11]},
 {title:"内容组织与投入条件",status:'建议',paragraphs:['官方新手引导文档承认生成页中的条款、成本和排队不易理解。社区既要展示效果，也要让人知道复用需要什么、何时收费、谁负责资源维护。','MakeNow 可先人工连接原作、方法、复现结果与作者答疑。多元拾光还没有供给与稳定案例，先建设收益池无法解决这一缺口；固定报酬采购小样更容易控制成本与验收。'],refs:[4]}
 ],gaps:['最初核心作者的招募过程与成本，资料不足。','补偿提案所有条款的线上执行状态未核。','真实结算资格、收入分布和社区留存增量未验证。'],sources:[s('Civitai 官方仓库','https://github.com/civitai/civitai','访问 2026-09-08','产品目标；不以 Star 数当活跃'),s('Creator Compensation 调整提案','https://civitai.com/articles/33749/proposal-fixing-creator-compensation-and-leveling-up-licensing-fees','浏览器显示 2026-08-11','官方原页实读；时区可能差一天；仍明确为提案'),s('Image Resource Tracking','https://github.com/civitai/civitai/blob/main/docs/features/image-resources.md','未标发布日期','作品资源关联','官方实现文档'),s('Guided Tours','https://github.com/civitai/civitai/blob/main/docs/features/guided-tours.md','未标发布日期','首效路径、兼容性与新手摩擦','官方实现文档'),s('Monetization Rules','https://github.com/civitai/civitai/blob/main/docs/features/monetization-rules.md','含 2026-09-04 更正','许可费与付费对象；不替代线上法律条款','官方实现文档'),s('Creator Program','https://github.com/civitai/civitai/blob/main/docs/features/creator-program.md','未标发布日期','收益池与结算机制','官方实现文档'),s('Buzz Accounts','https://github.com/civitai/civitai/blob/main/docs/features/buzz-accounts.md','未标发布日期','奖励与可结算资源的区别','官方实现文档'),s('Collaborative Collections','https://github.com/civitai/civitai/blob/main/docs/features/collaborative-collections.md','未标发布日期','策展邀请与投稿审核','官方实现文档'),s('Challenge Platform','https://github.com/civitai/civitai/blob/main/docs/features/challenge-platform.md','未标发布日期','挑战类别，用户创建分批开放','官方实现文档'),s('作者关于 Yellow Buzz 的反馈','https://www.reddit.com/r/civitai/comments/1t6wemi/severe_drop_in_yellow_buzz_compensation_recently/','2026-05-08','单一收入体验，未核交易','用户讨论'),s('Creator Collab Update','https://civitai.com/articles/33872/the-creator-collab-update-4-new-ways-to-get-seen-and-earn','浏览器显示 2026-08-20','官方原页实读，协作与改作展示')]
},
{
 id:'seaart',name:'SeaArt',group:'创作与资源',focus:'多类作者激励 · 模型选择与复用',thesis:"SeaArt同时容纳资源、应用与作品作者；内容筛选、同质化和不同收入分配规则增加了运营工作。",
 job:'兴趣及内容创作者出图出片；模型、应用与角色作者分发能力。',object:'模型、AI 应用／工作流、角色和生成作品',first:'作品详情看参数 → Remix／图生图 → 编辑 → 选择公开分享',supply:'原创模型、应用、角色分池激励；徽章、精选及合作',repeat:'生成任务、主题活动、角色与资源更新（机制推断）',business:'免费体力、会员和点数；作者按贡献结算',relevance:"案例用途、参数展示与复现反馈",notCopy:'三池分账、数字人及全部自动任务体系。',experiment:"对同一主题发布有差异的作品、角色表达与过程，观察用户连续两周的观看、评论、收藏回看和尝试；不靠重复泛风格图铺量。",access:'官方指南与 2.0 公告可读；未登录核精确体力、有效期和真实结算。用户投诉仅作为待复核线索。',
 sections:[
 {title:'从作品到下一次创作',status:'事实',paragraphs:['基础指南给出浏览作品、查看提示词与模型、Remix 或图生图、生成、编辑及分享的过程；模型详情可应用推荐参数。普通用户可从已知效果开始，作者不必为每个使用者重新教学。','2026 年 6 月的 2.0 公告提出多模态入口、模型详情与作者数据改进，并直接承认过去选模型困难、跨工具下载上传有摩擦。公告证明其要解决的问题，不证明每项改进实际提高了效率。'],refs:[1,2,5]},
 {title:'作者供给不是统一的发帖奖',status:'事实',paragraphs:['创作者计划将原创模型、AI 应用和角色分别计算贡献，结合下载、使用、分享和衍生创作；原创标记、审核及月度结算有明确要求。FAQ 还有最低提现门槛，不能将账面奖励直接当即时现金。','除了现金，还有原创徽章、首页精选、首发或独家合作与内测机会。奖励分配包含新鲜度和动态贡献，作者收益难仅凭一次作品表现预测。'],refs:[3,4]},
 {title:'任务奖励与消费边界',status:'边界',paragraphs:['平台使用每日、每周及一次性任务、站内和 Discord 活动；免费体力与会员、点数并存。不同语言资料的体力数额不一致，本报告不提供统一免费额度。','旧指南说部分点数不过期，而可见公告对新购与赠送资源另有有效期，且帖龄与正文年份不一致。规则存在待核冲突，不能给用户“永不过期”的承诺。'],refs:[1,7]},
 {title:'同质化供给的反证',status:'边界',paragraphs:["一则用户讨论抱怨作者在 SeaArt 与 Civitai 发布相似资源；评论也反问平台提供了什么独特价值，值得作者限制其他渠道分发。另有深链与精选体验投诉，未重现，不能写成当前全站缺陷。",'它提出了适用于多元拾光的问题：用户在别处也能看到同样效果时，为什么还来？可复现资料、明确用途、及时答疑、低试错成本，都是待验证的答案；更便宜或更多图本身未必足够。'],refs:[6]},
 {title:'UI／UX 与运营取舍',status:'建议',paragraphs:["作品详情可展示适用范围、参数和操作入口。先按用途整理案例并观察采用情况，再决定是否分别经营模型、角色和应用供给。",'作者报酬先购买过程包、复现与必要修改；点赞、浏览用于辅助分发，有效采用与失败反馈才适合帮助判断下一份内容。']}
 ],gaps:['实际奖励池、作者中位收入与独家合作成效，资料不足。','当前精确体力和资源有效期尚有公开规则冲突。','初始作者来源及社区净留存未验证。'],sources:[s('基础页面指南','https://docs.seaart.ai/guide-1/1-seaart-ai-basic-page','未标绝对更新日','首用路径、任务与分享'),s('模型功能指南','https://docs.seaart.ai/guide-1/2-seaart-ai-basic-function/2-6-models','未标绝对更新日','模型推荐参数与 Remix'),s('创作者激励计划','https://docs.seaart.ai/guide-1/6-permanent-events/seaart.ai-creator-incentive-program','含 2025-03 规则起点','三类供给、贡献计算、合作及审核'),s('激励计划 FAQ','https://docs.seaart.ai/guide-1/6-permanent-events/seaart.ai-creator-incentive-program/creator-incentive-program-faq','未标绝对更新日','结算与原创条件'),s('SeaArt AI 2.0 公告','https://www.seaart.ai/blog/seaart-ai-2-0-introducing','2026-06-18','产品演化及自述摩擦，不采用示例规模'),s('用户讨论：平台与 Civitai 的区别','https://www.reddit.com/r/SeaArtAI/comments/1odm8cq/to_all_creators_on_sea_art_make_the_site/','帖龄显示不一致；不定绝对日期','同质化与分发价值的个案线索','用户讨论'),s('Credit Validity 调整公告线索','https://www.reddit.com/r/SeaArtAI/comments/1rrljyk/notice_regarding_seaart_credit_validity_rule/','帖龄与正文年份冲突','SeaArt_Ai 账号发布；仅作规则冲突提示','账号公告／待核')]
},
{
 id:'openart',name:'OpenArt',group:'工具与作者生态',focus:'从图片灵感走向连续故事',thesis:"OpenArt的官方回顾将角色一致性需求与故事产品的发展联系起来。连续任务如何影响使用与付款，还需用户记录。",
 job:'创作者制作连续角色、音乐视频、解释视频及故事内容。',object:'灵感图、带参数作品、角色和 Story 内容',first:'发现效果 → 查看参考与参数 → Remix → 改成自己的故事',supply:'UGC 上传、Creative Partner 合作与 Affiliate 引荐各有分工',repeat:'同角色下一镜、下一集与后期修改（机制推断）',business:'分级订阅、生成资源与故事／角色配额；活动有期限',relevance:"连续创作任务与合作作者交付",notCopy:'完整多模态故事套件与未经验证的角色一致性承诺。',experiment:"比较连续角色作品系列和单次趣味作品两种内容节奏，提供可选幕后与尝试入口；分别记录观看者和制作参与者的次周回访。",access:'官方创始故事、合作页、定价与公开作品详情可读；Help 部分只读到问题标题，未测试复制和实际生成。',
 sections:[
 {title:'一个有启发的需求转向',status:'历史',paragraphs:['2026 年官方回顾称，团队最初做带提示词的图片浏览站，并通过 Hacker News 分享。后来用户反复要求角色一致性；继续追问后，团队发现他们想讲故事，遂扩展图像、视频、角色和音频能力。','这是官方对早期演化的自述，未独立核对最初 HN 帖子，也不采用同文的收入与活跃数字作为审计事实。可学的是追问目的，不能假设多元拾光的用户也一定需要同一种故事工具。'],refs:[1]},
 {title:'内容携带生成上下文',status:'事实',paragraphs:['公开作品详情可见提示词、参考图、模型、时长、比例、分辨率和音频选项，以及 Remix 入口。Story 社区按音乐视频、解释视频、角色 vlog 等任务组织发现。','这些入口降低从观看到创作的启动成本，但未登录验证参数能否完整复制。关于页也区分用户上传的 Discovery 和可能来自互联网抓取的图片搜索，不能把所有搜索结果都算原创社区供给。'],refs:[2,3]},
 {title:'作者合作与引荐分开计量',status:'事实',paragraphs:['Creative Partner Program 面向创作者、教育者与专业人士，提供资源、提前体验、官方展示及优先合作机会，并要求伙伴身份与回链等披露。Affiliate 则围绕引荐新订阅产生佣金，不是发帖分成。',"CPP 页的 Creative Fund 仍标 Coming Soon；不能写成已经发放。分销完整外链条款未读到，因此不承诺固定佣金或收益。"],refs:[4,5]},
 {title:'商业与生成局限',status:'边界',paragraphs:['定价按订阅、资源、并发、角色和故事等条件区分；调研当天还存在限时模型活动，不能将促销当永久无限权益。免费额度、隐私与退款的展开回答未完整读取。','官方长视频文章也承认跨镜头人物、服装、光照连续和后期组装是难点。成片、同款入口与稳定生产三者需要分别验证。'],refs:[6,7,8]},
 {title:'产品与运营的适用条件',status:'建议',paragraphs:['如果用户说“希望结果一致”，访谈还需要问：哪些对象需要一致、连续几次、拿去哪里、现在怎么补救、下一次什么时候发生。回答有机会把泛创作爱好区分成具体任务。','合作也应拆分：案例采购交付可用方法，渠道引荐带来合格用户，研究访谈暴露需求。给同一个作者多种权益时，仍分别验收这些价值。']}
 ],gaps:['最初获客成本与真实留存，资料不足。','公开作品的复制完整性和连续出品成功率未测。','伙伴平均收益及 Creative Fund 正式开放时间未核。'],sources:[s('The OpenArt Story','https://openart.ai/blog/the-openart-story/','2026-03-16','Emily Watterson，官方早期演化自述'),s('About OpenArt','https://openart.ai/about','未标更新日','上传内容与互联网搜索的区别'),s('公开作品：Cherry Sweet','https://openart.ai/suite/inspire/feed/p/248efc71b3155a2b95a59bfdd1bb7549','访问 2026-09-08','参数、参考与 Remix 实页','公开作品'),s('Creative Partner Program','https://openart.ai/programs/cpp','访问 2026-09-08','合作权益、披露与 Fund 待上线'),s('Affiliate Program','https://openart.ai/programs/affiliate','未标更新日','引荐订阅，完整外链条款未读'),s('Pricing','https://openart.ai/pricing','访问 2026-09-08','当前配额结构与限时活动'),s('Help Center','https://openart.ai/suite/help-center','访问 2026-09-08','部分答案采集受限'),s('官方长视频制作文章','https://openart.ai/blog/best-ai-video-generators-for-long-videos/','2026-07-23','只取连续性与后期难点，不采用竞品排名')]
},
{
 id:'nightcafe',name:'NightCafe',group:'创作与资源',focus:'兴趣创作 · 主题与评审仪式',thesis:"NightCafe的主题创作和反馈可能带来表达、参与与被认可的价值，相关使用记录主要属于兴趣创作。",
 job:'普通创作爱好者表达想法、参加主题创作并获得反馈。',object:'作品、Evolve 衍生链、主题挑战及聊天室',first:'选主题／作品 → 创作 → 投稿 → 评审和结果反馈',supply:'普通成员、活动参与者与成员主持的挑战共同供给',repeat:'下一主题、投票结果、同伴认可与创作习惯（机制推断）',business:'赚取 Relax 资源与购买 Fast 资源并存；订阅和增购',relevance:"创作主题、结果反馈与兴趣参与",notCopy:'复杂等级、每日竞赛、大量投票与全套任务系统。',experiment:"每周一个可观看、讨论或选做的题目，由运营主持回应；比较下一周再次观看、交流和投稿的人数，领奖行为单列，互评不设强制次数。",access:'官方挑战与积分相关帮助可读；未参加活动或领取资源。新旧免费资源说明有冲突。',
 sections:[
 {title:'价值可以是参与和表达',status:'事实',paragraphs:['官网强调让非专业艺术家也能创作。成员挑战可以规定主题、模型或上传限制、投稿时间与投票阶段，形成创作、评审、公布结果的节奏；平台也提供官方每日主题。',"内容对象不只是图片，还有作品之间的演化、参与某个主题的关系和小组对话。对于兴趣用户，这些关系可能比交付商业素材更重要，但没有测量其真实贡献。"],refs:[1,2,3]},
 {title:'供给者逐步成为组织者',status:'推断',paragraphs:['成员能够举办挑战，意味着活跃参与者有机会承担题目与组织角色。平台无需由少数编辑写出全部内容，但仍需规则、反作弊、资格判断及争议处理。',"可先评估成员出题与轮流点评；运营仍需安排规则、进度和争议处理。"],refs:[2,3]},
 {title:'奖励嵌在行为中',status:'事实',paragraphs:['当前帮助区分赚取的 Relax 与购买的 Fast，排队与并发条件不同。2025 年一项历史更新把奖励绑定到参赛并完成评审，而非只登录领取。','免费日常资源的帮助页存在新旧差异：有页面强调先创作再领取，另有旧页面描述通知领取。本报告不提供一个声称全账户通用的日赠数额。'],refs:[4,5,7,8]},
 {title:'商业与复访的解释边界',status:'边界',paragraphs:['订阅、资源增购及部分模型的无限使用有具体条件；某些操作仍会消耗资源。“无限”不意味着每个模型和选项都免费。社区反馈中也有积分有效期变化引发的不满，不能据单帖推算流失率。','日复一日参赛可能是稳定兴趣，也可能主要受奖励或排名驱动。多元拾光要观察活动外是否继续创作、会否带自己的题目、是否愿意花时间帮助别人。'],refs:[6,9]},
 {title:'UI／UX 与多元拾光的选择',status:'建议',paragraphs:['主题、截止时间、投稿条件、投票进度和结果，是组织行为的清晰信息结构。比单纯的瀑布流多出的价值是“这次参与什么，以及如何得到反馈”。','若多元拾光选择工作任务人群，每日趣味竞赛未必匹配；若选择兴趣社群，应明确成功指标是持续创作和有内容的互动，不必强行以商业付费证明所有价值。']}
 ],gaps:['不同挑战参与者在停止额外奖励后的回访，资料不足。','当前全账户免费资源规则存在帮助文档差异。','活动组织和治理的人力成本、兴趣人群付费结构未核。'],sources:[s('About NightCafe','https://nightcafe.studio/pages/about-nightcafe','未标日期；含 2019 起步回顾','产品愿景与 Reddit 分享历史自述'),s('创建成员挑战','https://help.nightcafe.studio/portal/en/kb/articles/creating-a-game-community-challenge','未标更新日','主题、投稿及组织权限'),s('Daily Challenge 资格与排名','https://help.nightcafe.studio/portal/en/kb/articles/daily-challenge-eligibility-rating-ranking','未标更新日','资格、评审与反作弊'),s('PRO 用户免费资源','https://help.nightcafe.studio/portal/en/kb/articles/do-i-still-get-free-credits-if-i-go-pro','访问 2026-09-08','创作与领取路径；与旧说明对照'),s('Fast 与 Relax Credits','https://help.nightcafe.studio/portal/en/kb/articles/fast-credits-vs-relax-credits','未标更新日','资源用途和等待条件'),s('无限模型仍扣点的条件','https://help.nightcafe.studio/portal/en/kb/articles/why-am-i-being-charged-credits-on-an-unlimited-model','未标更新日','订阅的使用边界'),s('Daily Competitor 更新','https://nightcafe.studio/blogs/blog/updates-earn-5-credits-everyday-new-video-models-more','2025-03-23','历史参赛和评审奖励'),s('旧免费积分说明','https://help.nightcafe.studio/portal/en/kb/articles/free-credits-questions','未标更新日','与较新帮助存在差异，不定统一数额'),s('用户对更新的讨论','https://www.reddit.com/r/nightcafe/comments/1qzw54q/what_do_you_think_about_the_recent_update/','公开帖；精确日期未核','有效期与使用体验个案','用户讨论')]
},
{
 id:'midjourney',name:'Midjourney',group:'工具与作者生态',focus:'公开作品发现 · 风格收藏',thesis:"Midjourney将公开生成结果用于发现与风格收藏，部分内容随制作产生。工具效果与后续创作需求仍是供给前提。",
 job:'影像创作者探索风格、生成并组织自己的作品。',object:'图像／视频、提示词、Style code、作品集和 Moodboards',first:'浏览 Explore／风格 → 订阅生成 → 复用提示和参考 → 整理资产',supply:'默认公开的生成作品、作者展示与提示经验；未见普遍发图现金分成',repeat:'下一次创作、审美积累、风格与项目组织（机制推断）',business:'订阅、计算时间与隐私分档；研究任务换 Fast 时间',relevance:"生成上下文、收藏与再次使用",notCopy:'自身缺乏独有能力时照搬付费先行、邀请稀缺感或日评分竞赛。',experiment:"围绕一个风格或故事主题编选作品和过程，保留收藏与相关内容入口；下一周记录收藏回看、系列观看、讨论和可选复用。",access:'官方网站、个人档案、生成和资源文档及 Discord 合作案例可核；会员生成与登录后的个人档案未测。',
 sections:[
 {title:'发现会进入个人创作资产',status:'事实',paragraphs:['网站概览介绍 Explore 的推荐、随机、热门与排名；作品详情可复用图像、文本或寻找相似内容。Style Explorer、Likes、Moodboards 和 Personalization 将灵感逐步连接到个人偏好和后续创作。','资料页可以策展作品，但档案只对登录成员可见，关注列表与数量有隐私限制。不能假设公开分享链接对游客完整展示所有社交信息。'],refs:[1,5]},
 {title:'生成本身形成一部分供给',status:'事实',paragraphs:['创作默认公开，作者不必再写一篇帖子才进入发现体系。需要保密的用户要考虑特定套餐的 Stealth；在共享 Discord 频道中的内容仍有可见边界。','新手指南的生成起点是登录并订阅，网站与 Discord 没有通用免费试用。这意味着这里的付费门槛依赖工具吸引力，不能直接作为尚无稳定案例的新社区冷启动模板。'],refs:[2,3,6]},
 {title:'早期社群选择与邀请',status:'历史',paragraphs:['Discord 的合作案例回顾，团队先测试用户偏好的交流方式，再从小型邀请测试扩大，并曾让付费订阅者邀请朋友。它说明平台选择与早期互动设计是有意为之。','这是合作方回顾，不能从今天的规模倒推出邀请机制的单独效果，也没有多元拾光能直接沿用的种子获客成本。'],refs:[7]},
 {title:'积分回报与复访理由',status:'事实',paragraphs:['评分任务可以获得 Fast 时间，但奖励有参与量、有效订阅和到期条件；它更像研究反馈换资源，不是无条件签到。外部社群还组织 office hours、项目交流和提示词讨论。',"工具需求、审美积累和同行帮助可能支持反复使用；未找到独立于生成产品的社区留存数据，也没有普遍发图现金奖励的确证。"],refs:[4,9]},
 {title:'UI／UX 的实质改进',status:'建议',paragraphs:['官方迁移说明指出聊天消息流不便检索、组织和整理，Web 侧改进项目与作品管理。这提醒多元拾光：聊天适合反馈，案例需要稳定可找的归档，两者解决不同问题。','MakeNow 的分享复制可以围绕已完成的任务积累，而社区提供发现、作者说明和答疑。先用人工目录检验用户真的回来找方法，再决定更完整的收藏与组织能力。'],refs:[8]}
 ],gaps:['邀请制的独立增长效果与作者持续贡献分布，资料不足。','付费用户中有多少因社区而回访，资料不足。','登录后的完整复用与隐私界面未测。'],sources:[s('Website Overview','https://docs.midjourney.com/hc/en-us/articles/33329460426765-Website-Overview','未标更新日','发现、复用及个人资产'),s('Getting Started','https://docs.midjourney.com/hc/en-us/articles/33329261836941-Getting-Started-Guide','未标更新日','订阅先于生成'),s('Comparing Plans','https://docs.midjourney.com/hc/en-us/articles/27870484040333-Comparing-Midjourney-Plans','访问 2026-09-08','套餐与隐私分档'),s('Earning Free Fast Time','https://docs.midjourney.com/hc/en-us/articles/28014817524109-Earning-Free-Fast-Time','未标更新日','任务奖励与到期条件'),s('Profiles','https://docs.midjourney.com/hc/en-us/articles/41117938447629-Profiles','未标更新日','策展、登录可见与关注隐私'),s('Keeping Creations Private','https://docs.midjourney.com/hc/en-us/articles/28014645615373-Keeping-Your-Creations-Private','未标更新日','默认公开与共享频道边界'),s('How Midjourney Built a Business on Discord','https://discord.com/build-case-studies/midjourney?directory=true','未标发布日期','用户测试与邀请历史','官方合作案例'),s('Transitioning to Web','https://docs.midjourney.com/hc/en-us/articles/41268334793613-Transitioning-to-Web','未标更新日','聊天信息与创作资产组织的摩擦'),s('官方 Discord 目录','https://discord.com/servers/662267976984297473','访问 2026-09-08','office hours、项目与提示交流')]
},
{
 id:'leonardo',name:'Leonardo.Ai',group:'工具与作者生态',focus:'专业案例合作 · 过程材料采购',thesis:"Leonardo通过专业作者合作提供案例和过程材料。现行合作入口与历史基金分别适用，不能合并为持续补贴。",
 job:'设计、营销、插画及影像创作者生成和编辑生产素材。',object:'作品、提示词、参考、个人 Library 与 Community Feed',first:'看社区作品 → 复制提示／Remix／参考 → 编辑并保存',supply:'普通公开作品、精选 Creator Program 与历史创作基金',repeat:'素材生产、编辑需求和案例学习（机制推断）',business:'会员资源、增购及限定慢速使用；公开与隐私条件分档',relevance:"合作作者筛选、过程材料与复现验收",notCopy:'大额基金、广泛资源赠送和未经验证的案例放大。',experiment:"采购作品与制作说明，先明确哪些仅供欣赏、哪些支持学习或复用；用后续内容和问题回应观察目标用户回访，复现只验有制作承诺的部分。",access:'官方帮助、Creator Program FAQ 与基金页可读；社区内会员操作和收入未测。',
 sections:[
 {title:'社区与工作资产相连',status:'事实',paragraphs:['官方商业使用和生成帮助确认 Community Feed 及个人 Library 的角色。用户可以从公开作品复用提示或参考，进入生成、放大、编辑或视频等操作，再保存或分享。',"因此它既有展示也有工具使用，不应只按外部 Discord 生态理解。具体复制效果和跨模型结果一致性，未通过生成验证。"],refs:[1,2,3]},
 {title:'专业作者合作的条件',status:'事实',paragraphs:['Creator Program 提供专属社群、订阅资源、提前访问及展示机会，属于筛选后的作者关系。2026 年 3 月 FAQ 明确申请暂停，保留候补；不能将该页存在理解为正在公开招募。','对于多元拾光，这类计划的价值在于专业作者与产品持续反馈，而非只发送一笔资源。作者是否能教会别人、愿否反馈失败，比粉丝数更接近当前供给缺口。'],refs:[5]},
 {title:'历史基金究竟购买什么',status:'历史',paragraphs:['2025 Imagination Fund 要求在限定周期完成作品及幕后过程等材料，申请窗口已经结束。这可以说明资助怎样转成可传播、可学习的内容，不能视为当前可申请权益。','用专业作者做出的展示证明工具可能完成某事，但仍可能包含高水平人工整理。多元拾光的案例验收需要同时看成品与别人能否复做。'],refs:[6]},
 {title:'免费、会员与隐私',status:'边界',paragraphs:['免费资源有日周期条件，付费资源涉及月度、结转或增购规则；部分第三方模型与慢速使用有额外限制。不同资源不能用一个“免费无限”的句子概括。',"公开与私密也和账号计划相关，FAQ 对删除生成图片存在订阅资格说明。对于涉及客户素材的人群，是否愿意公开过程可能直接影响内容供给；未实际测试删除或私密设置。"],refs:[1,4,7]},
 {title:'UI／UX 与复访判断',status:'建议',paragraphs:['用户一边管理自己的工作，一边从社区寻找方法，这种连接比额外要求大家发帖更自然。但频繁生成不必然带来互助和交流，应将工具复访与社区行为分别记账。','多元拾光可先把一个合作案例做成完整生产记录，让看过的人带真实素材尝试。若案例只带来观赏而无人采用，应调整任务选择或教学方式，再决定是否扩招作者。']}
 ],gaps:['Creator Program 恢复公开申请的时间未核。','历史基金实际成效和普通作者收入，资料不足。','社区对工具留存的独立作用与过程复制成功率未测。'],sources:[s('Frequently Asked Questions','https://intercom.help/leonardo-ai/en/articles/7051613-frequently-asked-questions','2026-02-16','产品、资源及账户条件'),s('Commercial Usage','https://intercom.help/leonardo-ai/en/articles/8044018-commercial-usage','未标绝对更新日','Community Feed 与公开内容使用语境'),s('How to Generate Images','https://intercom.help/leonardo-ai/en/articles/8942360-how-to-generate-images-with-leonardo-ai','未标绝对更新日','生成与操作路径'),s('Tokens FAQ','https://intercom.help/leonardo-ai/en/articles/9044700-tokens-frequently-asked-questions','访问 2026-09-08；显示相对更新时间','不同资源与订阅边界'),s('Creator Program FAQ','https://intercom.help/leonardo-ai/en/articles/9003169-leonardo-creator-program-faq','2026-03-03','当前暂停申请、候补及作者权益'),s('Imagination Fund','https://www.leonardo.ai/leonardo-imagination-fund','2025-09 至 10 月申请；已结束','历史作品与过程材料要求'),s('Private & Public Images','https://intercom.help/leonardo-ai/en/articles/8044029-private-public-images','未标绝对更新日','隐私与账户条件，未实操')]
},
{
 id:'runway',name:'Runway',group:'工具与作者生态',focus:'影像作者项目 · 工作流分享与复制',thesis:"Runway将作品、幕后、工作流和作者合作联系到影像制作。与MakeNow较接近的是方法分享与项目材料，影展另需组织及分发资源。",
 job:'影视、广告与专业影像创作者制作镜头、短片和项目。',object:'影像作品、Workflows、Apps、幕后教程与赛事',first:'学习案例／打开共享工作流 → 登录复制 → 换输入生成',supply:'精选 Creative Partners、作品征集、挑战和项目合作',repeat:'真实项目、后期修改、工作流复用与同行帮助（机制推断）',business:'试用、订阅和增购；团队／API；推荐奖励绑定付费深度',relevance:"工作流分享、使用条件与作者成本",notCopy:'影展基金、专业发行网络和大额品牌项目。',experiment:"用一段作品、幕后片段和创作讨论形成连续内容，观察观看与回应后的回访；确有接手需求时，再以重建困难判断画布分享投入。",access:'官方 Workflow、合作、资源和计费帮助可读；未登录共享工作流、申请计划或生成。历史基金入口已重定向。',
 sections:[
 {title:'工具内外共同形成生态',status:'事实',paragraphs:['官方资源页连接 Academy、用例、Discord 答疑、直播、线下活动、作品展示和 CPP。它的专业社区不是单个站内内容流，而是围绕作品与职业成长的多种关系。','Workflow 文档已经给出分享链接、接收者登录查看、Make a copy 继续创作；共享的是输入资产，不含节点输出，企业有额外公开设置。另可封装为 App 固定部分参数，服务工作区复用。'],refs:[2,3,12]},
 {title:'合作作者获得什么',status:'事实',paragraphs:['Creative Partners Program 通过作品集与加入理由筛选，提供 Max、提前体验、合作与专属活动。当前页面明确没有固定时间投入要求，不能把它误写成月交稿合同或统一现金补贴。','对多元拾光则需要相反地把采购交付写清：目前要解决的是没有可用案例，若只给身份和资源，不能保证得到可验收的内容。'],refs:[1]},
 {title:'赛事和基金的历史边界',status:'历史',paragraphs:["读取的 GEN:48 条款属于 2025 年一届，规定制作时间、影片长度、工具使用比例、技术说明及评审。2024 Hundred Film Fund 是历史启动公告，当前基金入口已转向 Studios。",'这些资料能说明如何把资源支持换成创作与过程展示，不能证明今天仍开放相同申请，也不能把计划投入金额当实际拨款。'],refs:[4,5,6]},
 {title:'付费与成片质量的现实',status:'边界',paragraphs:['帮助文档区分一次性试用、订阅与增购，并公布 2026 年以 Max 替代 Unlimited 的迁移安排，不能沿用旧无限套餐。推荐奖励要求双方持续付费一段时间，明显区别于注册即赠。','官方退款说明指出，生成成功但用户不满意并不自动退资源。导演幕后案例也出现重试、改风格、外部修图和补镜头，证明精选成片背后存在人工生产工作。'],refs:[7,8,9,10,11]},
 {title:"内容组织与投入条件",status:'建议',paragraphs:['链接分享和复制降低接手别人的方法的成本，但输入、输出、权限、依赖与隐私需要向使用者讲清。MakeNow 将来开发复制时，应先以真实交接任务判断最少需要带走什么。','一名合作作者、一个小项目、一份幕后说明和一次答疑，可提供初步的供需反馈。不必同时仿建影展基金和作者平台。']}
 ],gaps:['共享流程的完整运行成功率未测。','CPP 作者实际交付、平均收益及社区转化，资料不足。','基金现行申请与实际拨款未核；赛事所读为历史届次。'],sources:[s('Creative Partners Program','https://runway.com/creative-partners-program','访问 2026-09-08','当前权益和不强制时间投入'),s('Runway Resources','https://help.runwayml.com/hc/en-us/articles/37464713358099-Runway-Resources','未标更新日','学习、答疑与作者生态入口'),s('Introduction to Workflows','https://help.runwayml.com/hc/en-us/articles/45763528999699-Introduction-to-Workflows','未标更新日','分享、复制及输入／输出限制'),s('GEN:48 Official Rules','https://runway.com/gen48/terms','所读为 2025-08-23 至 25 日届次','历史赛事，不代表当前招募'),s('Hundred Film Fund 发布','https://runway.com/news/hundred-film-fund','2024-09-26','历史资金计划，不等于已拨付'),s('原基金入口','https://runway.com/hundred-film-fund','2026-09-08 重定向 Studios','现行开放状态未确认'),s('How Do Credits Work','https://help.runwayml.com/hc/en-us/articles/15124877443219-How-do-credits-work','未标更新日','一次试用、订阅与增购'),s('Which Plan Is Right for Me','https://help.runwayml.com/hc/en-us/articles/21664961171475-Which-plan-is-right-for-me','含 2026 迁移安排','Max 与旧 Unlimited 区别'),s('Referral Codes','https://help.runwayml.com/hc/en-us/articles/45681304402707-How-do-I-use-referral-codes','未标更新日','奖励绑定持续付费'),s('Credit Refunds','https://help.runwayml.com/hc/en-us/articles/34266159290003-Can-I-have-credits-refunded','未标更新日','质量不满意与生成错误的区别'),s('Gabe Michael：48 小时制片过程','https://runway.com/customers/48-hours-to-generate-a-film','历史案例；未标绝对发布日期','精选个案中的重试与人工工作'),s('Publishing Workflows as Apps','https://help.runwayml.com/hc/en-us/articles/47865876793747-Publishing-Workflows-as-Apps','未标更新日','封装为 App 与固定参数，官方直接说明')]
}
];
