import type { Profile, Source } from './research-types';
const s=(title:string,url:string,date:string,note:string,type='官方'):Source=>({title,url,date,note,type});
export const globalProfiles: Profile[] = [

{
 id:'seaart',name:'SeaArt',group:'创作与资源',focus:'多类作者激励 · 模型选择与复用',thesis:"SeaArt同时容纳资源、应用与作品作者；内容筛选、同质化和不同收入分配规则增加了运营工作。",
 job:'兴趣及内容创作者出图出片；模型、应用与角色作者分发能力。',object:'模型、AI 应用／工作流、角色和生成作品',first:'作品详情看参数 → Remix／图生图 → 编辑 → 选择公开分享',supply:'原创模型、应用、角色分池激励；徽章、精选及合作',repeat:'生成任务、主题活动、角色与资源更新（机制推断）',business:'免费体力、会员和点数；作者按贡献结算',relevance:"案例用途、参数展示与复现反馈",notCopy:'三池分账、数字人及全部自动任务体系。',experiment:"对同一主题发布有差异的作品、角色表达与过程，观察用户连续两周的观看、评论、收藏回看和尝试；不靠重复泛风格图铺量。",access:'官方指南与 2.0 公告可读；未登录核精确体力、有效期和真实结算。用户投诉仅作为待复核线索。',
 sections:[
 {title:'从作品到下一次创作',status:'事实',paragraphs:['基础指南给出浏览作品、查看提示词与模型、Remix 或图生图、生成、编辑及分享的过程；模型详情可应用推荐参数。普通用户可从已知效果开始，作者不必为每个使用者重新教学。','2026 年 6 月的 2.0 公告提出多模态入口、模型详情与作者数据改进，并直接承认过去选模型困难、跨工具下载上传有摩擦。公告证明其要解决的问题，不证明每项改进实际提高了效率。'],refs:[1,2,5]},
 {title:'作者供给不是统一的发帖奖',status:'事实',paragraphs:['创作者计划将原创模型、AI 应用和角色分别计算贡献，结合下载、使用、分享和衍生创作；原创标记、审核及月度结算有明确要求。FAQ 还有最低提现门槛，不能将账面奖励直接当即时现金。','除了现金，还有原创徽章、首页精选、首发或独家合作与内测机会。奖励分配包含新鲜度和动态贡献，作者收益难仅凭一次作品表现预测。'],refs:[3,4]},
 {title:'任务奖励与消费边界',status:'边界',paragraphs:['平台使用每日、每周及一次性任务、站内和 Discord 活动；免费体力与会员、点数并存。不同语言资料的体力数额不一致，本报告不提供统一免费额度。','旧指南说部分点数不过期，而可见公告对新购与赠送资源另有有效期，且帖龄与正文年份不一致。规则存在待核冲突，不能给用户“永不过期”的承诺。'],refs:[1,6]},
 {title:'同质化供给的反证',status:'边界',paragraphs:[],refs:[]},
 {title:'UI／UX 与运营取舍',status:'建议',paragraphs:["作品详情可展示适用范围、参数和操作入口。先按用途整理案例并观察采用情况，再决定是否分别经营模型、角色和应用供给。",'作者报酬先购买过程包、复现与必要修改；点赞、浏览用于辅助分发，有效采用与失败反馈才适合帮助判断下一份内容。']}
 ],gaps:['实际奖励池、作者中位收入与独家合作成效，资料不足。','当前精确体力和资源有效期尚有公开规则冲突。','初始作者来源及社区净留存未验证。'],sources:[s('基础页面指南','https://docs.seaart.ai/guide-1/1-seaart-ai-basic-page','未标绝对更新日','首用路径、任务与分享'),s('模型功能指南','https://docs.seaart.ai/guide-1/2-seaart-ai-basic-function/2-6-models','未标绝对更新日','模型推荐参数与 Remix'),s('创作者激励计划','https://docs.seaart.ai/guide-1/6-permanent-events/seaart.ai-creator-incentive-program','含 2025-03 规则起点','三类供给、贡献计算、合作及审核'),s('激励计划 FAQ','https://docs.seaart.ai/guide-1/6-permanent-events/seaart.ai-creator-incentive-program/creator-incentive-program-faq','未标绝对更新日','结算与原创条件'),s('SeaArt AI 2.0 公告','https://www.seaart.ai/blog/seaart-ai-2-0-introducing','2026-06-18','产品演化及自述摩擦，不采用示例规模'),s('Credit Validity 调整公告线索','https://www.reddit.com/r/SeaArtAI/comments/1rrljyk/notice_regarding_seaart_credit_validity_rule/','帖龄与正文年份冲突','SeaArt_Ai 账号发布；仅作规则冲突提示','账号公告／待核')]
},
{
 id:'openart',name:'OpenArt',group:'工具与作者生态',focus:'从图片灵感走向连续故事',thesis:"OpenArt的官方回顾将角色一致性需求与故事产品的发展联系起来。连续任务如何影响使用与付款，还需用户记录。",
 job:'创作者制作连续角色、音乐视频、解释视频及故事内容。',object:'灵感图、带参数作品、角色和 Story 内容',first:'发现效果 → 查看参考与参数 → Remix → 改成自己的故事',supply:'UGC 上传、Creative Partner 合作与 Affiliate 引荐各有分工',repeat:'同角色下一镜、下一集与后期修改（机制推断）',business:'分级订阅、生成资源与故事／角色配额；活动有期限',relevance:"连续创作任务与合作作者交付",notCopy:'完整多模态故事套件与未经验证的角色一致性承诺。',experiment:"比较连续角色作品系列和单次趣味作品两种内容节奏，提供可选幕后与尝试入口；分别记录观看者和制作参与者的次周回访。",access:'官方创始故事、合作页、定价与公开作品详情可读；Help 部分只读到问题标题，未测试复制和实际生成。',
 sections:[
 {title:'一个有启发的需求转向',status:'历史',paragraphs:['2026 年官方回顾称，团队最初做带提示词的图片浏览站，并通过 Hacker News 分享。后来用户反复要求角色一致性；继续追问后，团队发现他们想讲故事，遂扩展图像、视频、角色和音频能力。','这是官方对早期演化的自述，未独立核对最初 HN 帖子，也不采用同文的收入与活跃数字作为审计事实。它描述的是 OpenArt 的产品演化，不能代表全部 AI 创作用户的需要。'],refs:[1]},
 {title:'内容携带生成上下文',status:'事实',paragraphs:['公开作品详情可见提示词、参考图、模型、时长、比例、分辨率和音频选项，以及 Remix 入口。Story 社区按音乐视频、解释视频、角色 vlog 等任务组织发现。','早期公开页观察未包含参数复制验证；登录后的具体带入范围见本档案“分类、内容详情与实际操作”，尚无节省时间的测量结果。关于页另区分用户上传的 Discovery 和可能来自互联网抓取的图片搜索，不能把所有搜索结果都算原创社区供给。'],refs:[2,3]},
 {title:'作者合作与引荐分开计量',status:'事实',paragraphs:['Creative Partner Program 面向创作者、教育者与专业人士，提供资源、提前体验、官方展示及优先合作机会，并要求伙伴身份与回链等披露。Affiliate 则围绕引荐新订阅产生佣金，不是发帖分成。',"CPP 页的 Creative Fund 仍标 Coming Soon；不能写成已经发放。分销完整外链条款未读到，因此不承诺固定佣金或收益。"],refs:[4,5]},
 {title:'商业与生成局限',status:'边界',paragraphs:['定价按订阅、资源、并发、角色和故事等条件区分；调研当天还存在限时模型活动，不能将促销当永久无限权益。免费额度、隐私与退款的展开回答未完整读取。','官方长视频文章也承认跨镜头人物、服装、光照连续和后期组装是难点。成片、同款入口与稳定生产三者需要分别验证。'],refs:[6,7,8]},
 {title:'产品与运营的适用条件',status:'建议',paragraphs:['如果用户说“希望结果一致”，访谈还需要问：哪些对象需要一致、连续几次、拿去哪里、现在怎么补救、下一次什么时候发生。回答有机会把泛创作爱好区分成具体任务。','合作也应拆分：案例采购交付可用方法，渠道引荐带来合格用户，研究访谈暴露需求。给同一个作者多种权益时，仍分别验收这些价值。']}
 ],gaps:['最初获客成本与真实留存，资料不足。','公开作品的复制完整性和连续出品成功率未测。','伙伴平均收益及 Creative Fund 正式开放时间未核。'],sources:[s('The OpenArt Story','https://openart.ai/blog/the-openart-story/','2026-03-16','Emily Watterson，官方早期演化自述'),s('About OpenArt','https://openart.ai/about','未标更新日','上传内容与互联网搜索的区别'),s('公开作品：Cherry Sweet','https://openart.ai/suite/inspire/feed/p/248efc71b3155a2b95a59bfdd1bb7549','访问 2026-09-08','参数、参考与 Remix 实页','公开作品'),s('Creative Partner Program','https://openart.ai/programs/cpp','访问 2026-09-08','合作权益、披露与 Fund 待上线'),s('Affiliate Program','https://openart.ai/programs/affiliate','未标更新日','引荐订阅，完整外链条款未读'),s('Pricing','https://openart.ai/pricing','访问 2026-09-08','当前配额结构与限时活动'),s('Help Center','https://openart.ai/suite/help-center','访问 2026-09-08','部分答案采集受限'),s('官方长视频制作文章','https://openart.ai/blog/best-ai-video-generators-for-long-videos/','2026-07-23','只取连续性与后期难点，不采用竞品排名')]
},


{
 id:'leonardo',name:'Leonardo.Ai',group:'工具与作者生态',focus:'作品参考、任务蓝图与个人素材库',thesis:"Leonardo通过专业作者合作提供案例和过程材料。现行合作入口与历史基金分别适用，不能合并为持续补贴。",
 job:'设计、营销、插画及影像创作者生成和编辑生产素材。',object:'作品、提示词、参考、个人 Library 与 Community Feed',first:'看社区作品 → 复制提示／Remix／参考 → 编辑并保存',supply:'普通公开作品、精选 Creator Program 与历史创作基金',repeat:'素材生产、编辑需求和案例学习（机制推断）',business:'会员资源、增购及限定慢速使用；公开与隐私条件分档',relevance:"合作作者筛选、过程材料与复现验收",notCopy:'大额基金、广泛资源赠送和未经验证的案例放大。',experiment:"采购作品与制作说明，先明确哪些仅供欣赏、哪些支持学习或复用；用后续内容和问题回应观察目标用户回访，复现只验有制作承诺的部分。",access:'官方帮助、Creator Program FAQ 与基金页可读；社区内会员操作和收入未测。',
 sections:[
 {title:'社区与工作资产相连',status:'事实',paragraphs:['官方商业使用和生成帮助确认 Community Feed 及个人 Library 的角色。用户可以从公开作品复用提示或参考，进入生成、放大、编辑或视频等操作，再保存或分享。',"因此它既有展示也有工具使用，不应只按外部 Discord 生态理解。具体复制效果和跨模型结果一致性，未通过生成验证。"],refs:[1,2,3]},
 {title:'专业作者合作的条件',status:'事实',paragraphs:['Creator Program 提供专属社群、订阅资源、提前访问及展示机会，属于筛选后的作者关系。2026 年 3 月 FAQ 明确申请暂停，保留候补；不能将该页存在理解为正在公开招募。','该计划提供专业作者交流与反馈的条件；现有资料未说明这些权益实际带来了多少教学内容、产品反馈或持续供稿。'],refs:[5]},
 {title:'历史基金究竟购买什么',status:'历史',paragraphs:['2025 Imagination Fund 要求在限定周期完成作品及幕后过程等材料，申请窗口已经结束。这可以说明资助怎样转成可传播、可学习的内容，不能视为当前可申请权益。','专业作者的展示可说明特定作品被做出来，其中仍可能包含人工整理。它不能说明普通用户按相同方法也能完成。'],refs:[6]},
 {title:'免费、会员与隐私',status:'边界',paragraphs:['免费资源有日周期条件，付费资源涉及月度、结转或增购规则；部分第三方模型与慢速使用有额外限制。不同资源不能用一个“免费无限”的句子概括。',"公开与私密也和账号计划相关，FAQ 对删除生成图片存在订阅资格说明。对于涉及客户素材的人群，是否愿意公开过程可能直接影响内容供给；未实际测试删除或私密设置。"],refs:[1,4,7]},
 {title:'UI／UX 与复访判断',status:'建议',paragraphs:['用户一边管理自己的工作，一边从社区寻找方法，这种连接比额外要求大家发帖更自然。但频繁生成不必然带来互助和交流，应将工具复访与社区行为分别记账。','多元拾光可先把一个合作案例做成完整生产记录，让看过的人带真实素材尝试。若案例只带来观赏而无人采用，应调整任务选择或教学方式，再决定是否扩招作者。']}
 ],gaps:['Creator Program 恢复公开申请的时间未核。','历史基金实际成效和普通作者收入，资料不足。','社区对工具留存的独立作用与过程复制成功率未测。'],sources:[s('Frequently Asked Questions','https://intercom.help/leonardo-ai/en/articles/7051613-frequently-asked-questions','2026-02-16','产品、资源及账户条件'),s('Commercial Usage','https://intercom.help/leonardo-ai/en/articles/8044018-commercial-usage','未标绝对更新日','Community Feed 与公开内容使用语境'),s('How to Generate Images','https://intercom.help/leonardo-ai/en/articles/8942360-how-to-generate-images-with-leonardo-ai','未标绝对更新日','生成与操作路径'),s('Tokens FAQ','https://intercom.help/leonardo-ai/en/articles/9044700-tokens-frequently-asked-questions','访问 2026-09-08；显示相对更新时间','不同资源与订阅边界'),s('Creator Program FAQ','https://intercom.help/leonardo-ai/en/articles/9003169-leonardo-creator-program-faq','2026-03-03','当前暂停申请、候补及作者权益'),s('Imagination Fund','https://www.leonardo.ai/leonardo-imagination-fund','2025-09 至 10 月申请；已结束','历史作品与过程材料要求'),s('Private & Public Images','https://intercom.help/leonardo-ai/en/articles/8044029-private-public-images','未标绝对更新日','隐私与账户条件，未实操')]
},
{
 id:'runway',name:'Runway',group:'工具与作者生态',focus:'影像作者项目 · 工作流分享与复制',thesis:"Runway将作品、幕后、工作流和作者合作联系到影像制作。与MakeNow较接近的是方法分享与项目材料，影展另需组织及分发资源。",
 job:'影视、广告与专业影像创作者制作镜头、短片和项目。',object:'影像作品、Workflows、Apps、幕后教程与赛事',first:'学习案例／打开共享工作流 → 登录复制 → 换输入生成',supply:'精选 Creative Partners、作品征集、挑战和项目合作',repeat:'真实项目、后期修改、工作流复用与同行帮助（机制推断）',business:'试用、订阅和增购；团队／API；推荐奖励绑定付费深度',relevance:"工作流分享、使用条件与作者成本",notCopy:'影展基金、专业发行网络和大额品牌项目。',experiment:"用一段作品、幕后片段和创作讨论形成连续内容，观察观看与回应后的回访；确有接手需求时，再以重建困难判断画布分享投入。",access:'官方 Workflow、合作、资源和计费帮助可读；未登录共享工作流、申请计划或生成。历史基金入口已重定向。',
 sections:[
 {title:'工具内外共同形成生态',status:'事实',paragraphs:['官方资源页连接 Academy、用例、Discord 答疑、直播、线下活动、作品展示和 CPP。它的专业社区不是单个站内内容流，而是围绕作品与职业成长的多种关系。','Workflow 文档已经给出分享链接、接收者登录查看、Make a copy 继续创作；共享的是输入资产，不含节点输出，企业有额外公开设置。另可封装为 App 固定部分参数，服务工作区复用。'],refs:[2,3,12]},
 {title:'合作作者获得什么',status:'事实',paragraphs:['Creative Partners Program 通过作品集与加入理由筛选，提供 Max、提前体验、合作与专属活动。当前页面明确没有固定时间投入要求，不能把它误写成月交稿合同或统一现金补贴。','伙伴入选与作品采购不能混为一谈：该页提供身份、资源和合作机会，没有承诺固定稿量。'],refs:[1]},
 {title:'赛事和基金的历史边界',status:'历史',paragraphs:["读取的 GEN:48 条款属于 2025 年一届，规定制作时间、影片长度、工具使用比例、技术说明及评审。2024 Hundred Film Fund 是历史启动公告，当前基金入口已转向 Studios。",'这些资料能说明如何把资源支持换成创作与过程展示，不能证明今天仍开放相同申请，也不能把计划投入金额当实际拨款。'],refs:[4,5,6]},
 {title:'付费与成片质量的现实',status:'边界',paragraphs:['帮助文档区分一次性试用、订阅与增购，并公布 2026 年以 Max 替代 Unlimited 的迁移安排，不能沿用旧无限套餐。推荐奖励要求双方持续付费一段时间，明显区别于注册即赠。','官方退款说明指出，生成成功但用户不满意并不自动退资源。导演幕后案例也出现重试、改风格、外部修图和补镜头，证明精选成片背后存在人工生产工作。'],refs:[7,8,9,10,11]},
 {title:"内容组织与投入条件",status:'建议',paragraphs:['链接分享和复制降低接手别人的方法的成本，但输入、输出、权限、依赖与隐私需要向使用者讲清。MakeNow 将来开发复制时，应先以真实交接任务判断最少需要带走什么。','一名合作作者、一个小项目、一份幕后说明和一次答疑，可提供初步的供需反馈。不必同时仿建影展基金和作者平台。']}
 ],gaps:['共享流程的完整运行成功率未测。','CPP 作者实际交付、平均收益及社区转化，资料不足。','基金现行申请与实际拨款未核；赛事所读为历史届次。'],sources:[s('Creative Partners Program','https://runway.com/creative-partners-program','访问 2026-09-08','当前权益和不强制时间投入'),s('Runway Resources','https://help.runwayml.com/hc/en-us/articles/37464713358099-Runway-Resources','未标更新日','学习、答疑与作者生态入口'),s('Introduction to Workflows','https://help.runwayml.com/hc/en-us/articles/45763528999699-Introduction-to-Workflows','未标更新日','分享、复制及输入／输出限制'),s('GEN:48 Official Rules','https://runway.com/gen48/terms','所读为 2025-08-23 至 25 日届次','历史赛事，不代表当前招募'),s('Hundred Film Fund 发布','https://runway.com/news/hundred-film-fund','2024-09-26','历史资金计划，不等于已拨付'),s('原基金入口','https://runway.com/hundred-film-fund','2026-09-08 重定向 Studios','现行开放状态未确认'),s('How Do Credits Work','https://help.runwayml.com/hc/en-us/articles/15124877443219-How-do-credits-work','未标更新日','一次试用、订阅与增购'),s('Which Plan Is Right for Me','https://help.runwayml.com/hc/en-us/articles/21664961171475-Which-plan-is-right-for-me','含 2026 迁移安排','Max 与旧 Unlimited 区别'),s('Referral Codes','https://help.runwayml.com/hc/en-us/articles/45681304402707-How-do-I-use-referral-codes','未标更新日','奖励绑定持续付费'),s('Credit Refunds','https://help.runwayml.com/hc/en-us/articles/34266159290003-Can-I-have-credits-refunded','未标更新日','质量不满意与生成错误的区别'),s('Gabe Michael：48 小时制片过程','https://runway.com/customers/48-hours-to-generate-a-film','历史案例；未标绝对发布日期','精选个案中的重试与人工工作'),s('Publishing Workflows as Apps','https://help.runwayml.com/hc/en-us/articles/47865876793747-Publishing-Workflows-as-Apps','未标更新日','封装为 App 与固定参数，官方直接说明')]
}
];
