import Link from '@/components/research-link';
import data from '@/lib/theme-decisions.json';
import choices from '@/lib/task-choices.json';
import '@/components/market-social.css';
import '../../briefs/briefs.css';
function Source({href,children}:{href:string;children:React.ReactNode}) {return <a href={href} target="_blank" rel="noopener noreferrer">{children} ↗</a>}
export default function Page(){return <main className="ms-report proposal-brief">
<p><Link href="/community-options/presentation#theme-priority">返回主讲 · 主题建议</Link></p>
<header><p>主题与任务 / 决策建议</p><p><strong>前轮范围比较</strong> · 以下保留当时的优先级和待定建议；当前九类与产品路径已更新。<a href="/research-decisions">阅读当前方案 →</a></p><h1>哪些方向值得先做</h1><p>最新校准：写作、设计、角色故事和长转短收窄保留；商品图与MV衔接暂缓样板。</p><p className="brief-meta">{data.date} · {data.status}。本轮比较的是社区切入条件。各领域缺少同口径需求频率、未满足率与付费资料，暂不提供市场规模排名。</p></header>
<p><Source href="/community-options/freshness">查看最新工具能力、近期问题与六项取舍</Source></p><p className="brief-meta">以下保留前两轮比较过程；涉及首组配置，以最新校准为准。</p><nav className="brief-nav"><a href="#round2">第二轮取舍</a><a href="#criteria">判断依据</a><a href="#changes">本轮变化</a><a href="#comparison">全部候选</a><a href="#initial">首组任务建议</a><a href="#all-tasks">41项归属</a><a href="#checks">原页核读</a></nav>
<section id="round2"><h2>历史比较：第二轮建议已被最新校准替代</h2><p><Source href="/community-options/freshness">最新状态：商品图与MV暂缓，其余四项收窄保留</Source></p><p>{data.round2.summary}</p><p>{data.round2.reason}</p><div className="brief-options">{data.round2.decisions.map(r=><article key={r.task}><h3>{r.task} · {r.decision}</h3><p>{r.basis}</p><p><strong>内容要具体到：</strong>{r.content}</p></article>)}</div><p className="brief-meta">{data.round2.limits}</p><p>{data.round2.sources.map(s=><span key={s.url}><Source href={s.url}>{s.label}</Source>{' · '}</span>)}</p></section><section id="criteria"><h2>需求、已有满足与供给一起比较</h2><div className="brief-path"><div><h3>用户为什么需要</h3><p>谁在实际使用，想交付什么，哪里出现困难。一次求助支持具体问题，频率和规模另看统计。</p></div><div><h3>社区能增加什么</h3><p>先查原工具与原社区已经做好的部分，再比较方法取舍、作品讨论和知识维护。</p></div><div><h3>内容能否组织</h3><p>能否找到可公开的输入、过程和结果；专业判断由谁承担，作者是否愿意供稿与回应。</p></div></div><p>比较单位是具体任务。主线优先考虑结果清楚、已有使用材料、能表达选择理由的任务；创作入口另看作者意图和主动交流。材料较薄的方向保留候选，不用零分代替未知。所有主题进入内容样本的门槛相同：有可核对的任务、材料与选择理由；持续合作是后续运营条件。</p><p className="brief-meta">所有方向的本站合作、授权与持续供给均未落实。因此当前优先级指导选题与产品样本，不代表已经满足上线条件。成熟供给可作为基础能力跟进或外部接入，是否自建取决于它与主路径的关系。</p></section>
<section id="changes"><h2>前两轮比较与本轮调整</h2><div className="brief-options"><article><h3>九主题从重点范围回到比较席</h3><p>原范围继续保留；首页突出程度重新按任务判断。本地经营拆成具体场景，人像分开保真修整与记忆表达。</p></article><article><h3>两个开放方向重新进入主题候选</h3><p>教学有独立的学习目标；音乐与MV有完整创作及方法求助线索。它们都不应被九主题的目录顺序压到后面。</p></article><article><h3>长转短提升为跨主题重点</h3><p>历史、科普、门店和其他创作者都可能涉及选段与语义保留。按任务入口关联内容，无需先建新的行业频道。</p></article><article><h3>原六项候选已重新校准</h3><p>商品单图、文本修订、视觉草案、角色故事、长转短、MV衔接。目录图作为商品延展。用于比较两种入口的内容组织；不是同时开设六项服务。</p></article></div><p>此前以电商开篇的建议已撤回。商品图与MV衔接补齐近期材料后再决定样板；其余四项收窄到具体取舍。</p><Source href="/community-options/themes#selection">原范围如何确认</Source></section>
<section id="comparison"><h2>全部候选的比较与改选条件</h2><p>以下19组仅用于整理41项任务；组内数量和排列位置不代表需求规模。每组说明本轮建议及什么证据会改变它。</p>
{data.rows.map((r,index)=><article id={'candidate-'+index} key={r.name} className="brief-evidence"><h3>{r.name} · {r.placement}</h3><p><strong>需求依据：</strong>{r.demand}</p><div className="brief-comparison"><div><strong>已有满足</strong><p>{r.existing}</p></div><div><strong>社区可增加的内容</strong><p>{r.extra}</p></div></div><p><strong>供给条件：</strong>{r.supply}</p><p><strong>建议：</strong>{r.proposal}</p><p><strong>改选条件：</strong>{r.change}</p><p className="brief-meta">{r.ids.map(id=>{const task=choices.items.find(t=>t.id===id);return <span key={id}><Source href={task?'/research-decisions/tasks#'+id:'#task-'+id}>{task?.task||data.tasks.find(t=>t.id===id)?.task||id}</Source>{' · '}</span>})}</p></article>)}
</section>
<section id="initial"><h2>原六项建议与最新状态</h2><p>每项先取得一份能解释真实取舍的案例，再决定首页展示。缺少过程的内容可进入作品参考，不能充当方法比较。</p><div className="brief-options">{data.initial.map(t=><article key={t.id}><h3>{t.content}</h3><p>{t.why}</p><p className="brief-meta">拟放位置：{t.entry}</p><Source href={'#task-'+t.id}>任务与依据</Source></article>)}</div><p><strong>这轮等待确认的是主题优先级与首组内容任务。</strong>五套社区方案继续并列；这组题材可承载任务决策、共学、研讨、方法共建或互助，不自动等于选择某一套方案。</p></section>
<section id="all-tasks"><h2>41项任务均保留去向</h2><p>重点归属沿用既有记录；下面新增的是本轮配置建议。</p>{data.rows.map(r=><article key={r.name}><h3>{r.name}</h3>{data.tasks.filter(t=>t.theme===r.name).map(t=>{const known=choices.items.find(x=>x.id===t.id);return <div id={'task-'+t.id} key={t.id} style={{padding:'16px 0',borderBottom:'1px solid #ddd',scrollMarginTop:24}}><h4>{t.task}</h4><p>{t.substeps_or_boundary}</p><p className="brief-meta">{t.initial?'建议进入首组内容样本':'保留任务'} · {t.placement}</p>{known?<Source href={'/research-decisions/tasks#'+t.id}>已有办法、剩余问题与原始来源</Source>:<Source href="/research-records/task-evidence.txt">逐任务原始记录（按 {t.id} 查找）</Source>}</div>})}</article>)}</section>
<section id="checks"><h2>本轮核读：哪些已有办法影响选择</h2><div className="brief-options">{data.checks.map(c=><article key={c.url}><h3>{c.name}</h3><p>{c.finding}</p><p><strong>对选择的影响：</strong>{c.effect}</p><p className="brief-meta">{c.limit}</p><Source href={c.url}>原始来源</Source></article>)}</div><p className="brief-meta">以上四页本轮重新读取。音乐与MV的原始求助、制作自述由独立比较同步核读；其余行依据研究站已有归档。本轮没有重新全量采集，也未联系作者、运行制作或评估市场份额。</p><p><Source href="https://linux.do/t/topic/1200862">MV方法求助</Source> · <Source href="https://www.binwang.me/2026-01-02-Music-Video-Generation-with-AI.html">作者制作自述</Source></p><p><Source href="/research-records/open-comparison.txt">开放方向比较记录</Source> · <Source href="/research-records/supply-review.txt">九主题供给盘点</Source></p></section>
</main>}
