import {useState,useRef,useEffect} from 'react';
export const crossPageCases=['guest','session-expired','account-changed','view-denied','action-denied','readonly','removed','revoked','paused','unsaved','save-error','conflict','unknown','mobile-only','copy-error','offline','read-timeout','service-unavailable'];
export function CrossPageScenario({sample}:{sample:string}){
 const [phase,setPhase]=useState('idle'),[text,setText]=useState('尚未提交的示例内容'),[note,setNote]=useState('');
 const timer=useRef<ReturnType<typeof setTimeout>|null>(null),busy=useRef(false);useEffect(()=>()=>{if(timer.current)clearTimeout(timer.current)},[]);
 const wait=(next:string)=>{if(busy.current)return;busy.current=true;setPhase('pending');timer.current=setTimeout(()=>{busy.current=false;setPhase(next)},900)};
 const input=<label>内容<textarea value={text} onChange={e=>setText(e.target.value)} disabled={phase==='pending'}/></label>;
 const retained=<p>已填写内容保留，尚未提交。</p>;
 const home=()=>setPhase('list');
 const copyLink=async()=>{try{if(sample==='copy-error')throw new Error('demo');await navigator.clipboard.writeText(location.origin+'/community-options/c-prototype?page=app&item=video');setNote('链接已复制')}catch{setNote('复制失败，请长按上方链接手动复制')}};
 if(phase==='left')return <main className="gs-sample"><output>已离开编辑页</output></main>;
 if(phase==='related')return <main className="gs-sample"><h2>相关教程</h2><p>通过调整画面比例和主体位置，完成构图练习。</p><p>教程正文仍可阅读，关联资源已停止获取。</p><button disabled>获取资源</button></main>;
 if(phase==='history')return <main className="gs-sample"><h2>已有生成记录</h2><p>示例记录：已完成</p><p>本次结果说明仍可查看。</p><button disabled>再次生成</button></main>;
 if(phase==='list')return <main className="gs-sample"><h2>内容列表</h2><p>已返回可继续浏览的位置。</p></main>;
 if(['guest','session-expired'].includes(sample))return <main className="gs-sample">{input}{phase==='ready'?<><output>已恢复当前页面</output>{retained}<button onClick={()=>{setPhase('submitted');setNote('已主动提交')}}>提交</button></>:phase==='submitted'?<output>{note}</output>:<><h2>{sample==='guest'?'登录后继续':'登录已过期'}</h2>{retained}<button disabled={phase==='pending'} onClick={()=>wait('ready')}>{phase==='pending'?'正在恢复…':'模拟登录完成'}</button></>}</main>;
 if(sample==='account-changed')return <main className="gs-sample"><h2>账号已切换</h2><p>请返回原账号继续处理未完成内容。</p>{phase==='original'?<>{input}{retained}</>:<div className="gs-buttons"><button onClick={()=>setPhase('original')}>模拟返回原账号</button><button onClick={home}>使用当前账号浏览</button></div>}</main>;
 if(sample==='view-denied')return <main className="gs-sample"><h2>暂无查看权限</h2><p>当前账号无法查看此内容。</p><button onClick={home}>返回列表</button></main>;
 if(sample==='action-denied')return <main className="gs-sample">{input}<h2>暂不能提交</h2>{retained}<button disabled>提交</button></main>;
 if(sample==='readonly')return <main className="gs-sample"><h2>公开内容示例</h2><p>可阅读当前内容。</p><p>作者未开放复制或编辑。</p></main>;
 if(['removed','revoked','paused'].includes(sample))return <main className="gs-sample"><h2>{sample==='removed'?'内容暂不可访问':sample==='revoked'?'资源授权已撤回':'应用暂不可用'}</h2>{sample==='removed'?<button onClick={home}>返回列表</button>:<><p>{sample==='revoked'?'相关教程仍可阅读。':'应用说明和已有生成记录仍可查看。'}</p><button disabled>{sample==='revoked'?'获取资源':'开始使用'}</button><button onClick={()=>setPhase(sample==='revoked'?'related':'history')}>{sample==='revoked'?'返回相关内容':'查看已有记录'}</button></>}</main>;
 if(['unsaved','save-error','conflict'].includes(sample))return <main className="gs-sample">{input}{phase==='left'?<output>已离开编辑页</output>:phase==='saved'?<><output>草稿已保存</output><button onClick={()=>setPhase('left')}>离开</button></>:sample==='conflict'?<><h2>内容已有更新</h2><p>当前修改不能覆盖最新版本。</p><button onClick={()=>{setPhase('latest');setNote('最新版本已在下方展示，当前输入保持不变')}}>查看最新版本</button>{phase==='latest'&&<section><p>{note}</p><p>最新版本：已更新的示例正文</p></section>}<button onClick={()=>{setNote(text);setPhase('backup')}}>保留当前修改副本</button>{phase==='backup'&&<><output>当前修改已保留在本页副本中</output><pre>{note}</pre></>}</>:<><h2>{sample==='save-error'||phase==='failed'?'草稿保存失败':'离开前处理当前修改'}</h2>{(sample==='save-error'||phase==='failed')&&<p role="alert">当前内容仍保留在编辑页。</p>}<div className="gs-buttons"><button disabled={phase==='pending'} onClick={()=>wait(sample==='unsaved'&&phase!=='failed'?'failed':'saved')}>{phase==='pending'?'保存中…':'保存草稿'}</button><button disabled={phase==='pending'} onClick={()=>setPhase('editing')}>继续编辑</button><button disabled={phase==='pending'} onClick={()=>setPhase('confirm-discard')}>放弃修改</button></div>{phase==='editing'&&<output>可继续修改上方内容</output>}{phase==='confirm-discard'&&<section><p>放弃当前未保存修改？</p><button onClick={()=>{setText('');setPhase('left')}}>确认放弃</button><button onClick={()=>setPhase('editing')}>取消</button></section>}</>}</main>;
 if(sample==='unknown')return <main className="gs-sample"><h2>结果待确认</h2><p>原请求已发出，请勿重复提交。</p>{phase==='unconfirmed'&&<p role="alert">暂未确认结果，请稍后查询原记录。</p>}<button disabled={phase==='pending'} onClick={()=>wait('unconfirmed')}>{phase==='pending'?'查询中…':'查询原请求'}</button><button disabled={phase==='pending'} onClick={()=>setPhase('records')}>查看原记录</button>{phase==='records'&&<p>原记录：处理中，结果尚未确认。</p>}</main>;
 if(['mobile-only','copy-error'].includes(sample))return <main className="gs-sample"><h2>请在电脑端继续</h2><p>这里可以浏览介绍；画布和工作流操作请前往电脑端。</p><label>页面链接<input readOnly value={typeof location==='undefined'?'':location.origin+'/community-options/c-prototype?page=app&item=video'} aria-label="页面链接"/></label><button onClick={copyLink}>复制链接</button>{note&&<p role="alert">{note}</p>}</main>;
 return <main className="gs-sample">{sample==='offline'&&<div className="gs-items">已加载的内容</div>}<h2>{sample==='offline'?'网络连接已断开':sample==='read-timeout'?'加载超时':'服务暂不可用'}</h2><p>{sample==='offline'?'已有内容仍可查看，待网络恢复后重试。':sample==='read-timeout'?'本次内容尚未加载完成。':'请稍后再试。'}</p>{phase==='unavailable'&&<p role="alert">暂未恢复，请稍后重试。</p>}<button disabled={phase==='pending'} onClick={()=>wait('unavailable')}>{phase==='pending'?'检查中…':'重试'}</button></main>;
}
